/**
 * animOptions.ts — Liste des animations disponibles.
 */

export const WALKER_ANIM_OPTIONS = [
  { value: "idle", label: "Idle / Return to Default" },
  { value: "animations/anim_t_pose.glb", label: "📐 T-Pose (Rest)" },
  { value: "animations/miley_armature_01_rightward_movement_after_dodge.glb", label: "[MILEY] 01 Rightward Movement After Dodge (249f / 4.2s, 423KB)" },
  { value: "animations/miley_armature_02_leftward_movement_after_dodge.glb", label: "[MILEY] 02 Leftward Movement After Dodge (261f / 4.3s, 490KB)" },
  { value: "animations/miley_armature_03_side_movement_and_head_strikes.glb", label: "[MILEY] 03 Side Movement And Head Strikes (569f / 9.5s, 1015KB)" },
  { value: "animations/miley_armature_04_large_step_right_dodge.glb", label: "[MILEY] 04 Large Step Right Dodge (259f / 4.3s, 409KB)" },
  { value: "animations/miley_armature_05_large_step_left_dodge.glb", label: "[MILEY] 05 Large Step Left Dodge (283f / 4.7s, 431KB)" },
  { value: "animations/miley_armature_06_head_strike_after_dodge.glb", label: "[MILEY] 06 Head Strike After Dodge (455f / 7.6s, 673KB)" },
  { value: "animations/miley_armature_07_head_sway_and_leftward_dodge.glb", label: "[MILEY] 07 Head Sway And Leftward Dodge (337f / 5.6s, 485KB)" },
  { value: "animations/miley_armature_08_angry_walk.glb", label: "[MILEY] 08 Angry Walk (95f / 1.6s, 277KB)" },
  { value: "animations/miley_armature_08_head_sway_and_rightward_dodge.glb", label: "[MILEY] 08 Head Sway And Rightward Dodge (343f / 5.7s, 536KB)" },
  { value: "animations/miley_armature_09_dodge_with_belly_strikes.glb", label: "[MILEY] 09 Dodge With Belly Strikes (545f / 9.1s, 919KB)" },
  { value: "animations/miley_armature_10_dance_like_sidestep.glb", label: "[MILEY] 10 Dance Like Sidestep (759f / 12.6s, 1161KB)" },
  { value: "animations/miley_armature_11_head_combo_with_belly_strike.glb", label: "[MILEY] 11 Head Combo With Belly Strike (447f / 7.4s, 903KB)" },
  { value: "animations/miley_armature_16_taunt_beside_opponent.glb", label: "[MILEY] 16 Taunt Beside Opponent (785f / 13.1s, 1362KB)" },
  { value: "animations/miley_armature_26_drunk_walk.glb", label: "[MILEY] 26 Drunk Walk (339f / 5.7s, 805KB)" },
  { value: "animations/miley_armature_32_groove_walk.glb", label: "[MILEY] 32 Groove Walk (201f / 3.3s, 550KB)" },
  { value: "animations/miley_armature_41_provocative_walk.glb", label: "[MILEY] 41 Provocative Walk (167f / 2.8s, 408KB)" },
  { value: "animations/miley_armature_admire_bow_down.glb", label: "[MILEY] Admire Bow Down (301f / 5.0s, 648KB)" },
  { value: "animations/miley_armature_admire_draw_heart.glb", label: "[MILEY] Admire Draw Heart (398f / 6.6s, 843KB)" },
  { value: "animations/miley_armature_aerobic_dance.glb", label: "[MILEY] Aerobic Dance (910f / 15.2s, 1872KB)" },
  { value: "animations/miley_armature_against_wall_turn_l_to_sneakwalk.glb", label: "[MILEY] Against Wall Turn L To Sneakwalk (662f / 11.0s, 1343KB)" },
  { value: "animations/miley_armature_agent_behind_wall.glb", label: "[MILEY] Agent Behind Wall (470f / 7.8s, 977KB)" },
  { value: "animations/miley_armature_agent_cartwheel_landing.glb", label: "[MILEY] Agent Cartwheel Landing (274f / 4.6s, 736KB)" },
  { value: "animations/miley_armature_agent_draw_a_gun.glb", label: "[MILEY] Agent Draw A Gun (988f / 16.5s, 1773KB)" },
  { value: "animations/miley_armature_agent_elbow_strike_sweep_kick.glb", label: "[MILEY] Agent Elbow Strike Sweep Kick (307f / 5.1s, 548KB)" },
  { value: "animations/miley_armature_agent_flip_over.glb", label: "[MILEY] Agent Flip Over (310f / 5.2s, 822KB)" },
  { value: "animations/miley_armature_agent_jump_down.glb", label: "[MILEY] Agent Jump Down (343f / 5.7s, 740KB)" },
  { value: "animations/miley_armature_agent_jump_landing.glb", label: "[MILEY] Agent Jump Landing (289f / 4.8s, 692KB)" },
  { value: "animations/miley_armature_agent_leap_landing.glb", label: "[MILEY] Agent Leap Landing (267f / 4.4s, 672KB)" },
  { value: "animations/miley_armature_agent_leap_over.glb", label: "[MILEY] Agent Leap Over (310f / 5.2s, 682KB)" },
  { value: "animations/miley_armature_agent_roll_forward.glb", label: "[MILEY] Agent Roll Forward (221f / 3.7s, 618KB)" },
  { value: "animations/miley_armature_agent_snap_kick.glb", label: "[MILEY] Agent Snap Kick (314f / 5.2s, 829KB)" },
  { value: "animations/miley_armature_air_dance.glb", label: "[MILEY] Air Dance (562f / 9.4s, 1405KB)" },
  { value: "animations/miley_armature_ambitious_speech.glb", label: "[MILEY] Ambitious Speech (301f / 5.0s, 595KB)" },
  { value: "animations/miley_armature_argument_bossy_f.glb", label: "[MILEY] Argument Bossy F (718f / 12.0s, 1464KB)" },
  { value: "animations/miley_armature_axe_stand_m.glb", label: "[MILEY] Axe Stand M (463f / 7.7s, 1056KB)" },
  { value: "animations/miley_armature_axe_upright_m.glb", label: "[MILEY] Axe Upright M (661f / 11.0s, 1650KB)" },
  { value: "animations/miley_armature_b083_runtoblastb.glb", label: "[MILEY] B083 Runtoblastb (127f / 2.1s, 394KB)" },
  { value: "animations/miley_armature_b09_hold_gun_turn90_r.glb", label: "[MILEY] B09 Hold Gun Turn90 R (172f / 2.9s, 288KB)" },
  { value: "animations/miley_armature_b1_attack_back_somersault_flip.glb", label: "[MILEY] B1 Attack Back Somersault Flip (523f / 8.7s, 1118KB)" },
  { value: "animations/miley_armature_b1_fall_kicked_knockout.glb", label: "[MILEY] B1 Fall Kicked Knockout (523f / 8.7s, 1308KB)" },
  { value: "animations/miley_armature_b2_attack_front_kick.glb", label: "[MILEY] B2 Attack Front Kick (296f / 4.9s, 570KB)" },
  { value: "animations/miley_armature_b3_attack_reverse_turning_kick.glb", label: "[MILEY] B3 Attack Reverse Turning Kick (315f / 5.3s, 824KB)" },
  { value: "animations/miley_armature_basic_sing_aggressively.glb", label: "[MILEY] Basic Sing Aggressively (689f / 11.5s, 1385KB)" },
  { value: "animations/miley_armature_blade_blast_m.glb", label: "[MILEY] Blade Blast M (433f / 7.2s, 1014KB)" },
  { value: "animations/miley_armature_blade_wraparound_m.glb", label: "[MILEY] Blade Wraparound M (253f / 4.2s, 627KB)" },
  { value: "animations/miley_armature_c08_low_hold_gun_turn180_l.glb", label: "[MILEY] C08 Low Hold Gun Turn180 L (182f / 3.0s, 233KB)" },
  { value: "animations/miley_armature_catwalk_end.glb", label: "[MILEY] Catwalk End (96f / 1.6s, 233KB)" },
  { value: "animations/miley_armature_catwalk_loop.glb", label: "[MILEY] Catwalk Loop (79f / 1.3s, 213KB)" },
  { value: "animations/miley_armature_catwalk_start.glb", label: "[MILEY] Catwalk Start (33f / 0.6s, 144KB)" },
  { value: "animations/miley_armature_cc02_sideshoot.glb", label: "[MILEY] Cc02 Sideshoot (625f / 10.4s, 565KB)" },
  { value: "animations/miley_armature_change_pose.glb", label: "[MILEY] Change Pose (1083f / 18.0s, 2018KB)" },
  { value: "animations/miley_armature_chaos_duck_cover_f1.glb", label: "[MILEY] Chaos Duck Cover F1 (476f / 7.9s, 799KB)" },
  { value: "animations/miley_armature_chat_calm_f.glb", label: "[MILEY] Chat Calm F (778f / 13.0s, 1515KB)" },
  { value: "animations/miley_armature_chat_relax_f.glb", label: "[MILEY] Chat Relax F (1240f / 20.7s, 2320KB)" },
  { value: "animations/miley_armature_cheer_feminine_jump.glb", label: "[MILEY] Cheer Feminine Jump (382f / 6.4s, 782KB)" },
  { value: "animations/miley_armature_couple_pop_dance_f.glb", label: "[MILEY] Couple Pop Dance F (679f / 11.3s, 1374KB)" },
  { value: "animations/miley_armature_couple_pop_dance_m.glb", label: "[MILEY] Couple Pop Dance M (679f / 11.3s, 1406KB)" },
  { value: "animations/miley_armature_crouch_walk_r_againstwall.glb", label: "[MILEY] Crouch Walk R Againstwall (628f / 10.5s, 1572KB)" },
  { value: "animations/miley_armature_cuddle_kiss_f.glb", label: "[MILEY] Cuddle Kiss F (1142f / 19.0s, 1294KB)" },
  { value: "animations/miley_armature_cuddle_kiss_m.glb", label: "[MILEY] Cuddle Kiss M (1142f / 19.0s, 1508KB)" },
  { value: "animations/miley_armature_d1_attack_arms_block.glb", label: "[MILEY] D1 Attack Arms Block (342f / 5.7s, 635KB)" },
  { value: "animations/miley_armature_d1_dodge_sideways.glb", label: "[MILEY] D1 Dodge Sideways (342f / 5.7s, 687KB)" },
  { value: "animations/miley_armature_d3_dodge_duck.glb", label: "[MILEY] D3 Dodge Duck (394f / 6.6s, 982KB)" },
  { value: "animations/miley_armature_d4_attack_reverse_front_snap_kick.glb", label: "[MILEY] D4 Attack Reverse Front Snap Kick (515f / 8.6s, 1301KB)" },
  { value: "animations/miley_armature_d4_dodge_roll_back.glb", label: "[MILEY] D4 Dodge Roll Back (515f / 8.6s, 1307KB)" },
  { value: "animations/miley_armature_dance_graceful.glb", label: "[MILEY] Dance Graceful (1394f / 23.2s, 2797KB)" },
  { value: "animations/miley_armature_dancetomusic_f.glb", label: "[MILEY] Dancetomusic F (620f / 10.3s, 1249KB)" },
  { value: "animations/miley_armature_date_bearhug_f.glb", label: "[MILEY] Date Bearhug F (466f / 7.8s, 1193KB)" },
  { value: "animations/miley_armature_date_bearhug_m.glb", label: "[MILEY] Date Bearhug M (466f / 7.8s, 1193KB)" },
  { value: "animations/miley_armature_doubleblade_bladesurge_m.glb", label: "[MILEY] Doubleblade Bladesurge M (527f / 8.8s, 1089KB)" },
  { value: "animations/miley_armature_doubleblade_broadswordplay_m.glb", label: "[MILEY] Doubleblade Broadswordplay M (503f / 8.4s, 1279KB)" },
  { value: "animations/miley_armature_doubleblade_duel_f.glb", label: "[MILEY] Doubleblade Duel F (394f / 6.6s, 840KB)" },
  { value: "animations/miley_armature_doubleblade_rising_f.glb", label: "[MILEY] Doubleblade Rising F (382f / 6.4s, 817KB)" },
  { value: "animations/miley_armature_doubledagger_rapid_f.glb", label: "[MILEY] Doubledagger Rapid F (437f / 7.3s, 921KB)" },
  { value: "animations/miley_armature_dougie.glb", label: "[MILEY] Dougie (618f / 10.3s, 1267KB)" },
  { value: "animations/miley_armature_down_01.glb", label: "[MILEY] Down 01 (689f / 11.5s, 1562KB)" },
  { value: "animations/miley_armature_e07_low_hide_wall_reload.glb", label: "[MILEY] E07 Low Hide Wall Reload (295f / 4.9s, 388KB)" },
  { value: "animations/miley_armature_elegant_walk_1s.glb", label: "[MILEY] Elegant Walk 1s (94f / 1.6s, 230KB)" },
  { value: "animations/miley_armature_elegant_walk_2l.glb", label: "[MILEY] Elegant Walk 2l (92f / 1.5s, 214KB)" },
  { value: "animations/miley_armature_elegant_walk_3e.glb", label: "[MILEY] Elegant Walk 3e (97f / 1.6s, 322KB)" },
  { value: "animations/miley_armature_emote_f.glb", label: "[MILEY] Emote F (725f / 12.1s, 404KB)" },
  { value: "animations/miley_armature_energetic_dance_f.glb", label: "[MILEY] Energetic Dance F (572f / 9.5s, 1180KB)" },
  { value: "animations/miley_armature_energetic_dance_m.glb", label: "[MILEY] Energetic Dance M (572f / 9.5s, 1214KB)" },
  { value: "animations/miley_armature_eye_to_eye_hug_kiss_f.glb", label: "[MILEY] Eye To Eye Hug Kiss F (1124f / 18.7s, 1696KB)" },
  { value: "animations/miley_armature_eye_to_eye_hug_kiss_m.glb", label: "[MILEY] Eye To Eye Hug Kiss M (1124f / 18.7s, 1828KB)" },
  { value: "animations/miley_armature_f2_attack_straight_punch02.glb", label: "[MILEY] F2 Attack Straight Punch02 (235f / 3.9s, 386KB)" },
  { value: "animations/miley_armature_f2_fall_to_ground_face_up01.glb", label: "[MILEY] F2 Fall To Ground Face Up01 (235f / 3.9s, 580KB)" },
  { value: "animations/miley_armature_f_h_magespellcast_05.glb", label: "[MILEY] F H Magespellcast 05 (583f / 9.7s, 908KB)" },
  { value: "animations/miley_armature_fall_down_f.glb", label: "[MILEY] Fall Down F (579f / 9.6s, 1214KB)" },
  { value: "animations/miley_armature_farewell_kiss_f.glb", label: "[MILEY] Farewell Kiss F (1156f / 19.3s, 2337KB)" },
  { value: "animations/miley_armature_farewell_kiss_m.glb", label: "[MILEY] Farewell Kiss M (1156f / 19.3s, 2743KB)" },
  { value: "animations/miley_armature_firstreact_jogtorun_f.glb", label: "[MILEY] Firstreact Jogtorun F (665f / 11.1s, 1659KB)" },
  { value: "animations/miley_armature_g1_getup_kip_up.glb", label: "[MILEY] G1 Getup Kip Up (362f / 6.0s, 940KB)" },
  { value: "animations/miley_armature_g2_getup_handstand_kip_up.glb", label: "[MILEY] G2 Getup Handstand Kip Up (255f / 4.3s, 692KB)" },
  { value: "animations/miley_armature_groove_jump_up.glb", label: "[MILEY] Groove Jump Up (981f / 16.4s, 2125KB)" },
  { value: "animations/miley_armature_h1_attack_punches.glb", label: "[MILEY] H1 Attack Punches (306f / 5.1s, 564KB)" },
  { value: "animations/miley_armature_h1_hit_punches.glb", label: "[MILEY] H1 Hit Punches (306f / 5.1s, 589KB)" },
  { value: "animations/miley_armature_h2_attack_side_kicks.glb", label: "[MILEY] H2 Attack Side Kicks (334f / 5.6s, 603KB)" },
  { value: "animations/miley_armature_h2_hit_dodge.glb", label: "[MILEY] H2 Hit Dodge (334f / 5.6s, 844KB)" },
  { value: "animations/miley_armature_h3_hit_jumping_snap_kick.glb", label: "[MILEY] H3 Hit Jumping Snap Kick (568f / 9.5s, 1405KB)" },
  { value: "animations/miley_armature_h4_attack_rising_kick.glb", label: "[MILEY] H4 Attack Rising Kick (465f / 7.8s, 935KB)" },
  { value: "animations/miley_armature_h4_hit_staggering.glb", label: "[MILEY] H4 Hit Staggering (465f / 7.8s, 1163KB)" },
  { value: "animations/miley_armature_h5_hit_dodge_hug_belly.glb", label: "[MILEY] H5 Hit Dodge Hug Belly (468f / 7.8s, 1110KB)" },
  { value: "animations/miley_armature_idle01_f.glb", label: "[MILEY] Idle01 F (1987f / 33.1s, 3641KB)" },
  { value: "animations/miley_armature_idle02_f.glb", label: "[MILEY] Idle02 F (1909f / 31.8s, 3145KB)" },
  { value: "animations/miley_armature_idle03_f.glb", label: "[MILEY] Idle03 F (1109f / 18.5s, 1337KB)" },
  { value: "animations/miley_armature_invite_fight.glb", label: "[MILEY] Invite Fight (521f / 8.7s, 889KB)" },
  { value: "animations/miley_armature_ko1_attack_uppercut.glb", label: "[MILEY] Ko1 Attack Uppercut (300f / 5.0s, 470KB)" },
  { value: "animations/miley_armature_ko1_fall_to_ground_sprawl.glb", label: "[MILEY] Ko1 Fall To Ground Sprawl (300f / 5.0s, 741KB)" },
  { value: "animations/miley_armature_ko2_attack_hood_kicks.glb", label: "[MILEY] Ko2 Attack Hood Kicks (422f / 7.0s, 725KB)" },
  { value: "animations/miley_armature_ko2_fall_to_ground_axel_down.glb", label: "[MILEY] Ko2 Fall To Ground Axel Down (422f / 7.0s, 1065KB)" },
  { value: "animations/miley_armature_ko3_attack_hammer_fist.glb", label: "[MILEY] Ko3 Attack Hammer Fist (742f / 12.4s, 1805KB)" },
  { value: "animations/miley_armature_ko3_fall_to_ground_side_up02.glb", label: "[MILEY] Ko3 Fall To Ground Side Up02 (398f / 6.6s, 973KB)" },
  { value: "animations/miley_armature_livingroom_swing_m.glb", label: "[MILEY] Livingroom Swing M (1171f / 19.5s, 2777KB)" },
  { value: "animations/miley_armature_lose_shout.glb", label: "[MILEY] Lose Shout (386f / 6.4s, 672KB)" },
  { value: "animations/miley_armature_movingchat_strolling_f.glb", label: "[MILEY] Movingchat Strolling F (1068f / 17.8s, 2637KB)" },
  { value: "animations/miley_armature_movingdiscuss_calm_f.glb", label: "[MILEY] Movingdiscuss Calm F (845f / 14.1s, 2108KB)" },
  { value: "animations/miley_armature_musicalplaytime_f.glb", label: "[MILEY] Musicalplaytime F (562f / 9.4s, 1155KB)" },
  { value: "animations/miley_armature_p1_standoff_block_straight_punch.glb", label: "[MILEY] P1 Standoff Block Straight Punch (742f / 12.4s, 1779KB)" },
  { value: "animations/miley_armature_p1_standoff_push_knockout.glb", label: "[MILEY] P1 Standoff Push Knockout (742f / 12.4s, 1371KB)" },
  { value: "animations/miley_armature_p2_standoff_provokes_m1.glb", label: "[MILEY] P2 Standoff Provokes M1 (655f / 10.9s, 1559KB)" },
  { value: "animations/miley_armature_p2_standoff_provokes_m2.glb", label: "[MILEY] P2 Standoff Provokes M2 (655f / 10.9s, 1352KB)" },
  { value: "animations/miley_armature_panic_carrygirl_f.glb", label: "[MILEY] Panic Carrygirl F (350f / 5.8s, 921KB)" },
  { value: "animations/miley_armature_panic_walktorun_f03.glb", label: "[MILEY] Panic Walktorun F03 (690f / 11.5s, 1718KB)" },
  { value: "animations/miley_armature_pick_throw_f1.glb", label: "[MILEY] Pick Throw F1 (531f / 8.9s, 1345KB)" },
  { value: "animations/miley_armature_posing_f.glb", label: "[MILEY] Posing F (1358f / 22.6s, 2282KB)" },
  { value: "animations/miley_armature_propose_f.glb", label: "[MILEY] Propose F (1052f / 17.5s, 2567KB)" },
  { value: "animations/miley_armature_propose_m.glb", label: "[MILEY] Propose M (1052f / 17.5s, 2567KB)" },
  { value: "animations/miley_armature_protest_inplace_loop_f2.glb", label: "[MILEY] Protest Inplace Loop F2 (601f / 10.0s, 1130KB)" },
  { value: "animations/miley_armature_r15_staunch_bleeding_m.glb", label: "[MILEY] R15 Staunch Bleeding M (735f / 12.3s, 626KB)" },
  { value: "animations/miley_armature_routine_05.glb", label: "[MILEY] Routine 05 (659f / 11.0s, 1352KB)" },
  { value: "animations/miley_armature_s1_sparring_punch_m1.glb", label: "[MILEY] S1 Sparring Punch M1 (227f / 3.8s, 429KB)" },
  { value: "animations/miley_armature_s1_sparring_punch_m2.glb", label: "[MILEY] S1 Sparring Punch M2 (227f / 3.8s, 469KB)" },
  { value: "animations/miley_armature_s2_sparring_dodges01.glb", label: "[MILEY] S2 Sparring Dodges01 (267f / 4.4s, 558KB)" },
  { value: "animations/miley_armature_s2_sparring_kicks.glb", label: "[MILEY] S2 Sparring Kicks (267f / 4.4s, 642KB)" },
  { value: "animations/miley_armature_s3_sparring_dodges02.glb", label: "[MILEY] S3 Sparring Dodges02 (229f / 3.8s, 421KB)" },
  { value: "animations/miley_armature_s3_sparring_reverse_kicks.glb", label: "[MILEY] S3 Sparring Reverse Kicks (229f / 3.8s, 421KB)" },
  { value: "animations/miley_armature_s4_sparring_double_kicks_m1.glb", label: "[MILEY] S4 Sparring Double Kicks M1 (253f / 4.2s, 629KB)" },
  { value: "animations/miley_armature_s4_sparring_double_kicks_m2.glb", label: "[MILEY] S4 Sparring Double Kicks M2 (253f / 4.2s, 514KB)" },
  { value: "animations/miley_armature_s5_sparring_block_hit.glb", label: "[MILEY] S5 Sparring Block Hit (204f / 3.4s, 429KB)" },
  { value: "animations/miley_armature_s5_sparring_block_kick.glb", label: "[MILEY] S5 Sparring Block Kick (204f / 3.4s, 403KB)" },
  { value: "animations/miley_armature_sensual_dance_01.glb", label: "[MILEY] Sensual Dance 01 (669f / 11.1s, 1176KB)" },
  { value: "animations/miley_armature_sensual_dance_02.glb", label: "[MILEY] Sensual Dance 02 (822f / 13.7s, 2002KB)" },
  { value: "animations/miley_armature_sensual_dance_03.glb", label: "[MILEY] Sensual Dance 03 (552f / 9.2s, 1003KB)" },
  { value: "animations/miley_armature_sit_cuddle_hug_f.glb", label: "[MILEY] Sit Cuddle Hug F (722f / 12.0s, 1084KB)" },
  { value: "animations/miley_armature_sit_cuddle_hug_m.glb", label: "[MILEY] Sit Cuddle Hug M (722f / 12.0s, 965KB)" },
  { value: "animations/miley_armature_sit_look_up_laugh.glb", label: "[MILEY] Sit Look Up Laugh (301f / 5.0s, 453KB)" },
  { value: "animations/miley_armature_sit_talk.glb", label: "[MILEY] Sit Talk (1181f / 19.7s, 1639KB)" },
  { value: "animations/miley_armature_slow_dance_f.glb", label: "[MILEY] Slow Dance F (1232f / 20.5s, 2513KB)" },
  { value: "animations/miley_armature_slow_dance_m.glb", label: "[MILEY] Slow Dance M (1232f / 20.5s, 2022KB)" },
  { value: "animations/miley_armature_sneeze.glb", label: "[MILEY] Sneeze (383f / 6.4s, 699KB)" },
  { value: "animations/miley_armature_stand_talk.glb", label: "[MILEY] Stand Talk (1691f / 28.2s, 3134KB)" },
  { value: "animations/miley_armature_stand_to_sit.glb", label: "[MILEY] Stand To Sit (304f / 5.1s, 508KB)" },
  { value: "animations/miley_armature_t1_attack_thrown.glb", label: "[MILEY] T1 Attack Thrown (372f / 6.2s, 972KB)" },
  { value: "animations/miley_armature_t1_hit_suplex.glb", label: "[MILEY] T1 Hit Suplex (372f / 6.2s, 924KB)" },
  { value: "animations/miley_armature_t3_attack_shoulder_throw.glb", label: "[MILEY] T3 Attack Shoulder Throw (313f / 5.2s, 582KB)" },
  { value: "animations/miley_armature_t3_fall_shoulder_throw.glb", label: "[MILEY] T3 Fall Shoulder Throw (313f / 5.2s, 728KB)" },
  { value: "animations/miley_armature_t4_attack_knee_strike.glb", label: "[MILEY] T4 Attack Knee Strike (418f / 7.0s, 875KB)" },
  { value: "animations/miley_armature_t4_fall_belly_to_back_slam.glb", label: "[MILEY] T4 Fall Belly To Back Slam (418f / 7.0s, 1065KB)" },
  { value: "animations/miley_armature_t5_attack_headlock_takeover.glb", label: "[MILEY] T5 Attack Headlock Takeover (320f / 5.3s, 835KB)" },
  { value: "animations/miley_armature_t5_fall_headlock_takeover.glb", label: "[MILEY] T5 Fall Headlock Takeover (320f / 5.3s, 806KB)" },
  { value: "animations/miley_armature_talk_f.glb", label: "[MILEY] Talk F (926f / 15.4s, 520KB)" },
  { value: "animations/miley_armature_taunt_chest_pound.glb", label: "[MILEY] Taunt Chest Pound (371f / 6.2s, 728KB)" },
  { value: "animations/miley_armature_taunt_dance_loop.glb", label: "[MILEY] Taunt Dance Loop (176f / 2.9s, 329KB)" },
  { value: "animations/miley_armature_thanks_lady_bow.glb", label: "[MILEY] Thanks Lady Bow (371f / 6.2s, 641KB)" },
  { value: "animations/miley_armature_tight_hug_m.glb", label: "[MILEY] Tight Hug M (512f / 8.5s, 1300KB)" },
  { value: "animations/miley_armature_updown_walktorunstairs_f.glb", label: "[MILEY] Updown Walktorunstairs F (903f / 15.1s, 2217KB)" },
  { value: "animations/miley_armature_walk_f.glb", label: "[MILEY] Walk F (1077f / 18.0s, 1730KB)" },
  { value: "animations/miley_armature_walk_relaxed_end.glb", label: "[MILEY] Walk Relaxed End (162f / 2.7s, 339KB)" },
  { value: "animations/miley_armature_walk_relaxed_loop.glb", label: "[MILEY] Walk Relaxed Loop (293f / 4.9s, 531KB)" },
  { value: "animations/miley_armature_walk_relaxed_start.glb", label: "[MILEY] Walk Relaxed Start (213f / 3.5s, 409KB)" },
  { value: "animations/miley_armature_wand_attack.glb", label: "[MILEY] Wand Attack (351f / 5.8s, 694KB)" },
  { value: "animations/anim_acknowledging.glb", label: "acknowledging (48f / 1.6s, 104KB)" },
  { value: "animations/anim_action_idle_to_fight_idle.glb", label: "Action Idle To Fight Idle (31f / 1.0s, 90KB)" },
  { value: "animations/anim_action_idle_to_standing_idle.glb", label: "Action Idle To Standing Idle (29f / 1.0s, 88KB)" },
  { value: "animations/anim_administering_cpr.glb", label: "Administering Cpr (260f / 8.7s, 280KB)" },
  { value: "animations/anim_aerial_evade.glb", label: "Aerial Evade (111f / 3.7s, 169KB)" },
  { value: "animations/anim_agreeing.glb", label: "Agreeing (142f / 4.7s, 182KB)" },
  { value: "animations/anim_aiming.glb", label: "Aiming (61f / 2.0s, 105KB)" },
  { value: "animations/anim_aiming_gun.glb", label: "Aiming Gun (73f / 2.4s, 114KB)" },
  { value: "animations/anim_air_squat_bent_arms.glb", label: "Air Squat Bent Arms (57f / 1.9s, 110KB)" },
  { value: "animations/anim_angry.glb", label: "Angry (576f / 19.2s, 539KB)" },
  { value: "animations/anim_angry_gesture.glb", label: "Angry Gesture (176f / 5.9s, 212KB)" },
  { value: "animations/anim_annoyed_head_shake.glb", label: "annoyed head shake (74f / 2.5s, 109KB)" },
  { value: "animations/anim_arm_stretching.glb", label: "Arm Stretching (267f / 8.9s, 286KB)" },
  { value: "animations/anim_armada.glb", label: "Armada (50f / 1.7s, 106KB)" },
  { value: "animations/anim_armada_to_esquiva.glb", label: "armada to esquiva (123f / 4.1s, 167KB)" },
  { value: "animations/anim_arms_hip_hop_dance.glb", label: "Arms Hip Hop Dance (660f / 22.0s, 560KB)" },
  { value: "animations/anim_ascending_stairs.glb", label: "Ascending Stairs (42f / 1.4s, 101KB)" },
  { value: "animations/anim_asking_question.glb", label: "Asking Question (176f / 5.9s, 171KB)" },
  { value: "animations/anim_au.glb", label: "Au (88f / 2.9s, 181KB)" },
  { value: "animations/anim_au_to_role.glb", label: "Au To Role (121f / 4.0s, 249KB)" },
  { value: "animations/anim_back_flip_to_uppercut.glb", label: "Back Flip To Uppercut (176f / 5.9s, 183KB)" },
  { value: "animations/anim_back_squat.glb", label: "Back Squat (300f / 10.0s, 314KB)" },
  { value: "animations/anim_bartending.glb", label: "Bartending (408f / 13.6s, 403KB)" },
  { value: "animations/anim_bash.glb", label: "Bash (121f / 4.0s, 165KB)" },
  { value: "animations/anim_bashful.glb", label: "Bashful (331f / 11.0s, 339KB)" },
  { value: "animations/anim_beckoning.glb", label: "Beckoning (79f / 2.6s, 110KB)" },
  { value: "animations/anim_being_carried.glb", label: "Being Carried (158f / 5.3s, 172KB)" },
  { value: "animations/anim_being_carried_1.glb", label: "Being Carried (110f / 3.7s, 139KB)" },
  { value: "animations/anim_being_cocky.glb", label: "being cocky (87f / 2.9s, 137KB)" },
  { value: "animations/anim_belly_dance.glb", label: "Belly Dance (590f / 19.7s, 499KB)" },
  { value: "animations/anim_bellydancing.glb", label: "Bellydancing (762f / 25.4s, 637KB)" },
  { value: "animations/anim_bencao.glb", label: "Bencao (42f / 1.4s, 100KB)" },
  { value: "animations/anim_bicep_curl.glb", label: "Bicep Curl (177f / 5.9s, 126KB)" },
  { value: "animations/anim_big_hit_to_head.glb", label: "Big Hit To Head (50f / 1.7s, 84KB)" },
  { value: "animations/anim_big_hit_to_head_1.glb", label: "Big Hit To Head (48f / 1.6s, 82KB)" },
  { value: "animations/anim_big_rib_hit.glb", label: "Big Rib Hit (49f / 1.6s, 83KB)" },
  { value: "animations/anim_big_side_hit.glb", label: "Big Side Hit (45f / 1.5s, 82KB)" },
  { value: "animations/anim_block.glb", label: "Block (87f / 2.9s, 131KB)" },
  { value: "animations/anim_blocking.glb", label: "Blocking (37f / 1.2s, 76KB)" },
  { value: "animations/anim_blow_a_kiss.glb", label: "Blow A Kiss (138f / 4.6s, 166KB)" },
  { value: "animations/anim_body_jab_cross.glb", label: "Body Jab Cross (64f / 2.1s, 89KB)" },
  { value: "animations/anim_booty_hip_hop_dance.glb", label: "Booty Hip Hop Dance (148f / 4.9s, 174KB)" },
  { value: "animations/anim_box_idle.glb", label: "box idle (180f / 6.0s, 184KB)" },
  { value: "animations/anim_box_turn.glb", label: "box turn (47f / 1.6s, 99KB)" },
  { value: "animations/anim_box_turn_2.glb", label: "box turn (35f / 1.2s, 89KB)" },
  { value: "animations/anim_box_walk_arc.glb", label: "box walk arc (37f / 1.2s, 93KB)" },
  { value: "animations/anim_boxing.glb", label: "Boxing (53f / 1.8s, 85KB)" },
  { value: "animations/anim_boxing_1.glb", label: "Boxing (67f / 2.2s, 90KB)" },
  { value: "animations/anim_boxing_2.glb", label: "Boxing (67f / 2.2s, 90KB)" },
  { value: "animations/anim_boxing_3.glb", label: "Boxing (128f / 4.3s, 171KB)" },
  { value: "animations/anim_boxing_4.glb", label: "Boxing (67f / 2.2s, 90KB)" },
  { value: "animations/anim_boxing_5.glb", label: "Boxing (61f / 2.0s, 88KB)" },
  { value: "animations/anim_boxing_6.glb", label: "Boxing (75f / 2.5s, 93KB)" },
  { value: "animations/anim_braced_hang.glb", label: "Braced Hang (40f / 1.3s, 92KB)" },
  { value: "animations/anim_braced_hang_hop_left.glb", label: "Braced Hang Hop Left (46f / 1.5s, 96KB)" },
  { value: "animations/anim_braced_hang_shimmy.glb", label: "Braced Hang Shimmy (36f / 1.2s, 89KB)" },
  { value: "animations/anim_breakdance_1990.glb", label: "Breakdance 1990 (16f / 0.5s, 75KB)" },
  { value: "animations/anim_breakdance_1990_3.glb", label: "breakdance 1990 (106f / 3.5s, 153KB)" },
  { value: "animations/anim_breakdance_ending_1.glb", label: "breakdance ending 1 (196f / 6.5s, 228KB)" },
  { value: "animations/anim_breakdance_ending_2.glb", label: "breakdance ending 2 (242f / 8.1s, 265KB)" },
  { value: "animations/anim_breakdance_ending_3.glb", label: "breakdance ending 3 (193f / 6.4s, 225KB)" },
  { value: "animations/anim_breakdance_footwork_1.glb", label: "breakdance footwork 1 (96f / 3.2s, 145KB)" },
  { value: "animations/anim_breakdance_footwork_2.glb", label: "breakdance footwork 2 (49f / 1.6s, 106KB)" },
  { value: "animations/anim_breakdance_footwork_3.glb", label: "breakdance footwork 3 (138f / 4.6s, 179KB)" },
  { value: "animations/anim_breakdance_footwork_to_freeze.glb", label: "breakdance footwork to freeze (111f / 3.7s, 157KB)" },
  { value: "animations/anim_breakdance_footwork_to_idle.glb", label: "Breakdance Footwork To Idle (289f / 9.6s, 305KB)" },
  { value: "animations/anim_breakdance_freeze_var_1.glb", label: "breakdance freeze var 1 (125f / 4.2s, 168KB)" },
  { value: "animations/anim_breakdance_freeze_var_2.glb", label: "breakdance freeze var 2 (147f / 4.9s, 187KB)" },
  { value: "animations/anim_breakdance_freeze_var_3.glb", label: "breakdance freeze var 3 (186f / 6.2s, 221KB)" },
  { value: "animations/anim_breakdance_freeze_var_4.glb", label: "breakdance freeze var 4 (150f / 5.0s, 189KB)" },
  { value: "animations/anim_breakdance_freezes.glb", label: "Breakdance Freezes (202f / 6.7s, 232KB)" },
  { value: "animations/anim_breakdance_ready.glb", label: "breakdance ready (43f / 1.4s, 101KB)" },
  { value: "animations/anim_breakdance_ready_2.glb", label: "breakdance ready (33f / 1.1s, 92KB)" },
  { value: "animations/anim_breakdance_ready_3.glb", label: "breakdance ready (64f / 2.1s, 112KB)" },
  { value: "animations/anim_breakdance_swipes.glb", label: "breakdance swipes (91f / 3.0s, 140KB)" },
  { value: "animations/anim_breakdance_uprock.glb", label: "breakdance uprock (64f / 2.1s, 118KB)" },
  { value: "animations/anim_breakdance_uprock_2.glb", label: "breakdance uprock (109f / 3.6s, 155KB)" },
  { value: "animations/anim_breakdance_uprock_to_ground.glb", label: "breakdance uprock to ground (37f / 1.2s, 95KB)" },
  { value: "animations/anim_breakdance_uprock_to_ground_2.glb", label: "breakdance uprock to ground (137f / 4.6s, 179KB)" },
  { value: "animations/anim_breakdance_uprock_var_1.glb", label: "breakdance uprock var 1 (64f / 2.1s, 118KB)" },
  { value: "animations/anim_breakdance_uprock_var_1_end.glb", label: "breakdance uprock var 1 end (63f / 2.1s, 117KB)" },
  { value: "animations/anim_breakdance_uprock_var_1_start.glb", label: "breakdance uprock var 1 start (46f / 1.5s, 103KB)" },
  { value: "animations/anim_breakdance_uprock_var_2.glb", label: "breakdance uprock var 2 (159f / 5.3s, 197KB)" },
  { value: "animations/anim_brooklyn_uprock.glb", label: "Brooklyn Uprock (147f / 4.9s, 187KB)" },
  { value: "animations/anim_brutal_assassination.glb", label: "Brutal Assassination (149f / 5.0s, 182KB)" },
  { value: "animations/anim_brutal_assassination_1.glb", label: "Brutal Assassination (149f / 5.0s, 156KB)" },
  { value: "animations/anim_burpee.glb", label: "Burpee (95f / 3.2s, 144KB)" },
  { value: "animations/anim_burpee_end.glb", label: "Burpee End (74f / 2.5s, 126KB)" },
  { value: "animations/anim_button_pushing.glb", label: "Button Pushing (98f / 3.3s, 125KB)" },
  { value: "animations/anim_can_can.glb", label: "Can Can (111f / 3.7s, 157KB)" },
  { value: "animations/anim_capoeira.glb", label: "Capoeira (145f / 4.8s, 181KB)" },
  { value: "animations/anim_capoeira_2.glb", label: "capoeira (532f / 17.7s, 506KB)" },
  { value: "animations/anim_cards.glb", label: "Cards (274f / 9.1s, 292KB)" },
  { value: "animations/anim_catwalk_sequence_01.glb", label: "Catwalk Sequence 01 (439f / 14.6s, 430KB)" },
  { value: "animations/anim_catwalk_sequence_02.glb", label: "Catwalk Sequence 02 (366f / 12.2s, 370KB)" },
  { value: "animations/anim_catwalk_sequence_03.glb", label: "Catwalk Sequence 03 (373f / 12.4s, 376KB)" },
  { value: "animations/anim_catwalk_sequence_04.glb", label: "Catwalk Sequence 04 (365f / 12.2s, 369KB)" },
  { value: "animations/anim_catwalk_sequence_05.glb", label: "Catwalk Sequence 05 (306f / 10.2s, 320KB)" },
  { value: "animations/anim_catwalk_walking_not_in_place.glb", label: "Catwalk Walking not in place (36f / 1.2s, 94KB)" },
  { value: "animations/anim_chapa_2.glb", label: "Chapa 2 (42f / 1.4s, 100KB)" },
  { value: "animations/anim_chapa_giratoria.glb", label: "Chapa-Giratoria (91f / 3.0s, 140KB)" },
  { value: "animations/anim_chapa_giratoria_2.glb", label: "chapa giratoria 2 (72f / 2.4s, 125KB)" },
  { value: "animations/anim_chapaeu_de_couro.glb", label: "chapaeu de couro (104f / 3.5s, 151KB)" },
  { value: "animations/anim_cheering.glb", label: "Cheering (58f / 1.9s, 111KB)" },
  { value: "animations/anim_cheering_while_sitting.glb", label: "Cheering While Sitting (131f / 4.4s, 171KB)" },
  { value: "animations/anim_clapping.glb", label: "Clapping (36f / 1.2s, 79KB)" },
  { value: "animations/anim_clean_and_jerk.glb", label: "Clean And Jerk (521f / 17.4s, 489KB)" },
  { value: "animations/anim_climbing.glb", label: "Climbing (116f / 3.9s, 151KB)" },
  { value: "animations/anim_climbing_1.glb", label: "Climbing (116f / 3.9s, 229KB)" },
  { value: "animations/anim_climbing_a_rope.glb", label: "Climbing A Rope (78f / 2.6s, 131KB)" },
  { value: "animations/anim_climbing_a_rope_1.glb", label: "Climbing A Rope (73f / 2.4s, 124KB)" },
  { value: "animations/anim_climbing_down.glb", label: "Climbing Down (104f / 3.5s, 134KB)" },
  { value: "animations/anim_climbing_up_wall.glb", label: "Climbing Up Wall (61f / 2.0s, 113KB)" },
  { value: "animations/anim_closing.glb", label: "Closing (186f / 6.2s, 215KB)" },
  { value: "animations/anim_cocky_head_turn.glb", label: "Cocky Head Turn (77f / 2.6s, 129KB)" },
  { value: "animations/anim_convulsing.glb", label: "Convulsing (58f / 1.9s, 104KB)" },
  { value: "animations/anim_corkscrew_kip_up.glb", label: "Corkscrew Kip Up (84f / 2.8s, 196KB)" },
  { value: "animations/anim_counting.glb", label: "Counting (200f / 6.7s, 185KB)" },
  { value: "animations/anim_cow_milking.glb", label: "Cow Milking (137f / 4.6s, 179KB)" },
  { value: "animations/anim_crawl_backwards.glb", label: "Crawl Backwards (120f / 4.0s, 206KB)" },
  { value: "animations/anim_crawl_backwards_in_prone.glb", label: "Crawl Backwards In Prone (30f / 1.0s, 78KB)" },
  { value: "animations/anim_crawling_backwards.glb", label: "Crawling Backwards (63f / 2.1s, 107KB)" },
  { value: "animations/anim_cross_jumps_rotation.glb", label: "Cross Jumps Rotation (62f / 2.1s, 115KB)" },
  { value: "animations/anim_cross_punch.glb", label: "Cross Punch (61f / 2.0s, 88KB)" },
  { value: "animations/anim_crossleg_freeze.glb", label: "Crossleg Freeze (62f / 2.1s, 116KB)" },
  { value: "animations/anim_crouch_idle.glb", label: "crouch idle (51f / 1.7s, 95KB)" },
  { value: "animations/anim_crouch_look_around_corner.glb", label: "Crouch Look Around Corner (91f / 3.0s, 124KB)" },
  { value: "animations/anim_crouch_to_stand.glb", label: "Crouch To Stand (101f / 3.4s, 101KB)" },
  { value: "animations/anim_crouch_to_standing_idle.glb", label: "crouch to standing idle (19f / 0.6s, 76KB)" },
  { value: "animations/anim_crying.glb", label: "Crying (189f / 6.3s, 216KB)" },
  { value: "animations/anim_dancing.glb", label: "Dancing (372f / 12.4s, 403KB)" },
  { value: "animations/anim_dancing_1.glb", label: "Dancing (643f / 21.4s, 538KB)" },
  { value: "animations/anim_dancing_2.glb", label: "Dancing (80f / 2.7s, 144KB)" },
  { value: "animations/anim_dancing_6.glb", label: "Dancing (489f / 16.3s, 470KB)" },
  { value: "animations/anim_dancing_running_man.glb", label: "Dancing Running Man (326f / 10.9s, 335KB)" },
  { value: "animations/anim_dancing_twerk.glb", label: "Dancing Twerk (457f / 15.2s, 444KB)" },
  { value: "animations/anim_defeat.glb", label: "Defeat (144f / 4.8s, 118KB)" },
  { value: "animations/anim_descending_stairs.glb", label: "Descending Stairs (13f / 0.4s, 77KB)" },
  { value: "animations/anim_dig_and_plant_seeds_1.glb", label: "Dig And Plant Seeds (166f / 5.5s, 203KB)" },
  { value: "animations/anim_disappointed.glb", label: "Disappointed (127f / 4.2s, 164KB)" },
  { value: "animations/anim_dismissing_gesture.glb", label: "dismissing gesture (99f / 3.3s, 147KB)" },
  { value: "animations/anim_dive_roll.glb", label: "Dive Roll (119f / 4.0s, 238KB)" },
  { value: "animations/anim_dodging.glb", label: "Dodging (68f / 2.3s, 91KB)" },
  { value: "animations/anim_dodging_1.glb", label: "Dodging (71f / 2.4s, 91KB)" },
  { value: "animations/anim_double_leg_takedown___attacker.glb", label: "Double Leg Takedown   Attacker (218f / 7.3s, 247KB)" },
  { value: "animations/anim_double_leg_takedown_attacker.glb", label: "Double Leg Takedown - Attacker (106f / 3.5s, 155KB)" },
  { value: "animations/anim_double_leg_takedown_victim.glb", label: "Double Leg Takedown - Victim (218f / 7.3s, 248KB)" },
  { value: "animations/anim_drinking_fountain.glb", label: "Drinking Fountain (308f / 10.3s, 323KB)" },
  { value: "animations/anim_dropping.glb", label: "Dropping (135f / 4.5s, 156KB)" },
  { value: "animations/anim_drunk_idle.glb", label: "drunk idle (223f / 7.4s, 239KB)" },
  { value: "animations/anim_drunk_idle_variation.glb", label: "Drunk Idle Variation (120f / 4.0s, 164KB)" },
  { value: "animations/anim_drunk_idle_variation_1.glb", label: "Drunk Idle Variation (163f / 5.4s, 200KB)" },
  { value: "animations/anim_drunk_run_backward.glb", label: "drunk run backward (34f / 1.1s, 92KB)" },
  { value: "animations/anim_drunk_run_forward.glb", label: "drunk run forward (56f / 1.9s, 133KB)" },
  { value: "animations/anim_drunk_running_left_turn.glb", label: "drunk running left turn (46f / 1.5s, 104KB)" },
  { value: "animations/anim_drunk_turn.glb", label: "drunk turn (48f / 1.6s, 105KB)" },
  { value: "animations/anim_drunk_walk.glb", label: "Drunk Walk (91f / 3.0s, 142KB)" },
  { value: "animations/anim_drunk_walk_backwards.glb", label: "drunk walk backwards (48f / 1.6s, 103KB)" },
  { value: "animations/anim_drunk_walking_turn.glb", label: "drunk walking turn (78f / 2.6s, 130KB)" },
  { value: "animations/anim_ducking.glb", label: "Ducking (45f / 1.5s, 95KB)" },
  { value: "animations/anim_dwarf_idle.glb", label: "Dwarf Idle (211f / 7.0s, 233KB)" },
  { value: "animations/anim_dying.glb", label: "Dying (174f / 5.8s, 211KB)" },
  { value: "animations/anim_elbow_punch.glb", label: "Elbow Punch (53f / 1.8s, 85KB)" },
  { value: "animations/anim_elbow_uppercut_combo.glb", label: "Elbow Uppercut Combo (74f / 2.5s, 109KB)" },
  { value: "animations/anim_entering_code.glb", label: "Entering Code (226f / 7.5s, 214KB)" },
  { value: "animations/anim_entry.glb", label: "Entry (220f / 7.3s, 244KB)" },
  { value: "animations/anim_esquiva_1.glb", label: "esquiva 1 (139f / 4.6s, 180KB)" },
  { value: "animations/anim_esquiva_2.glb", label: "Esquiva 2 (68f / 2.3s, 121KB)" },
  { value: "animations/anim_esquiva_3.glb", label: "esquiva 3 (66f / 2.2s, 120KB)" },
  { value: "animations/anim_esquiva_4.glb", label: "esquiva 4 (85f / 2.8s, 135KB)" },
  { value: "animations/anim_esquiva_5.glb", label: "esquiva 5 (66f / 2.2s, 120KB)" },
  { value: "animations/anim_fall_flat.glb", label: "Fall Flat (77f / 2.6s, 176KB)" },
  { value: "animations/anim_falling.glb", label: "Falling (136f / 4.5s, 165KB)" },
  { value: "animations/anim_falling_idle.glb", label: "Falling Idle (22f / 0.7s, 79KB)" },
  { value: "animations/anim_female_dance_pose.glb", label: "Female Dance Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_dance_pose_2.glb", label: "Female Dance Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_dynamic_pose.glb", label: "Female Dynamic Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_laying_pose.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_laying_pose_1.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_laying_pose_3.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_laying_pose_4.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_laying_pose_9.glb", label: "Female Laying Pose (2f / 0.1s, 65KB)" },
  { value: "animations/anim_female_locomotion_pose.glb", label: "Female Locomotion Pose (2f / 0.1s, 1796KB)" },
  { value: "animations/anim_female_peek_and_aim.glb", label: "Female Peek And Aim (79f / 2.6s, 91KB)" },
  { value: "animations/anim_female_sitting_pose.glb", label: "Female Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_sitting_pose_1.glb", label: "Female Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_sitting_pose_2.glb", label: "Female Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_sitting_pose_3.glb", label: "Female Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_standing_pose.glb", label: "Female Standing Pose (2f / 0.1s, 62KB)" },
  { value: "animations/anim_female_standing_pose_1.glb", label: "Female Standing Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_standing_pose_2.glb", label: "Female Standing Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_standing_pose_3.glb", label: "Female Standing Pose (2f / 0.1s, 62KB)" },
  { value: "animations/anim_female_standing_pose_4.glb", label: "Female Standing Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_female_walk.glb", label: "Female Walk (36f / 1.2s, 79KB)" },
  { value: "animations/anim_femme_peek_around_corner.glb", label: "Femme Peek Around Corner (74f / 2.5s, 92KB)" },
  { value: "animations/anim_fight_idle.glb", label: "Fight Idle (72f / 2.4s, 1824KB)" },
  { value: "animations/anim_finding.glb", label: "Finding (414f / 13.8s, 410KB)" },
  { value: "animations/anim_fireball.glb", label: "Fireball (102f / 3.4s, 150KB)" },
  { value: "animations/anim_fist_fight_b.glb", label: "Fist Fight B (141f / 4.7s, 182KB)" },
  { value: "animations/anim_flair.glb", label: "Flair (31f / 1.0s, 90KB)" },
  { value: "animations/anim_flair_3.glb", label: "flair (51f / 1.7s, 107KB)" },
  { value: "animations/anim_flip_kick.glb", label: "Flip Kick (62f / 2.1s, 117KB)" },
  { value: "animations/anim_floating.glb", label: "Floating (109f / 3.6s, 152KB)" },
  { value: "animations/anim_flying.glb", label: "Flying (80f / 2.7s, 153KB)" },
  { value: "animations/anim_flying_bicycle_kick.glb", label: "Flying Bicycle Kick (21f / 0.7s, 72KB)" },
  { value: "animations/anim_focus.glb", label: "Focus (166f / 5.5s, 177KB)" },
  { value: "animations/anim_free_hang_hop_left.glb", label: "Free Hang Hop Left (64f / 2.1s, 106KB)" },
  { value: "animations/anim_free_hang_hop_right.glb", label: "Free Hang Hop Right (64f / 2.1s, 107KB)" },
  { value: "animations/anim_freehang_drop.glb", label: "Freehang Drop (41f / 1.4s, 93KB)" },
  { value: "animations/anim_front_flip.glb", label: "Front Flip (51f / 1.7s, 143KB)" },
  { value: "animations/anim_front_twist_flip.glb", label: "Front Twist Flip (67f / 2.2s, 169KB)" },
  { value: "animations/anim_gaming.glb", label: "Gaming (152f / 5.1s, 155KB)" },
  { value: "animations/anim_gangnam_style.glb", label: "gangnam style (372f / 12.4s, 373KB)" },
  { value: "animations/anim_getting_hit_backwards.glb", label: "Getting Hit Backwards (81f / 2.7s, 132KB)" },
  { value: "animations/anim_getting_up.glb", label: "Getting Up (82f / 2.7s, 120KB)" },
  { value: "animations/anim_ginga_backward.glb", label: "ginga backward (35f / 1.2s, 94KB)" },
  { value: "animations/anim_ginga_forward.glb", label: "ginga forward (38f / 1.3s, 97KB)" },
  { value: "animations/anim_ginga_sideways_1.glb", label: "ginga sideways 1 (51f / 1.7s, 107KB)" },
  { value: "animations/anim_ginga_sideways_2.glb", label: "ginga sideways 2 (68f / 2.3s, 127KB)" },
  { value: "animations/anim_ginga_sideways_to_au.glb", label: "ginga sideways to au (114f / 3.8s, 179KB)" },
  { value: "animations/anim_ginga_variation_1.glb", label: "Ginga Variation 1 (107f / 3.6s, 151KB)" },
  { value: "animations/anim_ginga_variation_2.glb", label: "ginga variation 2 (115f / 3.8s, 160KB)" },
  { value: "animations/anim_ginga_variation_3.glb", label: "ginga variation 3 (87f / 2.9s, 136KB)" },
  { value: "animations/anim_goalkeeper_body_block.glb", label: "Goalkeeper Body Block (104f / 3.5s, 151KB)" },
  { value: "animations/anim_goalkeeper_miss.glb", label: "Goalkeeper Miss (89f / 3.0s, 139KB)" },
  { value: "animations/anim_golf_chip.glb", label: "Golf Chip (384f / 12.8s, 204KB)" },
  { value: "animations/anim_goofy_running.glb", label: "Goofy Running (20f / 0.7s, 76KB)" },
  { value: "animations/anim_great_sword_idle.glb", label: "Great Sword Idle (114f / 3.8s, 130KB)" },
  { value: "animations/anim_great_sword_power_up.glb", label: "Great Sword Power Up (106f / 3.5s, 110KB)" },
  { value: "animations/anim_guitar_playing.glb", label: "Guitar Playing (144f / 4.8s, 169KB)" },
  { value: "animations/anim_gunplay.glb", label: "Gunplay (7f / 0.2s, 69KB)" },
  { value: "animations/anim_gunplay_1.glb", label: "Gunplay (77f / 2.6s, 90KB)" },
  { value: "animations/anim_gunplay_shooting.glb", label: "Gunplay Shooting (77f / 2.6s, 90KB)" },
  { value: "animations/anim_hand_raising.glb", label: "Hand Raising (123f / 4.1s, 164KB)" },
  { value: "animations/anim_hanging_idle.glb", label: "Hanging Idle (71f / 2.4s, 114KB)" },
  { value: "animations/anim_happy_hand_gesture.glb", label: "Happy Hand Gesture (89f / 3.0s, 138KB)" },
  { value: "animations/anim_happy_idle.glb", label: "Happy Idle (89f / 3.0s, 136KB)" },
  { value: "animations/anim_happy_walk.glb", label: "Happy Walk (34f / 1.1s, 95KB)" },
  { value: "animations/anim_happy_walk_backward.glb", label: "Happy Walk Backward (32f / 1.1s, 93KB)" },
  { value: "animations/anim_happy_walk_not_in_place.glb", label: "Happy Walk not in place (34f / 1.1s, 93KB)" },
  { value: "animations/anim_hard_head_nod.glb", label: "hard head nod (50f / 1.7s, 106KB)" },
  { value: "animations/anim_hard_landing.glb", label: "Hard Landing (61f / 2.0s, 106KB)" },
  { value: "animations/anim_having_a_meeting_female.glb", label: "Having A Meeting, Female (1401f / 46.7s, 1227KB)" },
  { value: "animations/anim_having_a_meeting_male.glb", label: "Having A Meeting, Male (1401f / 46.7s, 1227KB)" },
  { value: "animations/anim_head_hit.glb", label: "Head Hit (36f / 1.2s, 78KB)" },
  { value: "animations/anim_head_nod_yes.glb", label: "Head Nod Yes (79f / 2.6s, 131KB)" },
  { value: "animations/anim_head_spinning.glb", label: "Head Spinning (26f / 0.9s, 73KB)" },
  { value: "animations/anim_headbutt.glb", label: "Headbutt (64f / 2.1s, 89KB)" },
  { value: "animations/anim_header.glb", label: "Header (44f / 1.5s, 100KB)" },
  { value: "animations/anim_header_soccerball.glb", label: "Header Soccerball (58f / 1.9s, 110KB)" },
  { value: "animations/anim_header_soccerball_1.glb", label: "Header Soccerball (127f / 4.2s, 155KB)" },
  { value: "animations/anim_helping_out.glb", label: "Helping Out (225f / 7.5s, 217KB)" },
  { value: "animations/anim_hip_hop_dancing.glb", label: "Hip Hop Dancing (558f / 18.6s, 475KB)" },
  { value: "animations/anim_hip_hop_dancing_1.glb", label: "Hip Hop Dancing (474f / 15.8s, 428KB)" },
  { value: "animations/anim_hip_hop_dancing_13.glb", label: "Hip Hop Dancing (184f / 6.1s, 200KB)" },
  { value: "animations/anim_hip_hop_dancing_14.glb", label: "Hip Hop Dancing (143f / 4.8s, 124KB)" },
  { value: "animations/anim_hip_hop_dancing_17.glb", label: "Hip Hop Dancing (392f / 13.1s, 353KB)" },
  { value: "animations/anim_hip_hop_dancing_18.glb", label: "Hip Hop Dancing (124f / 4.1s, 129KB)" },
  { value: "animations/anim_hip_hop_dancing_19.glb", label: "Hip Hop Dancing (135f / 4.5s, 113KB)" },
  { value: "animations/anim_hip_hop_dancing_2.glb", label: "Hip Hop Dancing (410f / 13.7s, 404KB)" },
  { value: "animations/anim_hip_hop_dancing_3.glb", label: "Hip Hop Dancing (360f / 12.0s, 329KB)" },
  { value: "animations/anim_hip_hop_dancing_4.glb", label: "Hip Hop Dancing (471f / 15.7s, 412KB)" },
  { value: "animations/anim_hip_hop_dancing_5.glb", label: "Hip Hop Dancing (102f / 3.4s, 115KB)" },
  { value: "animations/anim_hip_hop_dancing_6.glb", label: "Hip Hop Dancing (191f / 6.4s, 163KB)" },
  { value: "animations/anim_hit_to_body.glb", label: "Hit To Body (36f / 1.2s, 79KB)" },
  { value: "animations/anim_hit_to_body_1.glb", label: "Hit To Body (41f / 1.4s, 81KB)" },
  { value: "animations/anim_hit_to_head.glb", label: "Hit To Head (77f / 2.6s, 179KB)" },
  { value: "animations/anim_hit_to_side_of_body.glb", label: "Hit To Side Of Body (85f / 2.8s, 191KB)" },
  { value: "animations/anim_hit_to_the_legs.glb", label: "Hit To The Legs (96f / 3.2s, 214KB)" },
  { value: "animations/anim_hokey_pokey.glb", label: "Hokey Pokey (351f / 11.7s, 356KB)" },
  { value: "animations/anim_holding_idle.glb", label: "holding idle (173f / 5.8s, 203KB)" },
  { value: "animations/anim_holding_turn_left.glb", label: "holding turn left (37f / 1.2s, 87KB)" },
  { value: "animations/anim_holding_turn_right.glb", label: "holding turn right (37f / 1.2s, 86KB)" },
  { value: "animations/anim_holding_walk.glb", label: "holding walk (42f / 1.4s, 98KB)" },
  { value: "animations/anim_hook.glb", label: "Hook (61f / 2.0s, 88KB)" },
  { value: "animations/anim_house_dancing.glb", label: "House Dancing (642f / 21.4s, 557KB)" },
  { value: "animations/anim_house_dancing_1.glb", label: "House Dancing (786f / 26.2s, 716KB)" },
  { value: "animations/anim_house_dancing_2.glb", label: "House Dancing (595f / 19.8s, 557KB)" },
  { value: "animations/anim_hurricane_kick.glb", label: "Hurricane Kick (56f / 1.9s, 75KB)" },
  { value: "animations/anim_idle.glb", label: "idle (251f / 8.4s, 272KB)" },
  { value: "animations/anim_idle_fight.glb", label: "Idle fight (67f / 2.2s, 90KB)" },
  { value: "animations/anim_idle_left_right.glb", label: "Idle Left Right (500f / 16.7s, 479KB)" },
  { value: "animations/anim_illegal_elbow_punch.glb", label: "Illegal Elbow Punch (62f / 2.1s, 88KB)" },
  { value: "animations/anim_injured_walk_right_turn.glb", label: "Injured Walk Right Turn (56f / 1.9s, 109KB)" },
  { value: "animations/anim_inside_crescent_kick.glb", label: "Inside Crescent Kick (81f / 2.7s, 1859KB)" },
  { value: "animations/anim_insult.glb", label: "Insult (81f / 2.7s, 132KB)" },
  { value: "animations/anim_inward_block.glb", label: "Inward Block (45f / 1.5s, 81KB)" },
  { value: "animations/anim_jab_to_elbow_punch.glb", label: "Jab To Elbow Punch (99f / 3.3s, 147KB)" },
  { value: "animations/anim_jazz_dancing.glb", label: "Jazz Dancing (164f / 5.5s, 152KB)" },
  { value: "animations/anim_jazz_dancing_1.glb", label: "Jazz Dancing (69f / 2.3s, 100KB)" },
  { value: "animations/anim_jazz_dancing_2.glb", label: "Jazz Dancing (71f / 2.4s, 89KB)" },
  { value: "animations/anim_jazz_dancing_4.glb", label: "Jazz Dancing (83f / 2.8s, 134KB)" },
  { value: "animations/anim_joyful_jump.glb", label: "Joyful Jump (57f / 1.9s, 110KB)" },
  { value: "animations/anim_jump.glb", label: "jump (51f / 1.7s, 107KB)" },
  { value: "animations/anim_jump_away.glb", label: "Jump Away (80f / 2.7s, 171KB)" },
  { value: "animations/anim_jump_down.glb", label: "Jump Down (106f / 3.5s, 104KB)" },
  { value: "animations/anim_jump_over.glb", label: "Jump Over (69f / 2.3s, 173KB)" },
  { value: "animations/anim_jump_push_up.glb", label: "Jump Push Up (36f / 1.2s, 94KB)" },
  { value: "animations/anim_jumping_down.glb", label: "Jumping Down (81f / 2.7s, 104KB)" },
  { value: "animations/anim_jumping_jacks.glb", label: "Jumping Jacks (33f / 1.1s, 94KB)" },
  { value: "animations/anim_jumping_over_into_combat.glb", label: "Jumping Over Into Combat (126f / 4.2s, 261KB)" },
  { value: "animations/anim_jumping_parkour.glb", label: "Jumping parkour (36f / 1.2s, 112KB)" },
  { value: "animations/anim_jumping_rope.glb", label: "Jumping Rope (78f / 2.6s, 94KB)" },
  { value: "animations/anim_kettlebell_swing.glb", label: "Kettlebell Swing (60f / 2.0s, 86KB)" },
  { value: "animations/anim_kick_soccerball.glb", label: "Kick Soccerball (18f / 0.6s, 74KB)" },
  { value: "animations/anim_kick_to_the_groin.glb", label: "Kick To The Groin (88f / 2.9s, 124KB)" },
  { value: "animations/anim_kick_to_the_groin_1.glb", label: "Kick To The Groin (105f / 3.5s, 136KB)" },
  { value: "animations/anim_kick_up_soccerball.glb", label: "Kick Up Soccerball (41f / 1.4s, 98KB)" },
  { value: "animations/anim_kicking.glb", label: "Kicking (66f / 2.2s, 89KB)" },
  { value: "animations/anim_kicking_1.glb", label: "Kicking (103f / 3.4s, 103KB)" },
  { value: "animations/anim_kicking_2.glb", label: "Kicking (69f / 2.3s, 116KB)" },
  { value: "animations/anim_kicking_3.glb", label: "Kicking (49f / 1.6s, 84KB)" },
  { value: "animations/anim_kicking_4.glb", label: "Kicking (81f / 2.7s, 125KB)" },
  { value: "animations/anim_kicking_5.glb", label: "Kicking (112f / 3.7s, 185KB)" },
  { value: "animations/anim_kicking_6.glb", label: "Kicking (67f / 2.2s, 90KB)" },
  { value: "animations/anim_kicking_7.glb", label: "Kicking (46f / 1.5s, 82KB)" },
  { value: "animations/anim_kicking_out.glb", label: "Kicking Out (49f / 1.6s, 95KB)" },
  { value: "animations/anim_kidney_hit.glb", label: "Kidney Hit (35f / 1.2s, 78KB)" },
  { value: "animations/anim_kip_up.glb", label: "Kip Up (62f / 2.1s, 117KB)" },
  { value: "animations/anim_kiss.glb", label: "Kiss (113f / 3.8s, 158KB)" },
  { value: "animations/anim_kiss_1.glb", label: "Kiss (113f / 3.8s, 158KB)" },
  { value: "animations/anim_kiss_from_man.glb", label: "Kiss from man (213f / 7.1s, 241KB)" },
  { value: "animations/anim_kiss_from_woman.glb", label: "Kiss from woman (213f / 7.1s, 241KB)" },
  { value: "animations/anim_knee_jab.glb", label: "Knee Jab (181f / 6.0s, 215KB)" },
  { value: "animations/anim_knee_kick_lead.glb", label: "Knee Kick Lead (71f / 2.4s, 117KB)" },
  { value: "animations/anim_kneeing_soccerball.glb", label: "Kneeing Soccerball (28f / 0.9s, 87KB)" },
  { value: "animations/anim_kneeling_idle.glb", label: "kneeling idle (129f / 4.3s, 158KB)" },
  { value: "animations/anim_kneeling_inspecting.glb", label: "Kneeling Inspecting (149f / 5.0s, 160KB)" },
  { value: "animations/anim_kneeling_pointing.glb", label: "Kneeling Pointing (118f / 3.9s, 144KB)" },
  { value: "animations/anim_laughing.glb", label: "Laughing (294f / 9.8s, 304KB)" },
  { value: "animations/anim_laying.glb", label: "Laying (131f / 4.4s, 153KB)" },
  { value: "animations/anim_laying_1.glb", label: "Laying (96f / 3.2s, 129KB)" },
  { value: "animations/anim_laying_idle.glb", label: "Laying Idle (376f / 12.5s, 277KB)" },
  { value: "animations/anim_laying_idle_1.glb", label: "Laying Idle (65f / 2.2s, 91KB)" },
  { value: "animations/anim_laying_mild_cough.glb", label: "Laying Mild Cough (51f / 1.7s, 95KB)" },
  { value: "animations/anim_laying_seizure.glb", label: "Laying Seizure (151f / 5.0s, 192KB)" },
  { value: "animations/anim_laying_severe_cough.glb", label: "Laying Severe Cough (54f / 1.8s, 111KB)" },
  { value: "animations/anim_laying_shrugging.glb", label: "Laying Shrugging (51f / 1.7s, 107KB)" },
  { value: "animations/anim_laying_sleeping.glb", label: "Laying Sleeping (52f / 1.7s, 84KB)" },
  { value: "animations/anim_lead_jab.glb", label: "Lead Jab (55f / 1.8s, 86KB)" },
  { value: "animations/anim_lead_jab_1.glb", label: "Lead Jab (33f / 1.1s, 78KB)" },
  { value: "animations/anim_leaning.glb", label: "Leaning (101f / 3.4s, 97KB)" },
  { value: "animations/anim_left_strafe.glb", label: "left strafe (21f / 0.7s, 82KB)" },
  { value: "animations/anim_left_strafe_walk.glb", label: "left strafe walk (29f / 1.0s, 89KB)" },
  { value: "animations/anim_left_strafe_walking.glb", label: "left strafe walking (32f / 1.1s, 90KB)" },
  { value: "animations/anim_left_turn.glb", label: "Left Turn (36f / 1.2s, 95KB)" },
  { value: "animations/anim_left_turn_90.glb", label: "left turn 90 (28f / 0.9s, 87KB)" },
  { value: "animations/anim_leg_sweep.glb", label: "Leg Sweep (87f / 2.9s, 137KB)" },
  { value: "animations/anim_leg_sweep_1.glb", label: "Leg Sweep (74f / 2.5s, 119KB)" },
  { value: "animations/anim_lengthy_head_nod.glb", label: "lengthy head nod (52f / 1.7s, 108KB)" },
  { value: "animations/anim_lifting.glb", label: "Lifting (217f / 7.2s, 244KB)" },
  { value: "animations/anim_light_hit_to_head.glb", label: "Light Hit To Head (26f / 0.9s, 74KB)" },
  { value: "animations/anim_listening_to_music.glb", label: "Listening To Music (135f / 4.5s, 114KB)" },
  { value: "animations/anim_locking_hip_hop_dance.glb", label: "Locking Hip Hop Dance (511f / 17.0s, 449KB)" },
  { value: "animations/anim_look_around.glb", label: "Look Around (401f / 13.4s, 397KB)" },
  { value: "animations/anim_look_away_gesture.glb", label: "look away gesture (55f / 1.8s, 111KB)" },
  { value: "animations/anim_looking.glb", label: "Looking (144f / 4.8s, 162KB)" },
  { value: "animations/anim_looking_around.glb", label: "Looking Around (191f / 6.4s, 223KB)" },
  { value: "animations/anim_looking_through_files_low.glb", label: "Looking Through Files Low (433f / 14.4s, 425KB)" },
  { value: "animations/anim_loser.glb", label: "Loser (99f / 3.3s, 143KB)" },
  { value: "animations/anim_low_crawl.glb", label: "Low Crawl (71f / 2.4s, 123KB)" },
  { value: "animations/anim_lying_down.glb", label: "Lying Down (173f / 5.8s, 208KB)" },
  { value: "animations/anim_macaco_side.glb", label: "macaco side (100f / 3.3s, 148KB)" },
  { value: "animations/anim_macarena_dance.glb", label: "Macarena Dance (248f / 8.3s, 251KB)" },
  { value: "animations/anim_male_crouch_pose.glb", label: "Male Crouch Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_male_dynamic_matrix_pose.glb", label: "Male Dynamic Matrix Pose (2f / 0.1s, 62KB)" },
  { value: "animations/anim_male_laying_pose.glb", label: "Male Laying Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_male_laying_pose_1.glb", label: "Male Laying Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_male_laying_pose_2.glb", label: "Male Laying Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_male_sitting_pose.glb", label: "Male Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_male_sitting_pose_1.glb", label: "Male Sitting Pose (2f / 0.1s, 62KB)" },
  { value: "animations/anim_male_sitting_pose_2.glb", label: "Male Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_male_sitting_pose_3.glb", label: "Male Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_male_standing_pose.glb", label: "Male Standing Pose (2f / 0.1s, 63KB)" },
  { value: "animations/anim_martelo_2.glb", label: "Martelo 2 (40f / 1.3s, 98KB)" },
  { value: "animations/anim_martelo_3.glb", label: "Martelo 3 (60f / 2.0s, 115KB)" },
  { value: "animations/anim_martelo_do_chau.glb", label: "martelo do chau (92f / 3.1s, 141KB)" },
  { value: "animations/anim_martelo_do_chau_sem_mao.glb", label: "Martelo Do Chau Sem Mao (93f / 3.1s, 142KB)" },
  { value: "animations/anim_meia_lua_de_compasso.glb", label: "Meia Lua De Compasso (53f / 1.8s, 108KB)" },
  { value: "animations/anim_meia_lua_de_compasso_back.glb", label: "Meia Lua De Compasso Back (67f / 2.2s, 120KB)" },
  { value: "animations/anim_meia_lua_de_frente.glb", label: "Meia Lua De Frente (75f / 2.5s, 127KB)" },
  { value: "animations/anim_military_signaling.glb", label: "Military Signaling (196f / 6.5s, 173KB)" },
  { value: "animations/anim_military_signaling_1.glb", label: "Military Signaling (186f / 6.2s, 182KB)" },
  { value: "animations/anim_mma_idle.glb", label: "Mma Idle (151f / 5.0s, 119KB)" },
  { value: "animations/anim_mma_kick.glb", label: "Mma Kick (62f / 2.1s, 116KB)" },
  { value: "animations/anim_mma_kick_1.glb", label: "Mma Kick (51f / 1.7s, 107KB)" },
  { value: "animations/anim_mma_kick_2.glb", label: "Mma Kick (49f / 1.6s, 106KB)" },
  { value: "animations/anim_moving_while_hanging.glb", label: "Moving While Hanging (43f / 1.4s, 101KB)" },
  { value: "animations/anim_neck_stretching.glb", label: "Neck Stretching (97f / 3.2s, 145KB)" },
  { value: "animations/anim_nervously_look_around.glb", label: "Nervously Look Around (189f / 6.3s, 192KB)" },
  { value: "animations/anim_ninja_idle.glb", label: "Ninja Idle (120f / 4.0s, 165KB)" },
  { value: "animations/anim_no.glb", label: "No (151f / 5.0s, 190KB)" },
  { value: "animations/anim_northern_soul_spin_combo.glb", label: "Northern Soul Spin Combo (266f / 8.9s, 285KB)" },
  { value: "animations/anim_offensive_idle.glb", label: "Offensive Idle (318f / 10.6s, 319KB)" },
  { value: "animations/anim_one_shoulder_lean.glb", label: "One Shoulder Lean (61f / 2.0s, 86KB)" },
  { value: "animations/anim_open_door_outwards.glb", label: "Open Door Outwards (124f / 4.1s, 168KB)" },
  { value: "animations/anim_opening.glb", label: "Opening (145f / 4.8s, 181KB)" },
  { value: "animations/anim_overhead_squat.glb", label: "Overhead Squat (57f / 1.9s, 94KB)" },
  { value: "animations/anim_patting.glb", label: "Patting (101f / 3.4s, 131KB)" },
  { value: "animations/anim_petting_animal.glb", label: "Petting Animal (426f / 14.2s, 418KB)" },
  { value: "animations/anim_pick_fruit.glb", label: "Pick Fruit (241f / 8.0s, 263KB)" },
  { value: "animations/anim_pick_fruit_2.glb", label: "pick fruit (187f / 6.2s, 214KB)" },
  { value: "animations/anim_pick_fruit_3.glb", label: "pick fruit (214f / 7.1s, 238KB)" },
  { value: "animations/anim_picking_at_shirt.glb", label: "Picking At Shirt (53f / 1.8s, 95KB)" },
  { value: "animations/anim_pike_walk.glb", label: "Pike Walk (196f / 6.5s, 227KB)" },
  { value: "animations/anim_pistol_idle.glb", label: "Pistol Idle (121f / 4.0s, 106KB)" },
  { value: "animations/anim_pistol_idle_1.glb", label: "Pistol Idle (250f / 8.3s, 156KB)" },
  { value: "animations/anim_pistol_idle_2.glb", label: "Pistol Idle (41f / 1.4s, 79KB)" },
  { value: "animations/anim_pistol_kneel_to_stand.glb", label: "Pistol Kneel To Stand (42f / 1.4s, 81KB)" },
  { value: "animations/anim_pivot.glb", label: "Pivot (136f / 4.5s, 114KB)" },
  { value: "animations/anim_plant_a_plant.glb", label: "Plant A Plant (228f / 7.6s, 252KB)" },
  { value: "animations/anim_plant_tree.glb", label: "Plant Tree (279f / 9.3s, 298KB)" },
  { value: "animations/anim_plotting.glb", label: "Plotting (100f / 3.3s, 148KB)" },
  { value: "animations/anim_pointing.glb", label: "Pointing (104f / 3.5s, 129KB)" },
  { value: "animations/anim_pontera.glb", label: "pontera (40f / 1.3s, 97KB)" },
  { value: "animations/anim_praying.glb", label: "Praying (201f / 6.7s, 219KB)" },
  { value: "animations/anim_praying_2.glb", label: "Praying (36f / 1.2s, 74KB)" },
  { value: "animations/anim_pull_plant.glb", label: "Pull Plant (141f / 4.7s, 184KB)" },
  { value: "animations/anim_pull_plant_1.glb", label: "Pull Plant (143f / 4.8s, 184KB)" },
  { value: "animations/anim_punch_combo.glb", label: "Punch Combo (67f / 2.2s, 91KB)" },
  { value: "animations/anim_punch_to_elbow_combo.glb", label: "Punch To Elbow Combo (151f / 5.0s, 244KB)" },
  { value: "animations/anim_punching.glb", label: "Punching (27f / 0.9s, 75KB)" },
  { value: "animations/anim_punching_1.glb", label: "Punching (31f / 1.0s, 77KB)" },
  { value: "animations/anim_punching_light.glb", label: "Punching Light (32f / 1.1s, 74KB)" },
  { value: "animations/anim_push_up.glb", label: "Push Up (47f / 1.6s, 83KB)" },
  { value: "animations/anim_putting_down.glb", label: "Putting Down (311f / 10.4s, 323KB)" },
  { value: "animations/anim_quad_punch.glb", label: "Quad Punch (66f / 2.2s, 91KB)" },
  { value: "animations/anim_queshada_1.glb", label: "queshada 1 (78f / 2.6s, 130KB)" },
  { value: "animations/anim_queshada_2.glb", label: "Queshada 2 (61f / 2.0s, 116KB)" },
  { value: "animations/anim_quick_informal_bow.glb", label: "Quick Informal Bow (83f / 2.8s, 133KB)" },
  { value: "animations/anim_rallying.glb", label: "Rallying (187f / 6.2s, 217KB)" },
  { value: "animations/anim_rapping.glb", label: "Rapping (238f / 7.9s, 260KB)" },
  { value: "animations/anim_rasteira_1.glb", label: "rasteira 1 (55f / 1.8s, 111KB)" },
  { value: "animations/anim_rasteira_2.glb", label: "rasteira 2 (75f / 2.5s, 127KB)" },
  { value: "animations/anim_receive_soccerball.glb", label: "Receive Soccerball (155f / 5.2s, 251KB)" },
  { value: "animations/anim_receiving_an_uppercut.glb", label: "Receiving An Uppercut (51f / 1.7s, 84KB)" },
  { value: "animations/anim_release_hostage_villain.glb", label: "Release Hostage - Villain (93f / 3.1s, 121KB)" },
  { value: "animations/anim_relieved_sigh.glb", label: "Relieved Sigh (91f / 3.0s, 140KB)" },
  { value: "animations/anim_restrain.glb", label: "Restrain (228f / 7.6s, 159KB)" },
  { value: "animations/anim_rib_hit.glb", label: "Rib Hit (31f / 1.0s, 76KB)" },
  { value: "animations/anim_right_block.glb", label: "Right Block (44f / 1.5s, 80KB)" },
  { value: "animations/anim_right_hook.glb", label: "Right Hook (34f / 1.1s, 88KB)" },
  { value: "animations/anim_right_strafe.glb", label: "right strafe (21f / 0.7s, 82KB)" },
  { value: "animations/anim_right_strafe_walk.glb", label: "right strafe walk (29f / 1.0s, 89KB)" },
  { value: "animations/anim_right_strafe_walking.glb", label: "right strafe walking (32f / 1.1s, 90KB)" },
  { value: "animations/anim_right_turn.glb", label: "Right Turn (36f / 1.2s, 95KB)" },
  { value: "animations/anim_right_turn_2.glb", label: "right turn (36f / 1.2s, 94KB)" },
  { value: "animations/anim_right_turn_90.glb", label: "right turn 90 (29f / 1.0s, 87KB)" },
  { value: "animations/anim_robot_hip_hop_dance.glb", label: "Robot Hip Hop Dance (464f / 15.5s, 435KB)" },
  { value: "animations/anim_roundhouse_kick.glb", label: "Roundhouse Kick (65f / 2.2s, 89KB)" },
  { value: "animations/anim_rumba_dancing.glb", label: "Rumba Dancing (72f / 2.4s, 107KB)" },
  { value: "animations/anim_rummaging.glb", label: "Rummaging (146f / 4.9s, 164KB)" },
  { value: "animations/anim_run_and_swing.glb", label: "Run And Swing (74f / 2.5s, 168KB)" },
  { value: "animations/anim_run_to_flip.glb", label: "Run To Flip (68f / 2.3s, 112KB)" },
  { value: "animations/anim_running.glb", label: "running (22f / 0.7s, 82KB)" },
  { value: "animations/anim_running_crawl.glb", label: "running crawl (20f / 0.7s, 82KB)" },
  { value: "animations/anim_running_slide.glb", label: "Running Slide (47f / 1.6s, 131KB)" },
  { value: "animations/anim_sad_idle.glb", label: "Sad Idle (121f / 4.0s, 162KB)" },
  { value: "animations/anim_salsa_dancing.glb", label: "Salsa Dancing (74f / 2.5s, 120KB)" },
  { value: "animations/anim_salsa_dancing_1.glb", label: "Salsa Dancing (844f / 28.1s, 764KB)" },
  { value: "animations/anim_salsa_dancing_2.glb", label: "Salsa Dancing (69f / 2.3s, 118KB)" },
  { value: "animations/anim_salsa_dancing_3.glb", label: "Salsa Dancing (648f / 21.6s, 541KB)" },
  { value: "animations/anim_salsa_dancing_4.glb", label: "Salsa Dancing (570f / 19.0s, 519KB)" },
  { value: "animations/anim_salsa_dancing_5.glb", label: "Salsa Dancing (69f / 2.3s, 118KB)" },
  { value: "animations/anim_salsa_dancing_man.glb", label: "Salsa Dancing man (79f / 2.6s, 125KB)" },
  { value: "animations/anim_samba_dancing.glb", label: "Samba Dancing (717f / 23.9s, 659KB)" },
  { value: "animations/anim_samba_dancing_1.glb", label: "Samba Dancing (655f / 21.8s, 607KB)" },
  { value: "animations/anim_samba_dancing_2.glb", label: "Samba Dancing (822f / 27.4s, 746KB)" },
  { value: "animations/anim_samba_dancing_5.glb", label: "Samba Dancing (560f / 18.7s, 477KB)" },
  { value: "animations/anim_sarcastic_head_nod.glb", label: "sarcastic head nod (66f / 2.2s, 119KB)" },
  { value: "animations/anim_scared.glb", label: "Scared (303f / 10.1s, 318KB)" },
  { value: "animations/anim_scissor_kick.glb", label: "Scissor Kick (84f / 2.8s, 134KB)" },
  { value: "animations/anim_searching_files_high.glb", label: "Searching Files High (293f / 9.8s, 308KB)" },
  { value: "animations/anim_searching_pockets.glb", label: "Searching Pockets (151f / 5.0s, 192KB)" },
  { value: "animations/anim_seated_idle.glb", label: "Seated Idle (126f / 4.2s, 142KB)" },
  { value: "animations/anim_shaking_hands_2.glb", label: "Shaking Hands 2 (132f / 4.4s, 172KB)" },
  { value: "animations/anim_shaking_head_no.glb", label: "shaking head no (52f / 1.7s, 108KB)" },
  { value: "animations/anim_shooting.glb", label: "Shooting (36f / 1.2s, 87KB)" },
  { value: "animations/anim_shooting_gun.glb", label: "Shooting Gun (160f / 5.3s, 190KB)" },
  { value: "animations/anim_shooting_pistol.glb", label: "Shooting Pistol (81f / 2.7s, 95KB)" },
  { value: "animations/anim_shoulder_throw_aggressor.glb", label: "Shoulder Throw, Aggressor (201f / 6.7s, 243KB)" },
  { value: "animations/anim_shoulder_throw_victim.glb", label: "Shoulder Throw, Victim (201f / 6.7s, 241KB)" },
  { value: "animations/anim_side_kick.glb", label: "Side Kick (61f / 2.0s, 88KB)" },
  { value: "animations/anim_silly_dancing.glb", label: "Silly Dancing (164f / 5.5s, 121KB)" },
  { value: "animations/anim_silly_dancing_2.glb", label: "Silly Dancing (116f / 3.9s, 106KB)" },
  { value: "animations/anim_singing.glb", label: "Singing (420f / 14.0s, 315KB)" },
  { value: "animations/anim_sit_to_stand.glb", label: "Sit To Stand (69f / 2.3s, 122KB)" },
  { value: "animations/anim_sitting.glb", label: "Sitting (179f / 6.0s, 210KB)" },
  { value: "animations/anim_sitting_2.glb", label: "Sitting (288f / 9.6s, 295KB)" },
  { value: "animations/anim_sitting_3.glb", label: "Sitting (134f / 4.5s, 174KB)" },
  { value: "animations/anim_sitting_angry.glb", label: "Sitting Angry (84f / 2.8s, 132KB)" },
  { value: "animations/anim_sitting_disbelief.glb", label: "Sitting Disbelief (144f / 4.8s, 184KB)" },
  { value: "animations/anim_sitting_drinking.glb", label: "Sitting Drinking (457f / 15.2s, 445KB)" },
  { value: "animations/anim_sitting_gun_motion.glb", label: "Sitting Gun Motion (145f / 4.8s, 163KB)" },
  { value: "animations/anim_sitting_idle.glb", label: "Sitting Idle (193f / 6.4s, 165KB)" },
  { value: "animations/anim_sitting_idle_1.glb", label: "Sitting Idle (309f / 10.3s, 302KB)" },
  { value: "animations/anim_sitting_laughing.glb", label: "Sitting Laughing (251f / 8.4s, 261KB)" },
  { value: "animations/anim_sitting_legs_swing.glb", label: "Sitting-legs-swing (64f / 2.1s, 88KB)" },
  { value: "animations/anim_sitting_talking.glb", label: "Sitting Talking (1323f / 44.1s, 1162KB)" },
  { value: "animations/anim_sitting_talking_1.glb", label: "Sitting Talking (1350f / 45.0s, 1183KB)" },
  { value: "animations/anim_sitting_thumbs_up.glb", label: "Sitting Thumbs Up (116f / 3.9s, 134KB)" },
  { value: "animations/anim_sitting_yell.glb", label: "Sitting Yell (114f / 3.8s, 156KB)" },
  { value: "animations/anim_situps.glb", label: "Situps (68f / 2.3s, 121KB)" },
  { value: "animations/anim_skinning_test.glb", label: "Skinning Test (59f / 2.0s, 111KB)" },
  { value: "animations/anim_sleeping_idle.glb", label: "Sleeping Idle (529f / 17.6s, 503KB)" },
  { value: "animations/anim_smoking.glb", label: "Smoking (538f / 17.9s, 503KB)" },
  { value: "animations/anim_snake_hip_hop_dance.glb", label: "Snake Hip Hop Dance (459f / 15.3s, 395KB)" },
  { value: "animations/anim_soccer_header.glb", label: "Soccer Header (72f / 2.4s, 119KB)" },
  { value: "animations/anim_soccer_idle.glb", label: "Soccer Idle (187f / 6.2s, 216KB)" },
  { value: "animations/anim_soccer_penalty_kick.glb", label: "Soccer Penalty Kick (46f / 1.5s, 1824KB)" },
  { value: "animations/anim_soccer_spin.glb", label: "Soccer Spin (39f / 1.3s, 103KB)" },
  { value: "animations/anim_soccer_tackle.glb", label: "Soccer Tackle (54f / 1.8s, 143KB)" },
  { value: "animations/anim_soccer_tackle_1.glb", label: "Soccer Tackle (83f / 2.8s, 189KB)" },
  { value: "animations/anim_soccer_tackle_2.glb", label: "Soccer Tackle (70f / 2.3s, 123KB)" },
  { value: "animations/anim_spat_in_face.glb", label: "Spat In Face (77f / 2.6s, 117KB)" },
  { value: "animations/anim_speedbag.glb", label: "Speedbag (200f / 6.7s, 230KB)" },
  { value: "animations/anim_spit_reaction.glb", label: "Spit Reaction (129f / 4.3s, 152KB)" },
  { value: "animations/anim_sprint_to_wall_climb.glb", label: "Sprint To Wall Climb (55f / 1.8s, 135KB)" },
  { value: "animations/anim_stall_soccerball.glb", label: "Stall Soccerball (65f / 2.2s, 117KB)" },
  { value: "animations/anim_stall_soccerball_1.glb", label: "Stall Soccerball (70f / 2.3s, 120KB)" },
  { value: "animations/anim_stand_up.glb", label: "Stand Up (146f / 4.9s, 185KB)" },
  { value: "animations/anim_stand_up_1.glb", label: "Stand Up (71f / 2.4s, 113KB)" },
  { value: "animations/anim_standard_run.glb", label: "Standard Run (23f / 0.8s, 84KB)" },
  { value: "animations/anim_standing_1h_cast_spell_01.glb", label: "standing 1H cast spell 01 (69f / 2.3s, 119KB)" },
  { value: "animations/anim_standing_1h_magic_attack_01.glb", label: "Standing 1H Magic Attack 01 (70f / 2.3s, 122KB)" },
  { value: "animations/anim_standing_1h_magic_attack_02.glb", label: "Standing 1H Magic Attack 02 (67f / 2.2s, 119KB)" },
  { value: "animations/anim_standing_1h_magic_attack_03.glb", label: "Standing 1H Magic Attack 03 (70f / 2.3s, 121KB)" },
  { value: "animations/anim_standing_2h_cast_spell_01.glb", label: "Standing 2H Cast Spell 01 (66f / 2.2s, 119KB)" },
  { value: "animations/anim_standing_2h_magic_area_attack_01.glb", label: "Standing 2H Magic Area Attack 01 (90f / 3.0s, 140KB)" },
  { value: "animations/anim_standing_2h_magic_area_attack_02.glb", label: "Standing 2H Magic Area Attack 02 (95f / 3.2s, 144KB)" },
  { value: "animations/anim_standing_2h_magic_attack_01.glb", label: "Standing 2H Magic Attack 01 (81f / 2.7s, 132KB)" },
  { value: "animations/anim_standing_2h_magic_attack_02.glb", label: "Standing 2H Magic Attack 02 (80f / 2.7s, 131KB)" },
  { value: "animations/anim_standing_2h_magic_attack_03.glb", label: "Standing 2H Magic Attack 03 (129f / 4.3s, 172KB)" },
  { value: "animations/anim_standing_2h_magic_attack_04.glb", label: "Standing 2H Magic Attack 04 (101f / 3.4s, 145KB)" },
  { value: "animations/anim_standing_2h_magic_attack_05.glb", label: "Standing 2H Magic Attack 05 (107f / 3.6s, 154KB)" },
  { value: "animations/anim_standing_arguing.glb", label: "Standing Arguing (625f / 20.8s, 585KB)" },
  { value: "animations/anim_standing_block_idle.glb", label: "standing block idle (51f / 1.7s, 93KB)" },
  { value: "animations/anim_standing_block_react_large.glb", label: "standing block react large (31f / 1.0s, 90KB)" },
  { value: "animations/anim_standing_cheering.glb", label: "Standing Cheering (104f / 3.5s, 150KB)" },
  { value: "animations/anim_standing_clap.glb", label: "Standing Clap (144f / 4.8s, 184KB)" },
  { value: "animations/anim_standing_cover_turn.glb", label: "Standing Cover Turn (31f / 1.0s, 86KB)" },
  { value: "animations/anim_standing_death_backward_01.glb", label: "Standing Death Backward 01 (78f / 2.6s, 112KB)" },
  { value: "animations/anim_standing_disarm_over_shoulder.glb", label: "standing disarm over shoulder (50f / 1.7s, 106KB)" },
  { value: "animations/anim_standing_disarm_underarm.glb", label: "standing disarm underarm (50f / 1.7s, 106KB)" },
  { value: "animations/anim_standing_idle.glb", label: "standing idle (55f / 1.8s, 95KB)" },
  { value: "animations/anim_standing_idle_looking_ver_1.glb", label: "standing idle looking ver. 1 (339f / 11.3s, 267KB)" },
  { value: "animations/anim_standing_idle_looking_ver_2.glb", label: "standing idle looking ver. 2 (231f / 7.7s, 203KB)" },
  { value: "animations/anim_standing_jump.glb", label: "Standing Jump (74f / 2.5s, 126KB)" },
  { value: "animations/anim_standing_jump_1.glb", label: "Standing Jump (45f / 1.5s, 1825KB)" },
  { value: "animations/anim_standing_melee_attack_360_high.glb", label: "standing melee attack 360 high (96f / 3.2s, 122KB)" },
  { value: "animations/anim_standing_melee_attack_360_low.glb", label: "standing melee attack 360 low (76f / 2.5s, 110KB)" },
  { value: "animations/anim_standing_melee_attack_backhand.glb", label: "standing melee attack backhand (96f / 3.2s, 121KB)" },
  { value: "animations/anim_standing_melee_attack_downward.glb", label: "standing melee attack downward (69f / 2.3s, 107KB)" },
  { value: "animations/anim_standing_melee_attack_horizontal.glb", label: "standing melee attack horizontal (73f / 2.4s, 108KB)" },
  { value: "animations/anim_standing_melee_attack_kick_ver_1.glb", label: "standing melee attack kick ver. 1 (57f / 1.9s, 99KB)" },
  { value: "animations/anim_standing_melee_attack_kick_ver_2.glb", label: "standing melee attack kick ver. 2 (43f / 1.4s, 91KB)" },
  { value: "animations/anim_standing_melee_combo_attack_ver_1.glb", label: "standing melee combo attack ver. 1 (141f / 4.7s, 149KB)" },
  { value: "animations/anim_standing_melee_combo_attack_ver_2.glb", label: "standing melee combo attack ver. 2 (126f / 4.2s, 140KB)" },
  { value: "animations/anim_standing_melee_combo_attack_ver_3.glb", label: "standing melee combo attack ver. 3 (83f / 2.8s, 115KB)" },
  { value: "animations/anim_standing_melee_kick.glb", label: "Standing Melee Kick (44f / 1.5s, 92KB)" },
  { value: "animations/anim_standing_melee_run_jump_attack.glb", label: "standing melee run jump attack (111f / 3.7s, 214KB)" },
  { value: "animations/anim_standing_react_death_right.glb", label: "Standing React Death Right (106f / 3.5s, 153KB)" },
  { value: "animations/anim_standing_run_back.glb", label: "standing run back (25f / 0.8s, 80KB)" },
  { value: "animations/anim_standing_run_forward.glb", label: "standing run forward (23f / 0.8s, 78KB)" },
  { value: "animations/anim_standing_taunt_battlecry.glb", label: "standing taunt battlecry (86f / 2.9s, 116KB)" },
  { value: "animations/anim_standing_taunt_chest_thump.glb", label: "standing taunt chest thump (77f / 2.6s, 109KB)" },
  { value: "animations/anim_standing_thumbs_up.glb", label: "Standing Thumbs Up (126f / 4.2s, 170KB)" },
  { value: "animations/anim_standing_turn_left_90.glb", label: "standing turn left 90 (53f / 1.8s, 97KB)" },
  { value: "animations/anim_standing_turn_right_90.glb", label: "standing turn right 90 (50f / 1.7s, 95KB)" },
  { value: "animations/anim_standing_using_touchscreen_tablet.glb", label: "Standing Using Touchscreen Tablet (995f / 33.2s, 668KB)" },
  { value: "animations/anim_standing_w_briefcase_idle.glb", label: "Standing W_Briefcase Idle (419f / 14.0s, 314KB)" },
  { value: "animations/anim_standing_walk_back.glb", label: "standing walk back (42f / 1.4s, 89KB)" },
  { value: "animations/anim_standing_walk_forward.glb", label: "standing walk forward (41f / 1.4s, 89KB)" },
  { value: "animations/anim_step_hip_hop_dance.glb", label: "Step Hip Hop Dance (235f / 7.8s, 175KB)" },
  { value: "animations/anim_stomach_hit.glb", label: "Stomach Hit (37f / 1.2s, 78KB)" },
  { value: "animations/anim_stomp.glb", label: "Stomp (57f / 1.9s, 104KB)" },
  { value: "animations/anim_sumo_high_pull.glb", label: "Sumo High Pull (79f / 2.6s, 93KB)" },
  { value: "animations/anim_superhuman_choke_lift.glb", label: "Superhuman Choke Lift (192f / 6.4s, 152KB)" },
  { value: "animations/anim_surprise_uppercut.glb", label: "Surprise Uppercut (106f / 3.5s, 128KB)" },
  { value: "animations/anim_surprised.glb", label: "Surprised (121f / 4.0s, 167KB)" },
  { value: "animations/anim_swagger_walk.glb", label: "Swagger Walk (85f / 2.8s, 120KB)" },
  { value: "animations/anim_swimming.glb", label: "Swimming (137f / 4.6s, 183KB)" },
  { value: "animations/anim_swimming_to_edge.glb", label: "Swimming To Edge (151f / 5.0s, 159KB)" },
  { value: "animations/anim_swing_dancing.glb", label: "Swing Dancing (628f / 20.9s, 439KB)" },
  { value: "animations/anim_swing_into_wall.glb", label: "Swing Into Wall (92f / 3.1s, 142KB)" },
  { value: "animations/anim_swing_to_land.glb", label: "Swing To Land (57f / 1.9s, 148KB)" },
  { value: "animations/anim_swing_to_land_1.glb", label: "Swing To Land (62f / 2.1s, 162KB)" },
  { value: "animations/anim_swing_to_land_2.glb", label: "Swing To Land (57f / 1.9s, 151KB)" },
  { value: "animations/anim_sword_and_shield_crouch_block_idle.glb", label: "Sword And Shield Crouch Block Idle (16f / 0.5s, 77KB)" },
  { value: "animations/anim_sword_and_shield_crouch_idle.glb", label: "Sword And Shield Crouch Idle (74f / 2.5s, 89KB)" },
  { value: "animations/anim_taken_hostage_victim.glb", label: "Taken Hostage - Victim (66f / 2.2s, 116KB)" },
  { value: "animations/anim_taken_hostage_villain.glb", label: "Taken Hostage - Villain (66f / 2.2s, 104KB)" },
  { value: "animations/anim_taking_item.glb", label: "Taking Item (142f / 4.7s, 161KB)" },
  { value: "animations/anim_taking_punch.glb", label: "Taking Punch (171f / 5.7s, 205KB)" },
  { value: "animations/anim_talking.glb", label: "Talking (179f / 6.0s, 214KB)" },
  { value: "animations/anim_talking_1.glb", label: "Talking (145f / 4.8s, 148KB)" },
  { value: "animations/anim_talking_2.glb", label: "Talking (114f / 3.8s, 149KB)" },
  { value: "animations/anim_talking_at_watercooler.glb", label: "Talking At Watercooler (1338f / 44.6s, 862KB)" },
  { value: "animations/anim_talking_on_a_cell_phone.glb", label: "Talking On A Cell Phone (1118f / 37.3s, 923KB)" },
  { value: "animations/anim_talking_on_phone.glb", label: "Talking On Phone (1166f / 38.9s, 1033KB)" },
  { value: "animations/anim_talking_phone_pacing.glb", label: "Talking Phone Pacing (1268f / 42.3s, 2066KB)" },
  { value: "animations/anim_talking_woman.glb", label: "Talking woman (179f / 6.0s, 214KB)" },
  { value: "animations/anim_taunt.glb", label: "Taunt (156f / 5.2s, 158KB)" },
  { value: "animations/anim_taunt_1.glb", label: "Taunt (117f / 3.9s, 162KB)" },
  { value: "animations/anim_taunt_2.glb", label: "Taunt (86f / 2.9s, 136KB)" },
  { value: "animations/anim_telling_a_secret.glb", label: "Telling A Secret (328f / 10.9s, 308KB)" },
  { value: "animations/anim_tender_placement.glb", label: "Tender Placement (279f / 9.3s, 296KB)" },
  { value: "animations/anim_texting.glb", label: "Texting (557f / 18.6s, 509KB)" },
  { value: "animations/anim_texting_while_standing.glb", label: "Texting While Standing (708f / 23.6s, 652KB)" },
  { value: "animations/anim_thankful.glb", label: "Thankful (91f / 3.0s, 140KB)" },
  { value: "animations/anim_thinking.glb", label: "Thinking (128f / 4.3s, 165KB)" },
  { value: "animations/anim_thoughtful_head_shake.glb", label: "Thoughtful Head Shake (93f / 3.1s, 142KB)" },
  { value: "animations/anim_threatening.glb", label: "Threatening (133f / 4.4s, 175KB)" },
  { value: "animations/anim_thriller_part_2.glb", label: "Thriller Part 2 (566f / 18.9s, 957KB)" },
  { value: "animations/anim_throwing.glb", label: "Throwing (168f / 5.6s, 178KB)" },
  { value: "animations/anim_tonic_seizure.glb", label: "Tonic Seizure (242f / 8.1s, 267KB)" },
  { value: "animations/anim_tripping.glb", label: "Tripping (84f / 2.8s, 136KB)" },
  { value: "animations/anim_troca_1.glb", label: "Troca 1 (156f / 5.2s, 190KB)" },
  { value: "animations/anim_tut_hip_hop_dance.glb", label: "Tut Hip Hop Dance (364f / 12.1s, 339KB)" },
  { value: "animations/anim_twist_dance.glb", label: "Twist Dance (284f / 9.5s, 301KB)" },
  { value: "animations/anim_typing.glb", label: "Typing (495f / 16.5s, 460KB)" },
  { value: "animations/anim_unarmed_equip_over_shoulder.glb", label: "unarmed equip over shoulder (51f / 1.7s, 107KB)" },
  { value: "animations/anim_unarmed_equip_underarm.glb", label: "unarmed equip underarm (34f / 1.1s, 93KB)" },
  { value: "animations/anim_unarmed_idle.glb", label: "unarmed idle (55f / 1.8s, 106KB)" },
  { value: "animations/anim_unarmed_idle_looking_ver_1.glb", label: "unarmed idle looking ver. 1 (334f / 11.1s, 337KB)" },
  { value: "animations/anim_unarmed_idle_looking_ver_2.glb", label: "unarmed idle looking ver. 2 (211f / 7.0s, 230KB)" },
  { value: "animations/anim_unarmed_jump.glb", label: "unarmed jump (71f / 2.4s, 123KB)" },
  { value: "animations/anim_unarmed_jump_running.glb", label: "unarmed jump running (43f / 1.4s, 107KB)" },
  { value: "animations/anim_unarmed_run_back.glb", label: "unarmed run back (24f / 0.8s, 83KB)" },
  { value: "animations/anim_unarmed_run_forward.glb", label: "unarmed run forward (25f / 0.8s, 75KB)" },
  { value: "animations/anim_unarmed_turn_left_90.glb", label: "unarmed turn left 90 (46f / 1.5s, 103KB)" },
  { value: "animations/anim_unarmed_turn_right_90.glb", label: "unarmed turn right 90 (46f / 1.5s, 101KB)" },
  { value: "animations/anim_unarmed_walk_back.glb", label: "unarmed walk back (40f / 1.3s, 98KB)" },
  { value: "animations/anim_unarmed_walk_forward.glb", label: "unarmed walk forward (42f / 1.4s, 100KB)" },
  { value: "animations/anim_uppercut.glb", label: "Uppercut (41f / 1.4s, 92KB)" },
  { value: "animations/anim_uppercut_jab.glb", label: "Uppercut Jab (109f / 3.6s, 129KB)" },
  { value: "animations/anim_vampiric_bite.glb", label: "Vampiric Bite (92f / 3.1s, 141KB)" },
  { value: "animations/anim_victory.glb", label: "Victory (184f / 6.1s, 219KB)" },
  { value: "animations/anim_walking.glb", label: "Walking (30f / 1.0s, 90KB)" },
  { value: "animations/anim_walking_backward.glb", label: "Walking Backward (38f / 1.3s, 95KB)" },
  { value: "animations/anim_walking_slow.glb", label: "Walking slow (139f / 4.6s, 180KB)" },
  { value: "animations/anim_wall_run.glb", label: "Wall Run (29f / 1.0s, 85KB)" },
  { value: "animations/anim_watering.glb", label: "Watering (169f / 5.6s, 207KB)" },
  { value: "animations/anim_waving.glb", label: "Waving (96f / 3.2s, 130KB)" },
  { value: "animations/anim_weight_shift.glb", label: "weight shift (284f / 9.5s, 300KB)" },
  { value: "animations/anim_wheelbarrow_dump.glb", label: "wheelbarrow dump (188f / 6.3s, 221KB)" },
  { value: "animations/anim_wheelbarrow_idle.glb", label: "wheelbarrow idle (44f / 1.5s, 80KB)" },
  { value: "animations/anim_wheelbarrow_walk_2.glb", label: "wheelbarrow walk (30f / 1.0s, 76KB)" },
  { value: "animations/anim_wiping_sweat.glb", label: "Wiping Sweat (80f / 2.7s, 114KB)" },
  { value: "animations/anim_writhing_in_pain.glb", label: "Writhing In Pain (171f / 5.7s, 130KB)" },
  { value: "animations/anim_writing.glb", label: "Writing (151f / 5.0s, 117KB)" },
  { value: "animations/anim_yelling.glb", label: "Yelling (236f / 7.9s, 262KB)" },
  { value: "animations/anim_ymca_dance.glb", label: "Ymca Dance (136f / 4.5s, 178KB)" },
  { value: "animations/anim_zombie_biting.glb", label: "Zombie Biting (209f / 7.0s, 238KB)" },
  { value: "animations/anim_zombie_biting_2.glb", label: "zombie biting (70f / 2.3s, 122KB)" },
  { value: "animations/anim_zombie_crawl.glb", label: "zombie crawl (155f / 5.2s, 197KB)" },
  { value: "animations/anim_zombie_death.glb", label: "zombie death (85f / 2.8s, 135KB)" },
  { value: "animations/anim_zombie_dying.glb", label: "zombie dying (100f / 3.3s, 148KB)" },
  { value: "animations/anim_zombie_neck_bite.glb", label: "zombie neck bite (123f / 4.1s, 167KB)" },
  { value: "animations/anim_zombie_scream.glb", label: "zombie scream (85f / 2.8s, 136KB)" },


].filter((v, i, a) => a.findIndex(t => t.value === v.value) === i).sort((a, b) => {
  if (a.value === "idle") return -1;
  if (b.value === "idle") return 1;
  const isATPose = a.value.includes("t_pose") || a.value.includes("t-pose") || a.value === "tpose";
  const isBTPose = b.value.includes("t_pose") || b.value.includes("t-pose") || b.value === "tpose";
  if (isATPose && !isBTPose) return -1;
  if (isBTPose && !isATPose) return 1;
  return a.label.localeCompare(b.label, 'fr', { sensitivity: 'base' });
});

