/**
 * animOptions.ts — Liste des animations disponibles.
 */

export const WALKER_ANIM_OPTIONS = [
  { value: "idle", label: "Idle / Return to Default" },
  { value: "media/sandbox/anims/miley_armature_01_rightward_movement_after_dodge.glb", label: "[MILEY] 01_rightward_movement (249f / 4.2s, 423KB)" },
  { value: "media/sandbox/anims/miley_armature_02_leftward_movement_after_dodge.glb", label: "[MILEY] 02_leftward_movement (261f / 4.3s, 490KB)" },
  { value: "media/sandbox/anims/miley_armature_03_side_movement_and_head_strikes.glb", label: "[MILEY] 03_side_movement (569f / 9.5s, 1015KB)" },
  { value: "media/sandbox/anims/miley_armature_04_large_step_right_dodge.glb", label: "[MILEY] 04_large_step_right_dodge (259f / 4.3s, 409KB)" },
  { value: "media/sandbox/anims/miley_armature_05_large_step_left_dodge.glb", label: "[MILEY] 05_large_step_left_dodge (283f / 4.7s, 431KB)" },
  { value: "media/sandbox/anims/miley_armature_06_head_strike_after_dodge.glb", label: "[MILEY] 06_head_strike (455f / 7.6s, 673KB)" },
  { value: "media/sandbox/anims/anim_t-pose.glb", label: "T-Pose (2f / 0.1s, 3486KB)" },
  { value: "media/sandbox/anims/anim_acknowledging.glb", label: "acknowledging (48f / 1.6s, 104KB)" },
  { value: "media/sandbox/anims/anim_action_idle_to_fight_idle.glb", label: "Action Idle To Fight Idle (31f / 1.0s, 90KB)" },
  { value: "media/sandbox/anims/anim_action_idle_to_standing_idle.glb", label: "Action Idle To Standing Idle (29f / 1.0s, 88KB)" },
  { value: "media/sandbox/anims/anim_administering_cpr.glb", label: "Administering Cpr (260f / 8.7s, 280KB)" },
  { value: "media/sandbox/anims/anim_aerial_evade.glb", label: "Aerial Evade (111f / 3.7s, 169KB)" },
  { value: "media/sandbox/anims/anim_agreeing.glb", label: "Agreeing (142f / 4.7s, 182KB)" },
  { value: "media/sandbox/anims/anim_aiming.glb", label: "Aiming (61f / 2.0s, 105KB)" },
  { value: "media/sandbox/anims/anim_aiming_gun.glb", label: "Aiming Gun (73f / 2.4s, 114KB)" },
  { value: "media/sandbox/anims/anim_air_squat_bent_arms.glb", label: "Air Squat Bent Arms (57f / 1.9s, 110KB)" },
  { value: "media/sandbox/anims/anim_angry.glb", label: "Angry (576f / 19.2s, 539KB)" },
  { value: "media/sandbox/anims/anim_angry_1.glb", label: "Angry (576f / 19.2s, 539KB)" },
  { value: "media/sandbox/anims/anim_angry_2.glb", label: "Angry (576f / 19.2s, 539KB)" },
  { value: "media/sandbox/anims/anim_angry_gesture.glb", label: "Angry Gesture (176f / 5.9s, 212KB)" },
  { value: "media/sandbox/anims/anim_annoyed_head_shake.glb", label: "annoyed head shake (74f / 2.5s, 109KB)" },
  { value: "media/sandbox/anims/anim_arm_stretching.glb", label: "Arm Stretching (267f / 8.9s, 286KB)" },
  { value: "media/sandbox/anims/anim_armada.glb", label: "Armada (50f / 1.7s, 106KB)" },
  { value: "media/sandbox/anims/anim_armada_1.glb", label: "Armada (50f / 1.7s, 106KB)" },
  { value: "media/sandbox/anims/anim_armada_to_esquiva.glb", label: "armada to esquiva (123f / 4.1s, 167KB)" },
  { value: "media/sandbox/anims/anim_arms_hip_hop_dance.glb", label: "Arms Hip Hop Dance (660f / 22.0s, 560KB)" },
  { value: "media/sandbox/anims/anim_arms_hip_hop_dance_1.glb", label: "Arms Hip Hop Dance (660f / 22.0s, 560KB)" },
  { value: "media/sandbox/anims/anim_ascending_stairs.glb", label: "Ascending Stairs (42f / 1.4s, 101KB)" },
  { value: "media/sandbox/anims/anim_asking_question.glb", label: "Asking Question (176f / 5.9s, 171KB)" },
  { value: "media/sandbox/anims/anim_au.glb", label: "Au (88f / 2.9s, 181KB)" },
  { value: "media/sandbox/anims/anim_au_to_role.glb", label: "Au To Role (121f / 4.0s, 249KB)" },
  { value: "media/sandbox/anims/anim_back_flip_to_uppercut.glb", label: "Back Flip To Uppercut (176f / 5.9s, 183KB)" },
  { value: "media/sandbox/anims/anim_back_squat.glb", label: "Back Squat (300f / 10.0s, 314KB)" },
  { value: "media/sandbox/anims/anim_backward_walking_turn.glb", label: "backward walking turn (60f / 2.0s, 112KB)" },
  { value: "media/sandbox/anims/anim_bartending.glb", label: "Bartending (408f / 13.6s, 403KB)" },
  { value: "media/sandbox/anims/anim_bash.glb", label: "Bash (121f / 4.0s, 165KB)" },
  { value: "media/sandbox/anims/anim_bashful.glb", label: "Bashful (331f / 11.0s, 339KB)" },
  { value: "media/sandbox/anims/anim_beckoning.glb", label: "Beckoning (79f / 2.6s, 110KB)" },
  { value: "media/sandbox/anims/anim_being_carried.glb", label: "Being Carried (158f / 5.3s, 172KB)" },
  { value: "media/sandbox/anims/anim_being_carried_1.glb", label: "Being Carried (110f / 3.7s, 139KB)" },
  { value: "media/sandbox/anims/anim_being_cocky.glb", label: "being cocky (87f / 2.9s, 137KB)" },
  { value: "media/sandbox/anims/anim_belly_dance.glb", label: "Belly Dance (590f / 19.7s, 499KB)" },
  { value: "media/sandbox/anims/anim_bellydancing.glb", label: "Bellydancing (762f / 25.4s, 637KB)" },
  { value: "media/sandbox/anims/anim_bencao.glb", label: "Bencao (42f / 1.4s, 100KB)" },
  { value: "media/sandbox/anims/anim_bicep_curl.glb", label: "Bicep Curl (177f / 5.9s, 126KB)" },
  { value: "media/sandbox/anims/anim_big_hit_to_head.glb", label: "Big Hit To Head (50f / 1.7s, 84KB)" },
  { value: "media/sandbox/anims/anim_big_hit_to_head_1.glb", label: "Big Hit To Head (48f / 1.6s, 82KB)" },
  { value: "media/sandbox/anims/anim_big_rib_hit.glb", label: "Big Rib Hit (49f / 1.6s, 83KB)" },
  { value: "media/sandbox/anims/anim_big_side_hit.glb", label: "Big Side Hit (45f / 1.5s, 82KB)" },
  { value: "media/sandbox/anims/anim_block.glb", label: "Block (87f / 2.9s, 131KB)" },
  { value: "media/sandbox/anims/anim_blocking.glb", label: "Blocking (37f / 1.2s, 76KB)" },
  { value: "media/sandbox/anims/anim_blow_a_kiss.glb", label: "Blow A Kiss (138f / 4.6s, 166KB)" },
  { value: "media/sandbox/anims/anim_body_jab_cross.glb", label: "Body Jab Cross (64f / 2.1s, 89KB)" },
  { value: "media/sandbox/anims/anim_booty_hip_hop_dance.glb", label: "Booty Hip Hop Dance (148f / 4.9s, 174KB)" },
  { value: "media/sandbox/anims/anim_box_idle.glb", label: "box idle (180f / 6.0s, 184KB)" },
  { value: "media/sandbox/anims/anim_box_turn.glb", label: "box turn (47f / 1.6s, 99KB)" },
  { value: "media/sandbox/anims/anim_box_turn_2.glb", label: "box turn (35f / 1.2s, 89KB)" },
  { value: "media/sandbox/anims/anim_box_walk_arc.glb", label: "box walk arc (37f / 1.2s, 93KB)" },
  { value: "media/sandbox/anims/anim_boxing.glb", label: "Boxing (53f / 1.8s, 85KB)" },
  { value: "media/sandbox/anims/anim_boxing_1.glb", label: "Boxing (67f / 2.2s, 90KB)" },
  { value: "media/sandbox/anims/anim_boxing_2.glb", label: "Boxing (67f / 2.2s, 90KB)" },
  { value: "media/sandbox/anims/anim_boxing_3.glb", label: "Boxing (128f / 4.3s, 171KB)" },
  { value: "media/sandbox/anims/anim_boxing_4.glb", label: "Boxing (67f / 2.2s, 90KB)" },
  { value: "media/sandbox/anims/anim_boxing_5.glb", label: "Boxing (61f / 2.0s, 88KB)" },
  { value: "media/sandbox/anims/anim_boxing_6.glb", label: "Boxing (75f / 2.5s, 93KB)" },
  { value: "media/sandbox/anims/anim_braced_hang.glb", label: "Braced Hang (40f / 1.3s, 92KB)" },
  { value: "media/sandbox/anims/anim_braced_hang_hop_left.glb", label: "Braced Hang Hop Left (46f / 1.5s, 96KB)" },
  { value: "media/sandbox/anims/anim_braced_hang_shimmy.glb", label: "Braced Hang Shimmy (36f / 1.2s, 89KB)" },
  { value: "media/sandbox/anims/anim_breakdance_1990.glb", label: "Breakdance 1990 (16f / 0.5s, 75KB)" },
  { value: "media/sandbox/anims/anim_breakdance_1990_2.glb", label: "breakdance 1990 (16f / 0.5s, 75KB)" },
  { value: "media/sandbox/anims/anim_breakdance_1990_3.glb", label: "breakdance 1990 (106f / 3.5s, 153KB)" },
  { value: "media/sandbox/anims/anim_breakdance_ending_1.glb", label: "breakdance ending 1 (196f / 6.5s, 228KB)" },
  { value: "media/sandbox/anims/anim_breakdance_ending_2.glb", label: "breakdance ending 2 (242f / 8.1s, 265KB)" },
  { value: "media/sandbox/anims/anim_breakdance_ending_3.glb", label: "breakdance ending 3 (193f / 6.4s, 225KB)" },
  { value: "media/sandbox/anims/anim_breakdance_footwork_1.glb", label: "breakdance footwork 1 (96f / 3.2s, 145KB)" },
  { value: "media/sandbox/anims/anim_breakdance_footwork_2.glb", label: "breakdance footwork 2 (49f / 1.6s, 106KB)" },
  { value: "media/sandbox/anims/anim_breakdance_footwork_3.glb", label: "breakdance footwork 3 (138f / 4.6s, 179KB)" },
  { value: "media/sandbox/anims/anim_breakdance_footwork_to_freeze.glb", label: "breakdance footwork to freeze (111f / 3.7s, 157KB)" },
  { value: "media/sandbox/anims/anim_breakdance_footwork_to_idle.glb", label: "Breakdance Footwork To Idle (289f / 9.6s, 305KB)" },
  { value: "media/sandbox/anims/anim_breakdance_footwork_to_idle_2.glb", label: "breakdance footwork to idle (289f / 9.6s, 305KB)" },
  { value: "media/sandbox/anims/anim_breakdance_freeze_var_1.glb", label: "breakdance freeze var 1 (125f / 4.2s, 168KB)" },
  { value: "media/sandbox/anims/anim_breakdance_freeze_var_2.glb", label: "breakdance freeze var 2 (147f / 4.9s, 187KB)" },
  { value: "media/sandbox/anims/anim_breakdance_freeze_var_3.glb", label: "breakdance freeze var 3 (186f / 6.2s, 221KB)" },
  { value: "media/sandbox/anims/anim_breakdance_freeze_var_4.glb", label: "breakdance freeze var 4 (150f / 5.0s, 189KB)" },
  { value: "media/sandbox/anims/anim_breakdance_freezes.glb", label: "Breakdance Freezes (202f / 6.7s, 232KB)" },
  { value: "media/sandbox/anims/anim_breakdance_freezes_1.glb", label: "Breakdance Freezes (202f / 6.7s, 232KB)" },
  { value: "media/sandbox/anims/anim_breakdance_freezes_2.glb", label: "Breakdance Freezes (202f / 6.7s, 232KB)" },
  { value: "media/sandbox/anims/anim_breakdance_ready.glb", label: "breakdance ready (43f / 1.4s, 101KB)" },
  { value: "media/sandbox/anims/anim_breakdance_ready_2.glb", label: "breakdance ready (33f / 1.1s, 92KB)" },
  { value: "media/sandbox/anims/anim_breakdance_ready_3.glb", label: "breakdance ready (64f / 2.1s, 112KB)" },
  { value: "media/sandbox/anims/anim_breakdance_swipes.glb", label: "breakdance swipes (91f / 3.0s, 140KB)" },
  { value: "media/sandbox/anims/anim_breakdance_uprock.glb", label: "breakdance uprock (64f / 2.1s, 118KB)" },
  { value: "media/sandbox/anims/anim_breakdance_uprock_2.glb", label: "breakdance uprock (109f / 3.6s, 155KB)" },
  { value: "media/sandbox/anims/anim_breakdance_uprock_to_ground.glb", label: "breakdance uprock to ground (37f / 1.2s, 95KB)" },
  { value: "media/sandbox/anims/anim_breakdance_uprock_to_ground_2.glb", label: "breakdance uprock to ground (137f / 4.6s, 179KB)" },
  { value: "media/sandbox/anims/anim_breakdance_uprock_var_1.glb", label: "breakdance uprock var 1 (64f / 2.1s, 118KB)" },
  { value: "media/sandbox/anims/anim_breakdance_uprock_var_1_end.glb", label: "breakdance uprock var 1 end (63f / 2.1s, 117KB)" },
  { value: "media/sandbox/anims/anim_breakdance_uprock_var_1_start.glb", label: "breakdance uprock var 1 start (46f / 1.5s, 103KB)" },
  { value: "media/sandbox/anims/anim_breakdance_uprock_var_2.glb", label: "breakdance uprock var 2 (159f / 5.3s, 197KB)" },
  { value: "media/sandbox/anims/anim_brooklyn_uprock.glb", label: "Brooklyn Uprock (147f / 4.9s, 187KB)" },
  { value: "media/sandbox/anims/anim_brutal_assassination.glb", label: "Brutal Assassination (149f / 5.0s, 182KB)" },
  { value: "media/sandbox/anims/anim_brutal_assassination_1.glb", label: "Brutal Assassination (149f / 5.0s, 156KB)" },
  { value: "media/sandbox/anims/anim_burpee.glb", label: "Burpee (95f / 3.2s, 144KB)" },
  { value: "media/sandbox/anims/anim_burpee_end.glb", label: "Burpee End (74f / 2.5s, 126KB)" },
  { value: "media/sandbox/anims/anim_button_pushing.glb", label: "Button Pushing (98f / 3.3s, 125KB)" },
  { value: "media/sandbox/anims/anim_can_can.glb", label: "Can Can (111f / 3.7s, 157KB)" },
  { value: "media/sandbox/anims/anim_capoeira.glb", label: "Capoeira (145f / 4.8s, 181KB)" },
  { value: "media/sandbox/anims/anim_capoeira_2.glb", label: "capoeira (532f / 17.7s, 506KB)" },
  { value: "media/sandbox/anims/anim_capoeira_3.glb", label: "capoeira (145f / 4.8s, 181KB)" },
  { value: "media/sandbox/anims/anim_cards.glb", label: "Cards (274f / 9.1s, 292KB)" },
  { value: "media/sandbox/anims/anim_catwalk_sequence_01.glb", label: "Catwalk Sequence 01 (439f / 14.6s, 430KB)" },
  { value: "media/sandbox/anims/anim_catwalk_sequence_02.glb", label: "Catwalk Sequence 02 (366f / 12.2s, 370KB)" },
  { value: "media/sandbox/anims/anim_catwalk_sequence_03.glb", label: "Catwalk Sequence 03 (373f / 12.4s, 376KB)" },
  { value: "media/sandbox/anims/anim_catwalk_sequence_04.glb", label: "Catwalk Sequence 04 (365f / 12.2s, 369KB)" },
  { value: "media/sandbox/anims/anim_catwalk_sequence_05.glb", label: "Catwalk Sequence 05 (306f / 10.2s, 320KB)" },
  { value: "media/sandbox/anims/anim_catwalk_walking_not_in_place.glb", label: "Catwalk Walking not in place (36f / 1.2s, 94KB)" },
  { value: "media/sandbox/anims/anim_ch22_nonpbr.glb", label: "Ch22 Nonpbr (2f / 0.1s, 61556KB)" },
  { value: "media/sandbox/anims/anim_ch47_nonpbr.glb", label: "Ch47 Nonpbr (2f / 0.1s, 56320KB)" },
  { value: "media/sandbox/anims/anim_chapa_2.glb", label: "Chapa 2 (42f / 1.4s, 100KB)" },
  { value: "media/sandbox/anims/anim_chapa_giratoria.glb", label: "Chapa-Giratoria (91f / 3.0s, 140KB)" },
  { value: "media/sandbox/anims/anim_chapa_giratoria_2.glb", label: "chapa giratoria 2 (72f / 2.4s, 125KB)" },
  { value: "media/sandbox/anims/anim_chapaeu_de_couro.glb", label: "chapaeu de couro (104f / 3.5s, 151KB)" },
  { value: "media/sandbox/anims/anim_cheering.glb", label: "Cheering (58f / 1.9s, 111KB)" },
  { value: "media/sandbox/anims/anim_cheering_while_sitting.glb", label: "Cheering While Sitting (131f / 4.4s, 171KB)" },
  { value: "media/sandbox/anims/anim_clapping.glb", label: "Clapping (36f / 1.2s, 79KB)" },
  { value: "media/sandbox/anims/anim_clean_and_jerk.glb", label: "Clean And Jerk (521f / 17.4s, 489KB)" },
  { value: "media/sandbox/anims/anim_climbing.glb", label: "Climbing (116f / 3.9s, 151KB)" },
  { value: "media/sandbox/anims/anim_climbing_1.glb", label: "Climbing (116f / 3.9s, 229KB)" },
  { value: "media/sandbox/anims/anim_climbing_a_rope.glb", label: "Climbing A Rope (78f / 2.6s, 131KB)" },
  { value: "media/sandbox/anims/anim_climbing_a_rope_1.glb", label: "Climbing A Rope (73f / 2.4s, 124KB)" },
  { value: "media/sandbox/anims/anim_climbing_down.glb", label: "Climbing Down (104f / 3.5s, 134KB)" },
  { value: "media/sandbox/anims/anim_climbing_up_wall.glb", label: "Climbing Up Wall (61f / 2.0s, 113KB)" },
  { value: "media/sandbox/anims/anim_closing.glb", label: "Closing (186f / 6.2s, 215KB)" },
  { value: "media/sandbox/anims/anim_cocky_head_turn.glb", label: "Cocky Head Turn (77f / 2.6s, 129KB)" },
  { value: "media/sandbox/anims/anim_convulsing.glb", label: "Convulsing (58f / 1.9s, 104KB)" },
  { value: "media/sandbox/anims/anim_corkscrew_kip_up.glb", label: "Corkscrew Kip Up (84f / 2.8s, 196KB)" },
  { value: "media/sandbox/anims/anim_counting.glb", label: "Counting (200f / 6.7s, 185KB)" },
  { value: "media/sandbox/anims/anim_couple_man.glb", label: "Couple Man (81f / 3.3s, 24310KB)" },
  { value: "media/sandbox/anims/anim_couple_woman.glb", label: "Couple Woman (81f / 3.3s, 7957KB)" },
  { value: "media/sandbox/anims/anim_cow_milking.glb", label: "Cow Milking (137f / 4.6s, 179KB)" },
  { value: "media/sandbox/anims/anim_crawl_backwards.glb", label: "Crawl Backwards (120f / 4.0s, 206KB)" },
  { value: "media/sandbox/anims/anim_crawl_backwards_in_prone.glb", label: "Crawl Backwards In Prone (30f / 1.0s, 78KB)" },
  { value: "media/sandbox/anims/anim_crawling_backwards.glb", label: "Crawling Backwards (63f / 2.1s, 107KB)" },
  { value: "media/sandbox/anims/anim_cross_jumps_rotation.glb", label: "Cross Jumps Rotation (62f / 2.1s, 115KB)" },
  { value: "media/sandbox/anims/anim_cross_punch.glb", label: "Cross Punch (61f / 2.0s, 88KB)" },
  { value: "media/sandbox/anims/anim_crossleg_freeze.glb", label: "Crossleg Freeze (62f / 2.1s, 116KB)" },
  { value: "media/sandbox/anims/anim_crouch_idle.glb", label: "crouch idle (51f / 1.7s, 95KB)" },
  { value: "media/sandbox/anims/anim_crouch_look_around_corner.glb", label: "Crouch Look Around Corner (91f / 3.0s, 124KB)" },
  { value: "media/sandbox/anims/anim_crouch_to_stand.glb", label: "Crouch To Stand (101f / 3.4s, 101KB)" },
  { value: "media/sandbox/anims/anim_crouch_to_standing_idle.glb", label: "crouch to standing idle (19f / 0.6s, 76KB)" },
  { value: "media/sandbox/anims/anim_crying.glb", label: "Crying (189f / 6.3s, 216KB)" },
  { value: "media/sandbox/anims/anim_dancing.glb", label: "Dancing (372f / 12.4s, 403KB)" },
  { value: "media/sandbox/anims/anim_dancing_1.glb", label: "Dancing (643f / 21.4s, 538KB)" },
  { value: "media/sandbox/anims/anim_dancing_2.glb", label: "Dancing (80f / 2.7s, 144KB)" },
  { value: "media/sandbox/anims/anim_dancing_3.glb", label: "Dancing (80f / 2.7s, 144KB)" },
  { value: "media/sandbox/anims/anim_dancing_4.glb", label: "Dancing (372f / 12.4s, 403KB)" },
  { value: "media/sandbox/anims/anim_dancing_5.glb", label: "Dancing (643f / 21.4s, 538KB)" },
  { value: "media/sandbox/anims/anim_dancing_6.glb", label: "Dancing (489f / 16.3s, 470KB)" },
  { value: "media/sandbox/anims/anim_dancing_7.glb", label: "Dancing (80f / 2.7s, 144KB)" },
  { value: "media/sandbox/anims/anim_dancing_maraschino_step.glb", label: "Dancing Maraschino Step (98f / 3.3s, 148KB)" },
  { value: "media/sandbox/anims/anim_dancing_maraschino_step_1.glb", label: "Dancing Maraschino Step (98f / 3.3s, 146KB)" },
  { value: "media/sandbox/anims/anim_dancing_running_man.glb", label: "Dancing Running Man (326f / 10.9s, 335KB)" },
  { value: "media/sandbox/anims/anim_dancing_twerk.glb", label: "Dancing Twerk (457f / 15.2s, 444KB)" },
  { value: "media/sandbox/anims/anim_defeat.glb", label: "Defeat (144f / 4.8s, 118KB)" },
  { value: "media/sandbox/anims/anim_descending_stairs.glb", label: "Descending Stairs (13f / 0.4s, 77KB)" },
  { value: "media/sandbox/anims/anim_dig_and_plant_seeds.glb", label: "Dig And Plant Seeds (166f / 5.5s, 204KB)" },
  { value: "media/sandbox/anims/anim_dig_and_plant_seeds_1.glb", label: "Dig And Plant Seeds (166f / 5.5s, 203KB)" },
  { value: "media/sandbox/anims/anim_disappointed.glb", label: "Disappointed (127f / 4.2s, 164KB)" },
  { value: "media/sandbox/anims/anim_dismissing_gesture.glb", label: "dismissing gesture (99f / 3.3s, 147KB)" },
  { value: "media/sandbox/anims/anim_dive_roll.glb", label: "Dive Roll (119f / 4.0s, 238KB)" },
  { value: "media/sandbox/anims/anim_dodging.glb", label: "Dodging (68f / 2.3s, 91KB)" },
  { value: "media/sandbox/anims/anim_dodging_1.glb", label: "Dodging (71f / 2.4s, 91KB)" },
  { value: "media/sandbox/anims/anim_double_leg_takedown___attacker.glb", label: "Double Leg Takedown   Attacker (218f / 7.3s, 247KB)" },
  { value: "media/sandbox/anims/anim_double_leg_takedown_attacker.glb", label: "Double Leg Takedown - Attacker (106f / 3.5s, 155KB)" },
  { value: "media/sandbox/anims/anim_double_leg_takedown_victim.glb", label: "Double Leg Takedown - Victim (218f / 7.3s, 248KB)" },
  { value: "media/sandbox/anims/anim_drinking_fountain.glb", label: "Drinking Fountain (308f / 10.3s, 323KB)" },
  { value: "media/sandbox/anims/anim_dropping.glb", label: "Dropping (135f / 4.5s, 156KB)" },
  { value: "media/sandbox/anims/anim_drunk_idle.glb", label: "drunk idle (223f / 7.4s, 239KB)" },
  { value: "media/sandbox/anims/anim_drunk_idle_variation.glb", label: "Drunk Idle Variation (120f / 4.0s, 164KB)" },
  { value: "media/sandbox/anims/anim_drunk_idle_variation_1.glb", label: "Drunk Idle Variation (163f / 5.4s, 200KB)" },
  { value: "media/sandbox/anims/anim_drunk_idle_variation_2.glb", label: "drunk idle variation (162f / 5.4s, 199KB)" },
  { value: "media/sandbox/anims/anim_drunk_run_backward.glb", label: "drunk run backward (34f / 1.1s, 92KB)" },
  { value: "media/sandbox/anims/anim_drunk_run_forward.glb", label: "drunk run forward (56f / 1.9s, 133KB)" },
  { value: "media/sandbox/anims/anim_drunk_running_left_turn.glb", label: "drunk running left turn (46f / 1.5s, 104KB)" },
  { value: "media/sandbox/anims/anim_drunk_turn.glb", label: "drunk turn (48f / 1.6s, 105KB)" },
  { value: "media/sandbox/anims/anim_drunk_walk.glb", label: "Drunk Walk (91f / 3.0s, 142KB)" },
  { value: "media/sandbox/anims/anim_drunk_walk_backwards.glb", label: "drunk walk backwards (48f / 1.6s, 103KB)" },
  { value: "media/sandbox/anims/anim_drunk_walking_turn.glb", label: "drunk walking turn (78f / 2.6s, 130KB)" },
  { value: "media/sandbox/anims/anim_ducking.glb", label: "Ducking (45f / 1.5s, 95KB)" },
  { value: "media/sandbox/anims/anim_dwarf_idle.glb", label: "Dwarf Idle (211f / 7.0s, 233KB)" },
  { value: "media/sandbox/anims/anim_dying.glb", label: "Dying (174f / 5.8s, 211KB)" },
  { value: "media/sandbox/anims/anim_elbow_punch.glb", label: "Elbow Punch (53f / 1.8s, 85KB)" },
  { value: "media/sandbox/anims/anim_elbow_uppercut_combo.glb", label: "Elbow Uppercut Combo (74f / 2.5s, 109KB)" },
  { value: "media/sandbox/anims/anim_entering_code.glb", label: "Entering Code (226f / 7.5s, 214KB)" },
  { value: "media/sandbox/anims/anim_entry.glb", label: "Entry (220f / 7.3s, 244KB)" },
  { value: "media/sandbox/anims/anim_esquiva_1.glb", label: "esquiva 1 (139f / 4.6s, 180KB)" },
  { value: "media/sandbox/anims/anim_esquiva_2.glb", label: "Esquiva 2 (68f / 2.3s, 121KB)" },
  { value: "media/sandbox/anims/anim_esquiva_3.glb", label: "esquiva 3 (66f / 2.2s, 120KB)" },
  { value: "media/sandbox/anims/anim_esquiva_4.glb", label: "esquiva 4 (85f / 2.8s, 135KB)" },
  { value: "media/sandbox/anims/anim_esquiva_5.glb", label: "esquiva 5 (66f / 2.2s, 120KB)" },
  { value: "media/sandbox/anims/anim_fall_flat.glb", label: "Fall Flat (77f / 2.6s, 176KB)" },
  { value: "media/sandbox/anims/anim_falling.glb", label: "Falling (136f / 4.5s, 165KB)" },
  { value: "media/sandbox/anims/anim_falling_idle.glb", label: "Falling Idle (22f / 0.7s, 79KB)" },
  { value: "media/sandbox/anims/anim_female_dance_pose.glb", label: "Female Dance Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_dance_pose_1.glb", label: "Female Dance Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_dance_pose_2.glb", label: "Female Dance Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_dynamic_pose.glb", label: "Female Dynamic Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_laying_pose.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_laying_pose_1.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_laying_pose_2.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_laying_pose_3.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_laying_pose_4.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_laying_pose_5.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_laying_pose_6.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_laying_pose_7.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_laying_pose_8.glb", label: "Female Laying Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_laying_pose_9.glb", label: "Female Laying Pose (2f / 0.1s, 65KB)" },
  { value: "media/sandbox/anims/anim_female_locomotion_pose.glb", label: "Female Locomotion Pose (2f / 0.1s, 1796KB)" },
  { value: "media/sandbox/anims/anim_female_peek_and_aim.glb", label: "Female Peek And Aim (79f / 2.6s, 91KB)" },
  { value: "media/sandbox/anims/anim_female_sitting_pose.glb", label: "Female Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_sitting_pose_1.glb", label: "Female Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_sitting_pose_2.glb", label: "Female Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_sitting_pose_3.glb", label: "Female Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_sitting_pose_4.glb", label: "Female Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_standing_pose.glb", label: "Female Standing Pose (2f / 0.1s, 62KB)" },
  { value: "media/sandbox/anims/anim_female_standing_pose_1.glb", label: "Female Standing Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_standing_pose_2.glb", label: "Female Standing Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_standing_pose_3.glb", label: "Female Standing Pose (2f / 0.1s, 62KB)" },
  { value: "media/sandbox/anims/anim_female_standing_pose_4.glb", label: "Female Standing Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_female_walk.glb", label: "Female Walk (36f / 1.2s, 79KB)" },
  { value: "media/sandbox/anims/anim_femme_peek_around_corner.glb", label: "Femme Peek Around Corner (74f / 2.5s, 92KB)" },
  { value: "media/sandbox/anims/anim_fight_idle.glb", label: "Fight Idle (72f / 2.4s, 1824KB)" },
  { value: "media/sandbox/anims/anim_finding.glb", label: "Finding (414f / 13.8s, 410KB)" },
  { value: "media/sandbox/anims/anim_fireball.glb", label: "Fireball (102f / 3.4s, 150KB)" },
  { value: "media/sandbox/anims/anim_fist_fight_b.glb", label: "Fist Fight B (141f / 4.7s, 182KB)" },
  { value: "media/sandbox/anims/anim_flair.glb", label: "Flair (31f / 1.0s, 90KB)" },
  { value: "media/sandbox/anims/anim_flair_2.glb", label: "flair (31f / 1.0s, 90KB)" },
  { value: "media/sandbox/anims/anim_flair_3.glb", label: "flair (51f / 1.7s, 107KB)" },
  { value: "media/sandbox/anims/anim_flip_kick.glb", label: "Flip Kick (62f / 2.1s, 117KB)" },
  { value: "media/sandbox/anims/anim_flip_kick_1.glb", label: "Flip Kick (62f / 2.1s, 117KB)" },
  { value: "media/sandbox/anims/anim_floating.glb", label: "Floating (109f / 3.6s, 152KB)" },
  { value: "media/sandbox/anims/anim_flying.glb", label: "Flying (80f / 2.7s, 153KB)" },
  { value: "media/sandbox/anims/anim_flying_bicycle_kick.glb", label: "Flying Bicycle Kick (21f / 0.7s, 72KB)" },
  { value: "media/sandbox/anims/anim_focus.glb", label: "Focus (166f / 5.5s, 177KB)" },
  { value: "media/sandbox/anims/anim_free_hang_hop_left.glb", label: "Free Hang Hop Left (64f / 2.1s, 106KB)" },
  { value: "media/sandbox/anims/anim_free_hang_hop_right.glb", label: "Free Hang Hop Right (64f / 2.1s, 107KB)" },
  { value: "media/sandbox/anims/anim_freehang_drop.glb", label: "Freehang Drop (41f / 1.4s, 93KB)" },
  { value: "media/sandbox/anims/anim_front_flip.glb", label: "Front Flip (51f / 1.7s, 143KB)" },
  { value: "media/sandbox/anims/anim_front_twist_flip.glb", label: "Front Twist Flip (67f / 2.2s, 169KB)" },
  { value: "media/sandbox/anims/anim_gaming.glb", label: "Gaming (152f / 5.1s, 155KB)" },
  { value: "media/sandbox/anims/anim_gangnam_style.glb", label: "gangnam style (372f / 12.4s, 373KB)" },
  { value: "media/sandbox/anims/anim_getting_hit_backwards.glb", label: "Getting Hit Backwards (81f / 2.7s, 132KB)" },
  { value: "media/sandbox/anims/anim_getting_up.glb", label: "Getting Up (82f / 2.7s, 120KB)" },
  { value: "media/sandbox/anims/anim_ginga_backward.glb", label: "ginga backward (35f / 1.2s, 94KB)" },
  { value: "media/sandbox/anims/anim_ginga_forward.glb", label: "ginga forward (38f / 1.3s, 97KB)" },
  { value: "media/sandbox/anims/anim_ginga_sideways_1.glb", label: "ginga sideways 1 (51f / 1.7s, 107KB)" },
  { value: "media/sandbox/anims/anim_ginga_sideways_2.glb", label: "ginga sideways 2 (68f / 2.3s, 127KB)" },
  { value: "media/sandbox/anims/anim_ginga_sideways_to_au.glb", label: "ginga sideways to au (114f / 3.8s, 179KB)" },
  { value: "media/sandbox/anims/anim_ginga_variation_1.glb", label: "Ginga Variation 1 (107f / 3.6s, 151KB)" },
  { value: "media/sandbox/anims/anim_ginga_variation_2.glb", label: "ginga variation 2 (115f / 3.8s, 160KB)" },
  { value: "media/sandbox/anims/anim_ginga_variation_3.glb", label: "ginga variation 3 (87f / 2.9s, 136KB)" },
  { value: "media/sandbox/anims/anim_goalkeeper_body_block.glb", label: "Goalkeeper Body Block (104f / 3.5s, 151KB)" },
  { value: "media/sandbox/anims/anim_goalkeeper_miss.glb", label: "Goalkeeper Miss (89f / 3.0s, 139KB)" },
  { value: "media/sandbox/anims/anim_golf_chip.glb", label: "Golf Chip (384f / 12.8s, 204KB)" },
  { value: "media/sandbox/anims/anim_goofy_running.glb", label: "Goofy Running (20f / 0.7s, 76KB)" },
  { value: "media/sandbox/anims/anim_great_sword_idle.glb", label: "Great Sword Idle (114f / 3.8s, 130KB)" },
  { value: "media/sandbox/anims/anim_great_sword_power_up.glb", label: "Great Sword Power Up (106f / 3.5s, 110KB)" },
  { value: "media/sandbox/anims/anim_guitar_playing.glb", label: "Guitar Playing (144f / 4.8s, 169KB)" },
  { value: "media/sandbox/anims/anim_gunplay.glb", label: "Gunplay (7f / 0.2s, 69KB)" },
  { value: "media/sandbox/anims/anim_gunplay_1.glb", label: "Gunplay (77f / 2.6s, 90KB)" },
  { value: "media/sandbox/anims/anim_gunplay_shooting.glb", label: "Gunplay Shooting (77f / 2.6s, 90KB)" },
  { value: "media/sandbox/anims/anim_hand_raising.glb", label: "Hand Raising (123f / 4.1s, 164KB)" },
  { value: "media/sandbox/anims/anim_hanging_idle.glb", label: "Hanging Idle (71f / 2.4s, 114KB)" },
  { value: "media/sandbox/anims/anim_happy_hand_gesture.glb", label: "Happy Hand Gesture (89f / 3.0s, 138KB)" },
  { value: "media/sandbox/anims/anim_happy_idle.glb", label: "Happy Idle (89f / 3.0s, 136KB)" },
  { value: "media/sandbox/anims/anim_happy_walk.glb", label: "Happy Walk (34f / 1.1s, 95KB)" },
  { value: "media/sandbox/anims/anim_happy_walk_backward.glb", label: "Happy Walk Backward (32f / 1.1s, 93KB)" },
  { value: "media/sandbox/anims/anim_happy_walk_not_in_place.glb", label: "Happy Walk not in place (34f / 1.1s, 93KB)" },
  { value: "media/sandbox/anims/anim_hard_head_nod.glb", label: "hard head nod (50f / 1.7s, 106KB)" },
  { value: "media/sandbox/anims/anim_hard_landing.glb", label: "Hard Landing (61f / 2.0s, 106KB)" },
  { value: "media/sandbox/anims/anim_having_a_meeting_female.glb", label: "Having A Meeting, Female (1401f / 46.7s, 1227KB)" },
  { value: "media/sandbox/anims/anim_having_a_meeting_male.glb", label: "Having A Meeting, Male (1401f / 46.7s, 1227KB)" },
  { value: "media/sandbox/anims/anim_head_hit.glb", label: "Head Hit (36f / 1.2s, 78KB)" },
  { value: "media/sandbox/anims/anim_head_nod_yes.glb", label: "Head Nod Yes (79f / 2.6s, 131KB)" },
  { value: "media/sandbox/anims/anim_head_spinning.glb", label: "Head Spinning (26f / 0.9s, 73KB)" },
  { value: "media/sandbox/anims/anim_headbutt.glb", label: "Headbutt (64f / 2.1s, 89KB)" },
  { value: "media/sandbox/anims/anim_header.glb", label: "Header (44f / 1.5s, 100KB)" },
  { value: "media/sandbox/anims/anim_header_soccerball.glb", label: "Header Soccerball (58f / 1.9s, 110KB)" },
  { value: "media/sandbox/anims/anim_header_soccerball_1.glb", label: "Header Soccerball (127f / 4.2s, 155KB)" },
  { value: "media/sandbox/anims/anim_helping_out.glb", label: "Helping Out (225f / 7.5s, 217KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing.glb", label: "Hip Hop Dancing (558f / 18.6s, 475KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_1.glb", label: "Hip Hop Dancing (474f / 15.8s, 428KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_10.glb", label: "Hip Hop Dancing (558f / 18.6s, 475KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_11.glb", label: "Hip Hop Dancing (474f / 15.8s, 428KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_12.glb", label: "Hip Hop Dancing (558f / 18.6s, 2207KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_13.glb", label: "Hip Hop Dancing (184f / 6.1s, 200KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_14.glb", label: "Hip Hop Dancing (143f / 4.8s, 124KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_15.glb", label: "Hip Hop Dancing (143f / 4.8s, 124KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_16.glb", label: "Hip Hop Dancing (471f / 15.7s, 412KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_17.glb", label: "Hip Hop Dancing (392f / 13.1s, 353KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_18.glb", label: "Hip Hop Dancing (124f / 4.1s, 129KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_19.glb", label: "Hip Hop Dancing (135f / 4.5s, 113KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_2.glb", label: "Hip Hop Dancing (410f / 13.7s, 404KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_3.glb", label: "Hip Hop Dancing (360f / 12.0s, 329KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_4.glb", label: "Hip Hop Dancing (471f / 15.7s, 412KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_5.glb", label: "Hip Hop Dancing (102f / 3.4s, 115KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_6.glb", label: "Hip Hop Dancing (191f / 6.4s, 163KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_7.glb", label: "Hip Hop Dancing (474f / 15.8s, 428KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_8.glb", label: "Hip Hop Dancing (558f / 18.6s, 475KB)" },
  { value: "media/sandbox/anims/anim_hip_hop_dancing_9.glb", label: "Hip Hop Dancing (474f / 15.8s, 428KB)" },
  { value: "media/sandbox/anims/anim_hit_to_body.glb", label: "Hit To Body (36f / 1.2s, 79KB)" },
  { value: "media/sandbox/anims/anim_hit_to_body_1.glb", label: "Hit To Body (41f / 1.4s, 81KB)" },
  { value: "media/sandbox/anims/anim_hit_to_head.glb", label: "Hit To Head (77f / 2.6s, 179KB)" },
  { value: "media/sandbox/anims/anim_hit_to_side_of_body.glb", label: "Hit To Side Of Body (85f / 2.8s, 191KB)" },
  { value: "media/sandbox/anims/anim_hit_to_the_legs.glb", label: "Hit To The Legs (96f / 3.2s, 214KB)" },
  { value: "media/sandbox/anims/anim_hokey_pokey.glb", label: "Hokey Pokey (351f / 11.7s, 356KB)" },
  { value: "media/sandbox/anims/anim_holding_idle.glb", label: "holding idle (173f / 5.8s, 203KB)" },
  { value: "media/sandbox/anims/anim_holding_turn_left.glb", label: "holding turn left (37f / 1.2s, 87KB)" },
  { value: "media/sandbox/anims/anim_holding_turn_right.glb", label: "holding turn right (37f / 1.2s, 86KB)" },
  { value: "media/sandbox/anims/anim_holding_walk.glb", label: "holding walk (42f / 1.4s, 98KB)" },
  { value: "media/sandbox/anims/anim_hook.glb", label: "Hook (61f / 2.0s, 88KB)" },
  { value: "media/sandbox/anims/anim_house_dancing.glb", label: "House Dancing (642f / 21.4s, 557KB)" },
  { value: "media/sandbox/anims/anim_house_dancing_1.glb", label: "House Dancing (786f / 26.2s, 716KB)" },
  { value: "media/sandbox/anims/anim_house_dancing_2.glb", label: "House Dancing (595f / 19.8s, 557KB)" },
  { value: "media/sandbox/anims/anim_hurricane_kick.glb", label: "Hurricane Kick (56f / 1.9s, 75KB)" },
  { value: "media/sandbox/anims/anim_idle.glb", label: "idle (251f / 8.4s, 272KB)" },
  { value: "media/sandbox/anims/anim_idle_fight.glb", label: "Idle fight (67f / 2.2s, 90KB)" },
  { value: "media/sandbox/anims/anim_idle_left_right.glb", label: "Idle Left Right (500f / 16.7s, 479KB)" },
  { value: "media/sandbox/anims/anim_illegal_elbow_punch.glb", label: "Illegal Elbow Punch (62f / 2.1s, 88KB)" },
  { value: "media/sandbox/anims/anim_injured_walk_right_turn.glb", label: "Injured Walk Right Turn (56f / 1.9s, 109KB)" },
  { value: "media/sandbox/anims/anim_inside_crescent_kick.glb", label: "Inside Crescent Kick (81f / 2.7s, 1859KB)" },
  { value: "media/sandbox/anims/anim_insult.glb", label: "Insult (81f / 2.7s, 132KB)" },
  { value: "media/sandbox/anims/anim_inward_block.glb", label: "Inward Block (45f / 1.5s, 81KB)" },
  { value: "media/sandbox/anims/anim_jab_to_elbow_punch.glb", label: "Jab To Elbow Punch (99f / 3.3s, 147KB)" },
  { value: "media/sandbox/anims/anim_jab_to_elbow_punch_1.glb", label: "Jab To Elbow Punch (99f / 3.3s, 1880KB)" },
  { value: "media/sandbox/anims/anim_jazz_dancing.glb", label: "Jazz Dancing (164f / 5.5s, 152KB)" },
  { value: "media/sandbox/anims/anim_jazz_dancing_1.glb", label: "Jazz Dancing (69f / 2.3s, 100KB)" },
  { value: "media/sandbox/anims/anim_jazz_dancing_2.glb", label: "Jazz Dancing (71f / 2.4s, 89KB)" },
  { value: "media/sandbox/anims/anim_jazz_dancing_3.glb", label: "Jazz Dancing (69f / 2.3s, 100KB)" },
  { value: "media/sandbox/anims/anim_jazz_dancing_4.glb", label: "Jazz Dancing (83f / 2.8s, 134KB)" },
  { value: "media/sandbox/anims/anim_joyful_jump.glb", label: "Joyful Jump (57f / 1.9s, 110KB)" },
  { value: "media/sandbox/anims/anim_jump.glb", label: "jump (51f / 1.7s, 107KB)" },
  { value: "media/sandbox/anims/anim_jump_away.glb", label: "Jump Away (80f / 2.7s, 171KB)" },
  { value: "media/sandbox/anims/anim_jump_away_1.glb", label: "Jump Away (80f / 2.7s, 171KB)" },
  { value: "media/sandbox/anims/anim_jump_down.glb", label: "Jump Down (106f / 3.5s, 104KB)" },
  { value: "media/sandbox/anims/anim_jump_over.glb", label: "Jump Over (69f / 2.3s, 173KB)" },
  { value: "media/sandbox/anims/anim_jump_push_up.glb", label: "Jump Push Up (36f / 1.2s, 94KB)" },
  { value: "media/sandbox/anims/anim_jumping_down.glb", label: "Jumping Down (81f / 2.7s, 104KB)" },
  { value: "media/sandbox/anims/anim_jumping_down_1.glb", label: "Jumping Down (81f / 2.7s, 104KB)" },
  { value: "media/sandbox/anims/anim_jumping_jacks.glb", label: "Jumping Jacks (33f / 1.1s, 94KB)" },
  { value: "media/sandbox/anims/anim_jumping_over_into_combat.glb", label: "Jumping Over Into Combat (126f / 4.2s, 261KB)" },
  { value: "media/sandbox/anims/anim_jumping_parkour.glb", label: "Jumping parkour (36f / 1.2s, 112KB)" },
  { value: "media/sandbox/anims/anim_jumping_rope.glb", label: "Jumping Rope (78f / 2.6s, 94KB)" },
  { value: "media/sandbox/anims/anim_kettlebell_swing.glb", label: "Kettlebell Swing (60f / 2.0s, 86KB)" },
  { value: "media/sandbox/anims/anim_kick_soccerball.glb", label: "Kick Soccerball (18f / 0.6s, 74KB)" },
  { value: "media/sandbox/anims/anim_kick_to_the_groin.glb", label: "Kick To The Groin (88f / 2.9s, 124KB)" },
  { value: "media/sandbox/anims/anim_kick_to_the_groin_1.glb", label: "Kick To The Groin (105f / 3.5s, 136KB)" },
  { value: "media/sandbox/anims/anim_kick_up_soccerball.glb", label: "Kick Up Soccerball (41f / 1.4s, 98KB)" },
  { value: "media/sandbox/anims/anim_kicking.glb", label: "Kicking (66f / 2.2s, 89KB)" },
  { value: "media/sandbox/anims/anim_kicking_1.glb", label: "Kicking (103f / 3.4s, 103KB)" },
  { value: "media/sandbox/anims/anim_kicking_2.glb", label: "Kicking (69f / 2.3s, 116KB)" },
  { value: "media/sandbox/anims/anim_kicking_3.glb", label: "Kicking (49f / 1.6s, 84KB)" },
  { value: "media/sandbox/anims/anim_kicking_4.glb", label: "Kicking (81f / 2.7s, 125KB)" },
  { value: "media/sandbox/anims/anim_kicking_5.glb", label: "Kicking (112f / 3.7s, 185KB)" },
  { value: "media/sandbox/anims/anim_kicking_6.glb", label: "Kicking (67f / 2.2s, 90KB)" },
  { value: "media/sandbox/anims/anim_kicking_7.glb", label: "Kicking (46f / 1.5s, 82KB)" },
  { value: "media/sandbox/anims/anim_kicking_out.glb", label: "Kicking Out (49f / 1.6s, 95KB)" },
  { value: "media/sandbox/anims/anim_kidney_hit.glb", label: "Kidney Hit (35f / 1.2s, 78KB)" },
  { value: "media/sandbox/anims/anim_kip_up.glb", label: "Kip Up (62f / 2.1s, 117KB)" },
  { value: "media/sandbox/anims/anim_kiss.glb", label: "Kiss (113f / 3.8s, 158KB)" },
  { value: "media/sandbox/anims/anim_kiss_1.glb", label: "Kiss (113f / 3.8s, 158KB)" },
  { value: "media/sandbox/anims/anim_kiss_from_man.glb", label: "Kiss from man (213f / 7.1s, 241KB)" },
  { value: "media/sandbox/anims/anim_kiss_from_woman.glb", label: "Kiss from woman (213f / 7.1s, 241KB)" },
  { value: "media/sandbox/anims/anim_knee_jab.glb", label: "Knee Jab (181f / 6.0s, 215KB)" },
  { value: "media/sandbox/anims/anim_knee_jab_1.glb", label: "Knee Jab (181f / 6.0s, 215KB)" },
  { value: "media/sandbox/anims/anim_knee_kick_lead.glb", label: "Knee Kick Lead (71f / 2.4s, 117KB)" },
  { value: "media/sandbox/anims/anim_kneeing_soccerball.glb", label: "Kneeing Soccerball (28f / 0.9s, 87KB)" },
  { value: "media/sandbox/anims/anim_kneeling_idle.glb", label: "kneeling idle (129f / 4.3s, 158KB)" },
  { value: "media/sandbox/anims/anim_kneeling_inspecting.glb", label: "Kneeling Inspecting (149f / 5.0s, 160KB)" },
  { value: "media/sandbox/anims/anim_kneeling_pointing.glb", label: "Kneeling Pointing (118f / 3.9s, 144KB)" },
  { value: "media/sandbox/anims/anim_laughing.glb", label: "Laughing (294f / 9.8s, 304KB)" },
  { value: "media/sandbox/anims/anim_laughing_1.glb", label: "Laughing (294f / 9.8s, 304KB)" },
  { value: "media/sandbox/anims/anim_laying.glb", label: "Laying (131f / 4.4s, 153KB)" },
  { value: "media/sandbox/anims/anim_laying_1.glb", label: "Laying (96f / 3.2s, 129KB)" },
  { value: "media/sandbox/anims/anim_laying_idle.glb", label: "Laying Idle (376f / 12.5s, 277KB)" },
  { value: "media/sandbox/anims/anim_laying_idle_1.glb", label: "Laying Idle (65f / 2.2s, 91KB)" },
  { value: "media/sandbox/anims/anim_laying_idle_2.glb", label: "Laying Idle (376f / 12.5s, 277KB)" },
  { value: "media/sandbox/anims/anim_laying_mild_cough.glb", label: "Laying Mild Cough (51f / 1.7s, 95KB)" },
  { value: "media/sandbox/anims/anim_laying_seizure.glb", label: "Laying Seizure (151f / 5.0s, 192KB)" },
  { value: "media/sandbox/anims/anim_laying_severe_cough.glb", label: "Laying Severe Cough (54f / 1.8s, 111KB)" },
  { value: "media/sandbox/anims/anim_laying_shrugging.glb", label: "Laying Shrugging (51f / 1.7s, 107KB)" },
  { value: "media/sandbox/anims/anim_laying_sleeping.glb", label: "Laying Sleeping (52f / 1.7s, 84KB)" },
  { value: "media/sandbox/anims/anim_lead_jab.glb", label: "Lead Jab (55f / 1.8s, 86KB)" },
  { value: "media/sandbox/anims/anim_lead_jab_1.glb", label: "Lead Jab (33f / 1.1s, 78KB)" },
  { value: "media/sandbox/anims/anim_leaning.glb", label: "Leaning (101f / 3.4s, 97KB)" },
  { value: "media/sandbox/anims/anim_left_strafe.glb", label: "left strafe (21f / 0.7s, 82KB)" },
  { value: "media/sandbox/anims/anim_left_strafe_walk.glb", label: "left strafe walk (29f / 1.0s, 89KB)" },
  { value: "media/sandbox/anims/anim_left_strafe_walking.glb", label: "left strafe walking (32f / 1.1s, 90KB)" },
  { value: "media/sandbox/anims/anim_left_turn.glb", label: "Left Turn (36f / 1.2s, 95KB)" },
  { value: "media/sandbox/anims/anim_left_turn_2.glb", label: "left turn (36f / 1.2s, 95KB)" },
  { value: "media/sandbox/anims/anim_left_turn_90.glb", label: "left turn 90 (28f / 0.9s, 87KB)" },
  { value: "media/sandbox/anims/anim_leg_sweep.glb", label: "Leg Sweep (87f / 2.9s, 137KB)" },
  { value: "media/sandbox/anims/anim_leg_sweep_1.glb", label: "Leg Sweep (74f / 2.5s, 119KB)" },
  { value: "media/sandbox/anims/anim_lengthy_head_nod.glb", label: "lengthy head nod (52f / 1.7s, 108KB)" },
  { value: "media/sandbox/anims/anim_lifting.glb", label: "Lifting (217f / 7.2s, 244KB)" },
  { value: "media/sandbox/anims/anim_light_hit_to_head.glb", label: "Light Hit To Head (26f / 0.9s, 74KB)" },
  { value: "media/sandbox/anims/anim_listening_to_music.glb", label: "Listening To Music (135f / 4.5s, 114KB)" },
  { value: "media/sandbox/anims/anim_locking_hip_hop_dance.glb", label: "Locking Hip Hop Dance (511f / 17.0s, 449KB)" },
  { value: "media/sandbox/anims/anim_lola_b_styperek.glb", label: "Lola B Styperek (2f / 0.1s, 3566KB)" },
  { value: "media/sandbox/anims/anim_look_around.glb", label: "Look Around (401f / 13.4s, 397KB)" },
  { value: "media/sandbox/anims/anim_look_away_gesture.glb", label: "look away gesture (55f / 1.8s, 111KB)" },
  { value: "media/sandbox/anims/anim_looking.glb", label: "Looking (144f / 4.8s, 162KB)" },
  { value: "media/sandbox/anims/anim_looking_around.glb", label: "Looking Around (191f / 6.4s, 223KB)" },
  { value: "media/sandbox/anims/anim_looking_through_files_low.glb", label: "Looking Through Files Low (433f / 14.4s, 425KB)" },
  { value: "media/sandbox/anims/anim_loser.glb", label: "Loser (99f / 3.3s, 143KB)" },
  { value: "media/sandbox/anims/anim_low_crawl.glb", label: "Low Crawl (71f / 2.4s, 123KB)" },
  { value: "media/sandbox/anims/anim_lying_down.glb", label: "Lying Down (173f / 5.8s, 208KB)" },
  { value: "media/sandbox/anims/anim_macaco_side.glb", label: "macaco side (100f / 3.3s, 148KB)" },
  { value: "media/sandbox/anims/anim_macarena_dance.glb", label: "Macarena Dance (248f / 8.3s, 251KB)" },
  { value: "media/sandbox/anims/anim_macarena_dance_1.glb", label: "Macarena Dance (248f / 8.3s, 251KB)" },
  { value: "media/sandbox/anims/anim_male_crouch_pose.glb", label: "Male Crouch Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_male_dynamic_matrix_pose.glb", label: "Male Dynamic Matrix Pose (2f / 0.1s, 62KB)" },
  { value: "media/sandbox/anims/anim_male_laying_pose.glb", label: "Male Laying Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_male_laying_pose_1.glb", label: "Male Laying Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_male_laying_pose_2.glb", label: "Male Laying Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_male_sitting_pose.glb", label: "Male Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_male_sitting_pose_1.glb", label: "Male Sitting Pose (2f / 0.1s, 62KB)" },
  { value: "media/sandbox/anims/anim_male_sitting_pose_2.glb", label: "Male Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_male_sitting_pose_3.glb", label: "Male Sitting Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_male_standing_pose.glb", label: "Male Standing Pose (2f / 0.1s, 63KB)" },
  { value: "media/sandbox/anims/anim_martelo_2.glb", label: "Martelo 2 (40f / 1.3s, 98KB)" },
  { value: "media/sandbox/anims/anim_martelo_3.glb", label: "Martelo 3 (60f / 2.0s, 115KB)" },
  { value: "media/sandbox/anims/anim_martelo_do_chau.glb", label: "martelo do chau (92f / 3.1s, 141KB)" },
  { value: "media/sandbox/anims/anim_martelo_do_chau_sem_mao.glb", label: "Martelo Do Chau Sem Mao (93f / 3.1s, 142KB)" },
  { value: "media/sandbox/anims/anim_meia_lua_de_compasso.glb", label: "Meia Lua De Compasso (53f / 1.8s, 108KB)" },
  { value: "media/sandbox/anims/anim_meia_lua_de_compasso_back.glb", label: "Meia Lua De Compasso Back (67f / 2.2s, 120KB)" },
  { value: "media/sandbox/anims/anim_meia_lua_de_frente.glb", label: "Meia Lua De Frente (75f / 2.5s, 127KB)" },
  { value: "media/sandbox/anims/anim_military_signaling.glb", label: "Military Signaling (196f / 6.5s, 173KB)" },
  { value: "media/sandbox/anims/anim_military_signaling_1.glb", label: "Military Signaling (186f / 6.2s, 182KB)" },
  { value: "media/sandbox/anims/anim_military_signaling_2.glb", label: "Military Signaling (186f / 6.2s, 182KB)" },
  { value: "media/sandbox/anims/anim_mma_idle.glb", label: "Mma Idle (151f / 5.0s, 119KB)" },
  { value: "media/sandbox/anims/anim_mma_kick.glb", label: "Mma Kick (62f / 2.1s, 116KB)" },
  { value: "media/sandbox/anims/anim_mma_kick_1.glb", label: "Mma Kick (51f / 1.7s, 107KB)" },
  { value: "media/sandbox/anims/anim_mma_kick_2.glb", label: "Mma Kick (49f / 1.6s, 106KB)" },
  { value: "media/sandbox/anims/anim_moving_while_hanging.glb", label: "Moving While Hanging (43f / 1.4s, 101KB)" },
  { value: "media/sandbox/anims/anim_neck_stretching.glb", label: "Neck Stretching (97f / 3.2s, 145KB)" },
  { value: "media/sandbox/anims/anim_nervously_look_around.glb", label: "Nervously Look Around (189f / 6.3s, 192KB)" },
  { value: "media/sandbox/anims/anim_ninja_idle.glb", label: "Ninja Idle (120f / 4.0s, 165KB)" },
  { value: "media/sandbox/anims/anim_no.glb", label: "No (151f / 5.0s, 190KB)" },
  { value: "media/sandbox/anims/anim_northern_soul_spin_combo.glb", label: "Northern Soul Spin Combo (266f / 8.9s, 285KB)" },
  { value: "media/sandbox/anims/anim_northern_soul_spin_combo_1.glb", label: "Northern Soul Spin Combo (266f / 8.9s, 285KB)" },
  { value: "media/sandbox/anims/anim_offensive_idle.glb", label: "Offensive Idle (318f / 10.6s, 319KB)" },
  { value: "media/sandbox/anims/anim_offensive_idle_1.glb", label: "Offensive Idle (318f / 10.6s, 319KB)" },
  { value: "media/sandbox/anims/anim_one_shoulder_lean.glb", label: "One Shoulder Lean (61f / 2.0s, 86KB)" },
  { value: "media/sandbox/anims/anim_open_door_outwards.glb", label: "Open Door Outwards (124f / 4.1s, 168KB)" },
  { value: "media/sandbox/anims/anim_opening.glb", label: "Opening (145f / 4.8s, 181KB)" },
  { value: "media/sandbox/anims/anim_overhead_squat.glb", label: "Overhead Squat (57f / 1.9s, 94KB)" },
  { value: "media/sandbox/anims/anim_patting.glb", label: "Patting (101f / 3.4s, 131KB)" },
  { value: "media/sandbox/anims/anim_petting_animal.glb", label: "Petting Animal (426f / 14.2s, 418KB)" },
  { value: "media/sandbox/anims/anim_pick_fruit.glb", label: "Pick Fruit (241f / 8.0s, 263KB)" },
  { value: "media/sandbox/anims/anim_pick_fruit_2.glb", label: "pick fruit (187f / 6.2s, 214KB)" },
  { value: "media/sandbox/anims/anim_pick_fruit_3.glb", label: "pick fruit (214f / 7.1s, 238KB)" },
  { value: "media/sandbox/anims/anim_picking_at_shirt.glb", label: "Picking At Shirt (53f / 1.8s, 95KB)" },
  { value: "media/sandbox/anims/anim_picking_at_shirt_1.glb", label: "Picking At Shirt (53f / 1.8s, 95KB)" },
  { value: "media/sandbox/anims/anim_pike_walk.glb", label: "Pike Walk (196f / 6.5s, 227KB)" },
  { value: "media/sandbox/anims/anim_pistol_idle.glb", label: "Pistol Idle (121f / 4.0s, 106KB)" },
  { value: "media/sandbox/anims/anim_pistol_idle_1.glb", label: "Pistol Idle (250f / 8.3s, 156KB)" },
  { value: "media/sandbox/anims/anim_pistol_idle_2.glb", label: "Pistol Idle (41f / 1.4s, 79KB)" },
  { value: "media/sandbox/anims/anim_pistol_kneel_to_stand.glb", label: "Pistol Kneel To Stand (42f / 1.4s, 81KB)" },
  { value: "media/sandbox/anims/anim_pistol_to_idle.glb", label: "Pistol To Idle (52f / 1.7s, 107KB)" },
  { value: "media/sandbox/anims/anim_pivot.glb", label: "Pivot (136f / 4.5s, 114KB)" },
  { value: "media/sandbox/anims/anim_plant_a_plant.glb", label: "Plant A Plant (228f / 7.6s, 252KB)" },
  { value: "media/sandbox/anims/anim_plant_tree.glb", label: "Plant Tree (279f / 9.3s, 298KB)" },
  { value: "media/sandbox/anims/anim_plotting.glb", label: "Plotting (100f / 3.3s, 148KB)" },
  { value: "media/sandbox/anims/anim_pointing.glb", label: "Pointing (104f / 3.5s, 129KB)" },
  { value: "media/sandbox/anims/anim_pontera.glb", label: "pontera (40f / 1.3s, 97KB)" },
  { value: "media/sandbox/anims/anim_praying.glb", label: "Praying (201f / 6.7s, 219KB)" },
  { value: "media/sandbox/anims/anim_praying_1.glb", label: "Praying (201f / 6.7s, 219KB)" },
  { value: "media/sandbox/anims/anim_praying_2.glb", label: "Praying (36f / 1.2s, 74KB)" },
  { value: "media/sandbox/anims/anim_pull_pilot_from_seat.glb", label: "Pull Pilot From Seat (284f / 9.5s, 258KB)" },
  { value: "media/sandbox/anims/anim_pull_plant.glb", label: "Pull Plant (141f / 4.7s, 184KB)" },
  { value: "media/sandbox/anims/anim_pull_plant_1.glb", label: "Pull Plant (143f / 4.8s, 184KB)" },
  { value: "media/sandbox/anims/anim_pull_plant_2.glb", label: "pull plant (143f / 4.8s, 184KB)" },
  { value: "media/sandbox/anims/anim_pulled_from_seat.glb", label: "Pulled From Seat (141f / 4.7s, 161KB)" },
  { value: "media/sandbox/anims/anim_punch_combo.glb", label: "Punch Combo (67f / 2.2s, 91KB)" },
  { value: "media/sandbox/anims/anim_punch_to_elbow_combo.glb", label: "Punch To Elbow Combo (151f / 5.0s, 244KB)" },
  { value: "media/sandbox/anims/anim_punching.glb", label: "Punching (27f / 0.9s, 75KB)" },
  { value: "media/sandbox/anims/anim_punching_1.glb", label: "Punching (31f / 1.0s, 77KB)" },
  { value: "media/sandbox/anims/anim_punching_light.glb", label: "Punching Light (32f / 1.1s, 74KB)" },
  { value: "media/sandbox/anims/anim_push_up.glb", label: "Push Up (47f / 1.6s, 83KB)" },
  { value: "media/sandbox/anims/anim_putting_down.glb", label: "Putting Down (311f / 10.4s, 323KB)" },
  { value: "media/sandbox/anims/anim_putting_down_1.glb", label: "Putting Down (311f / 10.4s, 323KB)" },
  { value: "media/sandbox/anims/anim_quad_punch.glb", label: "Quad Punch (66f / 2.2s, 91KB)" },
  { value: "media/sandbox/anims/anim_queshada_1.glb", label: "queshada 1 (78f / 2.6s, 130KB)" },
  { value: "media/sandbox/anims/anim_queshada_2.glb", label: "Queshada 2 (61f / 2.0s, 116KB)" },
  { value: "media/sandbox/anims/anim_quick_informal_bow.glb", label: "Quick Informal Bow (83f / 2.8s, 133KB)" },
  { value: "media/sandbox/anims/anim_rallying.glb", label: "Rallying (187f / 6.2s, 217KB)" },
  { value: "media/sandbox/anims/anim_rapping.glb", label: "Rapping (238f / 7.9s, 260KB)" },
  { value: "media/sandbox/anims/anim_rasteira_1.glb", label: "rasteira 1 (55f / 1.8s, 111KB)" },
  { value: "media/sandbox/anims/anim_rasteira_2.glb", label: "rasteira 2 (75f / 2.5s, 127KB)" },
  { value: "media/sandbox/anims/anim_receive_soccerball.glb", label: "Receive Soccerball (155f / 5.2s, 251KB)" },
  { value: "media/sandbox/anims/anim_receiving_an_uppercut.glb", label: "Receiving An Uppercut (51f / 1.7s, 84KB)" },
  { value: "media/sandbox/anims/anim_release_hostage_villain.glb", label: "Release Hostage - Villain (93f / 3.1s, 121KB)" },
  { value: "media/sandbox/anims/anim_relieved_sigh.glb", label: "Relieved Sigh (91f / 3.0s, 140KB)" },
  { value: "media/sandbox/anims/anim_removing_driver.glb", label: "Removing Driver (312f / 10.4s, 275KB)" },
  { value: "media/sandbox/anims/anim_restrain.glb", label: "Restrain (228f / 7.6s, 159KB)" },
  { value: "media/sandbox/anims/anim_rib_hit.glb", label: "Rib Hit (31f / 1.0s, 76KB)" },
  { value: "media/sandbox/anims/anim_right_block.glb", label: "Right Block (44f / 1.5s, 80KB)" },
  { value: "media/sandbox/anims/anim_right_hook.glb", label: "Right Hook (34f / 1.1s, 88KB)" },
  { value: "media/sandbox/anims/anim_right_strafe.glb", label: "right strafe (21f / 0.7s, 82KB)" },
  { value: "media/sandbox/anims/anim_right_strafe_walk.glb", label: "right strafe walk (29f / 1.0s, 89KB)" },
  { value: "media/sandbox/anims/anim_right_strafe_walking.glb", label: "right strafe walking (32f / 1.1s, 90KB)" },
  { value: "media/sandbox/anims/anim_right_turn.glb", label: "Right Turn (36f / 1.2s, 95KB)" },
  { value: "media/sandbox/anims/anim_right_turn_2.glb", label: "right turn (36f / 1.2s, 94KB)" },
  { value: "media/sandbox/anims/anim_right_turn_90.glb", label: "right turn 90 (29f / 1.0s, 87KB)" },
  { value: "media/sandbox/anims/anim_robot_hip_hop_dance.glb", label: "Robot Hip Hop Dance (464f / 15.5s, 435KB)" },
  { value: "media/sandbox/anims/anim_roundhouse_kick.glb", label: "Roundhouse Kick (65f / 2.2s, 89KB)" },
  { value: "media/sandbox/anims/anim_rumba_dancing.glb", label: "Rumba Dancing (72f / 2.4s, 107KB)" },
  { value: "media/sandbox/anims/anim_rummaging.glb", label: "Rummaging (146f / 4.9s, 164KB)" },
  { value: "media/sandbox/anims/anim_run_and_swing.glb", label: "Run And Swing (74f / 2.5s, 168KB)" },
  { value: "media/sandbox/anims/anim_run_backward_arc_right.glb", label: "run backward arc right (37f / 1.2s, 95KB)" },
  { value: "media/sandbox/anims/anim_run_to_flip.glb", label: "Run To Flip (68f / 2.3s, 112KB)" },
  { value: "media/sandbox/anims/anim_running.glb", label: "running (22f / 0.7s, 82KB)" },
  { value: "media/sandbox/anims/anim_running_crawl.glb", label: "running crawl (20f / 0.7s, 82KB)" },
  { value: "media/sandbox/anims/anim_running_slide.glb", label: "Running Slide (47f / 1.6s, 131KB)" },
  { value: "media/sandbox/anims/anim_sad_idle.glb", label: "Sad Idle (121f / 4.0s, 162KB)" },
  { value: "media/sandbox/anims/anim_salsa_dancing.glb", label: "Salsa Dancing (74f / 2.5s, 120KB)" },
  { value: "media/sandbox/anims/anim_salsa_dancing_1.glb", label: "Salsa Dancing (844f / 28.1s, 764KB)" },
  { value: "media/sandbox/anims/anim_salsa_dancing_2.glb", label: "Salsa Dancing (69f / 2.3s, 118KB)" },
  { value: "media/sandbox/anims/anim_salsa_dancing_3.glb", label: "Salsa Dancing (648f / 21.6s, 541KB)" },
  { value: "media/sandbox/anims/anim_salsa_dancing_4.glb", label: "Salsa Dancing (570f / 19.0s, 519KB)" },
  { value: "media/sandbox/anims/anim_salsa_dancing_5.glb", label: "Salsa Dancing (69f / 2.3s, 118KB)" },
  { value: "media/sandbox/anims/anim_salsa_dancing_6.glb", label: "Salsa Dancing (74f / 2.5s, 120KB)" },
  { value: "media/sandbox/anims/anim_salsa_dancing_man.glb", label: "Salsa Dancing man (79f / 2.6s, 125KB)" },
  { value: "media/sandbox/anims/anim_samba_dancing.glb", label: "Samba Dancing (717f / 23.9s, 659KB)" },
  { value: "media/sandbox/anims/anim_samba_dancing_1.glb", label: "Samba Dancing (655f / 21.8s, 607KB)" },
  { value: "media/sandbox/anims/anim_samba_dancing_2.glb", label: "Samba Dancing (822f / 27.4s, 746KB)" },
  { value: "media/sandbox/anims/anim_samba_dancing_3.glb", label: "Samba Dancing (717f / 23.9s, 659KB)" },
  { value: "media/sandbox/anims/anim_samba_dancing_4.glb", label: "Samba Dancing (655f / 21.8s, 607KB)" },
  { value: "media/sandbox/anims/anim_samba_dancing_5.glb", label: "Samba Dancing (560f / 18.7s, 477KB)" },
  { value: "media/sandbox/anims/anim_samba_dancing_6.glb", label: "Samba Dancing (822f / 27.4s, 746KB)" },
  { value: "media/sandbox/anims/anim_samba_dancing_7.glb", label: "Samba Dancing (717f / 23.9s, 659KB)" },
  { value: "media/sandbox/anims/anim_sarcastic_head_nod.glb", label: "sarcastic head nod (66f / 2.2s, 119KB)" },
  { value: "media/sandbox/anims/anim_scared.glb", label: "Scared (303f / 10.1s, 318KB)" },
  { value: "media/sandbox/anims/anim_scissor_kick.glb", label: "Scissor Kick (84f / 2.8s, 134KB)" },
  { value: "media/sandbox/anims/anim_searching_files_high.glb", label: "Searching Files High (293f / 9.8s, 308KB)" },
  { value: "media/sandbox/anims/anim_searching_pockets.glb", label: "Searching Pockets (151f / 5.0s, 192KB)" },
  { value: "media/sandbox/anims/anim_seated_idle.glb", label: "Seated Idle (126f / 4.2s, 142KB)" },
  { value: "media/sandbox/anims/anim_shaking_hands_2.glb", label: "Shaking Hands 2 (132f / 4.4s, 172KB)" },
  { value: "media/sandbox/anims/anim_shaking_head_no.glb", label: "shaking head no (52f / 1.7s, 108KB)" },
  { value: "media/sandbox/anims/anim_shooting.glb", label: "Shooting (36f / 1.2s, 87KB)" },
  { value: "media/sandbox/anims/anim_shooting_gun.glb", label: "Shooting Gun (160f / 5.3s, 190KB)" },
  { value: "media/sandbox/anims/anim_shooting_pistol.glb", label: "Shooting Pistol (81f / 2.7s, 95KB)" },
  { value: "media/sandbox/anims/anim_shoulder_throw_aggressor.glb", label: "Shoulder Throw, Aggressor (201f / 6.7s, 243KB)" },
  { value: "media/sandbox/anims/anim_shoulder_throw_victim.glb", label: "Shoulder Throw, Victim (201f / 6.7s, 241KB)" },
  { value: "media/sandbox/anims/anim_side_kick.glb", label: "Side Kick (61f / 2.0s, 88KB)" },
  { value: "media/sandbox/anims/anim_silly_dancing.glb", label: "Silly Dancing (164f / 5.5s, 121KB)" },
  { value: "media/sandbox/anims/anim_silly_dancing_1.glb", label: "Silly Dancing (164f / 5.5s, 121KB)" },
  { value: "media/sandbox/anims/anim_silly_dancing_2.glb", label: "Silly Dancing (116f / 3.9s, 106KB)" },
  { value: "media/sandbox/anims/anim_singing.glb", label: "Singing (420f / 14.0s, 315KB)" },
  { value: "media/sandbox/anims/anim_sit_to_stand.glb", label: "Sit To Stand (69f / 2.3s, 122KB)" },
  { value: "media/sandbox/anims/anim_sitting.glb", label: "Sitting (179f / 6.0s, 210KB)" },
  { value: "media/sandbox/anims/anim_sitting_1.glb", label: "Sitting (64f / 2.1s, 88KB)" },
  { value: "media/sandbox/anims/anim_sitting_2.glb", label: "Sitting (288f / 9.6s, 295KB)" },
  { value: "media/sandbox/anims/anim_sitting_3.glb", label: "Sitting (134f / 4.5s, 174KB)" },
  { value: "media/sandbox/anims/anim_sitting_angry.glb", label: "Sitting Angry (84f / 2.8s, 132KB)" },
  { value: "media/sandbox/anims/anim_sitting_disbelief.glb", label: "Sitting Disbelief (144f / 4.8s, 184KB)" },
  { value: "media/sandbox/anims/anim_sitting_drinking.glb", label: "Sitting Drinking (457f / 15.2s, 445KB)" },
  { value: "media/sandbox/anims/anim_sitting_gun_motion.glb", label: "Sitting Gun Motion (145f / 4.8s, 163KB)" },
  { value: "media/sandbox/anims/anim_sitting_idle.glb", label: "Sitting Idle (193f / 6.4s, 165KB)" },
  { value: "media/sandbox/anims/anim_sitting_idle_1.glb", label: "Sitting Idle (309f / 10.3s, 302KB)" },
  { value: "media/sandbox/anims/anim_sitting_laughing.glb", label: "Sitting Laughing (251f / 8.4s, 261KB)" },
  { value: "media/sandbox/anims/anim_sitting_legs_swing.glb", label: "Sitting-legs-swing (64f / 2.1s, 88KB)" },
  { value: "media/sandbox/anims/anim_sitting_talking.glb", label: "Sitting Talking (1323f / 44.1s, 1162KB)" },
  { value: "media/sandbox/anims/anim_sitting_talking_1.glb", label: "Sitting Talking (1350f / 45.0s, 1183KB)" },
  { value: "media/sandbox/anims/anim_sitting_thumbs_up.glb", label: "Sitting Thumbs Up (116f / 3.9s, 134KB)" },
  { value: "media/sandbox/anims/anim_sitting_yell.glb", label: "Sitting Yell (114f / 3.8s, 156KB)" },
  { value: "media/sandbox/anims/anim_situps.glb", label: "Situps (68f / 2.3s, 121KB)" },
  { value: "media/sandbox/anims/anim_skinning_test.glb", label: "Skinning Test (59f / 2.0s, 111KB)" },
  { value: "media/sandbox/anims/anim_sleeping_idle.glb", label: "Sleeping Idle (529f / 17.6s, 503KB)" },
  { value: "media/sandbox/anims/anim_smoking.glb", label: "Smoking (538f / 17.9s, 503KB)" },
  { value: "media/sandbox/anims/anim_snake_hip_hop_dance.glb", label: "Snake Hip Hop Dance (459f / 15.3s, 395KB)" },
  { value: "media/sandbox/anims/anim_snake_hip_hop_dance_1.glb", label: "Snake Hip Hop Dance (459f / 15.3s, 395KB)" },
  { value: "media/sandbox/anims/anim_soccer_header.glb", label: "Soccer Header (72f / 2.4s, 119KB)" },
  { value: "media/sandbox/anims/anim_soccer_idle.glb", label: "Soccer Idle (187f / 6.2s, 216KB)" },
  { value: "media/sandbox/anims/anim_soccer_penalty_kick.glb", label: "Soccer Penalty Kick (46f / 1.5s, 1824KB)" },
  { value: "media/sandbox/anims/anim_soccer_spin.glb", label: "Soccer Spin (39f / 1.3s, 103KB)" },
  { value: "media/sandbox/anims/anim_soccer_tackle.glb", label: "Soccer Tackle (54f / 1.8s, 143KB)" },
  { value: "media/sandbox/anims/anim_soccer_tackle_1.glb", label: "Soccer Tackle (83f / 2.8s, 189KB)" },
  { value: "media/sandbox/anims/anim_soccer_tackle_2.glb", label: "Soccer Tackle (70f / 2.3s, 123KB)" },
  { value: "media/sandbox/anims/anim_spat_in_face.glb", label: "Spat In Face (77f / 2.6s, 117KB)" },
  { value: "media/sandbox/anims/anim_speedbag.glb", label: "Speedbag (200f / 6.7s, 230KB)" },
  { value: "media/sandbox/anims/anim_spit_reaction.glb", label: "Spit Reaction (129f / 4.3s, 152KB)" },
  { value: "media/sandbox/anims/anim_sprint_to_wall_climb.glb", label: "Sprint To Wall Climb (55f / 1.8s, 135KB)" },
  { value: "media/sandbox/anims/anim_stall_soccerball.glb", label: "Stall Soccerball (65f / 2.2s, 117KB)" },
  { value: "media/sandbox/anims/anim_stall_soccerball_1.glb", label: "Stall Soccerball (70f / 2.3s, 120KB)" },
  { value: "media/sandbox/anims/anim_stand_up.glb", label: "Stand Up (146f / 4.9s, 185KB)" },
  { value: "media/sandbox/anims/anim_stand_up_1.glb", label: "Stand Up (71f / 2.4s, 113KB)" },
  { value: "media/sandbox/anims/anim_standard_run.glb", label: "Standard Run (23f / 0.8s, 84KB)" },
  { value: "media/sandbox/anims/anim_standing_1h_cast_spell_01.glb", label: "standing 1H cast spell 01 (69f / 2.3s, 119KB)" },
  { value: "media/sandbox/anims/anim_standing_1h_magic_attack_01.glb", label: "Standing 1H Magic Attack 01 (70f / 2.3s, 122KB)" },
  { value: "media/sandbox/anims/anim_standing_1h_magic_attack_02.glb", label: "Standing 1H Magic Attack 02 (67f / 2.2s, 119KB)" },
  { value: "media/sandbox/anims/anim_standing_1h_magic_attack_03.glb", label: "Standing 1H Magic Attack 03 (70f / 2.3s, 121KB)" },
  { value: "media/sandbox/anims/anim_standing_2h_cast_spell_01.glb", label: "Standing 2H Cast Spell 01 (66f / 2.2s, 119KB)" },
  { value: "media/sandbox/anims/anim_standing_2h_magic_area_attack_01.glb", label: "Standing 2H Magic Area Attack 01 (90f / 3.0s, 140KB)" },
  { value: "media/sandbox/anims/anim_standing_2h_magic_area_attack_02.glb", label: "Standing 2H Magic Area Attack 02 (95f / 3.2s, 144KB)" },
  { value: "media/sandbox/anims/anim_standing_2h_magic_attack_01.glb", label: "Standing 2H Magic Attack 01 (81f / 2.7s, 132KB)" },
  { value: "media/sandbox/anims/anim_standing_2h_magic_attack_02.glb", label: "Standing 2H Magic Attack 02 (80f / 2.7s, 131KB)" },
  { value: "media/sandbox/anims/anim_standing_2h_magic_attack_03.glb", label: "Standing 2H Magic Attack 03 (129f / 4.3s, 172KB)" },
  { value: "media/sandbox/anims/anim_standing_2h_magic_attack_04.glb", label: "Standing 2H Magic Attack 04 (101f / 3.4s, 145KB)" },
  { value: "media/sandbox/anims/anim_standing_2h_magic_attack_05.glb", label: "Standing 2H Magic Attack 05 (107f / 3.6s, 154KB)" },
  { value: "media/sandbox/anims/anim_standing_arguing.glb", label: "Standing Arguing (625f / 20.8s, 585KB)" },
  { value: "media/sandbox/anims/anim_standing_arguing_1.glb", label: "Standing Arguing (625f / 20.8s, 582KB)" },
  { value: "media/sandbox/anims/anim_standing_block_idle.glb", label: "standing block idle (51f / 1.7s, 93KB)" },
  { value: "media/sandbox/anims/anim_standing_block_react_large.glb", label: "standing block react large (31f / 1.0s, 90KB)" },
  { value: "media/sandbox/anims/anim_standing_cheering.glb", label: "Standing Cheering (104f / 3.5s, 150KB)" },
  { value: "media/sandbox/anims/anim_standing_clap.glb", label: "Standing Clap (144f / 4.8s, 184KB)" },
  { value: "media/sandbox/anims/anim_standing_cover_turn.glb", label: "Standing Cover Turn (31f / 1.0s, 86KB)" },
  { value: "media/sandbox/anims/anim_standing_death_backward_01.glb", label: "Standing Death Backward 01 (78f / 2.6s, 112KB)" },
  { value: "media/sandbox/anims/anim_standing_disarm_over_shoulder.glb", label: "standing disarm over shoulder (50f / 1.7s, 106KB)" },
  { value: "media/sandbox/anims/anim_standing_disarm_underarm.glb", label: "standing disarm underarm (50f / 1.7s, 106KB)" },
  { value: "media/sandbox/anims/anim_standing_idle.glb", label: "standing idle (55f / 1.8s, 95KB)" },
  { value: "media/sandbox/anims/anim_standing_idle_looking_ver_1.glb", label: "standing idle looking ver. 1 (339f / 11.3s, 267KB)" },
  { value: "media/sandbox/anims/anim_standing_idle_looking_ver_2.glb", label: "standing idle looking ver. 2 (231f / 7.7s, 203KB)" },
  { value: "media/sandbox/anims/anim_standing_jump.glb", label: "Standing Jump (74f / 2.5s, 126KB)" },
  { value: "media/sandbox/anims/anim_standing_jump_1.glb", label: "Standing Jump (45f / 1.5s, 1825KB)" },
  { value: "media/sandbox/anims/anim_standing_melee_attack_360_high.glb", label: "standing melee attack 360 high (96f / 3.2s, 122KB)" },
  { value: "media/sandbox/anims/anim_standing_melee_attack_360_low.glb", label: "standing melee attack 360 low (76f / 2.5s, 110KB)" },
  { value: "media/sandbox/anims/anim_standing_melee_attack_backhand.glb", label: "standing melee attack backhand (96f / 3.2s, 121KB)" },
  { value: "media/sandbox/anims/anim_standing_melee_attack_downward.glb", label: "standing melee attack downward (69f / 2.3s, 107KB)" },
  { value: "media/sandbox/anims/anim_standing_melee_attack_horizontal.glb", label: "standing melee attack horizontal (73f / 2.4s, 108KB)" },
  { value: "media/sandbox/anims/anim_standing_melee_attack_kick_ver_1.glb", label: "standing melee attack kick ver. 1 (57f / 1.9s, 99KB)" },
  { value: "media/sandbox/anims/anim_standing_melee_attack_kick_ver_2.glb", label: "standing melee attack kick ver. 2 (43f / 1.4s, 91KB)" },
  { value: "media/sandbox/anims/anim_standing_melee_combo_attack_ver_1.glb", label: "standing melee combo attack ver. 1 (141f / 4.7s, 149KB)" },
  { value: "media/sandbox/anims/anim_standing_melee_combo_attack_ver_2.glb", label: "standing melee combo attack ver. 2 (126f / 4.2s, 140KB)" },
  { value: "media/sandbox/anims/anim_standing_melee_combo_attack_ver_3.glb", label: "standing melee combo attack ver. 3 (83f / 2.8s, 115KB)" },
  { value: "media/sandbox/anims/anim_standing_melee_kick.glb", label: "Standing Melee Kick (44f / 1.5s, 92KB)" },
  { value: "media/sandbox/anims/anim_standing_melee_run_jump_attack.glb", label: "standing melee run jump attack (111f / 3.7s, 214KB)" },
  { value: "media/sandbox/anims/anim_standing_react_death_right.glb", label: "Standing React Death Right (106f / 3.5s, 153KB)" },
  { value: "media/sandbox/anims/anim_standing_react_large_from_left.glb", label: "standing react large from left (31f / 1.0s, 83KB)" },
  { value: "media/sandbox/anims/anim_standing_react_large_from_right.glb", label: "standing react large from right (52f / 1.7s, 96KB)" },
  { value: "media/sandbox/anims/anim_standing_react_large_gut.glb", label: "standing react large gut (45f / 1.5s, 91KB)" },
  { value: "media/sandbox/anims/anim_standing_run_back.glb", label: "standing run back (25f / 0.8s, 80KB)" },
  { value: "media/sandbox/anims/anim_standing_run_forward.glb", label: "standing run forward (23f / 0.8s, 78KB)" },
  { value: "media/sandbox/anims/anim_standing_taunt_battlecry.glb", label: "standing taunt battlecry (86f / 2.9s, 116KB)" },
  { value: "media/sandbox/anims/anim_standing_taunt_chest_thump.glb", label: "standing taunt chest thump (77f / 2.6s, 109KB)" },
  { value: "media/sandbox/anims/anim_standing_thumbs_up.glb", label: "Standing Thumbs Up (126f / 4.2s, 170KB)" },
  { value: "media/sandbox/anims/anim_standing_turn_left_90.glb", label: "standing turn left 90 (53f / 1.8s, 97KB)" },
  { value: "media/sandbox/anims/anim_standing_turn_right_90.glb", label: "standing turn right 90 (50f / 1.7s, 95KB)" },
  { value: "media/sandbox/anims/anim_standing_using_touchscreen_tablet.glb", label: "Standing Using Touchscreen Tablet (995f / 33.2s, 668KB)" },
  { value: "media/sandbox/anims/anim_standing_w_briefcase_idle.glb", label: "Standing W_Briefcase Idle (419f / 14.0s, 314KB)" },
  { value: "media/sandbox/anims/anim_standing_walk_back.glb", label: "standing walk back (42f / 1.4s, 89KB)" },
  { value: "media/sandbox/anims/anim_standing_walk_forward.glb", label: "standing walk forward (41f / 1.4s, 89KB)" },
  { value: "media/sandbox/anims/anim_standing_walk_left.glb", label: "standing walk left (38f / 1.3s, 87KB)" },
  { value: "media/sandbox/anims/anim_standing_walk_right.glb", label: "standing walk right (39f / 1.3s, 88KB)" },
  { value: "media/sandbox/anims/anim_step_hip_hop_dance.glb", label: "Step Hip Hop Dance (235f / 7.8s, 175KB)" },
  { value: "media/sandbox/anims/anim_stomach_hit.glb", label: "Stomach Hit (37f / 1.2s, 78KB)" },
  { value: "media/sandbox/anims/anim_stomp.glb", label: "Stomp (57f / 1.9s, 104KB)" },
  { value: "media/sandbox/anims/anim_stroke_hand_gesture.glb", label: "Stroke Hand Gesture (49f / 1.6s, 94KB)" },
  { value: "media/sandbox/anims/anim_stroke_shaking_head.glb", label: "Stroke Shaking Head (51f / 1.7s, 84KB)" },
  { value: "media/sandbox/anims/anim_sumo_high_pull.glb", label: "Sumo High Pull (79f / 2.6s, 93KB)" },
  { value: "media/sandbox/anims/anim_superhuman_choke_lift.glb", label: "Superhuman Choke Lift (192f / 6.4s, 152KB)" },
  { value: "media/sandbox/anims/anim_surprise_uppercut.glb", label: "Surprise Uppercut (106f / 3.5s, 128KB)" },
  { value: "media/sandbox/anims/anim_surprised.glb", label: "Surprised (121f / 4.0s, 167KB)" },
  { value: "media/sandbox/anims/anim_swagger_walk.glb", label: "Swagger Walk (85f / 2.8s, 120KB)" },
  { value: "media/sandbox/anims/anim_swimming.glb", label: "Swimming (137f / 4.6s, 183KB)" },
  { value: "media/sandbox/anims/anim_swimming_to_edge.glb", label: "Swimming To Edge (151f / 5.0s, 159KB)" },
  { value: "media/sandbox/anims/anim_swing_dancing.glb", label: "Swing Dancing (628f / 20.9s, 439KB)" },
  { value: "media/sandbox/anims/anim_swing_into_wall.glb", label: "Swing Into Wall (92f / 3.1s, 142KB)" },
  { value: "media/sandbox/anims/anim_swing_to_land.glb", label: "Swing To Land (57f / 1.9s, 148KB)" },
  { value: "media/sandbox/anims/anim_swing_to_land_1.glb", label: "Swing To Land (62f / 2.1s, 162KB)" },
  { value: "media/sandbox/anims/anim_swing_to_land_2.glb", label: "Swing To Land (57f / 1.9s, 151KB)" },
  { value: "media/sandbox/anims/anim_sword_and_shield_attack.glb", label: "Sword And Shield Attack (71f / 2.4s, 151KB)" },
  { value: "media/sandbox/anims/anim_sword_and_shield_crouch_block_idle.glb", label: "Sword And Shield Crouch Block Idle (16f / 0.5s, 77KB)" },
  { value: "media/sandbox/anims/anim_sword_and_shield_crouch_idle.glb", label: "Sword And Shield Crouch Idle (74f / 2.5s, 89KB)" },
  { value: "media/sandbox/anims/anim_taken_hostage_victim.glb", label: "Taken Hostage - Victim (66f / 2.2s, 116KB)" },
  { value: "media/sandbox/anims/anim_taken_hostage_villain.glb", label: "Taken Hostage - Villain (66f / 2.2s, 104KB)" },
  { value: "media/sandbox/anims/anim_taking_item.glb", label: "Taking Item (142f / 4.7s, 161KB)" },
  { value: "media/sandbox/anims/anim_taking_item_1.glb", label: "Taking Item (142f / 4.7s, 161KB)" },
  { value: "media/sandbox/anims/anim_taking_punch.glb", label: "Taking Punch (171f / 5.7s, 205KB)" },
  { value: "media/sandbox/anims/anim_talking.glb", label: "Talking (179f / 6.0s, 214KB)" },
  { value: "media/sandbox/anims/anim_talking_1.glb", label: "Talking (145f / 4.8s, 148KB)" },
  { value: "media/sandbox/anims/anim_talking_2.glb", label: "Talking (114f / 3.8s, 149KB)" },
  { value: "media/sandbox/anims/anim_talking_at_watercooler.glb", label: "Talking At Watercooler (1338f / 44.6s, 862KB)" },
  { value: "media/sandbox/anims/anim_talking_on_a_cell_phone.glb", label: "Talking On A Cell Phone (1118f / 37.3s, 923KB)" },
  { value: "media/sandbox/anims/anim_talking_on_phone.glb", label: "Talking On Phone (1166f / 38.9s, 1033KB)" },
  { value: "media/sandbox/anims/anim_talking_phone_pacing.glb", label: "Talking Phone Pacing (1268f / 42.3s, 2066KB)" },
  { value: "media/sandbox/anims/anim_talking_woman.glb", label: "Talking woman (179f / 6.0s, 214KB)" },
  { value: "media/sandbox/anims/anim_taunt.glb", label: "Taunt (156f / 5.2s, 158KB)" },
  { value: "media/sandbox/anims/anim_taunt_1.glb", label: "Taunt (117f / 3.9s, 162KB)" },
  { value: "media/sandbox/anims/anim_taunt_2.glb", label: "Taunt (86f / 2.9s, 136KB)" },
  { value: "media/sandbox/anims/anim_telling_a_secret.glb", label: "Telling A Secret (328f / 10.9s, 308KB)" },
  { value: "media/sandbox/anims/anim_tender_placement.glb", label: "Tender Placement (279f / 9.3s, 296KB)" },
  { value: "media/sandbox/anims/anim_tender_placement_1.glb", label: "Tender Placement (279f / 9.3s, 287KB)" },
  { value: "media/sandbox/anims/anim_texting.glb", label: "Texting (557f / 18.6s, 509KB)" },
  { value: "media/sandbox/anims/anim_texting_while_standing.glb", label: "Texting While Standing (708f / 23.6s, 652KB)" },
  { value: "media/sandbox/anims/anim_thankful.glb", label: "Thankful (91f / 3.0s, 140KB)" },
  { value: "media/sandbox/anims/anim_thinking.glb", label: "Thinking (128f / 4.3s, 165KB)" },
  { value: "media/sandbox/anims/anim_thoughtful_head_shake.glb", label: "Thoughtful Head Shake (93f / 3.1s, 142KB)" },
  { value: "media/sandbox/anims/anim_threatening.glb", label: "Threatening (133f / 4.4s, 175KB)" },
  { value: "media/sandbox/anims/anim_thriller_part_2.glb", label: "Thriller Part 2 (566f / 18.9s, 957KB)" },
  { value: "media/sandbox/anims/anim_throwing.glb", label: "Throwing (168f / 5.6s, 178KB)" },
  { value: "media/sandbox/anims/anim_tonic_seizure.glb", label: "Tonic Seizure (242f / 8.1s, 267KB)" },
  { value: "media/sandbox/anims/anim_tripping.glb", label: "Tripping (84f / 2.8s, 136KB)" },
  { value: "media/sandbox/anims/anim_troca_1.glb", label: "Troca 1 (156f / 5.2s, 190KB)" },
  { value: "media/sandbox/anims/anim_tut_hip_hop_dance.glb", label: "Tut Hip Hop Dance (364f / 12.1s, 339KB)" },
  { value: "media/sandbox/anims/anim_twist_dance.glb", label: "Twist Dance (284f / 9.5s, 301KB)" },
  { value: "media/sandbox/anims/anim_typing.glb", label: "Typing (495f / 16.5s, 460KB)" },
  { value: "media/sandbox/anims/anim_unarmed_equip_over_shoulder.glb", label: "unarmed equip over shoulder (51f / 1.7s, 107KB)" },
  { value: "media/sandbox/anims/anim_unarmed_equip_underarm.glb", label: "unarmed equip underarm (34f / 1.1s, 93KB)" },
  { value: "media/sandbox/anims/anim_unarmed_idle.glb", label: "unarmed idle (55f / 1.8s, 106KB)" },
  { value: "media/sandbox/anims/anim_unarmed_idle_looking_ver_1.glb", label: "unarmed idle looking ver. 1 (334f / 11.1s, 337KB)" },
  { value: "media/sandbox/anims/anim_unarmed_idle_looking_ver_2.glb", label: "unarmed idle looking ver. 2 (211f / 7.0s, 230KB)" },
  { value: "media/sandbox/anims/anim_unarmed_jump.glb", label: "unarmed jump (71f / 2.4s, 123KB)" },
  { value: "media/sandbox/anims/anim_unarmed_jump_running.glb", label: "unarmed jump running (43f / 1.4s, 107KB)" },
  { value: "media/sandbox/anims/anim_unarmed_run_back.glb", label: "unarmed run back (24f / 0.8s, 83KB)" },
  { value: "media/sandbox/anims/anim_unarmed_run_forward.glb", label: "unarmed run forward (25f / 0.8s, 75KB)" },
  { value: "media/sandbox/anims/anim_unarmed_turn_left_90.glb", label: "unarmed turn left 90 (46f / 1.5s, 103KB)" },
  { value: "media/sandbox/anims/anim_unarmed_turn_right_90.glb", label: "unarmed turn right 90 (46f / 1.5s, 101KB)" },
  { value: "media/sandbox/anims/anim_unarmed_walk_back.glb", label: "unarmed walk back (40f / 1.3s, 98KB)" },
  { value: "media/sandbox/anims/anim_unarmed_walk_forward.glb", label: "unarmed walk forward (42f / 1.4s, 100KB)" },
  { value: "media/sandbox/anims/anim_uppercut.glb", label: "Uppercut (41f / 1.4s, 92KB)" },
  { value: "media/sandbox/anims/anim_uppercut_jab.glb", label: "Uppercut Jab (109f / 3.6s, 129KB)" },
  { value: "media/sandbox/anims/anim_uppercut_jab_1.glb", label: "Uppercut Jab (109f / 3.6s, 129KB)" },
  { value: "media/sandbox/anims/anim_vampiric_bite.glb", label: "Vampiric Bite (92f / 3.1s, 141KB)" },
  { value: "media/sandbox/anims/anim_victory.glb", label: "Victory (184f / 6.1s, 219KB)" },
  { value: "media/sandbox/anims/anim_walking.glb", label: "Walking (30f / 1.0s, 90KB)" },
  { value: "media/sandbox/anims/anim_walking_backward.glb", label: "Walking Backward (38f / 1.3s, 95KB)" },
  { value: "media/sandbox/anims/anim_walking_slow.glb", label: "Walking slow (139f / 4.6s, 180KB)" },
  { value: "media/sandbox/anims/anim_walking_test.glb", label: "Walking Test (42f / 1.4s, 86KB)" },
  { value: "media/sandbox/anims/anim_wall_run.glb", label: "Wall Run (29f / 1.0s, 85KB)" },
  { value: "media/sandbox/anims/anim_watering.glb", label: "Watering (169f / 5.6s, 207KB)" },
  { value: "media/sandbox/anims/anim_waving.glb", label: "Waving (96f / 3.2s, 130KB)" },
  { value: "media/sandbox/anims/anim_weight_shift.glb", label: "weight shift (284f / 9.5s, 300KB)" },
  { value: "media/sandbox/anims/anim_wheelbarrow_dump.glb", label: "wheelbarrow dump (188f / 6.3s, 221KB)" },
  { value: "media/sandbox/anims/anim_wheelbarrow_idle.glb", label: "wheelbarrow idle (44f / 1.5s, 80KB)" },
  { value: "media/sandbox/anims/anim_wheelbarrow_walk.glb", label: "wheelbarrow walk (30f / 1.0s, 77KB)" },
  { value: "media/sandbox/anims/anim_wheelbarrow_walk_2.glb", label: "wheelbarrow walk (30f / 1.0s, 76KB)" },
  { value: "media/sandbox/anims/anim_wheelbarrow_walk_turn.glb", label: "Wheelbarrow Walk Turn (33f / 1.1s, 92KB)" },
  { value: "media/sandbox/anims/anim_wheelbarrow_walk_turn_2.glb", label: "wheelbarrow walk turn (33f / 1.1s, 91KB)" },
  { value: "media/sandbox/anims/anim_wheelchair.glb", label: "Wheelchair (49f / 1.6s, 107KB)" },
  { value: "media/sandbox/anims/anim_wiping_sweat.glb", label: "Wiping Sweat (80f / 2.7s, 114KB)" },
  { value: "media/sandbox/anims/anim_woman-solo.glb", label: "Woman-Solo (121f / 5.0s, 1826KB)" },
  { value: "media/sandbox/anims/anim_writhing_in_pain.glb", label: "Writhing In Pain (171f / 5.7s, 130KB)" },
  { value: "media/sandbox/anims/anim_writing.glb", label: "Writing (151f / 5.0s, 117KB)" },
  { value: "media/sandbox/anims/anim_x_bot.glb", label: "X Bot (2f / 0.1s, 1794KB)" },
  { value: "media/sandbox/anims/anim_yelling.glb", label: "Yelling (236f / 7.9s, 262KB)" },
  { value: "media/sandbox/anims/anim_ymca_dance.glb", label: "Ymca Dance (136f / 4.5s, 178KB)" },
  { value: "media/sandbox/anims/anim_ymca_dance_1.glb", label: "Ymca Dance (136f / 4.5s, 178KB)" },
  { value: "media/sandbox/anims/anim_zombie_attack.glb", label: "zombie attack (76f / 2.5s, 124KB)" },
  { value: "media/sandbox/anims/anim_zombie_biting.glb", label: "Zombie Biting (209f / 7.0s, 238KB)" },
  { value: "media/sandbox/anims/anim_zombie_biting_2.glb", label: "zombie biting (70f / 2.3s, 122KB)" },
  { value: "media/sandbox/anims/anim_zombie_crawl.glb", label: "zombie crawl (155f / 5.2s, 197KB)" },
  { value: "media/sandbox/anims/anim_zombie_death.glb", label: "zombie death (85f / 2.8s, 135KB)" },
  { value: "media/sandbox/anims/anim_zombie_dying.glb", label: "zombie dying (100f / 3.3s, 148KB)" },
  { value: "media/sandbox/anims/anim_zombie_idle.glb", label: "zombie idle (129f / 4.3s, 112KB)" },
  { value: "media/sandbox/anims/anim_zombie_neck_bite.glb", label: "zombie neck bite (123f / 4.1s, 167KB)" },
  { value: "media/sandbox/anims/anim_zombie_run.glb", label: "zombie run (25f / 0.8s, 75KB)" },
  { value: "media/sandbox/anims/anim_zombie_scream.glb", label: "zombie scream (85f / 2.8s, 136KB)" },
  { value: "media/sandbox/anims/anim_zombie_walk.glb", label: "zombie walk (122f / 4.1s, 111KB)" },
  { value: "media/sandbox/anims/anim_armature__emote_f_genaiguy.glb", label: " Emote F (725f / 12.1s, 41334KB)" },
  { value: "media/sandbox/anims/anim_armature__talk_f_genaiguy.glb", label: " Talk F (926f / 15.4s, 41318KB)" },
  { value: "media/sandbox/anims/anim_armature_air_dance_genaiguy.glb", label: "Air Dance (562f / 9.4s, 41340KB)" },
  { value: "media/sandbox/anims/anim_armature_b1_attack_back_somersault_flip_genaiguy.glb", label: "B1 Attack Back Somersault Flip (523f / 8.7s, 41339KB)" },
  { value: "media/sandbox/anims/miley_blender_b1_attack.glb", label: "B1 Attack Back Somersault (523f / 8.7s, 4728KB)" },
  { value: "media/sandbox/anims/miley_blender_idle01_f.glb", label: "Idle01 F (1987f / 33.1s, 3641KB)" },

  { value: "media/sandbox/anims/anim_armature_b1_fall_kicked_knockout_genaiguy.glb", label: "B1 Fall Kicked Knockout (523f / 8.7s, 41339KB)" },
  { value: "media/sandbox/anims/anim_armature_b2_attack_front_kick_genaiguy.glb", label: "B2 Attack Front Kick (296f / 4.9s, 41330KB)" },
  { value: "media/sandbox/anims/anim_armature_b3_attack_reverse_turning_kick_genaiguy.glb", label: "B3 Attack Reverse Turning Kick (315f / 5.3s, 41331KB)" },
  { value: "media/sandbox/anims/anim_armature_catwalk_end_genaiguy.glb", label: "Catwalk End (96f / 1.6s, 41322KB)" },
  { value: "media/sandbox/anims/anim_armature_catwalk_loop_genaiguy.glb", label: "Catwalk Loop (79f / 1.3s, 41322KB)" },
  { value: "media/sandbox/anims/anim_armature_catwalk_start_genaiguy.glb", label: "Catwalk Start (33f / 0.6s, 41320KB)" },
  { value: "media/sandbox/anims/anim_armature_change_pose_genaiguy.glb", label: "Change Pose (1083f / 18.0s, 41361KB)" },
  { value: "media/sandbox/anims/anim_armature_d1_attack_arms_block_genaiguy.glb", label: "D1 Attack Arms Block (342f / 5.7s, 41332KB)" },
  { value: "media/sandbox/anims/anim_armature_d1_dodge_sideways_genaiguy.glb", label: "D1 Dodge Sideways (342f / 5.7s, 41332KB)" },
  { value: "media/sandbox/anims/anim_armature_d3_dodge_duck_genaiguy.glb", label: "D3 Dodge Duck (394f / 6.6s, 41334KB)" },
  { value: "media/sandbox/anims/anim_armature_d4_attack_reverse_&_front_snap_kick_genaiguy.glb", label: "D4 Attack Reverse & Front Snap Kick (515f / 8.6s, 41339KB)" },
  { value: "media/sandbox/anims/anim_armature_d4_dodge_roll_back_genaiguy.glb", label: "D4 Dodge Roll Back (515f / 8.6s, 41339KB)" },
  { value: "media/sandbox/anims/anim_armature_dance_graceful_genaiguy.glb", label: "Dance Graceful (1394f / 23.2s, 41373KB)" },
  { value: "media/sandbox/anims/anim_armature_dougie_genaiguy.glb", label: "Dougie (618f / 10.3s, 41343KB)" },
  { value: "media/sandbox/anims/anim_armature_down_01_genaiguy.glb", label: "Down 01 (689f / 11.5s, 41346KB)" },
  { value: "media/sandbox/anims/anim_armature_female_idle_1_genaiguy.glb", label: "Female Idle 1 (341f / 5.7s, 41332KB)" },
  { value: "media/sandbox/anims/anim_armature_female_idle_2_genaiguy.glb", label: "Female Idle 2 (920f / 15.3s, 41355KB)" },
  { value: "media/sandbox/anims/anim_armature_idle01_f_genaiguy.glb", label: "Idle01 F (1987f / 33.1s, 41396KB)" },
  { value: "media/sandbox/anims/anim_armature_idle02_f_genaiguy.glb", label: "Idle02 F (1909f / 31.8s, 41393KB)" },
  { value: "media/sandbox/anims/anim_armature_idle03_f_genaiguy.glb", label: "Idle03 F (1109f / 18.5s, 41362KB)" },
  { value: "media/sandbox/anims/anim_armature_posing_f_genaiguy.glb", label: "Posing F (1358f / 22.6s, 41372KB)" },
  { value: "media/sandbox/anims/anim_armature_sensual_dance_01_genaiguy.glb", label: "Sensual Dance 01 (669f / 11.1s, 41345KB)" },
  { value: "media/sandbox/anims/anim_armature_sensual_dance_02_genaiguy.glb", label: "Sensual Dance 02 (822f / 13.7s, 41351KB)" },
  { value: "media/sandbox/anims/anim_armature_sensual_dance_03_genaiguy.glb", label: "Sensual Dance 03 (552f / 9.2s, 41340KB)" },
  { value: "media/sandbox/anims/anim_armature_sit_talk_genaiguy.glb", label: "Sit Talk (1181f / 19.7s, 41365KB)" },
  { value: "media/sandbox/anims/anim_armature_stand_talk_genaiguy.glb", label: "Stand Talk (1691f / 28.2s, 41385KB)" },
  { value: "media/sandbox/anims/anim_armature_stand_to_sit_genaiguy.glb", label: "Stand To Sit (304f / 5.1s, 41331KB)" },
  { value: "media/sandbox/anims/anim_armature_walk_relaxed_end_genaiguy.glb", label: "Walk Relaxed End (162f / 2.7s, 41325KB)" },
  { value: "media/sandbox/anims/anim_armature_walk_relaxed_loop_genaiguy.glb", label: "Walk Relaxed Loop (293f / 4.9s, 41330KB)" },
  { value: "media/sandbox/anims/anim_armature_walk_relaxed_start_genaiguy.glb", label: "Walk Relaxed Start (213f / 3.5s, 41327KB)" },
  { value: "media/sandbox/anims/anim_armature_walk_f_genaiguy.glb", label: "Walk F (1077f / 18.0s, 41361KB)" },

].filter((v, i, a) => a.findIndex(t => t.value === v.value) === i).sort((a, b) => {
  if (a.value === "idle") return -1;
  if (b.value === "idle") return 1;
  if (a.value.includes("t-pose")) return -1;
  if (b.value.includes("t-pose")) return 1;
  return a.label.localeCompare(b.label, 'fr', { sensitivity: 'base' });
});

