export interface HdriItem {
  id: string;
  name: string;
  url: string;
  type: 'hdr' | 'jpg';
}

export const HDRI_LIST: HdriItem[] = [
  { id: 'default', name: 'Ciel nuageux (Défaut) ⛅', url: '/environment/HDR_029_Sky_Cloudy_Bg.jpg', type: 'jpg' },

  // --- Nature, Forêts, Sentiers & Jardins ---
  { id: 'path_041', name: 'Sentier de terre arboré 🌲🚶', url: '/environment/hdri/HDR_041_Path.hdr', type: 'hdr' },
  { id: 'forest_slope', name: 'Sous-bois & Versant forestier 🌲', url: '/environment/hdri/forest_slope_1k.hdr', type: 'hdr' },
  { id: 'egg_hill_valley', name: 'Colline Egg Hill & Vue sur la vallée 🌄🌲', url: '/environment/hdri/egg-hill-distant-valley-glow_4K.hdr', type: 'hdr' },
  { id: 'gruntowa_golden_hour', name: 'Chemin Gruntowa à l\'heure dorée 🌅🌾', url: '/environment/hdri/gruntowa-april-golden-hour_4K.hdr', type: 'hdr' },
  { id: 'gruntowa_pre_sunset', name: 'Chemin Gruntowa avant le crépuscule 🌇🌾', url: '/environment/hdri/gruntowa-april-pre-sunset_4K.hdr', type: 'hdr' },
  { id: 'gruntowa_may_cumulus', name: 'Chemin Gruntowa & Cumulus de mai 🌾☁️', url: '/environment/hdri/gruntowa-may-cumulus_4K.hdr', type: 'hdr' },
  { id: 'naroznik_autumn_haze', name: 'Narożnik & Brume automnale 🍂🌫️', url: '/environment/hdri/naroznik-autumn-haze_4K.hdr', type: 'hdr' },
  { id: 'pilgrim_farmland', name: 'Terres de pèlerinage au soleil d\'octobre 🌾☀️', url: '/environment/hdri/pilgrim-farmland-october-sun_4K.hdr', type: 'hdr' },
  { id: 'polanica_fountain_square', name: 'Place de la fontaine à Polanica ⛲🌳', url: '/environment/hdri/polanica-fountain-square_4K.hdr', type: 'hdr' },
  { id: 'polanica_fountain_terrace', name: 'Terrasse fleurie & Fontaine Polanica ⛲🌺', url: '/environment/hdri/polanica-fountain-terrace_4K.hdr', type: 'hdr' },
  { id: 'rock_theatre_viewpoint', name: 'Belvédère du théâtre de roche 🪨🌲', url: '/environment/hdri/rock-theatre-viewpoint_4K.hdr', type: 'hdr' },
  { id: 'skarpa_winter_forest', name: 'Forêt d\'hiver Skarpa ❄️🌲', url: '/environment/hdri/skarpa-winter-forest_4K.hdr', type: 'hdr' },
  { id: 'sunlit_castle_fountain', name: 'Fontaine de château baignée de soleil 🏰⛲', url: '/environment/hdri/sunlit-castle-fountain_4K.hdr', type: 'hdr' },

  // --- Campagne, Champs, Prairies & Sports extérieurs ---
  { id: 'baseball_field_day', name: 'Terrain de baseball sous ciel clair ⚾🏟️', url: '/environment/hdri/HdrOutdoorFieldBaseballDayClear001_8k.hdr', type: 'hdr' },
  { id: 'sports_field_overcast', name: 'Grand terrain de sport sous ciel couvert 🏟️☁️', url: '/environment/hdri/HdrOutdoorFieldDayOvercast004_8k.hdr', type: 'hdr' },
  { id: 'soccer_field_winter', name: 'Terrain de football en hiver ⚽❄️', url: '/environment/hdri/HdrOutdoorSoccerFieldWinterDayClear001_8k.hdr', type: 'hdr' },
  { id: 'rafalonka_winter_meadow', name: 'Prairie d\'hiver Rafałonka ❄️🌾', url: '/environment/hdri/rafalonka-winter-meadow_4K.hdr', type: 'hdr' },
  { id: 'rubinkowo_sandbox', name: 'Espace sableux Rubinkowo 🏖️🌥️', url: '/environment/hdri/rubinkowo-sandbox-overcast_4K.hdr', type: 'hdr' },

  // --- Montagne & Hiver Enneigé ---

  // --- Mer, Plage, Lacs & Horizons Marins ---

  { id: 'harbor_3', name: 'Port maritime & Quais ⛵⚓', url: '/environment/hdri/Harbor_3_Free.hdr', type: 'hdr' },

  // --- Ciel, Altitude, Dômes & HDRI-Skies ---
  { id: 'kiara_dawn', name: 'Aube dorée Kiara 🌅', url: '/environment/hdri/kiara_1_dawn_1k.hdr', type: 'hdr' },
  { id: 'sky_cloudy_029', name: 'Ciel nuageux panoramique ⛅', url: '/environment/hdri/HDR_029_Sky_Cloudy.hdr', type: 'hdr' },

  // --- Ville, Rues, Architecture & Nuit ---
  { id: 'dikhololo_night', name: 'Dikhololo - Nuit étoilée & Camp 🌌', url: '/environment/hdri/dikhololo_night_1k.hdr', type: 'hdr' },
  { id: 'stonewall', name: 'Allée pavée & Mur de pierre historique 🧱🏛️', url: '/environment/hdri/Stonewall.hdr', type: 'hdr' },
  { id: 'broumov_runway', name: 'Piste d\'aérodrome Broumov 🛫🛣️', url: '/environment/hdri/broumov-airport-runway_4K.hdr', type: 'hdr' },
  { id: 'container_dock', name: 'Zone portuaire & Conteneurs 📦🏗️', url: '/environment/hdri/container_free.hdr', type: 'hdr' },
  { id: 'sunny_industrial_yard', name: 'Cour industrielle ensoleillée 🏭☀️', url: '/environment/hdri/sunny-industrial-yard_4K.hdr', type: 'hdr' },

  // --- Studios photo & Intérieurs Design ---
  { id: 'big_studio_01', name: 'Grand studio photo neutre 1 🎬💡', url: '/environment/hdri/big-studio-01_4K.hdr', type: 'hdr' },
  { id: 'fly_studio_05', name: 'Studio Fly à contraste élevé 5 💡🎥', url: '/environment/hdri/fly-studio-05_4K.hdr', type: 'hdr' },
  { id: 'studio_2nd_cyclorama', name: 'Cyclorama d\'étage de studio 📸⚪', url: '/environment/hdri/studio-2nd-floor-cyclorama_4K.hdr', type: 'hdr' },

  // --- Auto-generated city/environment HDRIs ---
  { id: 'abandoned_factory_canteen_01_4k', name: 'abandoned factory canteen 01 4k', url: '/environment/hdri/abandoned_factory_canteen_01_4k.hdr', type: 'hdr' },
  { id: 'abandoned_pathway_4k', name: 'abandoned pathway 4k', url: '/environment/hdri/abandoned_pathway_4k.hdr', type: 'hdr' },
  { id: 'abandoned_tank_farm_03_4k', name: 'abandoned tank farm 03 4k', url: '/environment/hdri/abandoned_tank_farm_03_4k.hdr', type: 'hdr' },
  { id: 'adams_place_bridge_4k', name: 'adams place bridge 4k', url: '/environment/hdri/adams_place_bridge_4k.hdr', type: 'hdr' },
  { id: 'aerodynamics_workshop_4k', name: 'aerodynamics workshop 4k', url: '/environment/hdri/aerodynamics_workshop_4k.hdr', type: 'hdr' },
  { id: 'ahornsteig_4k', name: 'ahornsteig 4k', url: '/environment/hdri/ahornsteig_4k.hdr', type: 'hdr' },
  { id: 'aloe_farm_shade_house_4k', name: 'aloe farm shade house 4k', url: '/environment/hdri/aloe_farm_shade_house_4k.hdr', type: 'hdr' },
  { id: 'alps_field_4k', name: 'alps field 4k', url: '/environment/hdri/alps_field_4k.hdr', type: 'hdr' },
  { id: 'arboretum_4k', name: 'arboretum 4k', url: '/environment/hdri/arboretum_4k.hdr', type: 'hdr' },
  { id: 'aristea_wreck_4k', name: 'aristea wreck 4k', url: '/environment/hdri/aristea_wreck_4k.hdr', type: 'hdr' },
  { id: 'autumn_field_4k', name: 'autumn field 4k', url: '/environment/hdri/autumn_field_4k.hdr', type: 'hdr' },
  { id: 'autumn_forest_04_4k', name: 'autumn forest 04 4k', url: '/environment/hdri/autumn_forest_04_4k.hdr', type: 'hdr' },
  { id: 'autumn_hockey_4k', name: 'autumn hockey 4k', url: '/environment/hdri/autumn_hockey_4k.hdr', type: 'hdr' },
  { id: 'ballawley_park_4k', name: 'ballawley park 4k', url: '/environment/hdri/ballawley_park_4k.hdr', type: 'hdr' },
  { id: 'belfast_sunset_4k', name: 'belfast sunset 4k', url: '/environment/hdri/belfast_sunset_4k.hdr', type: 'hdr' },
  { id: 'bell_park_pier_4k', name: 'bell park pier 4k', url: '/environment/hdri/bell_park_pier_4k.hdr', type: 'hdr' },
  { id: 'bethnal_green_entrance_4k', name: 'bethnal green entrance 4k', url: '/environment/hdri/bethnal_green_entrance_4k.hdr', type: 'hdr' },
  { id: 'between_bridges_4k', name: 'between bridges 4k', url: '/environment/hdri/between_bridges_4k.hdr', type: 'hdr' },
  { id: 'big_studio_01_4k', name: 'big studio 01 4K', url: '/environment/hdri/big-studio-01_4K.hdr', type: 'hdr' },
  { id: 'binnenalster_4k', name: 'binnenalster 4k', url: '/environment/hdri/binnenalster_4k.hdr', type: 'hdr' },
  { id: 'birbeck_street_underpass_4k', name: 'birbeck street underpass 4k', url: '/environment/hdri/birbeck_street_underpass_4k.hdr', type: 'hdr' },
  { id: 'birchwood_4k', name: 'birchwood 4k', url: '/environment/hdri/birchwood_4k.hdr', type: 'hdr' },
  { id: 'blender_institute_4k', name: 'blender institute 4k', url: '/environment/hdri/blender_institute_4k.hdr', type: 'hdr' },
  { id: 'blouberg_sunrise_1_4k', name: 'blouberg sunrise 1 4k', url: '/environment/hdri/blouberg_sunrise_1_4k.hdr', type: 'hdr' },
  { id: 'blouberg_sunrise_2_4k', name: 'blouberg sunrise 2 4k', url: '/environment/hdri/blouberg_sunrise_2_4k.hdr', type: 'hdr' },
  { id: 'blue_lagoon_4k', name: 'blue lagoon 4k', url: '/environment/hdri/blue_lagoon_4k.hdr', type: 'hdr' },
  { id: 'blue_lagoon_night_4k', name: 'blue lagoon night 4k', url: '/environment/hdri/blue_lagoon_night_4k.hdr', type: 'hdr' },
  { id: 'brick_factory_02_4k', name: 'brick factory 02 4k', url: '/environment/hdri/brick_factory_02_4k.hdr', type: 'hdr' },
  { id: 'broumov_airport_runway_4k', name: 'broumov airport runway 4K', url: '/environment/hdri/broumov-airport-runway_4K.hdr', type: 'hdr' },
  { id: 'brown_photostudio_02_4k', name: 'brown photostudio 02 4k', url: '/environment/hdri/brown_photostudio_02_4k.hdr', type: 'hdr' },
  { id: 'brown_photostudio_04_4k', name: 'brown photostudio 04 4k', url: '/environment/hdri/brown_photostudio_04_4k.hdr', type: 'hdr' },
  { id: 'brown_photostudio_07_4k', name: 'brown photostudio 07 4k', url: '/environment/hdri/brown_photostudio_07_4k.hdr', type: 'hdr' },
  { id: 'bryanston_park_sunrise_4k', name: 'bryanston park sunrise 4k', url: '/environment/hdri/bryanston_park_sunrise_4k.hdr', type: 'hdr' },
  { id: 'buikslotermeerplein_4k', name: 'buikslotermeerplein 4k', url: '/environment/hdri/buikslotermeerplein_4k.hdr', type: 'hdr' },
  { id: 'cambridge_4k', name: 'cambridge 4k', url: '/environment/hdri/cambridge_4k.hdr', type: 'hdr' },
  { id: 'camdeboo_road_4k', name: 'camdeboo road 4k', url: '/environment/hdri/camdeboo_road_4k.hdr', type: 'hdr' },
  { id: 'canary_wharf_4k', name: 'canary wharf 4k', url: '/environment/hdri/canary_wharf_4k.hdr', type: 'hdr' },
  { id: 'cave_wall_4k', name: 'cave wall 4k', url: '/environment/hdri/cave_wall_4k.hdr', type: 'hdr' },
  { id: 'cayley_interior_4k', name: 'cayley interior 4k', url: '/environment/hdri/cayley_interior_4k.hdr', type: 'hdr' },
  { id: 'cayley_lookout_4k', name: 'cayley lookout 4k', url: '/environment/hdri/cayley_lookout_4k.hdr', type: 'hdr' },
  { id: 'chapel_day_4k', name: 'chapel day 4k', url: '/environment/hdri/chapel_day_4k.hdr', type: 'hdr' },
  { id: 'chinese_garden_4k', name: 'chinese garden 4k', url: '/environment/hdri/chinese_garden_4k.hdr', type: 'hdr' },
  { id: 'christmas_photo_studio_03_4k', name: 'christmas photo studio 03 4k', url: '/environment/hdri/christmas_photo_studio_03_4k.hdr', type: 'hdr' },
  { id: 'christmas_photo_studio_04_4k', name: 'christmas photo studio 04 4k', url: '/environment/hdri/christmas_photo_studio_04_4k.hdr', type: 'hdr' },
  { id: 'christmas_photo_studio_05_4k', name: 'christmas photo studio 05 4k', url: '/environment/hdri/christmas_photo_studio_05_4k.hdr', type: 'hdr' },
  { id: 'circus_maximus_1_4k', name: 'circus maximus 1 4k', url: '/environment/hdri/circus_maximus_1_4k.hdr', type: 'hdr' },
  { id: 'citrus_orchard_road_4k', name: 'citrus orchard road 4k', url: '/environment/hdri/citrus_orchard_road_4k.hdr', type: 'hdr' },
  { id: 'climbing_gym_4k', name: 'climbing gym 4k', url: '/environment/hdri/climbing_gym_4k.hdr', type: 'hdr' },
  { id: 'cobblestone_street_night_4k', name: 'cobblestone street night 4k', url: '/environment/hdri/cobblestone_street_night_4k.hdr', type: 'hdr' },
  { id: 'colosseum_4k', name: 'colosseum 4k', url: '/environment/hdri/colosseum_4k.hdr', type: 'hdr' },
  { id: 'comfy_cafe_4k', name: 'comfy cafe 4k', url: '/environment/hdri/comfy_cafe_4k.hdr', type: 'hdr' },
  { id: 'concrete_bowl', name: 'Concrete Bowl', url: '/environment/hdri/Concrete_Bowl.hdr', type: 'hdr' },
  { id: 'courtyard_night_4k', name: 'courtyard night 4k', url: '/environment/hdri/courtyard_night_4k.hdr', type: 'hdr' },
  { id: 'dam_bridge_4k', name: 'dam bridge 4k', url: '/environment/hdri/dam_bridge_4k.hdr', type: 'hdr' },
  { id: 'dam_wall_4k', name: 'dam wall 4k', url: '/environment/hdri/dam_wall_4k.hdr', type: 'hdr' },
  { id: 'derelict_highway_noon_4k', name: 'derelict highway noon 4k', url: '/environment/hdri/derelict_highway_noon_4k.hdr', type: 'hdr' },
  { id: 'derelict_overpass_4k', name: 'derelict overpass 4k', url: '/environment/hdri/derelict_overpass_4k.hdr', type: 'hdr' },
  { id: 'derelict_underpass_4k', name: 'derelict underpass 4k', url: '/environment/hdri/derelict_underpass_4k.hdr', type: 'hdr' },
  { id: 'dirt_bike_track_01_4k', name: 'dirt bike track 01 4k', url: '/environment/hdri/dirt_bike_track_01_4k.hdr', type: 'hdr' },
  { id: 'docklands_01_4k', name: 'docklands 01 4k', url: '/environment/hdri/docklands_01_4k.hdr', type: 'hdr' },
  { id: 'docklands_02_4k', name: 'docklands 02 4k', url: '/environment/hdri/docklands_02_4k.hdr', type: 'hdr' },
  { id: 'dreifaltigkeitsberg_4k', name: 'dreifaltigkeitsberg 4k', url: '/environment/hdri/dreifaltigkeitsberg_4k.hdr', type: 'hdr' },
  { id: 'dresden_moat_4k', name: 'dresden moat 4k', url: '/environment/hdri/dresden_moat_4k.hdr', type: 'hdr' },
  { id: 'dusseldorf_bridge_4k', name: 'dusseldorf bridge 4k', url: '/environment/hdri/dusseldorf_bridge_4k.hdr', type: 'hdr' },
  { id: 'emmarentia_4k', name: 'emmarentia 4k', url: '/environment/hdri/emmarentia_4k.hdr', type: 'hdr' },
  { id: 'epping_forest_01_4k', name: 'epping forest 01 4k', url: '/environment/hdri/epping_forest_01_4k.hdr', type: 'hdr' },
  { id: 'evening_meadow_4k', name: 'evening meadow 4k', url: '/environment/hdri/evening_meadow_4k.hdr', type: 'hdr' },
  { id: 'factory_yard_4k', name: 'factory yard 4k', url: '/environment/hdri/factory_yard_4k.hdr', type: 'hdr' },
  { id: 'felsenlabyrinth_4k', name: 'felsenlabyrinth 4k', url: '/environment/hdri/felsenlabyrinth_4k.hdr', type: 'hdr' },
  { id: 'ferndale_studio_02_4k', name: 'ferndale studio 02 4k', url: '/environment/hdri/ferndale_studio_02_4k.hdr', type: 'hdr' },
  { id: 'ferndale_studio_10_4k', name: 'ferndale studio 10 4k', url: '/environment/hdri/ferndale_studio_10_4k.hdr', type: 'hdr' },
  { id: 'ferndale_studio_12_4k', name: 'ferndale studio 12 4k', url: '/environment/hdri/ferndale_studio_12_4k.hdr', type: 'hdr' },
  { id: 'fish_hoek_beach_4k', name: 'fish hoek beach 4k', url: '/environment/hdri/fish_hoek_beach_4k.hdr', type: 'hdr' },
  { id: 'flamingo_pan_4k', name: 'flamingo pan 4k', url: '/environment/hdri/flamingo_pan_4k.hdr', type: 'hdr' },
  { id: 'flower_road_4k', name: 'flower road 4k', url: '/environment/hdri/flower_road_4k.hdr', type: 'hdr' },
  { id: 'fly_studio_05_4k', name: 'fly studio 05 4K', url: '/environment/hdri/fly-studio-05_4K.hdr', type: 'hdr' },
  { id: 'freight_station_4k', name: 'freight station 4k', url: '/environment/hdri/freight_station_4k.hdr', type: 'hdr' },
  { id: 'frozen_lake_4k', name: 'frozen lake 4k', url: '/environment/hdri/frozen_lake_4k.hdr', type: 'hdr' },
  { id: 'furry_clouds_4k', name: 'furry clouds 4k', url: '/environment/hdri/furry_clouds_4k.hdr', type: 'hdr' },
  { id: 'georgentor_4k', name: 'georgentor 4k', url: '/environment/hdri/georgentor_4k.hdr', type: 'hdr' },
  { id: 'golden_bay_4k', name: 'golden bay 4k', url: '/environment/hdri/golden_bay_4k.hdr', type: 'hdr' },
  { id: 'gothic_manor_02_4k', name: 'gothic manor 02 4k', url: '/environment/hdri/gothic_manor_02_4k.hdr', type: 'hdr' },
  { id: 'graffiti_shelter_4k', name: 'graffiti shelter 4k', url: '/environment/hdri/graffiti_shelter_4k.hdr', type: 'hdr' },
  { id: 'gray_pier_4k', name: 'gray pier 4k', url: '/environment/hdri/gray_pier_4k.hdr', type: 'hdr' },
  { id: 'green_sanctuary_4k', name: 'green sanctuary 4k', url: '/environment/hdri/green_sanctuary_4k.hdr', type: 'hdr' },
  { id: 'gruntowa_may_cumulus_4k', name: 'gruntowa may cumulus 4K', url: '/environment/hdri/gruntowa-may-cumulus_4K.hdr', type: 'hdr' },
  { id: 'gym_entrance_4k', name: 'gym entrance 4k', url: '/environment/hdri/gym_entrance_4k.hdr', type: 'hdr' },
  { id: 'halle_skyline', name: 'Halle Skyline', url: '/environment/hdri/Halle_Skyline.hdr', type: 'hdr' },
  { id: 'hansaplatz_4k', name: 'hansaplatz 4k', url: '/environment/hdri/hansaplatz_4k.hdr', type: 'hdr' },
  { id: 'harties_4k', name: 'harties 4k', url: '/environment/hdri/harties_4k.hdr', type: 'hdr' },
  { id: 'homecoming_center_rooftop_4k', name: 'homecoming center rooftop 4k', url: '/environment/hdri/homecoming_center_rooftop_4k.hdr', type: 'hdr' },
  { id: 'horn_koppe_snow_4k', name: 'horn koppe snow 4k', url: '/environment/hdri/horn-koppe_snow_4k.hdr', type: 'hdr' },
  { id: 'hospital_room_2_4k', name: 'hospital room 2 4k', url: '/environment/hdri/hospital_room_2_4k.hdr', type: 'hdr' },
  { id: 'hospital_room_4k', name: 'hospital room 4k', url: '/environment/hdri/hospital_room_4k.hdr', type: 'hdr' },
  { id: 'hotel_rooftop_balcony_4k', name: 'hotel rooftop balcony 4k', url: '/environment/hdri/hotel_rooftop_balcony_4k.hdr', type: 'hdr' },
  { id: 'indoor_pool_4k', name: 'indoor pool 4k', url: '/environment/hdri/indoor_pool_4k.hdr', type: 'hdr' },
  { id: 'industrial_wooden_attic_4k', name: 'industrial wooden attic 4k', url: '/environment/hdri/industrial_wooden_attic_4k.hdr', type: 'hdr' },
  { id: 'klippad_sunrise_2_4k', name: 'klippad sunrise 2 4k', url: '/environment/hdri/klippad_sunrise_2_4k.hdr', type: 'hdr' },
  { id: 'ladybrand_heritage_house_4k', name: 'ladybrand heritage house 4k', url: '/environment/hdri/ladybrand_heritage_house_4k.hdr', type: 'hdr' },
  { id: 'lake_pier_4k', name: 'lake pier 4k', url: '/environment/hdri/lake_pier_4k.hdr', type: 'hdr' },
  { id: 'lakeside_4k', name: 'lakeside 4k', url: '/environment/hdri/lakeside_4k.hdr', type: 'hdr' },
  { id: 'lakeside_dawn_4k', name: 'lakeside dawn 4k', url: '/environment/hdri/lakeside_dawn_4k.hdr', type: 'hdr' },
  { id: 'lakeside_night_4k', name: 'lakeside night 4k', url: '/environment/hdri/lakeside_night_4k.hdr', type: 'hdr' },
  { id: 'lakeside_sunrise_4k', name: 'lakeside sunrise 4k', url: '/environment/hdri/lakeside_sunrise_4k.hdr', type: 'hdr' },
  { id: 'laufenurg_church_4k', name: 'laufenurg church 4k', url: '/environment/hdri/laufenurg_church_4k.hdr', type: 'hdr' },
  { id: 'lebombo_4k', name: 'lebombo 4k', url: '/environment/hdri/lebombo_4k.hdr', type: 'hdr' },
  { id: 'lilienstein_4k', name: 'lilienstein 4k', url: '/environment/hdri/lilienstein_4k.hdr', type: 'hdr' },
  { id: 'limpopo_golf_course_4k', name: 'limpopo golf course 4k', url: '/environment/hdri/limpopo_golf_course_4k.hdr', type: 'hdr' },
  { id: 'little_paris_eiffel_tower_4k', name: 'little paris eiffel tower 4k', url: '/environment/hdri/little_paris_eiffel_tower_4k.hdr', type: 'hdr' },
  { id: 'lot_02_4k', name: 'lot 02 4k', url: '/environment/hdri/lot_02_4k.hdr', type: 'hdr' },
  { id: 'lythwood_field_4k', name: 'lythwood field 4k', url: '/environment/hdri/lythwood_field_4k.hdr', type: 'hdr' },
  { id: 'malagas_ferry_road_4k', name: 'malagas ferry road 4k', url: '/environment/hdri/malagas_ferry_road_4k.hdr', type: 'hdr' },
  { id: 'meadow_2_4k', name: 'meadow 2 4k', url: '/environment/hdri/meadow_2_4k.hdr', type: 'hdr' },
  { id: 'minedump_flats_4k', name: 'minedump flats 4k', url: '/environment/hdri/minedump_flats_4k.hdr', type: 'hdr' },
  { id: 'missile_launch_facility_01_4k', name: 'missile launch facility 01 4k', url: '/environment/hdri/missile_launch_facility_01_4k.hdr', type: 'hdr' },
  { id: 'misty_pines_4k', name: 'misty pines 4k', url: '/environment/hdri/misty_pines_4k.hdr', type: 'hdr' },
  { id: 'modern_bathroom_4k', name: 'modern bathroom 4k', url: '/environment/hdri/modern_bathroom_4k.hdr', type: 'hdr' },
  { id: 'modern_buildings_2_4k', name: 'modern buildings 2 4k', url: '/environment/hdri/modern_buildings_2_4k.hdr', type: 'hdr' },
  { id: 'modern_buildings_4k', name: 'modern buildings 4k', url: '/environment/hdri/modern_buildings_4k.hdr', type: 'hdr' },
  { id: 'modern_buildings_night_4k', name: 'modern buildings night 4k', url: '/environment/hdri/modern_buildings_night_4k.hdr', type: 'hdr' },
  { id: 'moulton_falls_train_tunnel_east_4k', name: 'moulton falls train tunnel east 4k', url: '/environment/hdri/moulton_falls_train_tunnel_east_4k.hdr', type: 'hdr' },
  { id: 'moulton_station_train_tunnel_west_4k', name: 'moulton station train tunnel west 4k', url: '/environment/hdri/moulton_station_train_tunnel_west_4k.hdr', type: 'hdr' },
  { id: 'museumplein_4k', name: 'museumplein 4k', url: '/environment/hdri/museumplein_4k.hdr', type: 'hdr' },
  { id: 'nagoya_wall_path_4k', name: 'nagoya wall path 4k', url: '/environment/hdri/nagoya_wall_path_4k.hdr', type: 'hdr' },
  { id: 'naroznik_autumn_haze_4k', name: 'naroznik autumn haze 4K', url: '/environment/hdri/naroznik-autumn-haze_4K.hdr', type: 'hdr' },
  { id: 'near_the_river_01_4k', name: 'near the river 01 4k', url: '/environment/hdri/near_the_river_01_4k.hdr', type: 'hdr' },
  { id: 'neon_photostudio_4k', name: 'neon photostudio 4k', url: '/environment/hdri/neon_photostudio_4k.hdr', type: 'hdr' },
  { id: 'noon_grass_4k', name: 'noon grass 4k', url: '/environment/hdri/noon_grass_4k.hdr', type: 'hdr' },
  { id: 'oberer_kuhberg_4k', name: 'oberer kuhberg 4k', url: '/environment/hdri/oberer_kuhberg_4k.hdr', type: 'hdr' },
  { id: 'old_apartments_walkway_4k', name: 'old apartments walkway 4k', url: '/environment/hdri/old_apartments_walkway_4k.hdr', type: 'hdr' },
  { id: 'old_tree_in_city_park_4k', name: 'old tree in city park 4k', url: '/environment/hdri/old_tree_in_city_park_4k.hdr', type: 'hdr' },
  { id: 'orlando_stadium_4k', name: 'orlando stadium 4k', url: '/environment/hdri/orlando_stadium_4k.hdr', type: 'hdr' },
  { id: 'ouchy_pier_4k', name: 'ouchy pier 4k', url: '/environment/hdri/ouchy_pier_4k.hdr', type: 'hdr' },
  { id: 'outdoor_umbrellas_4k', name: 'outdoor umbrellas 4k', url: '/environment/hdri/outdoor_umbrellas_4k.hdr', type: 'hdr' },
  { id: 'outdoor_workshop_4k', name: 'outdoor workshop 4k', url: '/environment/hdri/outdoor_workshop_4k.hdr', type: 'hdr' },
  { id: 'passendorf_snow_4k', name: 'passendorf snow 4k', url: '/environment/hdri/passendorf_snow_4k.hdr', type: 'hdr' },
  { id: 'pav_studio_02_4k', name: 'pav studio 02 4k', url: '/environment/hdri/pav_studio_02_4k.hdr', type: 'hdr' },
  { id: 'pergola_walkway_4k', name: 'pergola walkway 4k', url: '/environment/hdri/pergola_walkway_4k.hdr', type: 'hdr' },
  { id: 'piazza_martin_lutero_4k', name: 'piazza martin lutero 4k', url: '/environment/hdri/piazza_martin_lutero_4k.hdr', type: 'hdr' },
  { id: 'pilgrim_farmland_october_sun_4k', name: 'pilgrim farmland october sun 4K', url: '/environment/hdri/pilgrim-farmland-october-sun_4K.hdr', type: 'hdr' },
  { id: 'pillars_4k', name: 'pillars 4k', url: '/environment/hdri/pillars_4k.hdr', type: 'hdr' },
  { id: 'pink_sunrise_4k', name: 'pink sunrise 4k', url: '/environment/hdri/pink_sunrise_4k.hdr', type: 'hdr' },
  { id: 'polanica_fountain_square_4k', name: 'polanica fountain square 4K', url: '/environment/hdri/polanica-fountain-square_4K.hdr', type: 'hdr' },
  { id: 'polanica_fountain_terrace_4k', name: 'polanica fountain terrace 4K', url: '/environment/hdri/polanica-fountain-terrace_4K.hdr', type: 'hdr' },
  { id: 'pool_4k', name: 'pool 4k', url: '/environment/hdri/pool_4k.hdr', type: 'hdr' },
  { id: 'potsdamer_platz_4k', name: 'potsdamer platz 4k', url: '/environment/hdri/potsdamer_platz_4k.hdr', type: 'hdr' },
  { id: 'preller_drive_4k', name: 'preller drive 4k', url: '/environment/hdri/preller_drive_4k.hdr', type: 'hdr' },
  { id: 'pretville_street_4k', name: 'pretville street 4k', url: '/environment/hdri/pretville_street_4k.hdr', type: 'hdr' },
  { id: 'quarry_01_4k', name: 'quarry 01 4k', url: '/environment/hdri/quarry_01_4k.hdr', type: 'hdr' },
  { id: 'quarry_cloudy_4k', name: 'quarry cloudy 4k', url: '/environment/hdri/quarry_cloudy_4k.hdr', type: 'hdr' },
  { id: 'qwantani_dusk_2_4k', name: 'qwantani dusk 2 4k', url: '/environment/hdri/qwantani_dusk_2_4k.hdr', type: 'hdr' },
  { id: 'qwantani_night_4k', name: 'qwantani night 4k', url: '/environment/hdri/qwantani_night_4k.hdr', type: 'hdr' },
  { id: 'qwantani_night_puresky_4k', name: 'qwantani night puresky 4k', url: '/environment/hdri/qwantani_night_puresky_4k.hdr', type: 'hdr' },
  { id: 'qwantani_noon_4k', name: 'qwantani noon 4k', url: '/environment/hdri/qwantani_noon_4k.hdr', type: 'hdr' },
  { id: 'qwantani_sunset_4k', name: 'qwantani sunset 4k', url: '/environment/hdri/qwantani_sunset_4k.hdr', type: 'hdr' },
  { id: 'radkow_lake_4k', name: 'radkow lake 4k', url: '/environment/hdri/radkow_lake_4k.hdr', type: 'hdr' },
  { id: 'rafalonka_winter_meadow_4k', name: 'rafalonka winter meadow 4K', url: '/environment/hdri/rafalonka-winter-meadow_4K.hdr', type: 'hdr' },
  { id: 'rainforest_trail_4k', name: 'rainforest trail 4k', url: '/environment/hdri/rainforest_trail_4k.hdr', type: 'hdr' },
  { id: 'rathaus_4k', name: 'rathaus 4k', url: '/environment/hdri/rathaus_4k.hdr', type: 'hdr' },
  { id: 'red_hill_curve_4k', name: 'red hill curve 4k', url: '/environment/hdri/red_hill_curve_4k.hdr', type: 'hdr' },
  { id: 'red_hill_straight_4k', name: 'red hill straight 4k', url: '/environment/hdri/red_hill_straight_4k.hdr', type: 'hdr' },
  { id: 'red_wall_4k', name: 'red wall 4k', url: '/environment/hdri/red_wall_4k.hdr', type: 'hdr' },
  { id: 'resting_place_2_4k', name: 'resting place 2 4k', url: '/environment/hdri/resting_place_2_4k.hdr', type: 'hdr' },
  { id: 'resting_place_4k', name: 'resting place 4k', url: '/environment/hdri/resting_place_4k.hdr', type: 'hdr' },
  { id: 'river_alcove_4k', name: 'river alcove 4k', url: '/environment/hdri/river_alcove_4k.hdr', type: 'hdr' },
  { id: 'river_rocks_4k', name: 'river rocks 4k', url: '/environment/hdri/river_rocks_4k.hdr', type: 'hdr' },
  { id: 'river_walk_1_4k', name: 'river walk 1 4k', url: '/environment/hdri/river_walk_1_4k.hdr', type: 'hdr' },
  { id: 'rock_theatre_viewpoint_4k', name: 'rock theatre viewpoint 4K', url: '/environment/hdri/rock-theatre-viewpoint_4K.hdr', type: 'hdr' },
  { id: 'rogland_clear_night_4k', name: 'rogland clear night 4k', url: '/environment/hdri/rogland_clear_night_4k.hdr', type: 'hdr' },
  { id: 'roof_garden_4k', name: 'roof garden 4k', url: '/environment/hdri/roof_garden_4k.hdr', type: 'hdr' },
  { id: 'roofless_ruins_4k', name: 'roofless ruins 4k', url: '/environment/hdri/roofless_ruins_4k.hdr', type: 'hdr' },
  { id: 'rooftop_night_4k', name: 'rooftop night 4k', url: '/environment/hdri/rooftop_night_4k.hdr', type: 'hdr' },
  { id: 'rooitou_park_4k', name: 'rooitou park 4k', url: '/environment/hdri/rooitou_park_4k.hdr', type: 'hdr' },
  { id: 'rosendal_park_sunset_4k', name: 'rosendal park sunset 4k', url: '/environment/hdri/rosendal_park_sunset_4k.hdr', type: 'hdr' },
  { id: 'rosendal_plains_1_4k', name: 'rosendal plains 1 4k', url: '/environment/hdri/rosendal_plains_1_4k.hdr', type: 'hdr' },
  { id: 'rubinkowo_sandbox_overcast_4k', name: 'rubinkowo sandbox overcast 4K', url: '/environment/hdri/rubinkowo-sandbox-overcast_4K.hdr', type: 'hdr' },
  { id: 'sandflat_sunset', name: 'Sandflat Sunset', url: '/environment/hdri/Sandflat_Sunset.hdr', type: 'hdr' },
  { id: 'sandsloot_4k', name: 'sandsloot 4k', url: '/environment/hdri/sandsloot_4k.hdr', type: 'hdr' },
  { id: 'san_giuseppe_bridge_4k', name: 'san giuseppe bridge 4k', url: '/environment/hdri/san_giuseppe_bridge_4k.hdr', type: 'hdr' },
  { id: 'satara_night_4k', name: 'satara night 4k', url: '/environment/hdri/satara_night_4k.hdr', type: 'hdr' },
  { id: 'schadowplatz_4k', name: 'schadowplatz 4k', url: '/environment/hdri/schadowplatz_4k.hdr', type: 'hdr' },
  { id: 'scythian_tombs_2_4k', name: 'scythian tombs 2 4k', url: '/environment/hdri/scythian_tombs_2_4k.hdr', type: 'hdr' },
  { id: 'secluded_beach_4k', name: 'secluded beach 4k', url: '/environment/hdri/secluded_beach_4k.hdr', type: 'hdr' },
  { id: 'shanghai_bund_4k', name: 'shanghai bund 4k', url: '/environment/hdri/shanghai_bund_4k.hdr', type: 'hdr' },
  { id: 'shanghai_riverside_4k', name: 'shanghai riverside 4k', url: '/environment/hdri/shanghai_riverside_4k.hdr', type: 'hdr' },
  { id: 'simons_town_harbour_4k', name: 'simons town harbour 4k', url: '/environment/hdri/simons_town_harbour_4k.hdr', type: 'hdr' },
  { id: 'simons_town_road_4k', name: 'simons town road 4k', url: '/environment/hdri/simons_town_road_4k.hdr', type: 'hdr' },
  { id: 'simons_town_rocks_4k', name: 'simons town rocks 4k', url: '/environment/hdri/simons_town_rocks_4k.hdr', type: 'hdr' },
  { id: 'skarpa_winter_forest_4k', name: 'skarpa winter forest 4K', url: '/environment/hdri/skarpa-winter-forest_4K.hdr', type: 'hdr' },
  { id: 'skukuza_golf_4k', name: 'skukuza golf 4k', url: '/environment/hdri/skukuza_golf_4k.hdr', type: 'hdr' },
  { id: 'skylit_garage_4k', name: 'skylit garage 4k', url: '/environment/hdri/skylit_garage_4k.hdr', type: 'hdr' },
  { id: 'small_cave_4k', name: 'small cave 4k', url: '/environment/hdri/small_cave_4k.hdr', type: 'hdr' },
  { id: 'small_empty_room_1_4k', name: 'small empty room 1 4k', url: '/environment/hdri/small_empty_room_1_4k.hdr', type: 'hdr' },
  { id: 'small_harbor_01_4k', name: 'small harbor 01 4k', url: '/environment/hdri/small_harbor_01_4k.hdr', type: 'hdr' },
  { id: 'small_harbour_morning_4k', name: 'small harbour morning 4k', url: '/environment/hdri/small_harbour_morning_4k.hdr', type: 'hdr' },
  { id: 'small_harbour_sunset_4k', name: 'small harbour sunset 4k', url: '/environment/hdri/small_harbour_sunset_4k.hdr', type: 'hdr' },
  { id: 'small_rural_road_02_4k', name: 'small rural road 02 4k', url: '/environment/hdri/small_rural_road_02_4k.hdr', type: 'hdr' },
  { id: 'snow_field_2_4k', name: 'snow field 2 4k', url: '/environment/hdri/snow_field_2_4k.hdr', type: 'hdr' },
  { id: 'snowy_field_4k', name: 'snowy field 4k', url: '/environment/hdri/snowy_field_4k.hdr', type: 'hdr' },
  { id: 'snowy_forest_4k', name: 'snowy forest 4k', url: '/environment/hdri/snowy_forest_4k.hdr', type: 'hdr' },
  { id: 'solitude_night_4k', name: 'solitude night 4k', url: '/environment/hdri/solitude_night_4k.hdr', type: 'hdr' },
  { id: 'spaichingen_hill_4k', name: 'spaichingen hill 4k', url: '/environment/hdri/spaichingen_hill_4k.hdr', type: 'hdr' },
  { id: 'spiaggia_di_mondello_4k', name: 'spiaggia di mondello 4k', url: '/environment/hdri/spiaggia_di_mondello_4k.hdr', type: 'hdr' },
  { id: 'spree_bank_4k', name: 'spree bank 4k', url: '/environment/hdri/spree_bank_4k.hdr', type: 'hdr' },
  { id: 'spruit_sunrise_4k', name: 'spruit sunrise 4k', url: '/environment/hdri/spruit_sunrise_4k.hdr', type: 'hdr' },
  { id: 'stadium_01_4k', name: 'stadium 01 4k', url: '/environment/hdri/stadium_01_4k.hdr', type: 'hdr' },
  { id: 'st_fagans_interior_4k', name: 'st fagans interior 4k', url: '/environment/hdri/st_fagans_interior_4k.hdr', type: 'hdr' },
  { id: 'stierberg_sunrise_4k', name: 'stierberg sunrise 4k', url: '/environment/hdri/stierberg_sunrise_4k.hdr', type: 'hdr' },
  { id: 'st_peters_square_night_4k', name: 'st peters square night 4k', url: '/environment/hdri/st_peters_square_night_4k.hdr', type: 'hdr' },
  { id: 'studio_2nd_floor_cyclorama_4k', name: 'studio 2nd floor cyclorama 4K', url: '/environment/hdri/studio-2nd-floor-cyclorama_4K.hdr', type: 'hdr' },
  { id: 'subway_entrance_4k', name: 'subway entrance 4k', url: '/environment/hdri/subway_entrance_4k.hdr', type: 'hdr' },
  { id: 'sundowner_overlook_4k', name: 'sundowner overlook 4k', url: '/environment/hdri/sundowner_overlook_4k.hdr', type: 'hdr' },
  { id: 'sunflowers_4k', name: 'sunflowers 4k', url: '/environment/hdri/sunflowers_4k.hdr', type: 'hdr' },
  { id: 'sunlit_castle_fountain_4k', name: 'sunlit castle fountain 4K', url: '/environment/hdri/sunlit-castle-fountain_4K.hdr', type: 'hdr' },
  { id: 'sunny_industrial_yard_4k', name: 'sunny industrial yard 4K', url: '/environment/hdri/sunny-industrial-yard_4K.hdr', type: 'hdr' },
  { id: 'sunset_fairway_4k', name: 'sunset fairway 4k', url: '/environment/hdri/sunset_fairway_4k.hdr', type: 'hdr' },
  { id: 'sunset_in_the_chalk_quarry_4k', name: 'sunset in the chalk quarry 4k', url: '/environment/hdri/sunset_in_the_chalk_quarry_4k.hdr', type: 'hdr' },
  { id: 'surgery_4k', name: 'surgery 4k', url: '/environment/hdri/surgery_4k.hdr', type: 'hdr' },
  { id: 'symmetrical_garden_02_4k', name: 'symmetrical garden 02 4k', url: '/environment/hdri/symmetrical_garden_02_4k.hdr', type: 'hdr' },
  { id: 'symmetrical_garden_4k', name: 'symmetrical garden 4k', url: '/environment/hdri/symmetrical_garden_4k.hdr', type: 'hdr' },
  { id: 'tcom_colorfulalley_colorful_alley_8k_hdri_sphere_paris', name: 'TCom ColorfulAlley colorful alley 8K hdri sphere PARIS', url: '/environment/hdri/TCom_ColorfulAlley_colorful_alley_8K_hdri_sphere-PARIS.hdr', type: 'hdr' },
  { id: 'tcom_norwayforest_8k_hdri_sphere', name: 'TCom NorwayForest 8K hdri sphere', url: '/environment/hdri/TCom_NorwayForest_8K_hdri_sphere.hdr', type: 'hdr' },
  { id: 'teatro_massimo_4k', name: 'teatro massimo 4k', url: '/environment/hdri/teatro_massimo_4k.hdr', type: 'hdr' },
  { id: 'teufelsberg_lookout_4k', name: 'teufelsberg lookout 4k', url: '/environment/hdri/teufelsberg_lookout_4k.hdr', type: 'hdr' },
  { id: 'teufelsberg_roof_4k', name: 'teufelsberg roof 4k', url: '/environment/hdri/teufelsberg_roof_4k.hdr', type: 'hdr' },
  { id: 'the_sky_is_on_fire_4k', name: 'the sky is on fire 4k', url: '/environment/hdri/the_sky_is_on_fire_4k.hdr', type: 'hdr' },
  { id: 'tiber_1_4k', name: 'tiber 1 4k', url: '/environment/hdri/tiber_1_4k.hdr', type: 'hdr' },
  { id: 'tiber_2_4k', name: 'tiber 2 4k', url: '/environment/hdri/tiber_2_4k.hdr', type: 'hdr' },
  { id: 'tiber_island_4k', name: 'tiber island 4k', url: '/environment/hdri/tiber_island_4k.hdr', type: 'hdr' },
  { id: 'tree_lined_driveway_4k', name: 'tree lined driveway 4k', url: '/environment/hdri/tree_lined_driveway_4k.hdr', type: 'hdr' },
  { id: 'tropical_beachstairs_8k', name: 'Tropical BeachStairs 8k', url: '/environment/hdri/Tropical_BeachStairs_8k.hdr', type: 'hdr' },
  { id: 'tropical_cemetery_b', name: 'Tropical Cemetery B', url: '/environment/hdri/Tropical_Cemetery_B.hdr', type: 'hdr' },
  { id: 'tucker_wreck_4k', name: 'tucker wreck 4k', url: '/environment/hdri/tucker_wreck_4k.hdr', type: 'hdr' },
  { id: 'tv_studio_4k', name: 'tv studio 4k', url: '/environment/hdri/tv_studio_4k.hdr', type: 'hdr' },
  { id: 'ulmer_muenster_4k', name: 'ulmer muenster 4k', url: '/environment/hdri/ulmer_muenster_4k.hdr', type: 'hdr' },
  { id: 'umhlanga_sunrise_4k', name: 'umhlanga sunrise 4k', url: '/environment/hdri/umhlanga_sunrise_4k.hdr', type: 'hdr' },
  { id: 'under_bridge_4k', name: 'under bridge 4k', url: '/environment/hdri/under_bridge_4k.hdr', type: 'hdr' },
  { id: 'unfinished_office_4k', name: 'unfinished office 4k', url: '/environment/hdri/unfinished_office_4k.hdr', type: 'hdr' },
  { id: 'unfinished_office_night_4k', name: 'unfinished office night 4k', url: '/environment/hdri/unfinished_office_night_4k.hdr', type: 'hdr' },
  { id: 'ushaka_dolphin_stadium_4k', name: 'ushaka dolphin stadium 4k', url: '/environment/hdri/ushaka_dolphin_stadium_4k.hdr', type: 'hdr' },
  { id: 'valley_of_desolation_4k', name: 'valley of desolation 4k', url: '/environment/hdri/valley_of_desolation_4k.hdr', type: 'hdr' },
  { id: 'venetian_crossroads_4k', name: 'venetian crossroads 4k', url: '/environment/hdri/venetian_crossroads_4k.hdr', type: 'hdr' },
  { id: 'venice_dawn_1_4k', name: 'venice dawn 1 4k', url: '/environment/hdri/venice_dawn_1_4k.hdr', type: 'hdr' },
  { id: 'venice_sunrise_4k', name: 'venice sunrise 4k', url: '/environment/hdri/venice_sunrise_4k.hdr', type: 'hdr' },
  { id: 'venice_sunset_4k', name: 'venice sunset 4k', url: '/environment/hdri/venice_sunset_4k.hdr', type: 'hdr' },
  { id: 'viale_giuseppe_garibaldi_4k', name: 'viale giuseppe garibaldi 4k', url: '/environment/hdri/viale_giuseppe_garibaldi_4k.hdr', type: 'hdr' },
  { id: 'vignaioli_night_4k', name: 'vignaioli night 4k', url: '/environment/hdri/vignaioli_night_4k.hdr', type: 'hdr' },
  { id: 'waterkloof_farm_4k', name: 'waterkloof farm 4k', url: '/environment/hdri/waterkloof_farm_4k.hdr', type: 'hdr' },
  { id: 'whipple_creek_gazebo_4k', name: 'whipple creek gazebo 4k', url: '/environment/hdri/whipple_creek_gazebo_4k.hdr', type: 'hdr' },
  { id: 'white_cliff_top_4k', name: 'white cliff top 4k', url: '/environment/hdri/white_cliff_top_4k.hdr', type: 'hdr' },
  { id: 'winter_evening_4k', name: 'winter evening 4k', url: '/environment/hdri/winter_evening_4k.hdr', type: 'hdr' },
  { id: 'winter_lake_01_4k', name: 'winter lake 01 4k', url: '/environment/hdri/winter_lake_01_4k.hdr', type: 'hdr' },
  { id: 'winter_river_4k', name: 'winter river 4k', url: '/environment/hdri/winter_river_4k.hdr', type: 'hdr' },
  { id: 'wobbly_bridge_4k', name: 'wobbly bridge 4k', url: '/environment/hdri/wobbly_bridge_4k.hdr', type: 'hdr' },
  { id: 'wooden_lounge_4k', name: 'wooden lounge 4k', url: '/environment/hdri/wooden_lounge_4k.hdr', type: 'hdr' },
  { id: 'wooden_studio_07_4k', name: 'wooden studio 07 4k', url: '/environment/hdri/wooden_studio_07_4k.hdr', type: 'hdr' },
  { id: 'wooden_studio_11_4k', name: 'wooden studio 11 4k', url: '/environment/hdri/wooden_studio_11_4k.hdr', type: 'hdr' },
  { id: 'wrestling_gym_4k', name: 'wrestling gym 4k', url: '/environment/hdri/wrestling_gym_4k.hdr', type: 'hdr' },
  { id: 'xiequ_yuan_4k', name: 'xiequ yuan 4k', url: '/environment/hdri/xiequ_yuan_4k.hdr', type: 'hdr' },
  { id: 'zavelstein_4k', name: 'zavelstein 4k', url: '/environment/hdri/zavelstein_4k.hdr', type: 'hdr' },
  { id: 'zhengyang_gate_4k', name: 'zhengyang gate 4k', url: '/environment/hdri/zhengyang_gate_4k.hdr', type: 'hdr' },
  { id: 'zwinger_night_4k', name: 'zwinger night 4k', url: '/environment/hdri/zwinger_night_4k.hdr', type: 'hdr' },
];

export function getRandomHdriId(): string {
  const index = Math.floor(Math.random() * HDRI_LIST.length);
  return HDRI_LIST[index].id;
}

export function getHdriById(id: string): HdriItem {
  return HDRI_LIST.find(h => h.id === id) || HDRI_LIST[0];
}
