export const CC3_TO_MIXAMO: Record<string, string> = {
  'CC_Base_Waist': 'Spine',
  'CC_Base_Spine01': 'Spine1',
  'CC_Base_Spine02': 'Spine2',
  'CC_Base_NeckTwist01': 'Neck',
  'CC_Base_NeckTwist02': 'Neck',
  'CC_Base_Head': 'Head',
  'CC_Base_L_Clavicle': 'LeftShoulder',
  'CC_Base_L_Upperarm': 'LeftArm',
  'CC_Base_L_Forearm': 'LeftForeArm',
  'CC_Base_L_Hand': 'LeftHand',
  'CC_Base_R_Clavicle': 'RightShoulder',
  'CC_Base_R_Upperarm': 'RightArm',
  'CC_Base_R_Forearm': 'RightForeArm',
  'CC_Base_R_Hand': 'RightHand',
  'CC_Base_L_Thigh': 'LeftUpLeg',
  'CC_Base_L_Calf': 'LeftLeg',
  'CC_Base_L_Foot': 'LeftFoot',
  'CC_Base_L_ToeBase': 'LeftToeBase',
  'CC_Base_R_Thigh': 'RightUpLeg',
  'CC_Base_R_Calf': 'RightLeg',
  'CC_Base_R_Foot': 'RightFoot',
  'CC_Base_R_ToeBase': 'RightToeBase',
  'CC_Base_L_Thumb1': 'LeftHandThumb1',
  'CC_Base_L_Thumb2': 'LeftHandThumb2',
  'CC_Base_L_Thumb3': 'LeftHandThumb3',
  'CC_Base_L_Index1': 'LeftHandIndex1',
  'CC_Base_L_Index2': 'LeftHandIndex2',
  'CC_Base_L_Index3': 'LeftHandIndex3',
  'CC_Base_L_Mid1': 'LeftHandMiddle1',
  'CC_Base_L_Mid2': 'LeftHandMiddle2',
  'CC_Base_L_Mid3': 'LeftHandMiddle3',
  'CC_Base_L_Ring1': 'LeftHandRing1',
  'CC_Base_L_Ring2': 'LeftHandRing2',
  'CC_Base_L_Ring3': 'LeftHandRing3',
  'CC_Base_L_Pinky1': 'LeftHandPinky1',
  'CC_Base_L_Pinky2': 'LeftHandPinky2',
  'CC_Base_L_Pinky3': 'LeftHandPinky3',
  'CC_Base_R_Thumb1': 'RightHandThumb1',
  'CC_Base_R_Thumb2': 'RightHandThumb2',
  'CC_Base_R_Thumb3': 'RightHandThumb3',
  'CC_Base_R_Index1': 'RightHandIndex1',
  'CC_Base_R_Index2': 'RightHandIndex2',
  'CC_Base_R_Index3': 'RightHandIndex3',
  'CC_Base_R_Mid1': 'RightHandMiddle1',
  'CC_Base_R_Mid2': 'RightHandMiddle2',
  'CC_Base_R_Mid3': 'RightHandMiddle3',
  'CC_Base_R_Ring1': 'RightHandRing1',
  'CC_Base_R_Ring2': 'RightHandRing2',
  'CC_Base_R_Ring3': 'RightHandRing3',
  'CC_Base_R_Pinky1': 'RightHandPinky1',
  'CC_Base_R_Pinky2': 'RightHandPinky2',
  'CC_Base_R_Pinky3': 'RightHandPinky3'
};

export const BONE_SYNONYMS: Record<string, string[]> = {
  'Hips': ['hips', 'pelvis', 'cog', 'roothips', 'rootground', 'hip'],
  'Spine': ['spine01', 'spinelower', 'spine0', 'spine1', 'spine'],
  'Spine2': ['spine02', 'spineupper', 'spine2', 'spine03', 'spine', 'spine3'],
  'Neck': ['neck', 'headnecklower'],
  'Head': ['head', 'headneckupper'],
  'LeftShoulder': ['leftshoulder', 'shoulderl', 'claviclel', 'armleftshoulder', 'larmclavicle', 'shlderl', 'armleftshoulder1'],
  'LeftArm': ['armleftshoulder2', 'upperarml', 'larmhumerus', 'upperarm.l', 'upper_arm.l', 'leftarm', 'armleftelbow', 'arm.l', 'bicepl'],
  'LeftForeArm': ['lowerarml', 'larmradius', 'forearm.l', 'forearm_l', 'leftforearm', 'armleftelbow', 'armleftwrist', 'forarml', 'forearml'],
  'LeftHand': ['handl', 'larmwrist', 'hand.l', 'hand_l', 'wrist.l', 'wrist_l', 'lefthand', 'armleftwrist', 'palml'],
  'RightShoulder': ['rightshoulder', 'shoulderr', 'clavicler', 'armrightshoulder', 'rarmclavicle', 'shlderr', 'armrightshoulder1'],
  'RightArm': ['rightarm', 'armrightshoulder2', 'upperarmr', 'armrightelbow', 'rarmhumerus', 'upperarm.r', 'upper_arm.r', 'arm.r', 'bicepr'],
  'RightForeArm': ['lowerarmr', 'rarmradius', 'forearm.r', 'forearm_r', 'rightforearm', 'armrightelbow', 'armrightwrist', 'forarmr', 'forearmr'],
  'RightHand': ['handr', 'rarmwrist', 'hand.r', 'hand_r', 'wrist.r', 'wrist_r', 'righthand', 'armrightwrist', 'palmr'],
  'LeftUpLeg': ['legleftthigh', 'thighl', 'llegfemur', 'thigh.l', 'thigh_l', 'leftupleg'],
  'LeftLeg': ['legleftknee', 'calfl', 'shinl', 'llegtibia', 'shin.l', 'shin_l', 'calf.l', 'calf_l', 'leftleg'],
  'LeftFoot': ['legleftankle', 'footl', 'llegankle', 'foot.l', 'foot_l', 'ankle.l', 'ankle_l', 'leftfoot'],
  'LeftToeBase': ['leglefttoes', 'balll', 'toel', 'llegball', 'toe.l', 'toe_l', 'ball.l', 'ball_l', 'lefttoebase'],
  'RightUpLeg': ['legrightthigh', 'thighr', 'rlegfemur', 'thigh.r', 'thigh_r', 'rightupleg'],
  'RightLeg': ['legrightknee', 'calfr', 'shinr', 'rlegtibia', 'shin.r', 'shin_r', 'calf.r', 'calf_r', 'rightleg'],
  'RightFoot': ['legrightankle', 'footr', 'rlegankle', 'foot.r', 'foot_r', 'ankle.r', 'ankle_r', 'rightfoot'],
  'RightToeBase': ['legrighttoes', 'ballr', 'toer', 'rlegball', 'toe.r', 'toe_r', 'ball.r', 'ball_r', 'righttoebase']
};
