// =============================================
// INVENTORY DATA — port de js/ui/inventoryData.js
// dims: { w, d, h } en cm (w=X, d=Z, h=Y)
// =============================================

export type ConsumableFrequency = 'hebdo' | 'mensuel' | 'trimestriel' | 'annuel';

export interface InventoryItem {
  id: string;
  name: string;
  brand: string;
  category: string;
  qty: number;
  dims: { w: number; d: number; h: number };
  notes?: string;
  glbPath?: string;
  photos?: string[];
  url?: string;
  actions?: string[];
  // Consumable-specific
  frequency?: ConsumableFrequency;
  stock?: number;
  location?: string;
}

export interface StorageSpace {
  id: string;
  name: string;
  dims: { w: number; d: number; h: number };
  notes?: string;
  actions?: string[];
}

export interface Category {
  id: string;
  label: string;
}

export const INVENTORY: InventoryItem[] = [

  // ── STORAGE ──────────────────────────────────────────────────────────────────
  { id: 'kallax-2x1',       name: 'Kallax 2×1',                     brand: 'IKEA',     category: 'storage',   qty: 5,  dims: { w: 77, d: 39, h: 41 }, notes: 'NE (1), SE (2 pivotées), NW (1 pivotée), cuisine (1)', glbPath: 'media/glb/KALLAX etag 77x41 blanc.glb', photos: ['media/photos/ikea/kallax-2x1-1.jpg', 'media/photos/ikea/kallax-2x1-2.jpg', 'media/photos/ikea/kallax-2x1-3.jpg'] },
  { id: 'kallax-2x2',       name: 'Kallax 2×2',                     brand: 'IKEA',     category: 'storage',   qty: 3,  dims: { w: 77, d: 39, h: 77 }, notes: 'NE (1), cuisine (2)',                                 glbPath: 'media/glb/KALLAX etag 77x77 blanc.glb', photos: ['media/photos/ikea/kallax-2x2-1.jpg', 'media/photos/ikea/kallax-2x2-2.jpg', 'media/photos/ikea/kallax-2x2-3.jpg'] },
  { id: 'kallax-1x1',       name: 'Kallax 1×1',                     brand: 'IKEA',     category: 'storage',   qty: 2,  dims: { w: 42, d: 39, h: 41 }, notes: 'NW milieu + haut (pivotées)',                         glbPath: 'media/glb/KALLAX etag 42x41 blanc.glb', photos: ['media/photos/ikea/kallax-1x1-1.jpg', 'media/photos/ikea/kallax-1x1-2.jpg'] },
  { id: 'shelf-lack',        name: 'Étagère LACK',                  brand: 'IKEA',     category: 'storage',   qty: 1,  dims: { w: 110,  d: 26,   h: 5    }, notes: 'Murale, mur A', glbPath: 'media/glb/LACK étagère murale 110x26 blanc.glb', photos: ['media/photos/ikea/shelf-lack-1.jpg', 'media/photos/ikea/shelf-lack-2.jpg', 'media/photos/ikea/shelf-lack-3.jpg'] },
  { id: 'basket-fniss',      name: 'Corbeille FNISS',               brand: 'IKEA',     category: 'storage',   qty: 2,  dims: { w: 28,   d: 28,   h: 28   }, notes: '1 SDB, 1 séjour',             glbPath: 'media/glb/FNISS poubelle 10 l blanc.glb', photos: ['media/photos/ikea/basket-fniss-1.jpg', 'media/photos/ikea/basket-fniss-2.jpg', 'media/photos/ikea/basket-fniss-3.jpg'] },
  { id: 'dimpa',             name: 'Sac DIMPA',                     brand: 'IKEA',     category: 'storage',   qty: 5,  dims: { w: 68,   d: 27,   h: 67   }, notes: '5 sacs séjour mur C',          glbPath: 'media/glb/DIMPA.glb', photos: ['media/photos/ikea/dimpa-1.jpg', 'media/photos/ikea/dimpa-2.jpg', 'media/photos/ikea/dimpa-3.jpg'] },
  { id: 'rail-mulig',        name: 'Tringle MULIG',                 brand: 'IKEA',     category: 'storage',   qty: 1,  dims: { w: 60,   d: 26,   h: 16   }, notes: 'Blanc',                        glbPath: 'media/glb/MULIG.glb', photos: ['media/photos/ikea/rail-mulig-1.jpg', 'media/photos/ikea/rail-mulig-2.jpg', 'media/photos/ikea/rail-mulig-3.jpg'] },
  { id: 'meuble-t',          name: 'Bibliothèque (MeubleT)',         brand: '',         category: 'storage',   qty: 1,  dims: { w: 100,  d: 40,   h: 50   }, notes: 'Procédural, mur C' },
  { id: 'drona',             name: 'Boîte DRONA',                   brand: 'IKEA',     category: 'storage',   qty: 29, dims: { w: 33,   d: 38,   h: 33   }, notes: 'Dans les Kallax NE/SE/NW/cuisine, Mackapär, meubles SDB et cuisine', glbPath: 'media/glb/DRÖNA.glb', photos: ['media/photos/ikea/drona-1.jpg', 'media/photos/ikea/drona-2.jpg', 'media/photos/ikea/drona-3.jpg'] },

  // ── FURNITURE ────────────────────────────────────────────────────────────────
  { id: 'utaker-stack',     name: 'Utåker - Lit empilable (paire)', brand: 'IKEA',     category: 'furniture', qty: 1, dims: { w: 205,  d: 83,   h: 46   }, notes: 'Lit empilable IKEA vendu en pair (bas + haut), 2× matelas 200×80cm', actions: ['bed-toggle', 'bed-sofa'], photos: ['media/photos/ikea/utaker-stack-1.jpg', 'media/photos/ikea/utaker-stack-2.jpg', 'media/photos/ikea/utaker-stack-3.jpg'] },
  { id: 'utaker-lower',     name: 'Utåker - Lit bas',               brand: 'IKEA',     category: 'furniture', qty: 1, dims: { w: 205,  d: 83,   h: 23   }, notes: 'Empilable, vendu en pair avec lit haut, matelas 200×80cm bleu', glbPath: 'media/glb/UTÅKER lit empilable 80x200 pin (bas).glb', photos: ['media/photos/ikea/utaker-lower-1.jpg', 'media/photos/ikea/utaker-lower-2.jpg', 'media/photos/ikea/utaker-lower-3.jpg'] },
  { id: 'utaker-upper',     name: 'Utåker - Lit haut',              brand: 'IKEA',     category: 'furniture', qty: 1, dims: { w: 205,  d: 83,   h: 23   }, notes: 'Empilable, vendu en pair avec lit bas, matelas 200×80cm blanc', glbPath: 'media/glb/UTÅKER lit empilable 80x200 pin (haut).glb', photos: ['media/photos/ikea/utaker-upper-1.jpg', 'media/photos/ikea/utaker-upper-2.jpg', 'media/photos/ikea/utaker-upper-3.jpg'] },
  { id: 'desk-bollsidan',   name: 'Bollsidan - Bureau assis-debout', brand: 'IKEA',     category: 'furniture', qty: 2, dims: { w: 68,   d: 36,   h: 70   }, notes: 'Surface 68×36cm ; bureau 2 : laptop + téléphone + mug', actions: ['desk1-toggle', 'desk1-position'], photos: ['media/photos/ikea/desk-bollsidan-1.jpg', 'media/photos/ikea/desk-bollsidan-2.jpg', 'media/photos/ikea/desk-bollsidan-3.jpg'] },
  { id: 'smorkull-chair',   name: 'Chaise de bureau Smörkull',      brand: 'IKEA',     category: 'furniture', qty: 1, dims: { w: 66,   d: 65,   h: 108  }, notes: 'Chaise de bureau av accoudoirs, Gräsnäs rouge', glbPath: 'media/glb/SMÖRKULL.glb', url: 'https://www.ikea.com/fr/fr/p/smoerkull-chaise-de-bureau-av-accoudoirs-graesnaes-rouge-60503437/', photos: ['media/photos/ikea/smorkull-chair-1.jpg', 'media/photos/ikea/smorkull-chair-2.jpg', 'media/photos/ikea/smorkull-chair-3.jpg', 'media/photos/ikea/smorkull-chair-4.jpg', 'media/photos/ikea/smorkull-chair-5.jpg', 'media/photos/ikea/smorkull-chair-6.jpg', 'media/photos/ikea/smorkull-chair-7.jpg', 'media/photos/ikea/smorkull-chair-8.jpg', 'media/photos/ikea/smorkull-chair-9.jpg', 'media/photos/ikea/smorkull-chair-10.jpg', 'media/photos/ikea/smorkull-chair-11.jpg'] },
  { id: 'sunnersta',        name: 'Desserte SUNNERSTA',             brand: 'IKEA',     category: 'furniture', qty: 1, dims: { w: 36,   d: 56,   h: 90   }, notes: 'Roulante, têtes de mannequin dessus', glbPath: 'media/glb/sunnersta_trolley_ikea.glb', photos: ['media/photos/ikea/sunnersta-1.jpg', 'media/photos/ikea/sunnersta-2.jpg', 'media/photos/ikea/sunnersta-3.jpg'] },
  { id: 'chest-bench',      name: 'Coffre banc YITAHOME 100 Gal',  brand: 'YITAHOME', category: 'furniture', qty: 1, dims: { w: 122,  d: 55,   h: 62   }, notes: 'Gris, jardin derrière canapé ouest' },
  { id: 'viggja',           name: 'Desserte VIGGJA',                brand: 'IKEA',     category: 'furniture', qty: 1, dims: { w: 37,   d: 50,   h: 74   }, notes: 'Jardin, à côté canapé ouest', glbPath: 'media/glb/viggja.glb', photos: ['media/photos/ikea/viggja-1.jpg', 'media/photos/ikea/viggja-2.jpg', 'media/photos/ikea/viggja-3.jpg'] },
  { id: 'armrest-sofa',     name: 'Canapé de jardin (grand)',       brand: 'Tectake',  category: 'furniture', qty: 1, dims: { w: 61,   d: 157,  h: 89   }, notes: 'Tectake Sintra - Canapé de jardin modulable transformable en lit de jour / transat, résine tressée grise', actions: ['sofa-arm-left', 'sofa-arm-right'], url: 'https://www.amazon.fr/gp/product/B0FFHJ2TVP', photos: ['media/photos/sofa/armrest-sofa-gris-1.jpg', 'media/photos/sofa/armrest-sofa-gris-2.jpg', 'media/photos/sofa/armrest-sofa-gris-3.jpg', 'media/photos/sofa/armrest-sofa-gris-4.jpg', 'media/photos/sofa/armrest-sofa-gris-5.jpg', 'media/photos/sofa/armrest-sofa-gris-6.jpg', 'media/photos/sofa/armrest-sofa-gris-7.jpg', 'media/photos/sofa/armrest-sofa-gris-8.jpg'] },
  { id: 'armless-sofa',     name: 'Canapé de jardin (petit)',       brand: '',         category: 'furniture', qty: 1, dims: { w: 60,   d: 100,  h: 100  }, notes: 'Rouge, sans accoudoirs' },
  { id: 'tent-quechua-2sec', name: 'Tente Quechua 2 Seconds Easy 2P', brand: 'Quechua', category: 'furniture', qty: 1, dims: { w: 140,  d: 200,  h: 100  }, notes: 'Pop-up dôme 2 places, version compacte verte (réf 8784754) — procédural' },
  { id: 'vihals-chair',     name: 'Chaise pliante VIHALS',          brand: 'IKEA',    category: 'furniture', qty: 1, dims: { w: 43,   d: 47,   h: 80   }, notes: 'Rouge, pliable (réf 70592744). Action plier/déplier avec animation hinge.', glbPath: 'media/glb/vihals.glb', actions: ['vihals-toggle'], photos: ['media/photos/ikea/vihals-chair-1.jpg', 'media/photos/ikea/vihals-chair-2.jpg', 'media/photos/ikea/vihals-chair-3.jpg'] },

  // ── TECH ─────────────────────────────────────────────────────────────────────
  { id: 'tv',               name: 'Télévision CHiQ L32H7A',         brand: 'CHiQ',      category: 'tech',     qty: 1, dims: { w: 73,   d: 8,    h: 45   }, notes: '32" (80cm diag) — Android 9 Smart TV, HD, WiFi, BT, Google Assistant, Netflix, Prime Video, 2×HDMI, USB — Classe F — murale, orientée séjour', actions: ['tv-toggle'], photos: ['media/photos/chiq-l32h7a-1.jpg'] },
  { id: 'mini-pc',          name: 'Mini PC MLLSE G2 Pro',            brand: 'MLLSE',     category: 'tech',     qty: 1, dims: { w: 8.7,  d: 8.7,  h: 3.9  }, notes: 'Intel Twin Lake N150, LPDDR5 12 Go, 512 Go SSD, Wi-Fi 5, BT 5.0 — bleu nuit, bouton rouge', photos: ['media/photos/mllse-g2-pro-1.jpg', 'media/photos/mllse-g2-pro-2.jpg', 'media/photos/mllse-g2-pro-3.jpg', 'media/photos/mllse-g2-pro-4.jpg', 'media/photos/mllse-g2-pro-5.jpg', 'media/photos/mllse-g2-pro-6.jpg'] },
  { id: 'laptop',           name: 'Framework Laptop 13"',           brand: 'Framework', category: 'tech',     qty: 1, dims: { w: 29.7, d: 22.8, h: 1.55 }, notes: 'AMD Ryzen AI 5 340, 2256×1504 13", bureau 2', photos: ['media/photos/framework-laptop13-1.jpg', 'media/photos/framework-laptop13-2.jpg', 'media/photos/framework-laptop13-3.jpg', 'media/photos/framework-laptop13-4.jpg', 'media/photos/framework-laptop13-5.jpg', 'media/photos/framework-laptop13-6.jpg'] },
  { id: 'phone',            name: 'Téléphone OnePlus Nord 4',       brand: 'OnePlus',   category: 'tech',     qty: 1, dims: { w: 7.5,  d: 16.2, h: 0.8  }, notes: 'Coque rouge, bureau 2', photos: ['media/photos/oneplus-nord4-2.jpg', 'media/photos/oneplus-nord4-3.jpg', 'media/photos/oneplus-nord4-4.jpg', 'media/photos/oneplus-nord4-5.jpg'] },
  { id: 'scooter',          name: 'Trottinette Xiaomi 4',           brand: 'Xiaomi',    category: 'tech',     qty: 1, dims: { w: 56.5, d: 119.2, h: 127.1 }, notes: 'Guidon déplié, couloir — Acheté le 08/07/2025 — Darty', glbPath: 'media/glb/xiaomi_electric_scooter_4.glb', photos: ['media/photos/xiaomi-scooter4-1.jpg'] },
  { id: 'air-performer',    name: 'Air Performer AMF870/15',        brand: 'Philips',   category: 'tech',     qty: 1, dims: { w: 32.5, d: 32.5, h: 106.4 }, notes: 'Purificateur/ventilateur bladeless, 70 m², Wi-Fi', photos: ['media/photos/philips-amf870-1.avif', 'media/photos/philips-amf870-2.avif', 'media/photos/philips-amf870-3.avif', 'media/photos/philips-amf870-4.avif', 'media/photos/philips-amf870-5.avif', 'media/photos/philips-amf870-6.avif'] },
  { id: 'vacuum-cleaner',   name: 'Aspirateur balai X-Force Flex RH2079WO', brand: 'Rowenta', category: 'tech', qty: 1, dims: { w: 24.8, d: 23.4, h: 112 }, notes: 'Sans fil 18V, 100 AW, 30 min autonomie, rouge | Acheté le 14/02/2026 — garantie 2 ans (jusqu\'au 14/02/2028)', glbPath: 'media/glb/toon_-_vacuum_cleaner.glb', photos: ['media/photos/rowenta-rh2079wo-1.jpg', 'media/photos/rowenta-rh2079wo-2.jpg', 'media/photos/rowenta-rh2079wo-3.jpg', 'media/photos/rowenta-rh2079wo-4.jpg'] },
  { id: 'sony-srs-xb33',    name: 'Enceinte Sony SRS-XB33',         brand: 'Sony',      category: 'tech',     qty: 1, dims: { w: 24.6, d: 10.6, h: 9.7  }, notes: 'EXTRA BASS Bluetooth, IPX5, 24h autonomie, rouge Fusion — jardin/couloir', glbPath: 'media/glb/jbl_charge_3_speaker.glb', photos: ['media/photos/sony-srs-xb33-1.jpg', 'media/photos/sony-srs-xb33-2.jpg', 'media/photos/sony-srs-xb33-3.jpg', 'media/photos/sony-srs-xb33-4.jpg', 'media/photos/sony-srs-xb33-5.jpg'] },
  { id: 'tyco-rebound',     name: 'Tyco R/C Rebound 4×4 Jet Turbo', brand: 'Tyco',      category: 'tech',     qty: 1, dims: { w: 20,   d: 25,   h: 14   }, notes: 'Voiture RC monster truck 6.0V — drive on 2 sides (sports car / pickup), 9 fonctions radio. Procédural. Souvenir d\'enfance, premier objet électronique démonté pour analyse.', url: 'https://tycocollectors.com/models/1994-tyco-rebound-4x4-european/', photos: ['media/photos/tyco/tyco-rebound-1.png', 'media/photos/tyco/tyco-rebound-2.png', 'media/photos/tyco/tyco-rebound-3.png', 'media/photos/tyco/tyco-rebound-4.png'] },
  { id: 'matter-hub',       name: 'Hub Matter',                     brand: '',          category: 'tech',     qty: 1, dims: { w: 9,    d: 9,    h: 2.2  }, notes: 'Passerelle domotique Matter — 90×90×22 mm, blanc mat, RESET + USB Type-C + RJ45 LAN. Procédural.', photos: ['media/photos/matter/matter-hub-1.png'] },

  // ── KITCHEN ──────────────────────────────────────────────────────────────────
  { id: 'counter',          name: 'Plan de travail',                brand: '',         category: 'kitchen',   qty: 1, dims: { w: 100,  d: 60,   h: 3    }, notes: 'Blanc, avec trou évier' },
  { id: 'cabinet-wood',     name: 'METOD 40×60×80 + RINGHULT + KALLROR', brand: 'IKEA', category: 'kitchen', qty: 1, dims: { w: 40, d: 60, h: 80 }, notes: 'Blanc + porte gris brillant + poignée inox 213mm, meuble sous évier', glbPath: 'media/glb/METOD Rangement blanc 40x60x80 cm.glb', actions: ['cabinet-toggle'], photos: ['media/photos/ikea/cabinet-wood-1.jpg'] },
  { id: 'ringhult-door',    name: 'RINGHULT Porte 40×80 gris brillant', brand: 'IKEA',  category: 'kitchen',   qty: 1, dims: { w: 40,   d: 2,    h: 80   }, notes: 'Porte placard cuisine sous évier', glbPath: 'media/glb/RINGHULT Porte brillant gris clair 40x80 cm.glb', photos: ['media/photos/ikea/ringhult-door-1.jpg', 'media/photos/ikea/ringhult-door-2.jpg', 'media/photos/ikea/ringhult-door-3.jpg'] },
  { id: 'kallror',          name: 'KALLROR Poignée inox 213 mm',    brand: 'IKEA',     category: 'kitchen',   qty: 3, dims: { w: 21.3, d: 3.5,  h: 3.5  }, notes: 'Acier inoxydable, meubles cuisine + SDB (×3)', glbPath: 'media/glb/KALLROR Poignée acier inoxydable 213 mm.glb', photos: ['media/photos/ikea/kallror-1.jpg', 'media/photos/ikea/kallror-2.jpg', 'media/photos/ikea/kallror-3.jpg'] },
  { id: 'fridge',           name: 'LAGAN Réfrigérateur 113 l',      brand: 'IKEA',     category: 'kitchen',   qty: 1, dims: { w: 60,   d: 63,   h: 172  }, notes: 'Blanc, comp. congélateur', glbPath: 'media/glb/LAGAN Réfrigérateur av comp congélateur indépendant-blanc 97-16 l.glb', actions: ['fridge-toggle'], photos: ['media/photos/ikea/fridge-1.jpg', 'media/photos/ikea/fridge-2.jpg', 'media/photos/ikea/fridge-3.jpg'] },
  { id: 'sink-boholmen',    name: 'Évier BOHOLMEN 1 bac',          brand: 'IKEA',     category: 'kitchen',   qty: 1, dims: { w: 30,   d: 47,   h: 15   }, notes: 'Inox, avec robinet', photos: ['media/photos/ikea/sink-boholmen-1.jpg', 'media/photos/ikea/sink-boholmen-2.jpg', 'media/photos/ikea/sink-boholmen-3.jpg'] },
  { id: 'stove',            name: 'Plaque VÄLBILDAD',               brand: 'IKEA',     category: 'kitchen',   qty: 1, dims: { w: 29,   d: 52,   h: 5    }, notes: 'Induction', glbPath: 'media/glb/VÄLBILDAD.glb', photos: ['media/photos/ikea/stove-1.jpg', 'media/photos/ikea/stove-2.jpg', 'media/photos/ikea/stove-3.jpg'] },
  { id: 'ninja-sp101',      name: 'Mini four Foodi Flip SP101EU',   brand: 'Ninja',    category: 'kitchen',   qty: 1, dims: { w: 51,   d: 37,   h: 19.5 }, notes: '8-en-1, inox brossé, porte vitrée + flip-back', actions: ['ninja-toggle'] },
  { id: 'moules-airfryer',  name: 'Moules jetables papier air fryer ×120', brand: 'Kitchen Cook', category: 'kitchen', qty: 120, dims: { w: 20, d: 20, h: 15 }, notes: 'Papier cuisson pour air fryer | Acheté le 14/02/2026' },
  { id: 'freezer',          name: 'Congélateur CHIQ CSD46D4E',     brand: 'CHIQ',     category: 'kitchen',   qty: 1, dims: { w: 45,   d: 47,   h: 50   }, notes: 'Noir, niche séjour', glbPath: 'media/glb/TILLREDA Réfrigérateur indépendant-blanc 43 l.glb', actions: ['freezer-toggle'] },

  // Vaisselle / couverts
  { id: 'fourchette',       name: 'Fourchette',                     brand: '',         category: 'kitchen',   qty: 6,  dims: { w: 2.5,  d: 20,   h: 1.2  }, notes: 'Tiroir cuisine' },
  { id: 'couteau',          name: 'Couteau de table',               brand: '',         category: 'kitchen',   qty: 6,  dims: { w: 1.8,  d: 23,   h: 1.2  }, notes: 'Tiroir cuisine' },
  { id: 'grande-cuillere',  name: 'Grande cuillère',                brand: '',         category: 'kitchen',   qty: 6,  dims: { w: 3.5,  d: 20,   h: 1.5  }, notes: 'Tiroir cuisine — cuillère à soupe' },
  { id: 'petite-cuillere',  name: 'Petite cuillère',                brand: '',         category: 'kitchen',   qty: 6,  dims: { w: 2.5,  d: 13,   h: 1.0  }, notes: 'Tiroir cuisine — cuillère à café' },
  { id: 'assiette',         name: 'Assiette',                       brand: '',         category: 'kitchen',   qty: 6,  dims: { w: 26,   d: 26,   h: 2    }, notes: 'Placard cuisine — plate plate Ø 26 cm' },
  { id: 'mug-set',          name: 'Mug',                            brand: '',         category: 'kitchen',   qty: 6,  dims: { w: 9,    d: 12,   h: 9.5  }, notes: 'Placard cuisine — anse incluse' },
  { id: 'trash-bin',        name: 'Poubelle TATAY Smart Deco 25L',  brand: 'TATAY',    category: 'kitchen',   qty: 1,  dims: { w: 26,   d: 36,   h: 47   }, notes: 'Effet bois, pédale, B0BJQS1P6C', actions: ['bin-toggle'] },

  // ── BATHROOM ─────────────────────────────────────────────────────────────────
  { id: 'vathult-350',           name: 'VÅTHULT éclairage LED miroir 350 mm alu', brand: 'IKEA', category: 'bathroom', qty: 1, dims: { w: 35, d: 4, h: 4 }, notes: 'Au-dessus miroir vasque SDB', glbPath: 'media/glb/VÅTHULT éclairage LED élément-miroir 350 mm alu.glb', photos: ['media/photos/ikea/vathult-350-1.jpg', 'media/photos/ikea/vathult-350-2.jpg', 'media/photos/ikea/vathult-350-3.jpg'] },
  { id: 'bathroom-cabinet-west', name: 'METOD 40×37×60 + RINGHULT + KALLROR (ouest)', brand: 'IKEA', category: 'bathroom', qty: 1, dims: { w: 40, d: 37, h: 60 }, notes: 'Blanc + porte gris brillant + poignée inox 213mm', glbPath: 'media/glb/METOD Rangement mural blanc 40x37x60 cm.glb', actions: ['cbn-west-toggle'], photos: ['media/photos/ikea/bathroom-cabinet-west-1.jpg'] },
  { id: 'bathroom-cabinet-east', name: 'METOD 40×37×60 + RINGHULT + KALLROR (est)',  brand: 'IKEA', category: 'bathroom', qty: 1, dims: { w: 40, d: 37, h: 60 }, notes: 'Blanc + porte gris brillant + poignée inox 213mm', glbPath: 'media/glb/METOD Rangement mural blanc 40x37x60 cm.glb', actions: ['cbn-east-toggle'], photos: ['media/photos/ikea/bathroom-cabinet-east-1.jpg'] },
  { id: 'ringhult-door-sdb',    name: 'RINGHULT Porte 40×60 gris brillant', brand: 'IKEA', category: 'bathroom', qty: 2, dims: { w: 40, d: 2, h: 60 }, notes: 'Porte meubles SDB ouest et est', glbPath: 'media/glb/RINGHULT Porte brillant gris clair 40x60 cm.glb', photos: ['media/photos/ikea/ringhult-door-sdb-1.jpg', 'media/photos/ikea/ringhult-door-sdb-2.jpg', 'media/photos/ikea/ringhult-door-sdb-3.jpg'] },
  { id: 'tisken-panier',        name: 'TISKEN Panier ventouse blanc',       brand: 'IKEA', category: 'bathroom', qty: 2, dims: { w: 22, d: 10, h: 12 }, notes: 'Sur miroir vasque SDB, mi-hauteur, bord gauche et droit', glbPath: 'media/glb/TISKEN Panier à ventouse blanc.glb', photos: ['media/photos/ikea/tisken-panier-1.jpg', 'media/photos/ikea/tisken-panier-2.jpg', 'media/photos/ikea/tisken-panier-3.jpg'] },
  { id: 'shower',           name: 'Receveur de douche 90×90',       brand: '',         category: 'bathroom',  qty: 1, dims: { w: 90,   d: 90,   h: 15   }, notes: 'Shower tray + VALLAMOSSE barre douchette + mitigeur thermostatique', glbPath: 'media/glb/Shower tray 90x90cm.glb' },
  { id: 'toilet',           name: 'WC President Horizontal Outlet', brand: '',         category: 'bathroom',  qty: 1, dims: { w: 40,   d: 70,   h: 80   }, notes: 'Sortie horizontale', glbPath: 'media/glb/president_toilet_horizontal_outlet.glb', actions: ['wc-lid-toggle'] },
  { id: 'vasque-sdb',       name: 'HAVBÄCK-ORRSJÖN 62×49×69 cm',   brand: 'IKEA',     category: 'bathroom',  qty: 1, dims: { w: 62,   d: 49,   h: 69   }, notes: 'Meuble avec tiroirs, vasque, mitigeur blanc', glbPath: 'media/glb/HAVBÄCK - ORRSJÖN Meuble avec tiroirs-vasque-mitigeur blanc 62x49x69 cm.glb', photos: ['media/photos/ikea/vasque-sdb-1.jpg', 'media/photos/ikea/vasque-sdb-2.jpg', 'media/photos/ikea/vasque-sdb-3.jpg'] },
  { id: 'water-heater',     name: 'Ballon eau chaude 100L',         brand: '',         category: 'bathroom',  qty: 1, dims: { w: 40,   d: 40,   h: 80   }, notes: 'Cylindrique, vertical' },
  { id: 'oral-b-toothbrush',      name: 'Brosse à dents électrique Oral-B', brand: 'Oral-B', category: 'bathroom', qty: 2, dims: { w: 2.5, d: 3.6, h: 21.6 }, notes: 'Brosse rechargeable avec socle chargeur, SDB vasque', glbPath: 'media/glb/oral-b-vitality-red.glb' },
  { id: 'oral-b-toothbrush-head', name: 'Tête de brosse à dents Oral-B',    brand: 'Oral-B', category: 'bathroom', qty: 6, dims: { w: 1.6, d: 2.1, h: 7.2 }, notes: 'Recharge brosse électrique', glbPath: 'media/glb/oral-b_toothbrush_head.glb' },
  { id: 'philips-mg9558',   name: 'Tondeuse Philips MG9558/15 Series 9000', brand: 'Philips', category: 'bathroom', qty: 1, dims: { w: 4.5, d: 4.5, h: 22 }, notes: 'Multi-groomer 13 accessoires — barbe, corps, visage — IPX7, 120 min autonomie, 1h charge — SDB vasque' },
  { id: 'bathtub',          name: 'Baignoire',                      brand: '',         category: 'bathroom',  qty: 1, dims: { w: 150,  d: 70,   h: 50   }, notes: 'Coins arrondis, jardin' },

  // ── CLOTHING ─────────────────────────────────────────────────────────────────
  { id: 'mackapar',         name: 'Portant MACKAPÄR',               brand: 'IKEA',     category: 'clothing',  qty: 1, dims: { w: 77,  d: 32,  h: 200 }, notes: 'Avec 2 vêtements + casquette', glbPath: 'media/glb/mackapar_ikea.glb', photos: ['media/photos/ikea/mackapar-1.jpg', 'media/photos/ikea/mackapar-2.jpg', 'media/photos/ikea/mackapar-3.jpg'] },
  { id: 'salopette',        name: 'Salopette noire',                brand: '',         category: 'clothing',  qty: 1, dims: { w: 6,   d: 40,  h: 150 }, notes: 'Noire, suspendue', glbPath: 'media/glb/salopette-noir.glb' },
  { id: 'baseball-cap',     name: 'Casquette baseball',             brand: '',         category: 'clothing',  qty: 3, dims: { w: 25,  d: 20,  h: 15  }, notes: '3 casquettes rouges sur portant', glbPath: 'media/glb/baseball_cap.glb' },
  { id: 'backpack',         name: 'Sac à dos',                      brand: '',         category: 'clothing',  qty: 1, dims: { w: 40,  d: 17,  h: 43  }, notes: 'Rouge procédural, mur A' },
  { id: 'sneaker',          name: 'Sneakers',                       brand: '',         category: 'clothing',  qty: 2, dims: { w: 30,  d: 12,  h: 12  }, notes: 'Paire, mur A niche', glbPath: 'media/glb/sneaker.glb' },
  { id: 'jordan-hex-mule', name: 'Jordan Hex Mule SP',             brand: 'Nike/Jordan', category: 'clothing', qty: 2, dims: { w: 20.4, d: 28.5, h: 4.8 }, notes: 'Paire, University Red, taille 44.5, FJ0603-600' },
  { id: 'tshirt-noir-L',   name: 'T-shirt noir (pack ×6) taille L', brand: 'Temu',       category: 'clothing', qty: 6, dims: { w: 30, d: 20, h: 12 }, notes: 'Pack 6 t-shirts noirs, L — goods_id 601100392589571', photos: ['media/photos/temu/tshirt-noir-1.jpg', 'media/photos/temu/tshirt-noir-2.jpg', 'media/photos/temu/tshirt-noir-3.jpg', 'media/photos/temu/tshirt-noir-4.jpg', 'media/photos/temu/tshirt-noir-5.jpg', 'media/photos/temu/tshirt-noir-6.jpg', 'media/photos/temu/tshirt-noir-7.jpg', 'media/photos/temu/tshirt-noir-8.jpg', 'media/photos/temu/tshirt-noir-9.jpg', 'media/photos/temu/tshirt-noir-10.jpg', 'media/photos/temu/tshirt-noir-11.jpg', 'media/photos/temu/tshirt-noir-12.jpg', 'media/photos/temu/tshirt-noir-13.jpg'] },
  { id: 'tshirt-noir-XL',  name: 'T-shirt noir (pack ×6) taille XL', brand: 'Temu',      category: 'clothing', qty: 6, dims: { w: 30, d: 20, h: 12 }, notes: 'Pack 6 t-shirts noirs, XL — goods_id 601100392589571', photos: ['media/photos/temu/tshirt-noir-1.jpg', 'media/photos/temu/tshirt-noir-2.jpg', 'media/photos/temu/tshirt-noir-3.jpg', 'media/photos/temu/tshirt-noir-4.jpg', 'media/photos/temu/tshirt-noir-5.jpg', 'media/photos/temu/tshirt-noir-6.jpg', 'media/photos/temu/tshirt-noir-7.jpg', 'media/photos/temu/tshirt-noir-8.jpg', 'media/photos/temu/tshirt-noir-9.jpg', 'media/photos/temu/tshirt-noir-10.jpg', 'media/photos/temu/tshirt-noir-11.jpg', 'media/photos/temu/tshirt-noir-12.jpg', 'media/photos/temu/tshirt-noir-13.jpg'] },
  { id: 'calecon-rouge',   name: 'Caleçon rouge',                   brand: '',            category: 'clothing', qty: 20, dims: { w: 20, d: 15, h: 2  }, notes: '20 caleçons rouges' },
  { id: 'chaussette-rouge', name: 'Chaussettes fines rouges',       brand: '',            category: 'clothing', qty: 10, dims: { w: 10, d: 8,  h: 2  }, notes: '10 paires, chaussettes fines' },

  // ── DECOR ─────────────────────────────────────────────────────────────────────
  { id: 'lillhavet',        name: 'LILLHAVET',                      brand: 'IKEA',     category: 'decor',     qty: 1, dims: { w: 22,   d: 14,   h: 28   }, notes: 'Meuble haut cuisine, droite', glbPath: 'media/glb/LILLHAVET.glb', photos: ['media/photos/ikea/lillhavet-1.jpg', 'media/photos/ikea/lillhavet-2.jpg', 'media/photos/ikea/lillhavet-3.jpg'] },
  { id: 'mirror-nissedal-a',name: 'Miroir Nissedal 40×150 (mur A)', brand: 'IKEA',     category: 'decor',     qty: 4, dims: { w: 40,  d: 5,   h: 150 }, notes: 'Mur A, Reflector', glbPath: 'media/glb/NISSEDAL miroir 40x150 noir.glb', photos: ['media/photos/ikea/mirror-nissedal-a-1.jpg', 'media/photos/ikea/mirror-nissedal-a-2.jpg', 'media/photos/ikea/mirror-nissedal-a-3.jpg'] },
  { id: 'mirror-nissedal-d',name: 'Miroir Nissedal 65×65 (mur D)',  brand: 'IKEA',     category: 'decor',     qty: 3, dims: { w: 65,  d: 5,   h: 65  }, notes: 'Mur D, Reflector',  glbPath: 'media/glb/NISSEDAL miroir 65x65 noir.glb', photos: ['media/photos/ikea/mirror-nissedal-d-1.jpg', 'media/photos/ikea/mirror-nissedal-d-2.jpg', 'media/photos/ikea/mirror-nissedal-d-3.jpg'] },
  { id: 'mug',              name: 'Mug rouge',                      brand: '',         category: 'decor',     qty: 1, dims: { w: 8,   d: 8,   h: 9.5 }, notes: 'Bureau 2' },
  { id: 'mannequin-head',   name: 'Tête de mannequin',              brand: '',         category: 'decor',     qty: 3, dims: { w: 41,  d: 22,  h: 45  }, notes: '1 Sunnersta, 1 Kallax NW, 1 LACK' },
  { id: 'lamp-ola',         name: 'Lampe OLA',                      brand: 'IKEA',     category: 'decor',     qty: 1, dims: { w: 30,  d: 30,  h: 120 }, notes: 'Sur pied, meuble TV', glbPath: 'media/glb/ikea_lamp_ola.glb', photos: ['media/photos/ikea/lamp-ola-1.jpg', 'media/photos/ikea/lamp-ola-2.jpg', 'media/photos/ikea/lamp-ola-3.jpg'] },
  { id: 'altappen-rug',     name: 'Dalle terrasse ALTAPPEN',        brand: 'IKEA',     category: 'decor',     qty: 40, dims: { w: 30,  d: 30,  h: 0.6 }, notes: 'Jardin, dalles assemblées', photos: ['media/photos/ikea/altappen-rug-1.jpg', 'media/photos/ikea/altappen-rug-2.jpg', 'media/photos/ikea/altappen-rug-3.jpg'] },
  { id: 'potted-palm',      name: 'Palmier en pot',                 brand: '',         category: 'decor',     qty: 1, dims: { w: 60,  d: 60,  h: 150 }, notes: 'Jardin, entre canapé et desserte', glbPath: 'media/glb/potted_palm.glb' },
  { id: 'palm-leaf',        name: 'Feuille de palmier artificielle', brand: '',        category: 'decor',     qty: 1, dims: { w: 40,  d: 40,  h: 80  }, notes: 'Plante artificielle Palm_Leaf1', glbPath: 'media/glb/Palm_Leaf1.glb' },
  { id: 'jogging-suit',     name: 'Jogging suit',                   brand: '',         category: 'clothing',  qty: 1, dims: { w: 40,  d: 20,  h: 170 }, notes: 'Jardin, près de la baignoire', glbPath: 'media/glb/realistic_human_cloths.glb' },

  // ── CONSOMABLES ───────────────────────────────────────────────────────────────
  // Produits du quotidien rachetés régulièrement (1×/an minimum)
  { id: 'cons-papier-toilette', name: 'Papier toilette (pack 12)',  brand: '',         category: 'consumable', qty: 1, dims: { w: 40, d: 20, h: 22 }, frequency: 'mensuel',    stock: 8,  location: 'Placard SDB',     notes: 'Pack de 12 rouleaux' },
  { id: 'cons-sopalin',         name: 'Sopalin (pack 4)',           brand: '',         category: 'consumable', qty: 1, dims: { w: 40, d: 22, h: 25 }, frequency: 'mensuel',    stock: 3,  location: 'Placard cuisine', notes: 'Essuie-tout pack 4 rouleaux' },
  { id: 'cons-mouchoirs',       name: 'Mouchoirs (étui 10)',        brand: '',         category: 'consumable', qty: 1, dims: { w: 22, d: 12, h: 8  }, frequency: 'mensuel',    stock: 5,  location: 'Placard SDB',     notes: 'Étui 10 paquets' },
  { id: 'cons-dentifrice',      name: 'Dentifrice 75 ml',           brand: 'Signal',   category: 'consumable', qty: 1, dims: { w: 18, d: 5,  h: 4  }, frequency: 'mensuel',    stock: 2,  location: 'SDB vasque',      notes: 'Tube' },
  { id: 'cons-tete-brosse-elec', name: 'Tête de brosse à dents électrique', brand: '', category: 'consumable', qty: 1, dims: { w: 2.5, d: 2.5, h: 8.5 }, frequency: 'trimestriel', stock: 4, location: 'SDB vasque',      notes: 'Recharge brosse à dents électrique — changer tous les 3 mois' },
  { id: 'cons-savon',           name: 'Savon liquide 250 ml',       brand: '',         category: 'consumable', qty: 1, dims: { w: 6,  d: 6,  h: 18 }, frequency: 'mensuel',    stock: 1,  location: 'SDB vasque',      notes: 'Distributeur TACKAN' },
  { id: 'cons-shampoing',       name: 'Shampoing 400 ml',           brand: '',         category: 'consumable', qty: 1, dims: { w: 7,  d: 7,  h: 22 }, frequency: 'mensuel',    stock: 1,  location: 'SDB douche',      notes: 'Flacon' },
  { id: 'cons-creme-peau',      name: 'Crème pour la peau',         brand: '',         category: 'consumable', qty: 1, dims: { w: 7,  d: 4,  h: 15 }, frequency: 'mensuel',    stock: 1,  location: 'SDB vasque',      notes: 'Hydratante visage/corps' },
  { id: 'cons-lessive',         name: 'Lessive 3 L',                brand: '',         category: 'consumable', qty: 1, dims: { w: 24, d: 14, h: 28 }, frequency: 'trimestriel', stock: 1, location: 'Placard SDB',     notes: 'Bidon liquide' },
  { id: 'cons-liquide-vaisselle', name: 'Liquide vaisselle 1 L',    brand: '',         category: 'consumable', qty: 1, dims: { w: 8,  d: 6,  h: 28 }, frequency: 'mensuel',    stock: 1,  location: 'Cuisine évier',   notes: 'Flacon' },
  { id: 'cons-pizza',           name: 'Pizza surgelée',             brand: '',         category: 'consumable', qty: 4, dims: { w: 30, d: 30, h: 3  }, frequency: 'hebdo',      stock: 4,  location: 'Congélateur',     notes: 'Pizza 4 fromages / margherita' },
  { id: 'cons-pates',           name: 'Pâtes 500 g',                brand: '',         category: 'consumable', qty: 3, dims: { w: 8,  d: 6,  h: 25 }, frequency: 'hebdo',      stock: 3,  location: 'Placard cuisine', notes: 'Penne / spaghetti / fusilli' },
  { id: 'cons-riz',             name: 'Riz 1 kg',                   brand: '',         category: 'consumable', qty: 1, dims: { w: 14, d: 8,  h: 22 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Basmati / long grain' },
  { id: 'cons-lait',            name: 'Lait 1 L',                   brand: '',         category: 'consumable', qty: 2, dims: { w: 7,  d: 7,  h: 23 }, frequency: 'hebdo',      stock: 2,  location: 'Frigo',           notes: 'Brique UHT demi-écrémé' },
  { id: 'cons-beurre',          name: 'Beurre 250 g',               brand: '',         category: 'consumable', qty: 1, dims: { w: 11, d: 7,  h: 5  }, frequency: 'mensuel',    stock: 1,  location: 'Frigo',           notes: 'Plaquette demi-sel' },
  { id: 'cons-oeufs',           name: 'Œufs (boîte 6)',             brand: '',         category: 'consumable', qty: 1, dims: { w: 17, d: 11, h: 8  }, frequency: 'hebdo',      stock: 1,  location: 'Frigo',           notes: 'Bio plein air' },
  { id: 'cons-fromage',         name: 'Fromage râpé 200 g',         brand: '',         category: 'consumable', qty: 1, dims: { w: 18, d: 12, h: 4  }, frequency: 'hebdo',      stock: 1,  location: 'Frigo',           notes: 'Emmental / gruyère' },
  { id: 'cons-pain',            name: 'Pain (baguette)',            brand: '',         category: 'consumable', qty: 1, dims: { w: 65, d: 6,  h: 6  }, frequency: 'hebdo',      stock: 1,  location: 'Cuisine plan',    notes: 'Tradition' },
  { id: 'cons-cafe',            name: 'Café moulu 250 g',           brand: '',         category: 'consumable', qty: 1, dims: { w: 11, d: 6,  h: 16 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Arabica' },
  { id: 'cons-huile',           name: "Huile d'olive 1 L",          brand: '',         category: 'consumable', qty: 1, dims: { w: 9,  d: 9,  h: 30 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Vierge extra' },
  { id: 'cons-sel',             name: 'Sel 1 kg',                   brand: '',         category: 'consumable', qty: 1, dims: { w: 12, d: 6,  h: 18 }, frequency: 'annuel',     stock: 1,  location: 'Placard cuisine', notes: 'Fin / gros' },
  { id: 'cons-poivre',          name: 'Poivre (moulin)',            brand: '',         category: 'consumable', qty: 1, dims: { w: 5,  d: 5,  h: 15 }, frequency: 'annuel',     stock: 1,  location: 'Placard cuisine', notes: 'Moulin réutilisable' },
  { id: 'cons-sucre',           name: 'Sucre 1 kg',                 brand: '',         category: 'consumable', qty: 1, dims: { w: 14, d: 8,  h: 18 }, frequency: 'trimestriel', stock: 1, location: 'Placard cuisine', notes: 'Blanc en poudre' },
  { id: 'cons-farine',          name: 'Farine 1 kg',                brand: '',         category: 'consumable', qty: 1, dims: { w: 16, d: 10, h: 22 }, frequency: 'trimestriel', stock: 1, location: 'Placard cuisine', notes: 'T55' },
  { id: 'cons-nutella',         name: 'Nutella 400 g',              brand: 'Ferrero',  category: 'consumable', qty: 1, dims: { w: 9,  d: 9,  h: 12 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Pot' },
  { id: 'cons-chocolat',        name: 'Chocolat (tablette)',        brand: '',         category: 'consumable', qty: 2, dims: { w: 17, d: 8,  h: 1  }, frequency: 'hebdo',      stock: 2,  location: 'Placard cuisine', notes: 'Noir 70%' },
  { id: 'cons-herbes-provence', name: 'Herbes de Provence',         brand: '',         category: 'consumable', qty: 1, dims: { w: 5,  d: 5,  h: 10 }, frequency: 'annuel',     stock: 1,  location: 'Placard cuisine', notes: 'Pot mélange séché' },
  { id: 'cons-ketchup',         name: 'Ketchup 560 g',              brand: 'Heinz',    category: 'consumable', qty: 1, dims: { w: 7,  d: 7,  h: 23 }, frequency: 'mensuel',    stock: 1,  location: 'Frigo',           notes: 'Bouteille squeeze' },
  { id: 'cons-mayo',            name: 'Mayonnaise 470 ml',          brand: '',         category: 'consumable', qty: 1, dims: { w: 7,  d: 7,  h: 20 }, frequency: 'mensuel',    stock: 1,  location: 'Frigo',           notes: 'Bouteille squeeze' },
  { id: 'cons-olives',          name: 'Olives sans noyau 200 g',    brand: '',         category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 10 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Bocal vert ou noir' },
  { id: 'cons-saucisson',       name: 'Saucisson sec',              brand: '',         category: 'consumable', qty: 1, dims: { w: 6,  d: 6,  h: 25 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Pièce sèche' },
  { id: 'cons-desperado',       name: 'Desperados 33 cl',           brand: 'Desperados', category: 'consumable', qty: 6, dims: { w: 6,  d: 6,  h: 23 }, frequency: 'hebdo',    stock: 6,  location: 'Frigo',           notes: 'Bouteille bière tequila' },
  { id: 'cons-vodka',           name: 'Vodka 70 cl',                brand: '',         category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 30 }, frequency: 'trimestriel', stock: 1, location: 'Placard cuisine', notes: 'Bouteille' },
  { id: 'cons-redbull',         name: 'Redbull 25 cl',              brand: 'Red Bull', category: 'consumable', qty: 4, dims: { w: 5,  d: 5,  h: 14 }, frequency: 'hebdo',      stock: 4,  location: 'Frigo',           notes: 'Canette' },
  { id: 'cons-sirop',           name: 'Sirop 75 cl',                brand: '',         category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 28 }, frequency: 'trimestriel', stock: 1, location: 'Placard cuisine', notes: 'Bouteille — menthe / grenadine' },
  { id: 'cons-coca',            name: 'Coca-Cola 1,5 L',            brand: 'Coca-Cola', category: 'consumable', qty: 2, dims: { w: 9,  d: 9,  h: 33 }, frequency: 'hebdo',      stock: 2,  location: 'Frigo',           notes: 'Bouteille PET' },
  { id: 'cons-javel-cif',       name: 'Javel 5 en 1 Cif',           brand: 'Cif',       category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 28 }, frequency: 'mensuel',    stock: 1,  location: 'Placard SDB',     notes: 'Spray nettoyant multi-surfaces' },
  { id: 'cons-cif-creme-plaque', name: 'Cif Crème Plaque / Four',   brand: 'Cif',       category: 'consumable', qty: 1, dims: { w: 7,  d: 7,  h: 22 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Crème abrasive nettoyage plaques de cuisson et four' },
  { id: 'cons-nett-canalisation', name: 'Nettoyant Canalisation',    brand: '',          category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 25 }, frequency: 'mensuel',    stock: 1,  location: 'Placard SDB',     notes: 'Déboucheur / entretien canalisations' },
  { id: 'cons-gel-wc',           name: 'Gel WC',                     brand: '',          category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 22 }, frequency: 'mensuel',    stock: 1,  location: 'WC',              notes: 'Gel nettoyant WC' },
  { id: 'cons-anticalcaire',     name: 'Produit Anticalcaire',        brand: '',          category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 22 }, frequency: 'mensuel',    stock: 1,  location: 'Placard SDB',     notes: 'Détartrant' },
  { id: 'cons-javel-pur',        name: 'Javel Pur',                   brand: '',          category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 28 }, frequency: 'mensuel',    stock: 1,  location: 'Placard SDB',     notes: 'Eau de javel concentrée' },
  { id: 'cons-desodo-gaz',      name: 'Désodorisant spray gaz',      brand: '',          category: 'consumable', qty: 1, dims: { w: 6,  d: 6,  h: 17 }, frequency: 'mensuel',    stock: 1,  location: 'WC',              notes: 'Aérosol' },
  { id: 'cons-desodo-liquide',  name: 'Désodorisant liquide',        brand: '',          category: 'consumable', qty: 1, dims: { w: 5,  d: 5,  h: 12 }, frequency: 'mensuel',    stock: 1,  location: 'WC',              notes: 'Diffuseur flacon' },
  { id: 'cons-nems',            name: 'Nems surgelés',               brand: '',          category: 'consumable', qty: 4, dims: { w: 25, d: 15, h: 5  }, frequency: 'hebdo',      stock: 4,  location: 'Congélateur',     notes: 'Sachet' },
  { id: 'cons-nems-porc',       name: 'Nems porc',                   brand: '',          category: 'consumable', qty: 1, dims: { w: 25, d: 15, h: 5  }, frequency: 'hebdo',      stock: 1,  location: 'Congélateur',     notes: 'Sachet surgelé' },
  { id: 'cons-nems-veggie',     name: 'Nems végétariens',            brand: '',          category: 'consumable', qty: 1, dims: { w: 25, d: 15, h: 5  }, frequency: 'hebdo',      stock: 1,  location: 'Congélateur',     notes: 'Sachet surgelé' },
  { id: 'cons-merguez',         name: 'Merguez',                     brand: '',          category: 'consumable', qty: 1, dims: { w: 20, d: 15, h: 5  }, frequency: 'hebdo',      stock: 1,  location: 'Congélateur',     notes: 'Sachet' },
  { id: 'cons-brochette-poulet', name: 'Brochette de poulet',        brand: '',          category: 'consumable', qty: 1, dims: { w: 20, d: 15, h: 5  }, frequency: 'hebdo',      stock: 1,  location: 'Congélateur',     notes: 'Sachet' },
  { id: 'cons-brochette-poulet-provencal', name: 'Brochette poulet façon provençal sous vide', brand: '', category: 'consumable', qty: 3, dims: { w: 22, d: 8, h: 4 }, frequency: 'hebdo', stock: 3, location: 'Frigo', notes: 'Sachet sous vide individuel' },
  { id: 'cons-semoule',         name: 'Semoule de blé 500 g',        brand: '',          category: 'consumable', qty: 1, dims: { w: 15, d: 8,  h: 22 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Paquet' },
  { id: 'cons-lame-rasoir-elec', name: 'Lame rasoir électrique',     brand: 'Philips',   category: 'consumable', qty: 1, dims: { w: 10, d: 10, h: 5  }, frequency: 'annuel',     stock: 1,  location: 'SDB vasque',      notes: 'Tête de remplacement' },
  { id: 'cons-lingette-lavante', name: 'Lingettes lavantes',         brand: '',          category: 'consumable', qty: 1, dims: { w: 15, d: 10, h: 8  }, frequency: 'mensuel',    stock: 1,  location: 'SDB',             notes: 'Paquet' },
  { id: 'cons-chicoree',        name: 'Chicorée',                    brand: '',          category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 12 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Bocal / boîte soluble' },
  { id: 'cons-the',             name: 'Thé (boîte 25 sachets)',       brand: '',          category: 'consumable', qty: 1, dims: { w: 12, d: 8,  h: 10 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Sachets' },
  { id: 'cons-cure-dents',      name: 'Cure-dents (boîte)',           brand: '',          category: 'consumable', qty: 1, dims: { w: 8,  d: 3,  h: 10 }, frequency: 'trimestriel', stock: 1, location: 'Placard cuisine', notes: 'Boîte bois' },
  { id: 'cons-chewing-gum',     name: 'Chewing-gum',                 brand: '',          category: 'consumable', qty: 1, dims: { w: 6,  d: 3,  h: 9  }, frequency: 'hebdo',      stock: 1,  location: 'Placard cuisine', notes: 'Paquet' },
  { id: 'cons-tondeuse-philips', name: 'Tondeuse Philips blade',      brand: 'Philips',   category: 'consumable', qty: 1, dims: { w: 12, d: 8,  h: 5  }, frequency: 'annuel',     stock: 1,  location: 'SDB vasque',      notes: 'Tête de remplacement MG9558/15 Series 9000' },
  { id: 'cons-compote-pomme',    name: 'Compote pomme allégée (pack ×4)', brand: 'Vergers Gourmands', category: 'consumable', qty: 4, dims: { w: 19, d: 10, h: 9 }, frequency: 'hebdo', stock: 4, location: 'Placard cuisine', notes: 'Lidl — 0,99 € le pack, allégée en sucre' },
  { id: 'cons-cappuccino-choco', name: 'Cappuccino goût chocolat',     brand: 'Bellarom',  category: 'consumable', qty: 1, dims: { w: 14, d: 7,  h: 19 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Lidl — sachets instantanés' },
  { id: 'cons-okoia-k04017',    name: 'Nettoyant têtes de rasoirs K04017', brand: 'Okoia', category: 'consumable', qty: 2, dims: { w: 6,  d: 6,  h: 10 }, frequency: 'mensuel',    stock: 2,  location: 'SDB vasque',      notes: 'Spray nettoyant têtes rasoir électrique — Acheté le 14/02/2026' },

  // ── SACS / BAGAGERIE ──────────────────────────────────────────────────────────
  { id: 'sac-banane-kalenji', name: 'Sac banane Kalenji Activ Mblty noir', brand: 'Kalenji', category: 'clothing', qty: 2, dims: { w: 28, d: 8, h: 14 }, notes: '5 L — 3 poches — porte-bouteille 75 cl — sangle stabilisatrice amovible — imperméable — Decathlon', photos: ['media/photos/sac-banane-kalenji-activ-mblty-noir-1.jpg', 'media/photos/sac-banane-kalenji-activ-mblty-noir-2.jpg', 'media/photos/sac-banane-kalenji-activ-mblty-noir-3.jpg', 'media/photos/sac-banane-kalenji-activ-mblty-noir-4.jpg', 'media/photos/sac-banane-kalenji-activ-mblty-noir-5.jpg', 'media/photos/sac-banane-kalenji-activ-mblty-noir-6.jpg'] },

  // ── PORTES ────────────────────────────────────────────────────────────────────
  { id: 'door-entry',       name: 'Porte d\'entrée',                brand: '',         category: 'doors',     qty: 1, dims: { w: 90,  d: 4,   h: 204 }, notes: 'Rouge, mur diagonal, poignée L + knob rouge', actions: ['entry-door-toggle'] },
  { id: 'door-living',      name: 'Porte séjour',                   brand: '',         category: 'doors',     qty: 1, dims: { w: 83,  d: 4,   h: 204 }, notes: 'Blanche, mur D, poignée L double face', actions: ['living-door-toggle'] },
  { id: 'door-sdb',         name: 'Porte SDB',                      brand: '',         category: 'doors',     qty: 1, dims: { w: 4,   d: 83,  h: 204 }, notes: 'Blanche, mur couloir, poignée L double face', actions: ['bathroom-door-toggle'] },
  { id: 'door-glass',       name: 'Porte-fenêtre',                  brand: '',         category: 'doors',     qty: 1, dims: { w: 160, d: 5,   h: 190 }, notes: 'Double battant PVC blanc, vitrage, seuil 20cm', actions: ['east-glass-door-toggle'] },
];

export const STORAGE_SPACES: StorageSpace[] = [
  { id: 'kallax-ne-stack', name: 'Kallax NE',       dims: { w: 75.5, d: 39, h: 222 }, notes: 'Coin mur C+B — 2×1 bas + 2×2 haut empilés, 6 Drona + 1 dessus' },
  { id: 'kallax-se-stack', name: 'Kallax SE',       dims: { w: 75.5, d: 39, h: 151 }, notes: 'Mur B sud — 2× (2×1 pivoté), 4 Drona + meuble en T dessus' },
  { id: 'kallax-nw-stack', name: 'Kallax NW',       dims: { w: 75.5, d: 39, h: 227 }, notes: 'Coin mur A+C — tour 2×1 + 1×1 + 1×1 pivotés, 4 Drona' },
  { id: 'kallax-sw-stack', name: 'Kallax cuisine',  dims: { w: 75.5, d: 39, h: 371 }, notes: 'Niche mur D — 2×2 + 2×2 + 2×1 empilés, 4 Drona dans le bas' },
  { id: 'mackapar-stack',  name: 'Mackapär',        dims: { w: 77,   d: 32, h: 200 }, notes: 'Portant niche — combinaison + salopette + 2 Drona en haut' },
  { id: 'sunnersta-stack', name: 'Sunnersta',       dims: { w: 36,   d: 56, h: 90  }, notes: 'Desserte roulante — mannequin + casquette' },
  { id: 'cuisine-stack',   name: 'Cuisine',         dims: { w: 100,  d: 60, h: 93  }, notes: 'Plan de travail, évier, plaques, frigo, meuble bas, meuble haut + 3 Drona' },
  { id: 'corridor-closet', name: 'Placard couloir', dims: { w: 60,   d: 50, h: 250 }, notes: 'Porte pivotante + 3 étagères', actions: ['corr-doors-toggle'] },
  { id: 'sdb-closet',      name: 'Placard SDB',     dims: { w: 110,  d: 60, h: 250 }, notes: 'Double porte coulissante + étagère triangulaire 170cm (X=70→180, Z=600→660)', actions: ['sdb-closet-toggle'] },
];

export const CATEGORIES: Category[] = [
  { id: 'all',          label: 'Tout' },
  { id: 'actionnable',  label: '⚡ Actionnable' },
  { id: 'storage',      label: 'Rangement' },
  { id: 'furniture',    label: 'Mobilier' },
  { id: 'tech',         label: 'Tech' },
  { id: 'kitchen',      label: 'Cuisine' },
  { id: 'bathroom',     label: 'Salle d\'eau' },
  { id: 'clothing',     label: 'Vêtements' },
  { id: 'decor',        label: 'Déco' },
  { id: 'consumable',   label: '🛒 Consomables' },
  { id: 'glbs',         label: '🎲 GLBs' },
];
