// =============================================
// INVENTORY DATA — port de js/ui/inventoryData.js
// dims: { w, d, h } en cm (w=X, d=Z, h=Y)
// =============================================

export type ConsumableFrequency = 'hebdo' | 'mensuel' | 'trimestriel' | 'annuel';

export interface InventoryItem {
  id: string;
  name: string;
  brand: string;
  category: string;
  qty: number;
  dims: { w: number; d: number; h: number };
  notes?: string;
  glbPath?: string;
  photos?: string[];
  url?: string;
  price?: string;
  description?: string;
  actions?: string[];
  // Consumable-specific
  frequency?: ConsumableFrequency;
  stock?: number;
  location?: string;
  tags?: string[];
}

export interface StorageSpace {
  id: string;
  name: string;
  dims: { w: number; d: number; h: number };
  notes?: string;
  actions?: string[];
}

export interface Category {
  id: string;
  label: string;
}

export const INVENTORY: InventoryItem[] = [
  { id: 'bollsidan30574370', name: "BOLLSIDAN Table pour ordinateur portable, blanc, 68x36 cm", brand: 'IKEA', category: 'furniture', qty: 2, dims: { w: 68, d: 36, h: 70 }, glbPath: 'items/bollsidan30574370/Bollsidan30574370.glb', photos: ['items/bollsidan30574370/Bollsidan30574370.jpg', 'items/bollsidan30574370/Bollsidan30574370_1.jpg', 'items/bollsidan30574370/Bollsidan30574370_2.jpg', 'items/bollsidan30574370/Bollsidan30574370_3.jpg', 'items/bollsidan30574370/Bollsidan30574370_4.jpg', 'items/bollsidan30574370/Bollsidan30574370_5.jpg', 'items/bollsidan30574370/Bollsidan30574370_6.jpg'], url: 'https://www.ikea.com/fr/fr/p/bollsidan-table-pour-ordinateur-portable-blanc-30574370/', price: '39,99', notes: 'Surface 68×36cm ; bureau 1 : assis/debout avec Stackstod ; bureau 2 : laptop + téléphone + mug', actions: ['desk-toggle'] },
  { id: 'stackstod60620144', name: "STACKSTOD organiseur bureau, rouge, 32x18x16 cm", brand: 'IKEA', category: 'storage', qty: 3, dims: { w: 32, d: 18, h: 16 }, glbPath: 'items/stackstod60620144/Stackstod60620144.glb', photos: ['items/stackstod60620144/Stackstod60620144.jpg', 'items/stackstod60620144/Stackstod60620144_1.jpg', 'items/stackstod60620144/Stackstod60620144_2.jpg', 'items/stackstod60620144/Stackstod60620144_3.jpg', 'items/stackstod60620144/Stackstod60620144_4.jpg'], url: 'https://www.ikea.com/fr/fr/p/stackstod-organiseur-bureau-rouge-60620144/', price: '2,99', notes: '1 sur Bureau 1' },
  { id: 'koppla00314741', name: "KOPPLA Prise quadruple 2 ports USB, blanc, 3", brand: 'IKEA', category: 'furniture', qty: 1, dims: { w: 6, d: 30, h: 10 }, glbPath: 'items/koppla00314741/Koppla00314741.glb', photos: ['items/koppla00314741/Koppla00314741.jpg', 'items/koppla00314741/Koppla00314741_1.jpg', 'items/koppla00314741/Koppla00314741_2.jpg'], url: 'https://www.ikea.com/fr/fr/p/koppla-prise-quadruple-2-ports-usb-blanc-00314741/', price: '17,99', notes: '' },
  { id: 'grejig40329868', name: "GREJIG Étagère à chaussures, 58x27 cm", brand: 'IKEA', category: 'storage', qty: 4, dims: { w: 58, d: 27, h: 17 }, glbPath: 'items/grejig40329868/Grejig40329868.glb', photos: ['items/grejig40329868/Grejig40329868.jpg', 'items/grejig40329868/Grejig40329868_1.jpg', 'items/grejig40329868/Grejig40329868_2.jpg', 'items/grejig40329868/Grejig40329868_3.jpg', 'items/grejig40329868/Grejig40329868_4.jpg', 'items/grejig40329868/Grejig40329868_5.jpg'], url: 'https://www.ikea.com/fr/fr/p/grejig-etagere-a-chaussures-gris-40329868/', price: '3,99', notes: '3 entrée couloir + 1 placard SDB le long de la porte droite' },
  { id: 'fniss40295439', name: "FNISS poubelle, blanc, 10 l", brand: 'IKEA', category: 'storage', qty: 2, dims: { w: 28, d: 28, h: 28 }, glbPath: 'items/fniss40295439/Fniss40295439.glb', photos: ['items/fniss40295439/Fniss40295439.jpg', 'items/fniss40295439/Fniss40295439_1.jpg', 'items/fniss40295439/Fniss40295439_2.jpg', 'items/fniss40295439/Fniss40295439_3.jpg', 'items/fniss40295439/Fniss40295439_4.jpg', 'items/fniss40295439/Fniss40295439_5.jpg'], url: 'https://www.ikea.com/fr/fr/p/fniss-poubelle-blanc-40295439/', price: '1,99', notes: '1 couloir, 1 séjour' },
  { id: 'lack90282180', name: "LACK étagère murale, blanc, 110x26 cm", brand: 'IKEA', category: 'storage', qty: 1, dims: { w: 110, d: 26, h: 5 }, glbPath: 'items/lack90282180/Lack90282180.glb', photos: ['items/lack90282180/Lack90282180.jpg', 'items/lack90282180/Lack90282180_1.jpg', 'items/lack90282180/Lack90282180_2.jpg', 'items/lack90282180/Lack90282180_3.jpg', 'items/lack90282180/Lack90282180_4.jpg', 'items/lack90282180/Lack90282180_5.jpg', 'items/lack90282180/Lack90282180_6.jpg'], url: 'https://www.ikea.com/fr/fr/p/lack-etagere-murale-blanc-90282180/', price: '14,99', notes: 'Murale, mur A séjour' },
  { id: 'variera60136623', name: "VARIERA demi-étagère, blanc, 32x13x16 cm", brand: 'IKEA', category: 'storage', qty: 1, dims: { w: 32, d: 13, h: 16 }, glbPath: 'items/variera60136623/Variera60136623.glb', photos: ['items/variera60136623/Variera60136623.jpg', 'items/variera60136623/Variera60136623_1.jpg', 'items/variera60136623/Variera60136623_2.jpg', 'items/variera60136623/Variera60136623_3.jpg', 'items/variera60136623/Variera60136623_4.jpg'], url: 'https://www.ikea.com/fr/fr/p/variera-demi-etagere-blanc-60136623/', price: '4,99', notes: 'Sur Kallax NW' },
  { id: 'variera80136622', name: "VARIERA demi-étagère, blanc, 32x28x16 cm", brand: 'IKEA', category: 'storage', qty: 1, dims: { w: 32, d: 28, h: 16 }, glbPath: 'items/variera80136622/Variera80136622.glb', photos: ['items/variera80136622/Variera80136622.jpg', 'items/variera80136622/Variera80136622_1.jpg', 'items/variera80136622/Variera80136622_2.jpg', 'items/variera80136622/Variera80136622_3.jpg'], url: 'https://www.ikea.com/fr/fr/p/variera-demi-etagere-blanc-80136622/', price: '3,99', notes: 'Sur Kallax NE' },
  { id: 'valloxen10415612', name: "VALLOXEN Abattant WC, blanc", brand: 'IKEA', category: 'bathroom', qty: 1, dims: { w: 36, d: 44, h: 4.4 }, photos: ['items/valloxen10415612/Valloxen10415612.jpg', 'items/valloxen10415612/Valloxen10415612_1.jpg', 'items/valloxen10415612/Valloxen10415612_2.jpg'], url: 'https://www.ikea.com/fr/fr/p/valloxen-abattant-wc-blanc-10415612/', price: '19,99', notes: 'Abattant WC avec amortisseurs intégrés' },
  { id: 'trixig80568084', name: "TRIXIG ensemble de mèches, lot de 20", brand: 'IKEA', category: 'tools', qty: 1, dims: { w: 10, d: 10, h: 10 }, glbPath: 'items/trixig80568084/Trixig80568084.glb', photos: ['items/trixig80568084/Trixig80568084.jpg', 'items/trixig80568084/Trixig80568084_1.jpg', 'items/trixig80568084/Trixig80568084_2.jpg', 'items/trixig80568084/Trixig80568084_3.jpg'], url: 'https://www.ikea.com/fr/fr/p/trixig-ensemble-de-meches-lot-de-20-80568084/', price: '4,99', notes: '' },
  { id: 'trixig50546908', name: "TRIXIG set de 175 vis et chevilles", brand: 'IKEA', category: 'tools', qty: 1, dims: { w: 10, d: 10, h: 10 }, glbPath: 'items/trixig50546908/Trixig50546908.glb', photos: ['items/trixig50546908/Trixig50546908.jpg', 'items/trixig50546908/Trixig50546908_1.jpg', 'items/trixig50546908/Trixig50546908_2.jpg', 'items/trixig50546908/Trixig50546908_3.jpg', 'items/trixig50546908/Trixig50546908_4.jpg', 'items/trixig50546908/Trixig50546908_5.jpg'], url: 'https://www.ikea.com/fr/fr/p/trixig-set-de-175-vis-et-chevilles-50546908/', price: '6,99', notes: '' },
  { id: 'trixig10546910', name: "TRIXIG visseuse/perceuse, li", brand: 'IKEA', category: 'tools', qty: 1, dims: { w: 6.8, d: 18.8, h: 24 }, glbPath: 'items/trixig10546910/Trixig10546910.glb', photos: ['items/trixig10546910/Trixig10546910.jpg', 'items/trixig10546910/Trixig10546910_1.jpg', 'items/trixig10546910/Trixig10546910_2.jpg', 'items/trixig10546910/Trixig10546910_3.jpg', 'items/trixig10546910/Trixig10546910_4.jpg', 'items/trixig10546910/Trixig10546910_5.jpg', 'items/trixig10546910/Trixig10546910_6.jpg'], url: 'https://www.ikea.com/fr/fr/p/trixig-visseuse-perceuse-li-ion-10546910/', price: '34,99', notes: '' },
  { id: 'samla70102972', name: "SAMLA boîte, transparent, 28x19x14 cm/5 l", brand: 'IKEA', category: 'storage', qty: 1, dims: { w: 28, d: 19, h: 14 }, glbPath: 'items/samla70102972/Samla70102972.glb', photos: ['items/samla70102972/Samla70102972.jpg', 'items/samla70102972/Samla70102972_1.jpg', 'items/samla70102972/Samla70102972_2.jpg', 'items/samla70102972/Samla70102972_3.jpg', 'items/samla70102972/Samla70102972_4.jpg', 'items/samla70102972/Samla70102972_5.jpg', 'items/samla70102972/Samla70102972_6.jpg'], url: 'https://www.ikea.com/fr/fr/p/samla-boite-transparent-70102972/', price: '1,49', notes: '' },
  { id: 'samla50455088', name: "SAMLA couvercle pour boîte 5L, transparent", brand: 'IKEA', category: 'storage', qty: 1, dims: { w: 20, d: 28, h: 1 }, glbPath: 'items/samla50455088/Samla50455088.glb', photos: ['items/samla50455088/Samla50455088.jpg', 'items/samla50455088/Samla50455088_1.jpg', 'items/samla50455088/Samla50455088_2.jpg', 'items/samla50455088/Samla50455088_3.jpg'], url: 'https://www.ikea.com/fr/fr/p/samla-couvercle-pour-boite-5l-transparent-50455088/', price: '0,50', notes: '' },
  { id: 'samla90455086', name: "SAMLA couvercle pour boîte 11/22 L, transparent", brand: 'IKEA', category: 'storage', qty: 1, dims: { w: 28, d: 39, h: 1 }, glbPath: 'items/samla90455086/Samla90455086.glb', photos: ['items/samla90455086/Samla90455086.jpg', 'items/samla90455086/Samla90455086_1.jpg', 'items/samla90455086/Samla90455086_2.jpg', 'items/samla90455086/Samla90455086_3.jpg'], url: 'https://www.ikea.com/fr/fr/p/samla-couvercle-pour-boite-11-22-l-transparent-90455086/', price: '2', notes: '' },
  { id: 'samla80102976', name: "SAMLA boîte, transparent, 39x28x28 cm/22 l", brand: 'IKEA', category: 'storage', qty: 1, dims: { w: 39, d: 28, h: 28 }, glbPath: 'items/samla80102976/Samla80102976.glb', photos: ['items/samla80102976/Samla80102976.jpg', 'items/samla80102976/Samla80102976_1.jpg', 'items/samla80102976/Samla80102976_2.jpg', 'items/samla80102976/Samla80102976_3.jpg', 'items/samla80102976/Samla80102976_4.jpg', 'items/samla80102976/Samla80102976_5.jpg', 'items/samla80102976/Samla80102976_6.jpg', 'items/samla80102976/Samla80102976_7.jpg'], url: 'https://www.ikea.com/fr/fr/p/samla-boite-transparent-80102976/', price: '3,99', notes: '' },
  { id: 'samla69440836', name: "SAMLA boîte avec couvercle, transparent, 39x28x14 cm/11 l", brand: 'IKEA', category: 'storage', qty: 1, dims: { w: 39, d: 28, h: 14 }, glbPath: 'items/samla69440836/Samla69440836.glb', photos: ['items/samla69440836/Samla69440836.jpg', 'items/samla69440836/Samla69440836_1.jpg', 'items/samla69440836/Samla69440836_2.jpg', 'items/samla69440836/Samla69440836_3.jpg', 'items/samla69440836/Samla69440836_4.jpg', 'items/samla69440836/Samla69440836_5.jpg', 'items/samla69440836/Samla69440836_6.jpg', 'items/samla69440836/Samla69440836_7.jpg'], url: 'https://www.ikea.com/fr/fr/p/samla-boite-avec-couvercle-transparent-s69440836/', price: '4,99', notes: '' },
  { id: 'mulig30179435', name: "MULIG Tringle à vêtements, blanc", brand: 'IKEA', category: 'storage', qty: 1, dims: { w: 60, d: 26, h: 16 }, glbPath: 'items/mulig30179435/Mulig30179435.glb', photos: ['items/mulig30179435/Mulig30179435.jpg', 'items/mulig30179435/Mulig30179435_1.jpg', 'items/mulig30179435/Mulig30179435_2.jpg', 'items/mulig30179435/Mulig30179435_3.jpg', 'items/mulig30179435/Mulig30179435_4.jpg'], url: 'https://www.ikea.com/fr/fr/p/mulig-tringle-a-vetements-blanc-30179435/', price: '4,99', notes: 'Penderie mur A séjour avec 6 cintres Spruttig' },
  { id: 'spruttig20317079', name: "SPRUTTIG cintre, noir", brand: 'IKEA', category: 'storage', qty: 18, dims: { w: 39, d: 0.4, h: 19 }, glbPath: 'items/spruttig20317079/Spruttig20317079.glb', photos: ['items/spruttig20317079/Spruttig20317079.jpg', 'items/spruttig20317079/Spruttig20317079_1.jpg', 'items/spruttig20317079/Spruttig20317079_2.jpg', 'items/spruttig20317079/Spruttig20317079_3.jpg', 'items/spruttig20317079/Spruttig20317079_4.jpg', 'items/spruttig20317079/Spruttig20317079_5.jpg', 'items/spruttig20317079/Spruttig20317079_6.jpg'], url: 'https://www.ikea.com/fr/fr/p/spruttig-cintre-noir-20317079/', price: '3,50', notes: '18 cintres au total (6 par portant Mackapär et 6 sur tringle Mulig)' },
  { id: 'mackapar50530988', name: "MACKAPÄR rangement ouvert vêtements+chaussur, blanc, 78x32x200 cm", brand: 'IKEA', category: 'furniture', qty: 1, dims: { w: 78, d: 32, h: 200 }, glbPath: 'items/mackapar50530988/Mackapar50530988.glb', photos: ['items/mackapar50530988/Mackapar50530988.jpg', 'items/mackapar50530988/Mackapar50530988_1.jpg', 'items/mackapar50530988/Mackapar50530988_2.jpg', 'items/mackapar50530988/Mackapar50530988_3.jpg', 'items/mackapar50530988/Mackapar50530988_4.jpg', 'items/mackapar50530988/Mackapar50530988_5.jpg', 'items/mackapar50530988/Mackapar50530988_6.jpg', 'items/mackapar50530988/Mackapar50530988_7.jpg', 'items/mackapar50530988/Mackapar50530988_8.jpg'], url: 'https://www.ikea.com/fr/fr/p/mackapaer-rangement-ouvert-vetements-chaussur-blanc-50530988/', price: '89,99', notes: '' },
  { id: 'vatterso20562909', name: "VÄTTERSÖ boîte de rangement, extérieur, gris foncé, 156x72x79 cm", brand: 'IKEA', category: 'furniture', qty: 1, dims: { w: 156, d: 72, h: 79 }, glbPath: 'items/vatterso20562909/Vatterso20562909.glb', photos: ['items/vatterso20562909/Vatterso20562909.jpg', 'items/vatterso20562909/Vatterso20562909_1.jpg', 'items/vatterso20562909/Vatterso20562909_2.jpg', 'items/vatterso20562909/Vatterso20562909_3.jpg', 'items/vatterso20562909/Vatterso20562909_4.jpg', 'items/vatterso20562909/Vatterso20562909_5.jpg'], url: 'https://www.ikea.com/fr/fr/p/vaettersoe-boite-de-rangement-exterieur-gris-fonce-20562909/', price: '159', notes: '' },
  { id: 'lillhavet80461276', name: "LILLHAVET égouttoir multifonction, anthracite", brand: 'IKEA', category: 'furniture', qty: 1, dims: { w: 17.4, d: 47.8, h: 14 }, glbPath: 'items/lillhavet80461276/Lillhavet80461276.glb', photos: ['items/lillhavet80461276/Lillhavet80461276.jpg', 'items/lillhavet80461276/Lillhavet80461276_1.jpg', 'items/lillhavet80461276/Lillhavet80461276_2.jpg', 'items/lillhavet80461276/Lillhavet80461276_3.jpg', 'items/lillhavet80461276/Lillhavet80461276_4.jpg', 'items/lillhavet80461276/Lillhavet80461276_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/lillhavet-egouttoir-multifonction-anthracite-80461276/', price: '16,99', notes: '' },
  { id: 'fornuft80428475', name: "FÖRNUFT petite cuillère, acier inoxydable, 14 cm", brand: 'IKEA', category: 'furniture', qty: 1, dims: { w: 10, d: 14, h: 10 }, glbPath: 'items/fornuft80428475/Fornuft80428475.glb', photos: ['items/fornuft80428475/Fornuft80428475.jpg', 'items/fornuft80428475/Fornuft80428475_1.jpg', 'items/fornuft80428475/Fornuft80428475_2.jpg', 'items/fornuft80428475/Fornuft80428475_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/foernuft-petite-cuillere-acier-inoxydable-80428475/', price: '2,49', notes: '' },
  { id: 'fornuft90428489', name: "FÖRNUFT cuillère, acier inoxydable, 19 cm", brand: 'IKEA', category: 'furniture', qty: 1, dims: { w: 10, d: 19, h: 10 }, glbPath: 'items/fornuft90428489/Fornuft90428489.glb', photos: ['items/fornuft90428489/Fornuft90428489.jpg', 'items/fornuft90428489/Fornuft90428489_1.jpg', 'items/fornuft90428489/Fornuft90428489_2.jpg', 'items/fornuft90428489/Fornuft90428489_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/foernuft-cuillere-acier-inoxydable-90428489/', price: '2,49', notes: '' },
  { id: 'fornuft10428488', name: "FÖRNUFT couteau, acier inoxydable, 21 cm", brand: 'IKEA', category: 'furniture', qty: 1, dims: { w: 10, d: 21, h: 10 }, glbPath: 'items/fornuft10428488/Fornuft10428488.glb', photos: ['items/fornuft10428488/Fornuft10428488.jpg', 'items/fornuft10428488/Fornuft10428488_1.jpg', 'items/fornuft10428488/Fornuft10428488_2.jpg', 'items/fornuft10428488/Fornuft10428488_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/foernuft-couteau-acier-inoxydable-10428488/', price: '2,49', notes: '' },
  { id: 'fornuft40428482', name: "FÖRNUFT fourchette, acier inoxydable, 19 cm", brand: 'IKEA', category: 'furniture', qty: 1, dims: { w: 10, d: 19, h: 10 }, glbPath: 'items/fornuft40428482/Fornuft40428482.glb', photos: ['items/fornuft40428482/Fornuft40428482.jpg', 'items/fornuft40428482/Fornuft40428482_1.jpg', 'items/fornuft40428482/Fornuft40428482_2.jpg', 'items/fornuft40428482/Fornuft40428482_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/foernuft-fourchette-acier-inoxydable-40428482/', price: '2,49', notes: '' },
  { id: 'snitta00287295', name: "SNITTA couteau, noir, 22 cm", brand: 'IKEA', category: 'furniture', qty: 1, dims: { w: 10, d: 22, h: 10 }, glbPath: 'items/snitta00287295/Snitta00287295.glb', photos: ['items/snitta00287295/Snitta00287295.jpg', 'items/snitta00287295/Snitta00287295_1.jpg', 'items/snitta00287295/Snitta00287295_2.jpg', 'items/snitta00287295/Snitta00287295_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/snitta-couteau-noir-00287295/', price: '4,99', notes: '' },
  { id: 'famnig27470460', name: "FAMNIG HJÄRTA coussin, rouge, 40x101 cm", brand: 'IKEA', category: 'decor', qty: 1, dims: { w: 101, d: 40, h: 10 }, glbPath: 'items/famnig27470460/Famnig27470460.glb', photos: ['items/famnig27470460/Famnig27470460.jpg', 'items/famnig27470460/Famnig27470460_1.jpg', 'items/famnig27470460/Famnig27470460_2.jpg', 'items/famnig27470460/Famnig27470460_3.jpg', 'items/famnig27470460/Famnig27470460_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/famnig-hjaerta-coussin-rouge-27470460/', price: '14,99', notes: 'Utilisé comme parachute pour le déploiement des personnages' },
  { id: 'blaskata50569513', name: "BLÅSKATA coussin, cylindrique/gris clair, 80 cm", brand: 'IKEA', category: 'decor', qty: 1, dims: { w: 20, d: 100, h: 20 }, glbPath: 'items/blaskata50569513/Blaskata50569513.glb', photos: ['items/blaskata50569513/Blaskata50569513.jpg', 'items/blaskata50569513/Blaskata50569513_1.jpg', 'items/blaskata50569513/Blaskata50569513_2.jpg', 'items/blaskata50569513/Blaskata50569513_3.jpg', 'items/blaskata50569513/Blaskata50569513_4.jpg', 'items/blaskata50569513/Blaskata50569513_5.jpg', 'items/blaskata50569513/Blaskata50569513_6.jpg', 'items/blaskata50569513/Blaskata50569513_7.jpg', 'items/blaskata50569513/Blaskata50569513_8.jpg', 'items/blaskata50569513/Blaskata50569513_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/blaskata-coussin-cylindrique-gris-clair-50569513/', price: '24,99', notes: 'IKEA utilisé comme objet générique pour les traversins' },
  { id: 'dimpa10056770', name: "DIMPA sac de rangement, transparent, 65x22x65 cm", brand: 'IKEA', category: 'storage', qty: 5, dims: { w: 68, d: 27, h: 67 }, glbPath: 'items/dimpa10056770/Dimpa10056770.glb', photos: ['items/dimpa10056770/Dimpa10056770.jpg', 'items/dimpa10056770/Dimpa10056770_1.jpg', 'items/dimpa10056770/Dimpa10056770_2.jpg', 'items/dimpa10056770/Dimpa10056770_3.jpg', 'items/dimpa10056770/Dimpa10056770_4.jpg', 'items/dimpa10056770/Dimpa10056770_5.jpg', 'items/dimpa10056770/Dimpa10056770_6.jpg', 'items/dimpa10056770/Dimpa10056770_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/dimpa-sac-de-rangement-transparent-10056770/', price: '3,50', notes: '5 sacs séjour mur C' },
  { id: 'nissedal50320320', name: "NISSEDAL Miroir, noir, 65x65 cm, sans plomb", brand: 'IKEA', category: 'bathroom', qty: 3, dims: { w: 65, d: 10, h: 65 }, glbPath: 'items/nissedal50320320/Nissedal50320320.glb', photos: ['items/nissedal50320320/Nissedal50320320.jpg', 'items/nissedal50320320/Nissedal50320320_1.jpg', 'items/nissedal50320320/Nissedal50320320_2.jpg', 'items/nissedal50320320/Nissedal50320320_3.jpg', 'items/nissedal50320320/Nissedal50320320_4.jpg', 'items/nissedal50320320/Nissedal50320320_5.jpg', 'items/nissedal50320320/Nissedal50320320_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/nissedal-miroir-noir-50320320/', price: '39,99', notes: 'SDB' },
  { id: 'altappen90420898', name: "ALTAPPEN Caillebotis, gris clair", brand: 'IKEA', category: 'decor', qty: 1, dims: { w: 30, d: 30, h: 0.6 }, glbPath: 'items/altappen90420898/Altappen90420898.glb', photos: ['items/altappen90420898/Altappen90420898.jpg', 'items/altappen90420898/Altappen90420898_1.jpg', 'items/altappen90420898/Altappen90420898_2.jpg', 'items/altappen90420898/Altappen90420898_3.jpg', 'items/altappen90420898/Altappen90420898_4.jpg', 'items/altappen90420898/Altappen90420898_5.jpg', 'items/altappen90420898/Altappen90420898_6.jpg', 'items/altappen90420898/Altappen90420898_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/altappen-caillebotis-gris-clair-90420898/', price: '9,99', notes: 'Jardin, dalles assemblées' },
  { id: 'anneland60481727', name: "ÅNNELAND matelas hybride, mi-ferme/blanc, 80x200 cm", brand: 'IKEA', category: 'furniture', qty: 1, dims: { w: 80, d: 200, h: 24 }, glbPath: 'items/anneland70481722/Anneland70481722.glb', photos: ['items/anneland70481722/Anneland70481722.jpg', 'items/anneland70481722/Anneland70481722_1.jpg', 'items/anneland70481722/Anneland70481722_2.jpg', 'items/anneland70481722/Anneland70481722_3.jpg', 'items/anneland70481722/Anneland70481722_4.jpg', 'items/anneland70481722/Anneland70481722_5.jpg', 'items/anneland70481722/Anneland70481722_6.jpg', 'items/anneland70481722/Anneland70481722_7.jpg', 'items/anneland70481722/Anneland70481722_8.jpg', 'items/anneland70481722/Anneland70481722_9.jpg', 'items/anneland70481722/Anneland70481722_10.jpg', 'items/anneland70481722/Anneland70481722_11.jpg', 'items/anneland70481722/Anneland70481722_12.jpg', 'items/anneland70481722/Anneland70481722_13.jpg', 'items/anneland70481722/Anneland70481722_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/anneland-matelas-hybride-mi-ferme-blanc-60481727/', price: '349', notes: "Lit principal/haut/Ouest. Les lits peuvent s'empiler mais sont en mode canapé/séparé par défaut pour faire un lit et un canapé/plan de travail." },
  { id: 'vestmarka90470195', name: "VESTMARKA matelas à ressorts, ferme/bleu clair, 80x200 cm", brand: 'IKEA', category: 'furniture', qty: 1, dims: { w: 80, d: 200, h: 18 }, glbPath: 'items/vestmarka90470195/Vestmarka90470195.glb', photos: ['items/vestmarka90470195/Vestmarka90470195.jpg', 'items/vestmarka90470195/Vestmarka90470195_1.jpg', 'items/vestmarka90470195/Vestmarka90470195_2.jpg', 'items/vestmarka90470195/Vestmarka90470195_3.jpg', 'items/vestmarka90470195/Vestmarka90470195_4.jpg', 'items/vestmarka90470195/Vestmarka90470195_5.jpg', 'items/vestmarka90470195/Vestmarka90470195_6.jpg', 'items/vestmarka90470195/Vestmarka90470195_7.jpg', 'items/vestmarka90470195/Vestmarka90470195_8.jpg', 'items/vestmarka90470195/Vestmarka90470195_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/vestmarka-matelas-a-ressorts-ferme-bleu-clair-90470195/', price: '99', notes: "Lit secondaire/bas/Est/Amour. Les lits peuvent s'empiler mais sont en mode canapé/séparé par défaut." },
  { id: 'nasfjallet10558045', name: "NÄSFJÄLLET surmatelas, blanc, 80x200 cm", brand: 'IKEA', category: 'furniture', qty: 1, dims: { w: 80, d: 200, h: 4 }, glbPath: 'items/nasfjallet10558045/Nasfjallet10558045.glb', photos: ['items/nasfjallet10558045/Nasfjallet10558045.jpg', 'items/nasfjallet10558045/Nasfjallet10558045_1.jpg', 'items/nasfjallet10558045/Nasfjallet10558045_2.jpg', 'items/nasfjallet10558045/Nasfjallet10558045_3.jpg', 'items/nasfjallet10558045/Nasfjallet10558045_4.jpg', 'items/nasfjallet10558045/Nasfjallet10558045_5.jpg', 'items/nasfjallet10558045/Nasfjallet10558045_6.jpg', 'items/nasfjallet10558045/Nasfjallet10558045_7.jpg', 'items/nasfjallet10558045/Nasfjallet10558045_3d_preview.png'], url: 'https://www.ikea.com/fr/fr/p/naesfjaellet-surmatelas-blanc-10558045/', price: '35', notes: 'Sur-matelas pour lit principal (haut/Ouest).' },
  { id: 'kin-fine-camera', name: "Video-Surveillance OpenEye 12MP Cloud IP Fisheye Camera", brand: 'OpenEye', category: 'decor', qty: 1, dims: { w: 10, d: 10, h: 5 }, glbPath: 'media/sandbox/camera_render.glb', notes: 'Plafond', actions: [] },

  // ── STORAGE ──────────────────────────────────────────────────────────────────
  { id: 'kallax-2x1',       name: 'Kallax 2×1',                     brand: 'IKEA',     category: 'storage',   qty: 5,  dims: { w: 77, d: 39, h: 41 }, notes: 'NE (1), SE (2 pivotées), NW (1 pivotée), cuisine (1)', glbPath: 'items/kallax etag 77x41 blanc/KALLAX etag 77x41 blanc.glb', photos: ['items/kallax-2x1/kallax-2x1-1.jpg', 'items/kallax-2x1/kallax-2x1-2.jpg', 'items/kallax-2x1/kallax-2x1-3.jpg', 'items/kallax etag 77x41 blanc/KALLAX etag 77x41 blanc_3d_preview.png'] },
  { id: 'kallax-2x2',       name: 'Kallax 2×2',                     brand: 'IKEA',     category: 'storage',   qty: 3,  dims: { w: 77, d: 39, h: 77 }, notes: 'NE (1), cuisine (2)',                                 glbPath: 'items/kallax etag 77x77 blanc/KALLAX etag 77x77 blanc.glb', photos: ['items/kallax-2x2/kallax-2x2-1.jpg', 'items/kallax-2x2/kallax-2x2-2.jpg', 'items/kallax-2x2/kallax-2x2-3.jpg', 'items/kallax etag 77x77 blanc/KALLAX etag 77x77 blanc_3d_preview.png'] },
  { id: 'kallax-1x1',       name: 'Kallax 1×1',                     brand: 'IKEA',     category: 'storage',   qty: 2,  dims: { w: 42, d: 39, h: 41 }, notes: 'NW milieu + haut (pivotées)',                         glbPath: 'items/kallax etag 42x41 blanc/KALLAX etag 42x41 blanc.glb', photos: ['items/kallax-1x1/kallax-1x1-1.jpg', 'items/kallax-1x1/kallax-1x1-2.jpg', 'items/kallax etag 42x41 blanc/KALLAX etag 42x41 blanc_3d_preview.png'] },
  { id: 'meuble-t',          name: 'Bibliothèque (MeubleT)',         brand: '',         category: 'storage',   qty: 1,  dims: { w: 100,  d: 40,   h: 50   }, notes: 'Procédural, mur C' },
  { id: 'drona',             name: 'Boîte DRONA rouge',             brand: 'IKEA',     category: 'storage',   qty: 29, dims: { w: 33,   d: 38,   h: 33   }, notes: 'Dans les Kallax NE/SE/NW/cuisine, Mackapär, meubles SDB et cuisine', glbPath: 'items/dröna/DRÖNA.glb', photos: ['items/drona40249353/drona-1.jpg', 'items/drona40249353/drona-2.jpg', 'items/drona40249353/drona-3.jpg', 'items/drona40249353/drona-4.jpg', 'items/drona40249353/drona-5.jpg', 'items/dröna/DRÖNA_3d_preview.png'], price: '4,99', url: 'https://www.ikea.com/be/fr/p/droena-rangement-tissu-rouge-40249353/' },

  // ── FURNITURE ────────────────────────────────────────────────────────────────
  { id: 'utaker-stack',     name: 'Utåker - Lit empilable (paire)', brand: 'IKEA',     category: 'furniture', qty: 1, dims: { w: 205,  d: 83,   h: 46   }, notes: "Lit empilable IKEA. Les lits peuvent s'empiler mais sont en mode canapé/séparé par défaut, pour faire un lit et un canapé/plan de travail rangement/organisation.", actions: ['bed-toggle', 'bed-sofa'], photos: ['items/utaker-stack/utaker-stack-1.jpg', 'items/utaker-stack/utaker-stack-2.jpg', 'items/utaker-stack/utaker-stack-3.jpg'] },
  { id: 'utaker-lower',     name: 'Utåker - Lit bas',               brand: 'IKEA',     category: 'furniture', qty: 1, dims: { w: 205,  d: 83,   h: 23   }, notes: 'Lit secondaire/bas/Est/Amour. Matelas VESTMARKA 200x80cm.', glbPath: 'items/utåker lit empilable 80x200 pin (bas)/UTÅKER lit empilable 80x200 pin (bas).glb', photos: ['items/utaker-lower/utaker-lower-1.jpg', 'items/utaker-lower/utaker-lower-2.jpg', 'items/utaker-lower/utaker-lower-3.jpg', 'items/utåker lit empilable 80x200 pin (bas)/UTÅKER lit empilable 80x200 pin (bas)_3d_preview.png'] },
  { id: 'utaker-upper',     name: 'Utåker - Lit haut',              brand: 'IKEA',     category: 'furniture', qty: 1, dims: { w: 205,  d: 83,   h: 23   }, notes: 'Lit principal/haut/Ouest. Matelas ÅNNELAND 200x80cm + sur-matelas.', glbPath: 'items/utåker lit empilable 80x200 pin (haut)/UTÅKER lit empilable 80x200 pin (haut).glb', photos: ['items/utaker-upper/utaker-upper-1.jpg', 'items/utaker-upper/utaker-upper-2.jpg', 'items/utaker-upper/utaker-upper-3.jpg', 'items/utåker lit empilable 80x200 pin (haut)/UTÅKER lit empilable 80x200 pin (haut)_3d_preview.png'] },
  { id: 'smorkull-chair',   name: 'Chaise de bureau Smörkull',      brand: 'IKEA',     category: 'furniture', qty: 1, dims: { w: 66,   d: 65,   h: 108  }, notes: 'Chaise de bureau av accoudoirs, Gräsnäs rouge', glbPath: 'items/smörkull/SMÖRKULL.glb', url: 'https://www.ikea.com/fr/fr/p/smoerkull-chaise-de-bureau-av-accoudoirs-graesnaes-rouge-60503437/', photos: ['items/smorkull-chair/smorkull-chair-1.jpg', 'items/smorkull-chair/smorkull-chair-2.jpg', 'items/smorkull-chair/smorkull-chair-3.jpg', 'items/smorkull-chair/smorkull-chair-4.jpg', 'items/smorkull-chair/smorkull-chair-5.jpg', 'items/smorkull-chair/smorkull-chair-6.jpg', 'items/smorkull-chair/smorkull-chair-7.jpg', 'items/smorkull-chair/smorkull-chair-8.jpg', 'items/smorkull-chair/smorkull-chair-9.jpg', 'items/smorkull-chair/smorkull-chair-10.jpg', 'items/smorkull-chair/smorkull-chair-11.jpg', 'items/smörkull/SMÖRKULL_3d_preview.png'] },
  { id: 'raskog-large',     name: 'Desserte RÅSKOG (grande)',       brand: 'IKEA',     category: 'storage', qty: 1, dims: { w: 35,   d: 45,   h: 77   }, notes: 'Roulante, têtes de mannequin dessus', glbPath: 'items/råskog desserte 35x45x77 blanc/RÅSKOG desserte 35x45x77 blanc.glb', photos: ['items/råskog desserte 35x45x77 blanc/RÅSKOG desserte 35x45x77 blanc_3d_preview.png'] },
  { id: 'chest-bench',      name: 'Coffre banc YITAHOME 100 Gal',  brand: 'YITAHOME', category: 'furniture', qty: 1, dims: { w: 122,  d: 55,   h: 62   }, notes: 'Gris, jardin derrière canapé ouest' },
  { id: 'armrest-sofa',     name: 'Canapé de jardin (grand)',       brand: 'Tectake',  category: 'furniture', qty: 1, dims: { w: 61,   d: 157,  h: 89   }, notes: 'Tectake Sintra - Canapé de jardin modulable transformable en lit de jour / transat, résine tressée grise', actions: ['sofa-arm-left', 'sofa-arm-right'], url: 'https://www.amazon.fr/gp/product/B0FFHJ2TVP', photos: ['items/armrest-sofa-gris/armrest-sofa-gris-1.jpg', 'items/armrest-sofa-gris/armrest-sofa-gris-2.jpg', 'items/armrest-sofa-gris/armrest-sofa-gris-3.jpg', 'items/armrest-sofa-gris/armrest-sofa-gris-4.jpg', 'items/armrest-sofa-gris/armrest-sofa-gris-5.jpg', 'items/armrest-sofa-gris/armrest-sofa-gris-6.jpg', 'items/armrest-sofa-gris/armrest-sofa-gris-7.jpg', 'items/armrest-sofa-gris/armrest-sofa-gris-8.jpg'] },
  { id: 'armless-sofa',     name: 'Canapé de jardin (petit)',       brand: '',         category: 'furniture', qty: 1, dims: { w: 60,   d: 100,  h: 100  }, notes: 'Rouge, sans accoudoirs' },
  { id: 'tent-quechua-2sec', name: 'Tente Quechua 2 Seconds Easy 2P', brand: 'Quechua', category: 'furniture', qty: 1, dims: { w: 140,  d: 200,  h: 100  }, notes: 'Pop-up dôme 2 places, version compacte verte (réf 8784754) — procédural' },
  { id: 'vihals-chair',     name: 'Chaise pliante VIHALS',          brand: 'IKEA',    category: 'furniture', qty: 1, dims: { w: 43,   d: 47,   h: 80   }, notes: 'Rouge, pliable (réf 70592744). Action plier/déplier avec animation hinge.', glbPath: 'items/vihals/VIHALS.glb', actions: ['vihals-toggle'], photos: ['items/vihals-chair/vihals-chair-1.jpg', 'items/vihals-chair/vihals-chair-2.jpg', 'items/vihals-chair/vihals-chair-3.jpg', 'items/vihals/VIHALS_3d_preview.png'] },

  // ── TECH ─────────────────────────────────────────────────────────────────────
  { id: 'tv',               name: 'Télévision CHiQ L32H7A',         brand: 'CHiQ',      category: 'tech',     qty: 1, dims: { w: 73,   d: 8,    h: 45   }, notes: '32" (80cm diag) — Android 9 Smart TV, HD, WiFi, BT, Google Assistant, Netflix, Prime Video, 2×HDMI, USB — Classe F — murale, orientée séjour', actions: ['tv-toggle'], photos: ['items/chiq-l32h7a/chiq-l32h7a-1.jpg'] },
  { id: 'mini-pc',          name: 'Mini PC MLLSE G2 Pro',            brand: 'MLLSE',     category: 'tech',     qty: 1, dims: { w: 8.7,  d: 8.7,  h: 3.9  }, notes: 'Intel Twin Lake N150, LPDDR5 12 Go, 512 Go SSD, Wi-Fi 5, BT 5.0 — bleu nuit, bouton rouge', photos: ['items/mllse-g2-pro/mllse-g2-pro-1.jpg', 'items/mllse-g2-pro/mllse-g2-pro-2.jpg', 'items/mllse-g2-pro/mllse-g2-pro-3.jpg', 'items/mllse-g2-pro/mllse-g2-pro-4.jpg', 'items/mllse-g2-pro/mllse-g2-pro-5.jpg', 'items/mllse-g2-pro/mllse-g2-pro-6.jpg'] },
  { id: 'laptop',           name: 'Framework Laptop 13"',           brand: 'Framework', category: 'tech',     qty: 1, dims: { w: 29.7, d: 22.8, h: 1.55 }, notes: 'AMD Ryzen AI 5 340, 2256×1504 13", bureau 2', photos: ['items/framework-laptop13/framework-laptop13-1.jpg', 'items/framework-laptop13/framework-laptop13-2.jpg', 'items/framework-laptop13/framework-laptop13-3.jpg', 'items/framework-laptop13/framework-laptop13-4.jpg', 'items/framework-laptop13/framework-laptop13-5.jpg', 'items/framework-laptop13/framework-laptop13-6.jpg'] },
  { id: 'phone',            name: 'Téléphone OnePlus Nord 4',       brand: 'OnePlus',   category: 'tech',     qty: 1, dims: { w: 7.5,  d: 16.2, h: 0.8  }, notes: 'Coque rouge, bureau 2', photos: ['items/oneplus-nord4/oneplus-nord4-2.jpg', 'items/oneplus-nord4/oneplus-nord4-3.jpg', 'items/oneplus-nord4/oneplus-nord4-4.jpg', 'items/oneplus-nord4/oneplus-nord4-5.jpg'] },
  { id: 'scooter',          name: 'Trottinette Xiaomi 4',           brand: 'Xiaomi',    category: 'tech',     qty: 1, dims: { w: 56.5, d: 119.2, h: 127.1 }, notes: 'Guidon déplié, couloir — Acheté le 08/07/2025 — Darty', glbPath: 'items/xiaomi-scooter4/xiaomi-scooter4.glb', photos: ['items/xiaomi-scooter4/xiaomi-scooter4-1.jpg', 'items/xiaomi-scooter4/xiaomi-scooter4_3d_preview.png'] },
  { id: 'air-performer',    name: 'Air Performer AMF870/15',        brand: 'Philips',   category: 'tech',     qty: 1, dims: { w: 32.5, d: 32.5, h: 106.4 }, notes: 'Purificateur/ventilateur bladeless, 70 m², Wi-Fi', photos: ['items/philips-amf870/philips-amf870-1.avif', 'items/philips-amf870/philips-amf870-2.avif', 'items/philips-amf870/philips-amf870-3.avif', 'items/philips-amf870/philips-amf870-4.avif', 'items/philips-amf870/philips-amf870-5.avif', 'items/philips-amf870/philips-amf870-6.avif'] },
  { id: 'vacuum-cleaner',   name: 'Aspirateur balai X-Force Flex RH2079WO', brand: 'Rowenta', category: 'tech', qty: 1, dims: { w: 24.8, d: 23.4, h: 112 }, notes: 'Sans fil 18V, 100 AW, 30 min autonomie, rouge | Acheté le 14/02/2026 — garantie 2 ans (jusqu\'au 14/02/2028)', glbPath: 'items/rowenta-rh2079wo/rowenta-rh2079wo.glb', photos: ['items/rowenta-rh2079wo/rowenta-rh2079wo-1.jpg', 'items/rowenta-rh2079wo/rowenta-rh2079wo-2.jpg', 'items/rowenta-rh2079wo/rowenta-rh2079wo-3.jpg', 'items/rowenta-rh2079wo/rowenta-rh2079wo-4.jpg', 'items/rowenta-rh2079wo/rowenta-rh2079wo_3d_preview.png'] },
  { id: 'sony-srs-xb33',    name: 'Enceinte Sony SRS-XB33',         brand: 'Sony',      category: 'tech',     qty: 1, dims: { w: 24.6, d: 10.6, h: 9.7  }, notes: 'EXTRA BASS Bluetooth, IPX5, 24h autonomie, rouge Fusion — jardin/couloir', glbPath: 'items/jbl-charge3/jbl-charge3.glb', photos: ['items/sony-srs-xb33/sony-srs-xb33-1.jpg', 'items/sony-srs-xb33/sony-srs-xb33-2.jpg', 'items/sony-srs-xb33/sony-srs-xb33-3.jpg', 'items/sony-srs-xb33/sony-srs-xb33-4.jpg', 'items/sony-srs-xb33/sony-srs-xb33-5.jpg', 'items/jbl-charge3/jbl-charge3_3d_preview.png'] },
  { id: 'google-nest-mini', name: 'Google Nest Mini (2ᵉ gén.)',     brand: 'Google',    category: 'tech',     qty: 1, dims: { w: 9.8,  d: 9.8,  h: 4.2  }, notes: 'Enceinte connectée Wi-Fi — mur Ouest (A), bordure miroirs nord, à 1.05 m du sol', glbPath: 'items/google-nest/google-nest.glb', url: 'https://store.google.com/fr/product/google_nest_mini', actions: ['nestMini'] },
  { id: 'tyco-rebound',     name: 'Tyco R/C Rebound 4×4 Jet Turbo', brand: 'Tyco',      category: 'tech',     qty: 1, dims: { w: 20,   d: 25,   h: 14   }, notes: 'Voiture RC monster truck 6.0V — drive on 2 sides (sports car / pickup), 9 fonctions radio. Procédural. Souvenir d\'enfance, premier objet électronique démonté pour analyse.', url: 'https://tycocollectors.com/models/1994-tyco-rebound-4x4-european/', photos: ['items/tyco-rebound/tyco-rebound-1.png', 'items/tyco-rebound/tyco-rebound-2.png', 'items/tyco-rebound/tyco-rebound-3.png', 'items/tyco-rebound/tyco-rebound-4.png'] },
  { id: 'matter-hub',       name: 'Hub Matter',                     brand: '',          category: 'tech',     qty: 1, dims: { w: 9,    d: 9,    h: 2.2  }, notes: 'Passerelle domotique Matter — 90×90×22 mm, blanc mat, RESET + USB Type-C + RJ45 LAN. Procédural.', photos: ['items/matter-hub/matter-hub-1.png'] },
  { id: 'electric-racket',  name: 'Tapette à mouche électrique',    brand: '',          category: 'tech',     qty: 1, dims: { w: 24,   d: 2,    h: 43   }, notes: 'Tapette anti-moustique/mouche électrique', glbPath: 'items/electric-racket/electric-racket.glb' },
  { id: 'linky',            name: 'Compteur Linky',                 brand: 'Enedis',    category: 'tech',     qty: 1, dims: { w: 12,   d: 7.1,  h: 20   }, notes: 'Compteur électrique communicant Linky G3 — boîtier blanc, façade vert anis, écran LCD, boutons +/−, DEL témoin, logo enedis. Monté sur gaine 25.5×6.5cm dans le couloir, mur est, à 6cm de la face couloir du mur sud séjour, bas à 170cm du sol.', glbPath: 'items/compteur-linky/compteur-linky.glb', photos: ['items/compteur-linky/compteur-linky_3d_preview.png'], url: 'https://www.enedis.fr/presse/avec-linky-la-sobriete-energetique-portee-de-main' },
  { id: 'laser-distancemaster', name: 'Télémètre laser DistanceMaster Compact 25m', brand: 'Laserliner', category: 'tech', qty: 1, dims: { w: 4.2, d: 2.5, h: 10 }, notes: 'Télémètre laser 25 m — Laserliner DistanceMaster Compact (réf 080.948A) — 100×42×25 mm, 63 g, ABS gris foncé/noir + bumpers caoutchouc nervurés, façade blanche, logo orange Laserliner, LCD multi-lignes (max/min/dernière), 4 boutons (DIST/MIN-MAX orange, mode aire/volume, mode mesure indirecte, C/OFF), précision ±3 mm, plage 0.2–25 m, 2× pile AAA — Leroy Merlin. Procédural.', url: 'https://www.leroymerlin.fr/produits/telemetre-laser-25m-laserliner-distancemaster-compact-70189924.html', photos: ['items/distancemaster-compact/distancemaster-compact-1.png'] },

  // ── KITCHEN ──────────────────────────────────────────────────────────────────
  { id: 'counter',          name: 'Plan de travail',                brand: '',         category: 'kitchen',   qty: 1, dims: { w: 100,  d: 60,   h: 3    }, notes: 'Blanc, avec trou évier' },
  { id: 'cabinet-wood',     name: 'METOD 40×60×80 + RINGHULT + KALLROR', brand: 'IKEA', category: 'storage', qty: 1, dims: { w: 40, d: 60, h: 80 }, notes: 'Blanc + porte gris brillant + poignée inox 213mm, meuble sous évier', glbPath: 'items/metod rangement blanc 40x60x80 cm/METOD Rangement blanc 40x60x80 cm.glb', actions: ['cabinet-toggle'], photos: ['items/cabinet-wood/cabinet-wood-1.jpg', 'items/metod rangement blanc 40x60x80 cm/METOD Rangement blanc 40x60x80 cm_3d_preview.png'] },
  { id: 'ringhult-door',    name: 'RINGHULT Porte 40×80 gris brillant', brand: 'IKEA',  category: 'kitchen',   qty: 1, dims: { w: 40,   d: 2,    h: 80   }, notes: 'Porte placard cuisine sous évier', glbPath: 'items/ringhult porte brillant gris clair 40x80 cm/RINGHULT Porte brillant gris clair 40x80 cm.glb', photos: ['items/ringhult-door/ringhult-door-1.jpg', 'items/ringhult-door/ringhult-door-2.jpg', 'items/ringhult-door/ringhult-door-3.jpg', 'items/ringhult porte brillant gris clair 40x80 cm/RINGHULT Porte brillant gris clair 40x80 cm_3d_preview.png'] },
  { id: 'kallror',          name: 'KALLROR Poignée inox 213 mm',    brand: 'IKEA',     category: 'decor',   qty: 3, dims: { w: 21.3, d: 3.5,  h: 3.5  }, notes: 'Acier inoxydable, meubles cuisine + SDB (×3)', glbPath: 'items/kallror poignée acier inoxydable 213 mm/KALLROR Poignée acier inoxydable 213 mm.glb', photos: ['items/kallror/kallror-1.jpg', 'items/kallror/kallror-2.jpg', 'items/kallror/kallror-3.jpg', 'items/kallror poignée acier inoxydable 213 mm/KALLROR Poignée acier inoxydable 213 mm_3d_preview.png'] },
  { id: 'fridge',           name: 'LAGAN Réfrigérateur 113 l',      brand: 'IKEA',     category: 'kitchen',   qty: 1, dims: { w: 60,   d: 63,   h: 172  }, notes: 'Blanc, comp. congélateur', glbPath: 'items/lagan réfrigérateur av comp congélateur indépendant-blanc 97-16 l/LAGAN Réfrigérateur av comp congélateur indépendant-blanc 97-16 l.glb', actions: ['fridge-toggle'], photos: ['items/fridge/fridge-1.jpg', 'items/fridge/fridge-2.jpg', 'items/fridge/fridge-3.jpg', 'items/lagan réfrigérateur av comp congélateur indépendant-blanc 97-16 l/LAGAN Réfrigérateur av comp congélateur indépendant-blanc 97-16 l_3d_preview.png'] },
  { id: 'sink-boholmen',    name: 'Évier BOHOLMEN 1 bac',          brand: 'IKEA',     category: 'kitchen',   qty: 1, dims: { w: 30,   d: 47,   h: 15   }, notes: 'Inox, avec robinet', glbPath: 'items/boholmen évier 47x30 cm/BOHOLMEN Évier 47x30 cm.glb', photos: ['items/sink-boholmen/sink-boholmen-1.jpg', 'items/sink-boholmen/sink-boholmen-2.jpg', 'items/sink-boholmen/sink-boholmen-3.jpg', 'items/boholmen évier 47x30 cm/BOHOLMEN Évier 47x30 cm_3d_preview.png'] },
  { id: 'stove',            name: 'Plaque VÄLBILDAD',               brand: 'IKEA',     category: 'kitchen',   qty: 1, dims: { w: 29,   d: 52,   h: 5    }, notes: 'Induction', glbPath: 'items/välbildad/VÄLBILDAD.glb', photos: ['items/stove/stove-1.jpg', 'items/stove/stove-2.jpg', 'items/stove/stove-3.jpg', 'items/välbildad/VÄLBILDAD_3d_preview.png'] },
  { id: 'ninja-sp101',      name: 'Mini four Foodi Flip SP101EU',   brand: 'Ninja',    category: 'kitchen',   qty: 1, dims: { w: 51,   d: 37,   h: 19.5 }, notes: '8-en-1, inox brossé, porte vitrée + flip-back', actions: ['ninja-toggle'] },
  { id: 'moules-airfryer',  name: 'Moules jetables papier air fryer ×120', brand: 'Kitchen Cook', category: 'kitchen', qty: 120, dims: { w: 20, d: 20, h: 15 }, notes: 'Papier cuisson pour air fryer | Acheté le 14/02/2026' },
  { id: 'freezer',          name: 'Congélateur CHIQ CSD46D4E',     brand: 'CHIQ',     category: 'kitchen',   qty: 1, dims: { w: 45,   d: 47,   h: 50   }, notes: 'Noir, niche séjour', glbPath: 'items/tillreda réfrigérateur indépendant-blanc 43 l/TILLREDA Réfrigérateur indépendant-blanc 43 l.glb', photos: ['items/tillreda réfrigérateur indépendant-blanc 43 l/TILLREDA Réfrigérateur indépendant-blanc 43 l_3d_preview.png'], actions: ['freezer-toggle'] },

  // Vaisselle / couverts
  { id: 'fourchette',       name: 'Fourchette',                     brand: '',         category: 'kitchen',   qty: 6,  dims: { w: 2.5,  d: 20,   h: 1.2  }, notes: 'Tiroir cuisine' },
  { id: 'couteau',          name: 'Couteau de table',               brand: '',         category: 'kitchen',   qty: 6,  dims: { w: 1.8,  d: 23,   h: 1.2  }, notes: 'Tiroir cuisine' },
  { id: 'grande-cuillere',  name: 'Grande cuillère',                brand: '',         category: 'kitchen',   qty: 6,  dims: { w: 3.5,  d: 20,   h: 1.5  }, notes: 'Tiroir cuisine — cuillère à soupe' },
  { id: 'petite-cuillere',  name: 'Petite cuillère',                brand: '',         category: 'kitchen',   qty: 6,  dims: { w: 2.5,  d: 13,   h: 1.0  }, notes: 'Tiroir cuisine — cuillère à café' },
  { id: 'assiette',         name: 'Assiette',                       brand: '',         category: 'kitchen',   qty: 6,  dims: { w: 26,   d: 26,   h: 2    }, notes: 'Placard cuisine — plate plate Ø 26 cm' },
  { id: 'mug-set',          name: 'Mug',                            brand: '',         category: 'kitchen',   qty: 6,  dims: { w: 9,    d: 12,   h: 9.5  }, notes: 'Placard cuisine — anse incluse' },
  { id: 'trash-bin',        name: 'Poubelle TATAY Smart Deco 25L',  brand: 'TATAY',    category: 'kitchen',   qty: 1,  dims: { w: 26,   d: 36,   h: 47   }, notes: 'Effet bois, pédale, B0BJQS1P6C', actions: ['bin-toggle'] },

  // ── BATHROOM ─────────────────────────────────────────────────────────────────
  { id: 'vathult-350',           name: 'VÅTHULT éclairage LED miroir 350 mm alu', brand: 'IKEA', category: 'lighting', qty: 1, dims: { w: 35, d: 4, h: 4 }, notes: 'Au-dessus miroir vasque SDB', glbPath: 'items/våthult éclairage led élément-miroir 350 mm alu/VÅTHULT éclairage LED élément-miroir 350 mm alu.glb', photos: ['items/vathult-350/vathult-350-1.jpg', 'items/vathult-350/vathult-350-2.jpg', 'items/vathult-350/vathult-350-3.jpg', 'items/våthult éclairage led élément-miroir 350 mm alu/VÅTHULT éclairage LED élément-miroir 350 mm alu_3d_preview.png'] },
  { id: 'bathroom-cabinet-west', name: 'METOD 40×37×60 + RINGHULT + KALLROR (ouest)', brand: 'IKEA', category: 'storage', qty: 1, dims: { w: 40, d: 37, h: 60 }, notes: 'Blanc + porte gris brillant + poignée inox 213mm', glbPath: 'items/metod rangement mural blanc 40x37x60 cm/METOD Rangement mural blanc 40x37x60 cm.glb', actions: ['cbn-west-toggle'], photos: ['items/bathroom-cabinet-west/bathroom-cabinet-west-1.jpg', 'items/metod rangement mural blanc 40x37x60 cm/METOD Rangement mural blanc 40x37x60 cm_3d_preview.png'] },
  { id: 'bathroom-cabinet-east', name: 'METOD 40×37×60 + RINGHULT + KALLROR (est)',  brand: 'IKEA', category: 'storage', qty: 1, dims: { w: 40, d: 37, h: 60 }, notes: 'Blanc + porte gris brillant + poignée inox 213mm', glbPath: 'items/metod rangement mural blanc 40x37x60 cm/METOD Rangement mural blanc 40x37x60 cm.glb', actions: ['cbn-east-toggle'], photos: ['items/bathroom-cabinet-east/bathroom-cabinet-east-1.jpg', 'items/metod rangement mural blanc 40x37x60 cm/METOD Rangement mural blanc 40x37x60 cm_3d_preview.png'] },
  { id: 'ringhult-door-sdb',    name: 'RINGHULT Porte 40×60 gris brillant', brand: 'IKEA', category: 'decor', qty: 2, dims: { w: 40, d: 2, h: 60 }, notes: 'Porte meubles SDB ouest et est', glbPath: 'items/ringhult porte brillant gris clair 40x60 cm/RINGHULT Porte brillant gris clair 40x60 cm.glb', photos: ['items/ringhult-door-sdb/ringhult-door-sdb-1.jpg', 'items/ringhult-door-sdb/ringhult-door-sdb-2.jpg', 'items/ringhult-door-sdb/ringhult-door-sdb-3.jpg', 'items/ringhult porte brillant gris clair 40x60 cm/RINGHULT Porte brillant gris clair 40x60 cm_3d_preview.png'] },
  { id: 'tisken-panier',        name: 'TISKEN Panier ventouse blanc',       brand: 'IKEA', category: 'bathroom', qty: 2, dims: { w: 22, d: 10, h: 12 }, notes: 'Sur miroir vasque SDB, mi-hauteur, bord gauche et droit', glbPath: 'items/tisken panier à ventouse blanc/TISKEN Panier à ventouse blanc.glb', photos: ['items/tisken-panier/tisken-panier-1.jpg', 'items/tisken-panier/tisken-panier-2.jpg', 'items/tisken-panier/tisken-panier-3.jpg', 'items/tisken panier à ventouse blanc/TISKEN Panier à ventouse blanc_3d_preview.png'] },
  { id: 'shower',           name: 'Receveur de douche 90×90',       brand: '',         category: 'bathroom',  qty: 1, dims: { w: 90,   d: 90,   h: 15   }, notes: 'Shower tray + VALLAMOSSE barre douchette + mitigeur thermostatique', glbPath: 'items/shower/shower.glb', photos: ['items/shower/shower_3d_preview.png'] },
  { id: 'toilet',           name: 'WC President Horizontal Outlet', brand: '',         category: 'bathroom',  qty: 1, dims: { w: 40,   d: 70,   h: 80   }, notes: 'Sortie horizontale', glbPath: 'items/president-toilet/president-toilet.glb', photos: ['items/president-toilet/president-toilet_3d_preview.png'], actions: ['wc-lid-toggle', 'wc-seat-toggle', 'wc-flush'] },
  { id: 'vasque-sdb',       name: 'HAVBÄCK-ORRSJÖN 62×49×69 cm',   brand: 'IKEA',     category: 'bathroom',  qty: 1, dims: { w: 62,   d: 49,   h: 69   }, notes: 'Meuble avec tiroirs, vasque, mitigeur blanc', glbPath: 'items/havbäck - orrsjön meuble avec tiroirs-vasque-mitigeur blanc 62x49x69 cm/HAVBÄCK - ORRSJÖN Meuble avec tiroirs-vasque-mitigeur blanc 62x49x69 cm.glb', photos: ['items/vasque-sdb/vasque-sdb-1.jpg', 'items/vasque-sdb/vasque-sdb-2.jpg', 'items/vasque-sdb/vasque-sdb-3.jpg', 'items/havbäck - orrsjön meuble avec tiroirs-vasque-mitigeur blanc 62x49x69 cm/HAVBÄCK - ORRSJÖN Meuble avec tiroirs-vasque-mitigeur blanc 62x49x69 cm_3d_preview.png'] },
  { id: 'water-heater',     name: 'Ballon eau chaude 100L',         brand: '',         category: 'bathroom',  qty: 1, dims: { w: 40,   d: 40,   h: 80   }, notes: 'Cylindrique, vertical' },
  { id: 'oral-b-toothbrush',      name: 'Brosse à dents électrique Oral-B', brand: 'Oral-B', category: 'bathroom', qty: 2, dims: { w: 2.5, d: 3.6, h: 21.6 }, notes: 'Brosse rechargeable avec socle chargeur, SDB vasque', glbPath: 'items/oral-b-vitality-red/oral-b-vitality-red.glb', photos: ['items/oral-b-vitality-red/oral-b-vitality-red_3d_preview.png'] },
  { id: 'oral-b-toothbrush-head', name: 'Tête de brosse à dents Oral-B',    brand: 'Oral-B', category: 'bathroom', qty: 6, dims: { w: 1.6, d: 2.1, h: 7.2 }, notes: 'Recharge brosse électrique', glbPath: 'items/oral-b-toothbrush-head/oral-b-toothbrush-head.glb' },
  { id: 'philips-mg9558',   name: 'Tondeuse Philips MG9558/15 Series 9000', brand: 'Philips', category: 'bathroom', qty: 1, dims: { w: 4.5, d: 4.5, h: 22 }, notes: 'Multi-groomer 13 accessoires — barbe, corps, visage — IPX7, 120 min autonomie, 1h charge — SDB vasque' },
  { id: 'bathtub',          name: 'Baignoire',                      brand: '',         category: 'bathroom',  qty: 1, dims: { w: 150,  d: 70,   h: 50   }, notes: 'Coins arrondis, jardin' },

  // ── CLOTHING ─────────────────────────────────────────────────────────────────
  { id: 'salopette',        name: 'Salopette noire',                brand: '',         category: 'clothing',  qty: 1, dims: { w: 6,   d: 40,  h: 150 }, notes: 'Noire, suspendue', glbPath: 'characters/clothing/salopette-noir.glb' },
  { id: 'baseball-cap',     name: 'Casquette baseball',             brand: '',         category: 'clothing',  qty: 3, dims: { w: 20,  d: 25,  h: 15  }, notes: '3 casquettes rouges sur portant', glbPath: 'characters/accessories/baseball_cap.glb' },
  { id: 'backpack',         name: 'Sac à dos',                      brand: '',         category: 'clothing',  qty: 1, dims: { w: 40,  d: 17,  h: 43  }, notes: 'Rouge procédural, mur A' },
  { id: 'sneaker',          name: 'Sneakers',                       brand: '',         category: 'clothing',  qty: 2, dims: { w: 30,  d: 12,  h: 12  }, notes: 'Paire, mur A niche', glbPath: 'characters/accessories/sneaker.glb' },
  { id: 'jordan-hex-mule', name: 'Jordan Hex Mule SP',             brand: 'Nike/Jordan', category: 'clothing', qty: 2, dims: { w: 20.4, d: 28.5, h: 4.8 }, notes: 'Paire, University Red, taille 44.5, FJ0603-600' },
  { id: 'summer-outdoor-boot', name: "Baskets bottes d'été",       brand: 'Temu',        category: 'clothing', qty: 2, dims: { w: 22,   d: 30,   h: 19  }, notes: "Paire, bottes d'extérieur fermeture à crochets, rouge", url: 'https://www.temu.com/fr/chaussures-d%C3%A9contract%C3%A9es-et-confortables-pour-hommes-bottes-d-ext%C3%A9rieur-fermeture-%C3%A0-crochets-l%C3%A9g%C3%A8res-polyvalentes-et-tendance-g-601102843756024.html', photos: ['items/summer-boot/summer-boot-1.png', 'items/summer-boot/summer-boot-2.png', 'items/summer-boot/summer-boot-3.png'] },
  { id: 'winter-outdoor-boot', name: "Baskets bottes d'hiver (lourde)", brand: 'Temu',        category: 'clothing', qty: 2, dims: { w: 22.5, d: 30.5, h: 20  }, notes: "Paire de bottes d'extérieur lourdes pour l'hiver, semelle crantée isolée et col fourrure, rouge", url: '', photos: ['items/winter-boot/winter-boot-1.png', 'items/winter-boot/winter-boot-2.png', 'items/winter-boot/winter-boot-3.png'] },
  { id: 'tshirt-noir-L',   name: 'T-shirt noir (pack ×6) taille L', brand: 'Temu',       category: 'clothing', qty: 6, dims: { w: 30, d: 20, h: 12 }, notes: 'Pack 6 t-shirts noirs, L — goods_id 601100392589571', photos: ['items/tshirt-noir/tshirt-noir-1.jpg', 'items/tshirt-noir/tshirt-noir-2.jpg', 'items/tshirt-noir/tshirt-noir-3.jpg', 'items/tshirt-noir/tshirt-noir-4.jpg', 'items/tshirt-noir/tshirt-noir-5.jpg', 'items/tshirt-noir/tshirt-noir-6.jpg', 'items/tshirt-noir/tshirt-noir-7.jpg', 'items/tshirt-noir/tshirt-noir-8.jpg', 'items/tshirt-noir/tshirt-noir-9.jpg', 'items/tshirt-noir/tshirt-noir-10.jpg', 'items/tshirt-noir/tshirt-noir-11.jpg', 'items/tshirt-noir/tshirt-noir-12.jpg', 'items/tshirt-noir/tshirt-noir-13.jpg'] },
  { id: 'tshirt-noir-XL',  name: 'T-shirt noir (pack ×6) taille XL', brand: 'Temu',      category: 'clothing', qty: 6, dims: { w: 30, d: 20, h: 12 }, notes: 'Pack 6 t-shirts noirs, XL — goods_id 601100392589571', photos: ['items/tshirt-noir/tshirt-noir-1.jpg', 'items/tshirt-noir/tshirt-noir-2.jpg', 'items/tshirt-noir/tshirt-noir-3.jpg', 'items/tshirt-noir/tshirt-noir-4.jpg', 'items/tshirt-noir/tshirt-noir-5.jpg', 'items/tshirt-noir/tshirt-noir-6.jpg', 'items/tshirt-noir/tshirt-noir-7.jpg', 'items/tshirt-noir/tshirt-noir-8.jpg', 'items/tshirt-noir/tshirt-noir-9.jpg', 'items/tshirt-noir/tshirt-noir-10.jpg', 'items/tshirt-noir/tshirt-noir-11.jpg', 'items/tshirt-noir/tshirt-noir-12.jpg', 'items/tshirt-noir/tshirt-noir-13.jpg'] },
  { id: 'calecon-rouge',   name: 'Caleçon rouge',                   brand: '',            category: 'clothing', qty: 20, dims: { w: 20, d: 15, h: 2  }, notes: '20 caleçons rouges' },
  { id: 'chaussette-rouge', name: 'Chaussettes fines rouges',       brand: '',            category: 'clothing', qty: 10, dims: { w: 10, d: 8,  h: 2  }, notes: '10 paires, chaussettes fines' },

  // ── DECOR ─────────────────────────────────────────────────────────────────────

  { id: 'mirror-nissedal-a',name: 'Miroir Nissedal 40×150 (mur A)', brand: 'IKEA',     category: 'bathroom',     qty: 4, dims: { w: 40,  d: 5,   h: 150 }, notes: 'Mur A, Reflector', glbPath: 'items/nissedal miroir 40x150 noir/NISSEDAL miroir 40x150 noir.glb', photos: ['items/mirror-nissedal-a/mirror-nissedal-a-1.jpg', 'items/mirror-nissedal-a/mirror-nissedal-a-2.jpg', 'items/mirror-nissedal-a/mirror-nissedal-a-3.jpg', 'items/nissedal miroir 40x150 noir/NISSEDAL miroir 40x150 noir_3d_preview.png'] },


  { id: 'mug',              name: 'Mug rouge',                      brand: '',         category: 'decor',     qty: 1, dims: { w: 8,   d: 8,   h: 9.5 }, notes: 'Bureau 2' },
  { id: 'mannequin-head',   name: 'Tête de mannequin',              brand: '',         category: 'decor',     qty: 3, dims: { w: 41,  d: 22,  h: 45  }, notes: '1 Raskog grande, 1 Kallax NW, 1 LACK' },
  { id: 'lamp-ola',         name: 'Lampe OLA',                      brand: 'IKEA',     category: 'lighting',     qty: 1, dims: { w: 30,  d: 30,  h: 120 }, notes: 'Sur pied, meuble TV', glbPath: 'items/lamp-ola/lamp-ola.glb', photos: ['items/lamp-ola/lamp-ola-1.jpg', 'items/lamp-ola/lamp-ola-2.jpg', 'items/lamp-ola/lamp-ola-3.jpg', 'items/lamp-ola/lamp-ola_3d_preview.png'] },

  { id: 'potted-palm',      name: 'Palmier en pot',                 brand: '',         category: 'decor',     qty: 1, dims: { w: 60,  d: 60,  h: 150 }, notes: 'Jardin, entre canapé et desserte', glbPath: 'items/plant-monstera/potted_palm.glb', photos: ['items/plant-monstera/potted_palm_3d_preview.png'] },
  { id: 'palm-leaf',        name: 'Feuille de palmier artificielle', brand: '',        category: 'decor',     qty: 1, dims: { w: 40,  d: 40,  h: 80  }, notes: 'Plante artificielle Palm_Leaf1', glbPath: 'items/plant-monstera/plant-monstera.glb', photos: ['items/plant-monstera/plant-monstera_3d_preview.png'] },
  { id: 'jogging-suit',     name: 'Jogging suit',                   brand: '',         category: 'clothing',  qty: 1, dims: { w: 40,  d: 20,  h: 170 }, notes: 'Jardin, près de la baignoire', glbPath: 'characters/clothing/realistic_human_cloths.glb' },

  // ── CONSOMABLES ───────────────────────────────────────────────────────────────
  // Produits du quotidien rachetés régulièrement (1×/an minimum)
  { id: 'cons-papier-toilette', name: 'Papier toilette (pack 12)',  brand: '',         category: 'consumable', qty: 1, dims: { w: 40, d: 20, h: 22 }, frequency: 'mensuel',    stock: 8,  location: 'Placard SDB',     notes: 'Pack de 12 rouleaux' },
  { id: 'cons-sopalin',         name: 'Sopalin (pack 4)',           brand: '',         category: 'consumable', qty: 1, dims: { w: 40, d: 22, h: 25 }, frequency: 'mensuel',    stock: 3,  location: 'Placard cuisine', notes: 'Essuie-tout pack 4 rouleaux' },
  { id: 'cons-mouchoirs',       name: 'Mouchoirs (étui 10)',        brand: '',         category: 'consumable', qty: 1, dims: { w: 22, d: 12, h: 8  }, frequency: 'mensuel',    stock: 5,  location: 'Placard SDB',     notes: 'Étui 10 paquets' },
  { id: 'cons-dentifrice',      name: 'Dentifrice 75 ml',           brand: 'Signal',   category: 'consumable', qty: 1, dims: { w: 18, d: 5,  h: 4  }, frequency: 'mensuel',    stock: 2,  location: 'SDB vasque',      notes: 'Tube' },
  { id: 'cons-tete-brosse-elec', name: 'Tête de brosse à dents électrique', brand: '', category: 'consumable', qty: 1, dims: { w: 2.5, d: 2.5, h: 8.5 }, frequency: 'trimestriel', stock: 4, location: 'SDB vasque',      notes: 'Recharge brosse à dents électrique — changer tous les 3 mois' },
  { id: 'cons-savon',           name: 'Savon liquide 250 ml',       brand: '',         category: 'consumable', qty: 1, dims: { w: 6,  d: 6,  h: 18 }, frequency: 'mensuel',    stock: 1,  location: 'SDB vasque',      notes: 'Distributeur TACKAN' },
  { id: 'cons-shampoing',       name: 'Shampoing 400 ml',           brand: '',         category: 'consumable', qty: 1, dims: { w: 7,  d: 7,  h: 22 }, frequency: 'mensuel',    stock: 1,  location: 'SDB douche',      notes: 'Flacon' },
  { id: 'cons-creme-peau',      name: 'Crème pour la peau',         brand: '',         category: 'consumable', qty: 1, dims: { w: 7,  d: 4,  h: 15 }, frequency: 'mensuel',    stock: 1,  location: 'SDB vasque',      notes: 'Hydratante visage/corps' },
  { id: 'cons-lessive',         name: 'Lessive 3 L',                brand: '',         category: 'consumable', qty: 1, dims: { w: 24, d: 14, h: 28 }, frequency: 'trimestriel', stock: 1, location: 'Placard SDB',     notes: 'Bidon liquide' },
  { id: 'cons-liquide-vaisselle', name: 'Liquide vaisselle 1 L',    brand: '',         category: 'consumable', qty: 1, dims: { w: 8,  d: 6,  h: 28 }, frequency: 'mensuel',    stock: 1,  location: 'Cuisine évier',   notes: 'Flacon' },
  { id: 'cons-pizza',           name: 'Pizza surgelée',             brand: '',         category: 'consumable', qty: 4, dims: { w: 30, d: 30, h: 3  }, frequency: 'hebdo',      stock: 4,  location: 'Congélateur',     notes: 'Pizza 4 fromages / margherita' },
  { id: 'cons-pates',           name: 'Pâtes 500 g',                brand: '',         category: 'consumable', qty: 3, dims: { w: 8,  d: 6,  h: 25 }, frequency: 'hebdo',      stock: 3,  location: 'Placard cuisine', notes: 'Penne / spaghetti / fusilli' },
  { id: 'cons-riz',             name: 'Riz 1 kg',                   brand: '',         category: 'consumable', qty: 1, dims: { w: 14, d: 8,  h: 22 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Basmati / long grain' },
  { id: 'cons-lait',            name: 'Lait 1 L',                   brand: '',         category: 'consumable', qty: 2, dims: { w: 7,  d: 7,  h: 23 }, frequency: 'hebdo',      stock: 2,  location: 'Frigo',           notes: 'Brique UHT demi-écrémé' },
  { id: 'cons-beurre',          name: 'Beurre 250 g',               brand: '',         category: 'consumable', qty: 1, dims: { w: 11, d: 7,  h: 5  }, frequency: 'mensuel',    stock: 1,  location: 'Frigo',           notes: 'Plaquette demi-sel' },
  { id: 'cons-oeufs',           name: 'Œufs (boîte 6)',             brand: '',         category: 'consumable', qty: 1, dims: { w: 17, d: 11, h: 8  }, frequency: 'hebdo',      stock: 1,  location: 'Frigo',           notes: 'Bio plein air' },
  { id: 'cons-fromage',         name: 'Fromage râpé 200 g',         brand: '',         category: 'consumable', qty: 1, dims: { w: 18, d: 12, h: 4  }, frequency: 'hebdo',      stock: 1,  location: 'Frigo',           notes: 'Emmental / gruyère' },
  { id: 'cons-pain',            name: 'Pain (baguette)',            brand: '',         category: 'consumable', qty: 1, dims: { w: 65, d: 6,  h: 6  }, frequency: 'hebdo',      stock: 1,  location: 'Cuisine plan',    notes: 'Tradition' },
  { id: 'cons-cafe',            name: 'Café moulu 250 g',           brand: '',         category: 'consumable', qty: 1, dims: { w: 11, d: 6,  h: 16 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Arabica' },
  { id: 'cons-huile',           name: "Huile d'olive 1 L",          brand: '',         category: 'consumable', qty: 1, dims: { w: 9,  d: 9,  h: 30 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Vierge extra' },
  { id: 'cons-sel',             name: 'Sel 1 kg',                   brand: '',         category: 'consumable', qty: 1, dims: { w: 12, d: 6,  h: 18 }, frequency: 'annuel',     stock: 1,  location: 'Placard cuisine', notes: 'Fin / gros' },
  { id: 'cons-poivre',          name: 'Poivre (moulin)',            brand: '',         category: 'consumable', qty: 1, dims: { w: 5,  d: 5,  h: 15 }, frequency: 'annuel',     stock: 1,  location: 'Placard cuisine', notes: 'Moulin réutilisable' },
  { id: 'cons-sucre',           name: 'Sucre 1 kg',                 brand: '',         category: 'consumable', qty: 1, dims: { w: 14, d: 8,  h: 18 }, frequency: 'trimestriel', stock: 1, location: 'Placard cuisine', notes: 'Blanc en poudre' },
  { id: 'cons-farine',          name: 'Farine 1 kg',                brand: '',         category: 'consumable', qty: 1, dims: { w: 16, d: 10, h: 22 }, frequency: 'trimestriel', stock: 1, location: 'Placard cuisine', notes: 'T55' },
  { id: 'cons-nutella',         name: 'Nutella 400 g',              brand: 'Ferrero',  category: 'consumable', qty: 1, dims: { w: 9,  d: 9,  h: 12 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Pot' },
  { id: 'cons-chocolat',        name: 'Chocolat (tablette)',        brand: '',         category: 'consumable', qty: 2, dims: { w: 17, d: 8,  h: 1  }, frequency: 'hebdo',      stock: 2,  location: 'Placard cuisine', notes: 'Noir 70%' },
  { id: 'cons-herbes-provence', name: 'Herbes de Provence',         brand: '',         category: 'consumable', qty: 1, dims: { w: 5,  d: 5,  h: 10 }, frequency: 'annuel',     stock: 1,  location: 'Placard cuisine', notes: 'Pot mélange séché' },
  { id: 'cons-ketchup',         name: 'Ketchup 560 g',              brand: 'Heinz',    category: 'consumable', qty: 1, dims: { w: 7,  d: 7,  h: 23 }, frequency: 'mensuel',    stock: 1,  location: 'Frigo',           notes: 'Bouteille squeeze' },
  { id: 'cons-mayo',            name: 'Mayonnaise 470 ml',          brand: '',         category: 'consumable', qty: 1, dims: { w: 7,  d: 7,  h: 20 }, frequency: 'mensuel',    stock: 1,  location: 'Frigo',           notes: 'Bouteille squeeze' },
  { id: 'cons-olives',          name: 'Olives sans noyau 200 g',    brand: '',         category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 10 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Bocal vert ou noir' },
  { id: 'cons-saucisson',       name: 'Saucisson sec',              brand: '',         category: 'consumable', qty: 1, dims: { w: 6,  d: 6,  h: 25 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Pièce sèche' },
  { id: 'cons-desperado',       name: 'Desperados 33 cl',           brand: 'Desperados', category: 'consumable', qty: 6, dims: { w: 6,  d: 6,  h: 23 }, frequency: 'hebdo',    stock: 6,  location: 'Frigo',           notes: 'Bouteille bière tequila' },
  { id: 'cons-vodka',           name: 'Vodka 70 cl',                brand: '',         category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 30 }, frequency: 'trimestriel', stock: 1, location: 'Placard cuisine', notes: 'Bouteille' },
  { id: 'cons-redbull',         name: 'Redbull 25 cl',              brand: 'Red Bull', category: 'consumable', qty: 4, dims: { w: 5,  d: 5,  h: 14 }, frequency: 'hebdo',      stock: 4,  location: 'Frigo',           notes: 'Canette' },
  { id: 'cons-sirop',           name: 'Sirop 75 cl',                brand: '',         category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 28 }, frequency: 'trimestriel', stock: 1, location: 'Placard cuisine', notes: 'Bouteille — menthe / grenadine' },
  { id: 'cons-coca',            name: 'Coca-Cola 1,5 L',            brand: 'Coca-Cola', category: 'consumable', qty: 2, dims: { w: 9,  d: 9,  h: 33 }, frequency: 'hebdo',      stock: 2,  location: 'Frigo',           notes: 'Bouteille PET' },
  { id: 'cons-javel-cif',       name: 'Javel 5 en 1 Cif',           brand: 'Cif',       category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 28 }, frequency: 'mensuel',    stock: 1,  location: 'Placard SDB',     notes: 'Spray nettoyant multi-surfaces' },
  { id: 'cons-cif-creme-plaque', name: 'Cif Crème Plaque / Four',   brand: 'Cif',       category: 'consumable', qty: 1, dims: { w: 7,  d: 7,  h: 22 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Crème abrasive nettoyage plaques de cuisson et four' },
  { id: 'cons-nett-canalisation', name: 'Nettoyant Canalisation',    brand: '',          category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 25 }, frequency: 'mensuel',    stock: 1,  location: 'Placard SDB',     notes: 'Déboucheur / entretien canalisations' },
  { id: 'cons-gel-wc',           name: 'Gel WC',                     brand: '',          category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 22 }, frequency: 'mensuel',    stock: 1,  location: 'WC',              notes: 'Gel nettoyant WC' },
  { id: 'cons-anticalcaire',     name: 'Produit Anticalcaire',        brand: '',          category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 22 }, frequency: 'mensuel',    stock: 1,  location: 'Placard SDB',     notes: 'Détartrant' },
  { id: 'cons-javel-pur',        name: 'Javel Pur',                   brand: '',          category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 28 }, frequency: 'mensuel',    stock: 1,  location: 'Placard SDB',     notes: 'Eau de javel concentrée' },
  { id: 'cons-desodo-gaz',      name: 'Désodorisant spray gas',      brand: '',          category: 'consumable', qty: 1, dims: { w: 6,  d: 6,  h: 17 }, frequency: 'mensuel',    stock: 1,  location: 'WC',              notes: 'Aérosol' },
  { id: 'cons-desodo-liquide',  name: 'Désodorisant liquide',        brand: '',          category: 'consumable', qty: 1, dims: { w: 5,  d: 5,  h: 12 }, frequency: 'mensuel',    stock: 1,  location: 'WC',              notes: 'Diffuseur flacon' },
  { id: 'cons-nems',            name: 'Nems surgelés',               brand: '',          category: 'consumable', qty: 4, dims: { w: 25, d: 15, h: 5  }, frequency: 'hebdo',      stock: 4,  location: 'Congélateur',     notes: 'Sachet' },
  { id: 'cons-nems-porc',       name: 'Nems porc',                   brand: '',          category: 'consumable', qty: 1, dims: { w: 25, d: 15, h: 5  }, frequency: 'hebdo',      stock: 1,  location: 'Congélateur',     notes: 'Sachet surgelé' },
  { id: 'cons-nems-veggie',     name: 'Nems végétariens',            brand: '',          category: 'consumable', qty: 1, dims: { w: 25, d: 15, h: 5  }, frequency: 'hebdo',      stock: 1,  location: 'Congélateur',     notes: 'Sachet surgelé' },
  { id: 'cons-merguez',         name: 'Merguez',                     brand: '',          category: 'consumable', qty: 1, dims: { w: 20, d: 15, h: 5  }, frequency: 'hebdo',      stock: 1,  location: 'Congélateur',     notes: 'Sachet' },
  { id: 'cons-brochette-poulet', name: 'Brochette de poulet',        brand: '',          category: 'consumable', qty: 1, dims: { w: 20, d: 15, h: 5  }, frequency: 'hebdo',      stock: 1,  location: 'Congélateur',     notes: 'Sachet' },
  { id: 'cons-brochette-poulet-provencal', name: 'Brochette poulet façon provençal sous vide', brand: '', category: 'consumable', qty: 3, dims: { w: 22, d: 8, h: 4 }, frequency: 'hebdo', stock: 3, location: 'Frigo', notes: 'Sachet sous vide individuel' },
  { id: 'cons-semoule',         name: 'Semoule de blé 500 g',        brand: '',          category: 'consumable', qty: 1, dims: { w: 15, d: 8,  h: 22 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Paquet' },
  { id: 'cons-lame-rasoir-elec', name: 'Lame rasoir électrique',     brand: 'Philips',   category: 'consumable', qty: 1, dims: { w: 10, d: 10, h: 5  }, frequency: 'annuel',     stock: 1,  location: 'SDB vasque',      notes: 'Tête de remplacement' },
  { id: 'cons-lingette-lavante', name: 'Lingettes lavantes',         brand: '',          category: 'consumable', qty: 1, dims: { w: 15, d: 10, h: 8  }, frequency: 'mensuel',    stock: 1,  location: 'SDB',             notes: 'Paquet' },
  { id: 'cons-chicoree',        name: 'Chicorée',                    brand: '',          category: 'consumable', qty: 1, dims: { w: 8,  d: 8,  h: 12 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Bocal / boîte soluble' },
  { id: 'cons-the',             name: 'Thé (boîte 25 sachets)',       brand: '',          category: 'consumable', qty: 1, dims: { w: 12, d: 8,  h: 10 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Sachets' },
  { id: 'cons-cure-dents',      name: 'Cure-dents (boîte)',           brand: '',          category: 'consumable', qty: 1, dims: { w: 8,  d: 3,  h: 10 }, frequency: 'trimestriel', stock: 1, location: 'Placard cuisine', notes: 'Boîte bois' },
  { id: 'cons-chewing-gum',     name: 'Chewing-gum',                 brand: '',          category: 'consumable', qty: 1, dims: { w: 6,  d: 3,  h: 9  }, frequency: 'hebdo',      stock: 1,  location: 'Placard cuisine', notes: 'Paquet' },
  { id: 'cons-tondeuse-philips', name: 'Tondeuse Philips blade',      brand: 'Philips',   category: 'consumable', qty: 1, dims: { w: 12, d: 8,  h: 5  }, frequency: 'annuel',     stock: 1,  location: 'SDB vasque',      notes: 'Tête de remplacement MG9558/15 Series 9000' },
  { id: 'cons-compote-pomme',    name: 'Compote pomme allégée (pack ×4)', brand: 'Vergers Gourmands', category: 'consumable', qty: 4, dims: { w: 19, d: 10, h: 9 }, frequency: 'hebdo', stock: 4, location: 'Placard cuisine', notes: 'Lidl — 0,99 € le pack, allégée en sucre' },
  { id: 'cons-cappuccino-choco', name: 'Cappuccino goût chocolat',     brand: 'Bellarom',  category: 'consumable', qty: 1, dims: { w: 14, d: 7,  h: 19 }, frequency: 'mensuel',    stock: 1,  location: 'Placard cuisine', notes: 'Lidl — sachets instantanés' },
  { id: 'cons-okoia-k04017',    name: 'Nettoyant têtes de rasoirs K04017', brand: 'Okoia', category: 'consumable', qty: 2, dims: { w: 6,  d: 6,  h: 10 }, frequency: 'mensuel',    stock: 2,  location: 'SDB vasque',      notes: 'Spray nettoyant têtes rasoir électrique — Acheté le 14/02/2026' },

  // ── SACS / BAGAGERIE ──────────────────────────────────────────────────────────
  { id: 'sac-banane-kalenji', name: 'Sac banane Kalenji Activ Mblty noir', brand: 'Kalenji', category: 'clothing', qty: 2, dims: { w: 28, d: 8, h: 14 }, notes: '5 L — 3 poches — porte-bouteille 75 cl — sangle stabilisatrice amovible — imperméable — Decathlon', photos: ['items/sac-banane-kalenji-activ-mblty-noir/sac-banane-kalenji-activ-mblty-noir-1.jpg', 'items/sac-banane-kalenji-activ-mblty-noir/sac-banane-kalenji-activ-mblty-noir-2.jpg', 'items/sac-banane-kalenji-activ-mblty-noir/sac-banane-kalenji-activ-mblty-noir-3.jpg', 'items/sac-banane-kalenji-activ-mblty-noir/sac-banane-kalenji-activ-mblty-noir-4.jpg', 'items/sac-banane-kalenji-activ-mblty-noir/sac-banane-kalenji-activ-mblty-noir-5.jpg', 'items/sac-banane-kalenji-activ-mblty-noir/sac-banane-kalenji-activ-mblty-noir-6.jpg'] },

  // ── PORTES ────────────────────────────────────────────────────────────────────
  { id: 'door-entry',       name: 'Porte d\'entrée',                brand: '',         category: 'doors',     qty: 1, dims: { w: 90,  d: 4,   h: 204 }, notes: 'Rouge, mur diagonal, poignée L + knob rouge', actions: ['entry-door-toggle'] },
  { id: 'door-living',      name: 'Porte séjour',                   brand: '',         category: 'doors',     qty: 1, dims: { w: 83,  d: 4,   h: 204 }, notes: 'Blanche, mur D, poignée L double face', actions: ['living-door-toggle'] },
  { id: 'door-sdb',         name: 'Porte SDB',                      brand: '',         category: 'doors',     qty: 1, dims: { w: 4,   d: 83,  h: 204 }, notes: 'Blanche, mur couloir, poignée L double face', actions: ['bathroom-door-toggle'] },
  { id: 'door-glass',       name: 'Porte-fenêtre',                  brand: '',         category: 'doors',     qty: 1, dims: { w: 160, d: 5,   h: 190 }, notes: 'Double battant PVC blanc, vitrage, seuil 20cm', actions: ['east-glass-door-toggle'] },
  { id: 'door-bim-double',  name: 'S9000 Double Door',              brand: 'GEALAN',   category: 'doors',     qty: 1, dims: { w: 160, d: 8,   h: 210 }, notes: 'BIMObject S9000 Double-vent door with threshold', actions: ['bim-door-left-open', 'bim-door-right-open'] },
  { id: 'door-frame',       name: 'Dormant de porte',               brand: 'Standard', category: 'doors',     qty: 1, dims: { w: 88,  d: 9.2, h: 205 }, notes: 'Dormant/huisserie standard pour mur de 7.2 cm d\'épaisseur. Largeur totale 9.2 cm, recouvrement de 1 cm des deux côtés avec lèvres symétriques (3 cm de hauteur). Passage utile de 83 cm avec butée de 1.8 cm.' },

];

import { CHARACTERS } from '@features/scene/walkerConfig';

INVENTORY.push({
  id: 'ushiro',
  name: 'Chien Ushiro (Shiba Inu)',
  brand: 'Animal',
  category: 'walkers',
  qty: 1,
  dims: { w: 40, d: 80, h: 40 },
  glbPath: 'characters/ushiro/shiba_inu_dog_ushiro.glb',
  photos: ['characters/ushiro/shiba_inu_dog_ushiro_3d_preview.png'],
  notes: `Personnage : Chien Shiba Inu (Ushiro).`
});

INVENTORY.push({
  id: 'robin-bird',
  name: 'Oiseau Robin',
  brand: 'Animal',
  category: 'walkers',
  qty: 1,
  dims: { w: 10, d: 10, h: 10 },
  glbPath: 'characters/robin/robin.glb',
  photos: ['characters/robin/robin_3d_preview.png'],
  notes: `Personnage : Oiseau Robin.`
});

CHARACTERS.forEach(char => {
  if (!INVENTORY.some((item: InventoryItem) => item.id === char.id)) {
    const photos = char.path.includes('xbot') ? ['characters/xbot/Xbot_official_3d_preview.png'] : undefined;
    INVENTORY.push({
      id: char.id,
      name: char.name,
      brand: char.id === 'xbot_studio' ? 'Mixamo' : 'Lara Croft Style',
      category: 'walkers',
      qty: 1,
      dims: { w: 45, d: 25, h: char.height },
      glbPath: char.path,
      ...(photos ? { photos } : {}),
      notes: `Personnage : ${char.name}.`
    });
  }
});

export interface WigItem {
  id: string;
  name: string;
  glbPath?: string;
  photos?: string[];
}

export const WIGS_ITEMS: WigItem[] = [
  { id: 'hair_100', name: "Coupe #1 (Bob)", glbPath: 'characters/wigs/wig_100.glb', photos: ['characters/wigs/previews/wig_100.png'] },
  { id: 'hair_101', name: "Coupe #2 (Queue H.)", glbPath: 'characters/wigs/wig_101.glb', photos: ['characters/wigs/previews/wig_101.png'] },
  { id: 'hair_102', name: "Coupe #3 (Pixie)", glbPath: 'characters/wigs/wig_102.glb', photos: ['characters/wigs/previews/wig_102.png'] },
  { id: 'hair_103', name: "Coupe #4 (Wolf)", glbPath: 'characters/wigs/wig_103.glb', photos: ['characters/wigs/previews/wig_103.png'] },
  { id: 'hair_104', name: "Coupe #5 (Frange)", glbPath: 'characters/wigs/wig_104.glb', photos: ['characters/wigs/previews/wig_104.png'] },
  { id: 'hair_105', name: "Coupe #6 (Queue TT H.)", glbPath: 'characters/wigs/wig_105.glb', photos: ['characters/wigs/previews/wig_105.png'] },
  { id: 'hair_106', name: "Coupe #7 (Bob Frange)", glbPath: 'characters/wigs/wig_106.glb', photos: ['characters/wigs/previews/wig_106.png'] },
  { id: 'hair_107', name: "Coupe #8 (Couettes)", glbPath: 'characters/wigs/wig_107.glb', photos: ['characters/wigs/previews/wig_107.png'] },
  { id: 'hair_108', name: "Coupe #9 (Hérissée)", glbPath: 'characters/wigs/wig_108.glb', photos: ['characters/wigs/previews/wig_108.png'] },
  { id: 'hair_109', name: "Coupe #10 (Wavy Lob)", glbPath: 'characters/wigs/wig_109.glb', photos: ['characters/wigs/previews/wig_109.png'] },
  { id: 'hair_110', name: "Coupe #11 (Hime)", glbPath: 'characters/wigs/wig_110.glb', photos: ['characters/wigs/previews/wig_110.png'] },
  { id: 'hair_111', name: "Coupe #12 (Mi-tresse)", glbPath: 'characters/wigs/wig_111.glb', photos: ['characters/wigs/previews/wig_111.png'] },
  { id: 'hair_112', name: "Coupe #13 (Chignon)", glbPath: 'characters/wigs/wig_112.glb', photos: ['characters/wigs/previews/wig_112.png'] },
  { id: 'hair_zepeto', name: "Coupe #14 (Zepeto, zHairezt)", glbPath: 'characters/wigs/zepeto_hair.glb', photos: ['characters/wigs/previews/zepeto_hair.png'] },
  // { id: 'hair_pigtails', name: "Coupe #15 (Longues Couettes Blanches, zHairezt)", glbPath: 'characters/wigs/white_long_pigtails.glb', photos: ['characters/wigs/previews/white_long_pigtails.png'] },
  { id: 'hair_buns', name: "Coupe #16 (Longs Chignons Buns, zHairezt)", glbPath: 'characters/wigs/long_hair_with_buns.glb', photos: ['characters/wigs/previews/long_hair_with_buns.png'] },
  { id: 'hair_short_layers', name: "Coupe #17 (Courte Dégradée, zHairezt)", glbPath: 'characters/wigs/short_hair_cut_in_layers.glb', photos: ['characters/wigs/previews/short_hair_cut_in_layers.png'] },
  { id: 'hair_nmixx_hat_braids', name: "Coupe #18 (NMIXX Bonnet & Tresses, zHairezt)", glbPath: 'characters/wigs/nmixx_long_hair_with_hat_and_braids.glb', photos: ['characters/wigs/previews/nmixx_long_hair_with_hat_and_braids.png'] },
  // { id: 'hair_very_long', name: "Coupe #19 (Très Longue, zHairezt)", glbPath: 'characters/wigs/very_long_hair.glb', photos: ['characters/wigs/previews/very_long_hair.png'] },
  { id: 'hair_two_braids_bangs', name: "Coupe #20 (Deux Tresses Frange, zHairezt)", glbPath: 'characters/wigs/two_braids_with_bangs.glb', photos: ['characters/wigs/previews/two_braids_with_bangs.png'] },
  { id: 'hair_aespa_short', name: "Coupe #21 (Aespa Courte, zHairezt)", glbPath: 'characters/wigs/aespa_short_hair.glb', photos: ['characters/wigs/previews/aespa_short_hair.png'] },
  // { id: 'hair_wavy_ponytail', name: "Coupe #22 (Queue de Cheval Ondulée, zHairezt)", glbPath: 'characters/wigs/wavy_white_ponytail.glb', photos: ['characters/wigs/previews/wavy_white_ponytail.png'] },
  { id: 'hair_nimxx_short', name: "Coupe #23 (NIMXX Courte V1, zHairezt)", glbPath: 'characters/wigs/nimxx_short_hair.glb', photos: ['characters/wigs/previews/nimxx_short_hair.png'] },
  { id: 'hair_short_combed', name: "Coupe #24 (Courte Plaquée Arrière, zHairezt)", glbPath: 'characters/wigs/short_hair_combed_back.glb', photos: ['characters/wigs/previews/short_hair_combed_back.png'] },
  { id: 'hair_low_bun', name: "Coupe #25 (Chignon Bas Frange, zHairezt)", glbPath: 'characters/wigs/low_bun_with_bangs.glb', photos: ['characters/wigs/previews/low_bun_with_bangs.png'] },
  { id: 'hair_high_bun', name: "Coupe #26 (Chignon Haut Frange, zHairezt)", glbPath: 'characters/wigs/high_bun_with_bangs.glb', photos: ['characters/wigs/previews/high_bun_with_bangs.png'] },
  { id: 'hair_high_ponytail', name: "Coupe #27 (Petite Queue de Cheval Haute, zHairezt)", glbPath: 'characters/wigs/high_short_ponytail.glb', photos: ['characters/wigs/previews/high_short_ponytail.png'] },
  { id: 'hair_nmixx_short', name: "Coupe #28 (NMIXX Courte V2, zHairezt)", glbPath: 'characters/wigs/nmixx_short_hair.glb', photos: ['characters/wigs/previews/nmixx_short_hair.png'] },
  { id: 'hair_long_braids', name: "Coupe #29 (Longues Tresses Frange, zHairezt)", glbPath: 'characters/wigs/long_braids_with_bangs.glb', photos: ['characters/wigs/previews/long_braids_with_bangs.png'] },
  { id: 'hair_nmixx_16', name: "Coupe #30 (NMIXX #16, zHairezt)", glbPath: 'characters/wigs/nmixx_hair_n16.glb', photos: ['characters/wigs/previews/nmixx_hair_n16.png'] },
  { id: 'hair_zepeto_nmixx', name: "Coupe #31 (Zepeto NMIXX, zHairezt)", glbPath: 'characters/wigs/zepeto_nmixx_hair.glb', photos: ['characters/wigs/previews/zepeto_nmixx_hair.png'] },
  { id: 'hair_bob_buns', name: "Coupe #32 (Carré Bob Buns, zHairezt)", glbPath: 'characters/wigs/bob_haircut_with_buns.glb', photos: ['characters/wigs/previews/bob_haircut_with_buns.png'] },
  { id: 'hair_wavy_ponytails', name: "Coupe #33 (Longues Couettes Ondulées Blanches, zHairezt)", glbPath: 'characters/wigs/white_long_wavy_ponytails.glb', photos: ['characters/wigs/previews/white_long_wavy_ponytails.png'] },
  { id: 'hair_two_long_ponytails', name: "Coupe #34 (Deux Longues Couettes, zHairezt)", glbPath: 'characters/wigs/two_long_ponytails.glb', photos: ['characters/wigs/previews/two_long_ponytails.png'] },
  { id: 'hair_cyber_two_long_ponytails', name: "Coupe #35 (Cyber Deux Longues Couettes, zHairezt)", glbPath: 'characters/wigs/cyber_two_long_ponytails.glb', photos: ['characters/wigs/previews/cyber_two_long_ponytails.png'] },
  { id: 'hair_white_hair_with_bun', name: "Coupe #36 (Cheveux Blancs avec Chignon, zHairezt)", glbPath: 'characters/wigs/white_hair_with_bun.glb', photos: ['characters/wigs/previews/white_hair_with_bun.png'] },
  { id: 'hair_short_hair', name: "Coupe #37 (Cheveux Courts, zHairezt)", glbPath: 'characters/wigs/short_hair.glb', photos: ['characters/wigs/previews/short_hair.png'] },
  { id: 'hair_white_ponytail', name: "Coupe #38 (Queue de Cheval Blanche, zHairezt)", glbPath: 'characters/wigs/white_ponytail.glb', photos: ['characters/wigs/previews/white_ponytail.png'] },
  { id: 'hair_nmixx_hair_with_bangs', name: "Coupe #39 (NMIXX avec Frange, zHairezt)", glbPath: 'characters/wigs/nmixx_hair_with_bangs.glb', photos: ['characters/wigs/previews/nmixx_hair_with_bangs.png'] },
  // { id: 'hair_two_white_ponytails', name: "Coupe #40 (Deux Queues de Cheval Blanches, zHairezt)", glbPath: 'characters/wigs/two_white_ponytails.glb', photos: ['characters/wigs/previews/two_white_ponytails.png'] },
  { id: 'hair_wolf_haircut', name: "Coupe #41 (Coupe Wolf, zHairezt)", glbPath: 'characters/wigs/wolf_haircut.glb', photos: ['characters/wigs/previews/wolf_haircut.png'] },
  { id: 'hair_white_bob_hairct', name: "Coupe #42 (Carré Bob Blanc, zHairezt)", glbPath: 'characters/wigs/white_bob_hairct.glb', photos: ['characters/wigs/previews/white_bob_hairct.png'] },
  { id: 'hair_scbe_hair_combed_to_one_side', name: "Coupe #43 (Cheveux Plaqués sur le Côté, zHairezt)", glbPath: 'characters/wigs/scbe_hair_combed_to_one_side.glb', photos: ['characters/wigs/previews/scbe_hair_combed_to_one_side.png'] },
  { id: 'hair_wavy_wet_white_hair', name: "Coupe #44 (Cheveux Blancs Ondulés Mouillés, zHairezt)", glbPath: 'characters/wigs/wavy_wet_white_hair.glb', photos: ['characters/wigs/previews/wavy_wet_white_hair.png'] },
  { id: 'hair_nyyd_wavy_hair', name: "Coupe #45 (NYYD Ondulés, zHairezt)", glbPath: 'characters/wigs/nyyd_wavy_hair.glb', photos: ['characters/wigs/previews/nyyd_wavy_hair.png'] },
  { id: 'hair_short_wavy_hair_with_bangs', name: "Coupe #46 (Courts Ondulés avec Frange, zHairezt)", glbPath: 'characters/wigs/short_wavy_hair_with_bangs.glb', photos: ['characters/wigs/previews/short_wavy_hair_with_bangs.png'] },
  { id: 'hair_nmixxhair_whith_bangs', name: "Coupe #47 (NMIXX Frange V2, zHairezt)", glbPath: 'characters/wigs/nmixxhair_whith_bangs.glb', photos: ['characters/wigs/previews/nmixxhair_whith_bangs.png'] },
  { id: 'hair_long_hair_styled_to_the_sides', name: "Coupe #48 (Longs Stylisés sur les Côtés, zHairezt)", glbPath: 'characters/wigs/long_hair_styled_to_the_sides.glb', photos: ['characters/wigs/previews/long_hair_styled_to_the_sides.png'] },
  { id: 'hair_wavy_long_hair_with_bangs', name: "Coupe #49 (Longs Ondulés Frange, zHairezt)", glbPath: 'characters/wigs/wavy_long_hair_with_bangs.glb', photos: ['characters/wigs/previews/wavy_long_hair_with_bangs.png'] },
  { id: 'hair_wavy_white_hair_to_one_side', name: "Coupe #50 (Ondulés Blancs sur le Côté, zHairezt)", glbPath: 'characters/wigs/wavy_white_hair_to_one_side.glb', photos: ['characters/wigs/previews/wavy_white_hair_to_one_side.png'] },
  { id: 'hair_high_white_bunponytail', name: "Coupe #51 (Chignon/Queue Haut Blanc, zHairezt)", glbPath: 'characters/wigs/high_white_bunponytail.glb', photos: ['characters/wigs/previews/high_white_bunponytail.png'] },
  { id: 'hair_white_hair_arraged_to_one_side', name: "Coupe #52 (Cheveux Blancs Arrangés sur un Côté, zHairezt)", glbPath: 'characters/wigs/white_hair_arraged_to_one_side.glb', photos: ['characters/wigs/previews/white_hair_arraged_to_one_side.png'] },
  // { id: 'hair_black_long_hair', name: "Coupe #53 (Longs Cheveux Noirs, zHairezt)", glbPath: 'characters/wigs/black_long_hair.glb', photos: ['characters/wigs/previews/black_long_hair.png'] },
  // { id: 'hair_blonde_ponytail_with_bangs', name: "Coupe #54 (Queue de Cheval Blonde Frange, zHairezt)", glbPath: 'characters/wigs/blonde_ponytail_with_bangs.glb', photos: ['characters/wigs/previews/blonde_ponytail_with_bangs.png'] },
  { id: 'hair_bratz_curly_hair', name: "Coupe #55 (Bratz Bouclée, zHairezt)", glbPath: 'characters/wigs/bratz_curly_hair.glb', photos: ['characters/wigs/previews/bratz_curly_hair.png'] },
  { id: 'hair_bratz_long_hair', name: "Coupe #56 (Bratz Longue, zHairezt)", glbPath: 'characters/wigs/bratz_long_hair.glb', photos: ['characters/wigs/previews/bratz_long_hair.png'] },
  // { id: 'hair_chinook_wind_ponytail', name: "Coupe #57 (Chinook Queue de Cheval, zHairezt)", glbPath: 'characters/wigs/chinook_wind_ponytail.glb', photos: ['characters/wigs/previews/chinook_wind_ponytail.png'] },
  // { id: 'hair_hair_bitten', name: "Coupe #58 (Bitten, zHairezt)", glbPath: 'characters/wigs/hair_bitten.glb', photos: ['characters/wigs/previews/hair_bitten.png'] },
  { id: 'hair_kcon_long_hair', name: "Coupe #59 (KCON Longue, zHairezt)", glbPath: 'characters/wigs/kcon_long_hair.glb', photos: ['characters/wigs/previews/kcon_long_hair.png'] },
  // { id: 'hair_long_down_ponytail', name: "Coupe #60 (Longue Queue de Cheval Basse, zHairezt)", glbPath: 'characters/wigs/long_down_ponytail.glb', photos: ['characters/wigs/previews/long_down_ponytail.png'] },
  // { id: 'hair_long_hair_cut_in_layers', name: "Coupe #61 (Longue Dégradée, zHairezt)", glbPath: 'characters/wigs/long_hair_cut_in_layers.glb', photos: ['characters/wigs/previews/long_hair_cut_in_layers.png'] },
  { id: 'hair_long_hair_with_bow', name: "Coupe #62 (Longue avec Nœud, zHairezt)", glbPath: 'characters/wigs/long_hair_with_bow.glb', photos: ['characters/wigs/previews/long_hair_with_bow.png'] },
  // { id: 'hair_medium_short_hair_combed_to_the_sides', name: "Coupe #63 (Mi-Courte sur les Côtés, zHairezt)", glbPath: 'characters/wigs/medium_short_hair_combed_to_the_sides.glb', photos: ['characters/wigs/previews/medium_short_hair_combed_to_the_sides.png'] },
  { id: 'hair_nmixx_white_hair', name: "Coupe #64 (NMIXX Blanche, zHairezt)", glbPath: 'characters/wigs/nmixx_white_hair.glb', photos: ['characters/wigs/previews/nmixx_white_hair.png'] },
  { id: 'hair_nmixx_white_longshort_hair', name: "Coupe #65 (NMIXX Blanche Long/Court, zHairezt)", glbPath: 'characters/wigs/nmixx_white_longshort_hair.glb', photos: ['characters/wigs/previews/nmixx_white_longshort_hair.png'] },
  // { id: 'hair_noicepotatonp_osanahair', name: "Coupe #66 (Osana, zHairezt)", glbPath: 'characters/wigs/noicepotatonp_osanahair.glb', photos: ['characters/wigs/previews/noicepotatonp_osanahair.png'] },
  { id: 'hair_side_swept_curls', name: "Coupe #67 (Boucles Balayées sur le Côté, zHairezt)", glbPath: 'characters/wigs/side_swept_curls.glb', photos: ['characters/wigs/previews/side_swept_curls.png'] },
  { id: 'hair_straight_long_white_hair', name: "Coupe #68 (Longs Cheveux Lisses Blancs, zHairezt)", glbPath: 'characters/wigs/straight_long_white_hair.glb', photos: ['characters/wigs/previews/straight_long_white_hair.png'] },
  { id: 'hair_two_braids_with_red_ties', name: "Coupe #69 (Deux Tresses Attaches Rouges, zHairezt)", glbPath: 'characters/wigs/two_braids_with_red_ties.glb', photos: ['characters/wigs/previews/two_braids_with_red_ties.png'] },
  { id: 'hair_vcha_long_white_hair', name: "Coupe #70 (VCHA Longue Blanche, zHairezt)", glbPath: 'characters/wigs/vcha_long_white_hair.glb', photos: ['characters/wigs/previews/vcha_long_white_hair.png'] },
  { id: 'hair_wavy_hair_arranged_to_one_side', name: "Coupe #71 (Ondulés sur un Côté, zHairezt)", glbPath: 'characters/wigs/wavy_hair_arranged_to_one_side.glb', photos: ['characters/wigs/previews/wavy_hair_arranged_to_one_side.png'] },
  { id: 'hair_wavy_hair_with_bangs_02', name: "Coupe #72 (Ondulés Frange V2, zHairezt)", glbPath: 'characters/wigs/wavy_hair_with_bangs_02.glb', photos: ['characters/wigs/previews/wavy_hair_with_bangs_02.png'] },
  { id: 'hair_white_long_wavy_hair', name: "Coupe #73 (Longs Blancs Ondulés, zHairezt)", glbPath: 'characters/wigs/white_long_wavy_hair.glb', photos: ['characters/wigs/previews/white_long_wavy_hair.png'] }
];

export const RIGGED_WIGS_PATHS: Record<string, string> = {};
WIGS_ITEMS.filter(w => !!w.glbPath).forEach(w => {
  RIGGED_WIGS_PATHS[w.id] = w.glbPath!;
  RIGGED_WIGS_PATHS[w.id.replace(/^hair_/, '')] = w.glbPath!;
});

export const isRiggedWig = (id: string | number): boolean => {
  const strId = String(id);
  const cleanId = strId.replace(/^hair_/, '');
  return !!(RIGGED_WIGS_PATHS[strId] || RIGGED_WIGS_PATHS[cleanId]);
};

WIGS_ITEMS.forEach(wig => {
  if (!INVENTORY.some((item: InventoryItem) => item.id === wig.id)) {
    INVENTORY.push({
      id: wig.id,
      name: wig.name,
      brand: 'Custom',
      category: 'wigs',
      qty: 1,
      dims: { w: 25, d: 25, h: 25 },
      glbPath: wig.glbPath || 'characters/wigs/hair_pack_part_2.glb',
      photos: (wig as any).photos || (wig.glbPath ? [`characters/wigs/previews/${wig.glbPath.split('/').pop()?.replace('.glb', '')}.png`] : ['characters/wigs/previews/hair_pack_part_2.png']),
      notes: `Perruque 3D: ${wig.name}.`
    });
  }
});

export const STORAGE_SPACES: StorageSpace[] = [
  { id: 'kallax-ne-stack', name: 'Kallax NE',       dims: { w: 75.5, d: 39, h: 222 }, notes: 'Coin mur C+B — 2×1 bas + 2×2 haut empilés, 6 Drona + 1 dessus' },
  { id: 'kallax-se-stack', name: 'Kallax SE',       dims: { w: 75.5, d: 39, h: 151 }, notes: 'Mur B sud — 2× (2×1 pivoté), 4 Drona + meuble en T dessus' },
  { id: 'kallax-nw-stack', name: 'Kallax NW',       dims: { w: 75.5, d: 39, h: 227 }, notes: 'Coin mur A+C — tour 2×1 + 1×1 + 1×1 pivotés, 4 Drona' },
  { id: 'kallax-sw-stack', name: 'Kallax cuisine',  dims: { w: 75.5, d: 39, h: 371 }, notes: 'Niche mur D — 2×2 + 2×2 + 2×1 empilés, 4 Drona dans le bas' },
  { id: 'mackapar-stack',  name: 'Mackapär',        dims: { w: 77,   d: 32, h: 200 }, notes: 'Portant niche — combinaison + salopette + 2 Drona en haut' },
  { id: 'raskog-large-stack', name: 'RaskogLarge',     dims: { w: 35,   d: 45, h: 77  }, notes: 'Desserte roulante — mannequin + casquette' },
  { id: 'cuisine-stack',   name: 'Cuisine',         dims: { w: 100,  d: 60, h: 93  }, notes: 'Plan de travail, évier, plaques, frigo, meuble bas, meuble haut + 3 Drona' },
  { id: 'corridor-closet', name: 'Placard couloir', dims: { w: 60,   d: 50, h: 250 }, notes: 'Porte pivotante + 3 étagères', actions: ['corr-doors-toggle'] },
  { id: 'sdb-closet',      name: 'Placard SDB',     dims: { w: 110,  d: 60, h: 250 }, notes: 'Double porte coulissante + étagère triangulaire 170cm (X=70→180, Z=600→660)', actions: ['sdb-closet-toggle'] },
];

export const CATEGORIES: Category[] = [
  { id: 'all',          label: 'Tout' },
  { id: 'spaces',       label: '🏠 Espaces & Pièces' },
  { id: 'actionnable',  label: '⚡ Actionnable' },
  { id: 'doors',        label: '🚪 Portes' },
  { id: 'storage',      label: 'Rangement' },
  { id: 'furniture',    label: 'Mobilier' },
  { id: 'tech',         label: 'Tech' },
  { id: 'kitchen',      label: 'Cuisine' },
  { id: 'bathroom',     label: 'Salle d\'eau' },
  { id: 'clothing',     label: 'Vêtements' },
  { id: 'decor',        label: 'Déco' },
  { id: 'consumable',   label: '🛒 Consomables' },
  { id: 'walkers',      label: '👥 Personnages' },
  { id: 'wigs',         label: '💇 Perruques' },
  { id: 'glbs',         label: '🎲 GLBs' },
];
// Mise à jour des catégories IKEA
